### ISSUE TITLE
Response property doesn't exist on FileUploadResult.

### ISSUE THREAD

**Issue by dragonfire1119** [driftyco/ionic-native#1002]
Error
================
``Property 'response' does not exist on type 'FileUploadResult | FileTransferError'.``

```
fileTransfer.upload(targetPath, url, options).then(data => {
     let response = JSON.parse(data.response);
});
```

I was on ``"ionic-native": "^2.2.11"`` but I upgraded to ``"ionic-native": "^2.4.1",``

Looks like the error is happening on this commit:
https://github.com/driftyco/ionic-native/commit/1976c38dc73be088640aeac4e355d257b945cff7#diff-2f9b79bc9c725972a5f02017d72a1e66R226

Steps to resolve error
================

I did delete the node_modules & reinstall everything.

Looked for the the ``response`` https://github.com/driftyco/ionic-native/blob/master/src/plugins/filetransfer.ts#L66

Versions
================
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0

**Comment by phoenixtrigo** [comment]
Hi guys!

It happens to me right now and I already deleted node_modules and do ```npm install``` and same error.

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0

**Comment by dragonfire1119** [comment]
@ihadeed Since you closed this is it going to be released?

**Comment by sjosen** [comment]
I have the same error

**Comment by dragonfire1119** [comment]
@sjosen Until he releases the commit you would need to go back to ``"ionic-native": "2.2.11"``.

**Comment by betollaque** [comment]
I have the same error with ionic-native": 2.4.1, Please when will be ready this release? 
@dragonfire1119  Could you explain how you solved temporally this error?

**Comment by dragonfire1119** [comment]
@betollaque you would need to change your ionic native version to "ionic-native": "2.2.11".

**Comment by phoenixtrigo** [comment]
@betollaque I solved by applying the fix manually. Not the best solution but it does the job until the new release are out.

**Comment by betollaque** [comment]
Thanks guys for help. @phoenixtrigo  I found 2 files in my ionic project:

- node_modules\ionic-native\dist\es5\plugins\filetransfer.d.ts

- node_modules\ionic-native\dist\esm\plugins\filetransfer.d.ts

 Both files have this line: `upload(fileUrl: string, url: string, options?: FileUploadOptions, trustAllHosts?: boolean): Promise<FileUploadResult | FileTransferError>;` 

Here I'm little confuse, could you indicate what file and line did you fix?

**Comment by ihadeed** [comment]
@betollaque remove ` | FileTransferError` from there and it will work.

**Comment by betollaque** [comment]
Is working! thanks!

**Comment by phoenixtrigo** [comment]
@betollaque glad to hear it's working now.

I think the file depends on the target you have configured on the tsconfig.ts file.   
If ```"target": "es5"``` then   node_modules\ionic-native\dist\es5\plugins\filetransfer.d.ts  
If ```"target": "esm"``` then   node_modules\ionic-native\dist\esm\plugins\filetransfer.d.ts  

then it's just like @ihadeed said, remove the ```| FileTransferError``` from the corresponding file.

**Comment by sgadekar81** [comment]
I am getting same error
