### ISSUE TITLE
Latest release - 2.0.0 Native  plugin Network.connection does not exists

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#1005]
_From @bimal72 on January 26, 2017 5:39_

**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Hello,
I have just upgraded my project with latest release, 2.0.0 and it breaks my existing code ..

```
Network.connection !== "none"
```
I am assuming I should replace this line with ...
```
Network.type !== "none"
```
Let me confirm please

_Copied from original issue: driftyco/ionic#10177_

**Comment by jgw96** [comment]
_From @dylanvdmerwe on January 26, 2017 7:4_

This was changed a long time ago in the ionic native plugin. https://github.com/driftyco/ionic-native/releases/tag/v2.2.12

**Comment by ihadeed** [comment]
I'm assuming this is resolved/answered. Closing.
