### ISSUE TITLE
Firebase onNotificationOpen no work when app completed exited.

### ISSUE THREAD

**Issue by jafaripur** [driftyco/ionic-native#1007]
When app is open or is in backgroun the ``onNotificationOpen`` event trigger when click on notification. But when application exited completed and removed from memory, tapping on new received notification start app but now trigger ``onNotificationOpen`` to detect data which receive from server.

I worked before with push notification plugin and this behavior work as well.

**Comment by ihadeed** [comment]
This is an issue with the plugin. See https://github.com/arnesson/cordova-plugin-firebase/issues/129
