### ISSUE TITLE
For iOS  not able to generate device token but for android it work.

### ISSUE THREAD

**Issue by akashkuber-tudip** [driftyco/ionic-native#1009]
I used given code like following
let push = PushNotification.init({
    android: {
        senderID: "12345679"
    },
    ios: {
        alert: "true",
        badge: true,
        sound: 'false'
    },
    windows: {}
});

push.on('registration', (data) => {
    console.log(data.registrationId);
});

push.on('notification', (data) => {
    console.log(data.message);
    console.log(data.title);
    console.log(data.count);
    console.log(data.sound);
    console.log(data.image);
    console.log(data.additionalData);
});

push.on('error', (e) => {
    console.log(e.message);
});

but when I try to generate device token it will never generate.

**Comment by ihadeed** [comment]
Are you running on a simulator or a real device?
