### ISSUE TITLE
background-geolocation

### ISSUE THREAD

**Issue by 4ware** [driftyco/ionic-native#101]
I would love to migrate our app to ionic2 but this could not be done without this plugin.

**Comment by keithdmoore** [comment]
@4ware Are you talking about this plugin?  https://github.com/transistorsoft/cordova-background-geolocation-lt

**Comment by 4ware** [comment]
@keithdmoore It might be wiser to use https://github.com/mauron85/cordova-plugin-background-geolocation since the original plugin moved to some paid "premium" scheme now.

**Comment by vfdev-5** [comment]
I'd like to try write a wrapper in my [fork](https://github.com/vfdev-5/ionic-native)
However, I do not understand how can I test it with an app...

**Comment by ihadeed** [comment]
hey @vfdev-5 

I see you added the interfaces for now. Next step would be to add wrappers for the functions, then add the plugin to index.ts.

Once you're done with that run `npm run build_bundle` to compile the library and have something that you can import in a Cordova project and test.

**Comment by vfdev-5** [comment]
Hi @ihadeed 
I added wrappers for the functions and the plugin to the index.ts as you said. The compilation is OK and I 'tested' it with a demo application - ionic 2 version of [this](https://github.com/mauron85/cordova-plugin-background-geolocation/tree/master/example/SampleApp)
What is the next step, pull-request, ... ?

**Comment by ihadeed** [comment]
@vfdev-5 yes if the functionality works submit a PR and I'll review & merge.

**Comment by joshgarwood** [comment]
Is ionic-native now using this plugin instead of the one from mauron85?  I recently got the latest ionic2 build (beta8), installed the mauron85 plugin, and imported ionic-native, but it looks like the configure function is now a promise instead of an observable:

```
    var backgroundOptions = {
            desiredAccuracy: 10,
            stationaryRadius: 10,
            distanceFilter: 30,
            debug: false
        };

        // This seems to work
        BackgroundGeolocation.configure(backgroundOptions).then((location) => {
            this.notifyLocation(location);
            BackgroundGeolocation.finish();
        });


        // this does not
        BackgroundGeolocation.configure(
            location => {
                //this.notifyLocation(location);
                BackgroundGeolocation.finish();
            }, 
            err => {
                console.log(err);
            }, 
            backgroundOptions);
```

The [documentation suggests](http://ionicframework.com/docs/v2/native/backgroundgeolocation/) that the second implementation should work.  So I'm just trying to figure out the proper way to do this.  Any help would be much appreciated.

Thanks!

**Comment by vfdev-5** [comment]
@joshgarwood, you are right, there is a problem with the documentation. As you suggest, the first method is the right one.
