### ISSUE TITLE
Ionic Native HeaderColor plugin not working

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-native#1015]
_From @dipolediamond on January 29, 2017 1:20_

**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The HeaderColor listed in the docs [http://ionicframework.com/docs/v2/native/headerolor/](http://ionicframework.com/docs/v2/native/headerolor/) (there's a typo in the documentation, it's spelt Headerolor) does not work. 

**Expected behavior:**
Access plugin methods on import and be able to call the tint method.

**Steps to reproduce:**
Install the plugin
```
ionic plugin add cordova-plugin-headercolor
```
Try to import the plugin
```
import { HeaderColor } from 'ionic-native';
```

**Related code:**

```
import { HeaderColor } from 'ionic-native';
```

**Other information:**
The error displayed
```
Module '"/APP_INSTALL_PATH/node_modules/ionic-native/dist/es5/index"' has no exported member 'HeaderColor'.
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: 5.0.13 
OS: OS X El Capitan
Node Version: v6.2.0
Xcode version: Xcode 7.3.1 Build version 7D1014
```

_Copied from original issue: driftyco/ionic#10225_

**Comment by ihadeed** [comment]
@dipolediamond please update to latest version of `ionic-native`.

**Comment by dipolediamond** [comment]
Thanks @ihadeed and @brandyscarney. Updating to the latest version fixed it.

**Comment by siphiwe** [comment]
Hi. I have this exact problem and updating ionic native doesn't help (it was on 2.9.0 already), nor does reinstalling it along with the failing plugin (PhotoLibrary). My ionic info:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.8
Node Version: v4.2.6
Xcode version: Not installed

Please assist.
Thanks

**Comment by siphiwe** [comment]
Just updated node to v7.6.0. Didn't help either

**Comment by siphiwe** [comment]
Downgrading to ionic-native@2.8.1 sorted me out. Probably be a regression in 2.9.0.
