### ISSUE TITLE
Splashscreen inconsistent on different android versions

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic-native#1023]
I know it is not this repository's issue, but perhaps there is a need for some touch-up.

Using these settings:
```
<preference name="ShowSplashScreenSpinner" value="true" />
<preference name="FadeSplashScreen" value="false" />
<preference name="SplashScreen" value="screen"/>
```

And this code on my main app file: (outside of the app class, right at the beginning of the file after importing)
```
Splashscreen.show();
```

I am getting really inconsistent behaviour.

**Android 7**:
Splashscreen is shown until a time I call the `hide` method. 

**Android 6**:
Splashscreen is shown until the app loads, and does not "wait" for my `hide` method calling.

**Android 5**:
Splashscreen is shown for 1-2 seconds, then fades to a white screen, then a second later it is shown again, and fades when I tell it to fade.

So trying using it in 3 different version of android is inconsistent. If I am not doing something wrong, how can this be improved?

**Comment by ihadeed** [comment]
@AmitMY 

This isn't an Ionic Native issue.

You should see the available preferences here https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-splashscreen/#preferences

I think you need to add `AutoHideSplashScreen` and set it to `false`.
