### ISSUE TITLE
Modal on top of google map

### ISSUE THREAD

**Issue by leonhh** [driftyco/ionic-native#1024]
I'm using the google maps plugin which is working totally fine but when presenting a modal on top of the google map all click elements and slide events are not working. However when I change the size of the google map the items which are in the modal but aren't on top of the map anymore are working fine again.

**Way to reproduce**
Create a page with a google map. Add a button to present a modal and add a button inside the modal. Check if the click events work.

**Target OS:** Android 6.0.1
**Ionic version:** 2 final

No errors are being generated.

**Comment by ihadeed** [comment]
This is not an Ionic Native issue. 

I suggest you open an issue with at the [plugin's repo](https://github.com/mapsplugin/cordova-plugin-googlemaps) or the post it on the Ionic Framework forums.
