### ISSUE TITLE
Cannot find name 'CaptureError' from media-capture

### ISSUE THREAD

**Issue by ryaa** [driftyco/ionic-native#1026]
Imported all the required types 

> import { File, FileOpener, FileChooser, Transfer, FileUploadResult, FileTransferError, FileUploadOptions, Camera, MediaCapture, MediaFile, CaptureError, CaptureVideoOptions } from 'ionic-native';

However Visual Studio Code still complains when i reference CaptureError in the component

> message: 'Cannot find name 'CaptureError'.'
> at: '282,28'
> source: 'ts'

What is strange is that all the other types are resolved fine.
I also reviewed similar issues (https://github.com/driftyco/ionic-native/issues/876, https://github.com/driftyco/ionic-native/issues/396) however this does not help

**Comment by ihadeed** [comment]
Should be fixed in latest release
