### ISSUE TITLE
Network

### ISSUE THREAD

**Issue by anivaisu** [driftyco/ionic-native#1028]
Hi ,
  I am Using ionic 2 check internet connection

  this is my code
  i install cordova plugin network information
  import { Network} from 'ionic-native';
  declare var navigator: any;
  declare var Connection: any;
  if(Network.connection === 'none')
      {
        console.log("success");
         let alert = this.alertCtrl.create({
            title: "Internet Connection",
            subTitle:"Please Check Your Network connection",
            buttons: [
                {
                    text: 'Ok',
                    handler: () => {
                        this.platform.exitApp();
                    }
                }
                ]
        });
        alert.present();
       
     }
  App start and mydevice network disconnected
  Network connection cannot check  and  cannot display alert

  I get this warning msg 
 **Native: tried calling Network.connection, but the Network plugin is not installed.
 Install the Network plugin: 'ionic plugin add cordova-plugin-network-information'**
  
 another way i used this
  navigator.connection.type == Connection.NONE 
  i get follow this err
  Type cannot undefined 
  How to fix this issue,
 Kindly advice me,
 Thanks & Regards

**Comment by ihadeed** [comment]
@anivaisu please see https://github.com/driftyco/ionic-native/releases/tag/v2.2.12

You should be calling `Network.type` instead of `Network.connection`.
