### ISSUE TITLE
Plugin Request: Document Viewer (for PDF viewing)

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic-native#1029]
An awesome plugin for viewing PDF documents: https://github.com/sitewaerts/cordova-plugin-document-viewer

Would be amazing if this could be added to ionic native.

**Comment by danielsogl** [comment]
Hey @dylanvdmerwe,

I will add this plugin later this week. This plugin will be really helpful!

**Comment by dylanvdmerwe** [comment]
Epic!
