### ISSUE TITLE
NETWORK

### ISSUE THREAD

**Issue by anivaisu** [driftyco/ionic-native#1034]
Hi all,
 
  I Update ionic-Native in my app
  This is my code
     if(Network.type === 'none')
      {
        console.log("success");
         let alert = this.alertCtrl.create({
            title: "Internet Connection",
            subTitle:"Please Check Your Network connection",
            buttons: [
                {
                    text: 'Ok',
                    handler: () => {
                        this.platform.exitApp();
                    }
                }
                ]
        });
        alert.present();
       
     }

and I was installed Cordova Network plugin Information

Still I am getting this warning msg

**Native: tried calling Network.type, but the Network plugin is not installed.
pluginWarn @ plugin.js:19
plugin.js:24 Install the Network plugin: 'ionic plugin add cordova-plugin-network-information'**

again reinstall the plugin

How to fix it

Kindly advice me,
Thanks & Regards

**Comment by ihadeed** [comment]
Are you wrapping you code with `this.platform.ready()` ?

**Comment by anivaisu** [comment]
yes my code inside this.platform.ready() still I am getting same error pls advice me

**Comment by ihadeed** [comment]
@anivaisu what platform(s) are you getting this error message on? I will try to reproduce the issue on my end.

**Comment by anivaisu** [comment]
**@ihadeed** Platform is android
 Run App using this cmd
ionic serve
display warning msg network plugin not installed
But i was installed the Cordova Network plugin Information

**Comment by ihadeed** [comment]
`ionic serve` runs your app as a website in the browser. It doesn't include any of the cordova platform files. The plugin isn't supposed to work there. You need to run your app on a device or a simulator.

**Comment by anivaisu** [comment]
@ihadeed Thank u so much Now its work
