### ISSUE TITLE
cordova-plugin-network-information: onConnect and onDisconnect events not firing

### ISSUE THREAD

**Issue by megharajdeepak** [driftyco/ionic-native#1036]
I am using this simple example from ionic 2 doc:

```javascript

    constructor(public platform: Platform, public alertCtrl: AlertController) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      
     let disconnectSubscription = Network.onDisconnect().subscribe(() => {
        alert('network was disconnected :-(');
      });

      let connectSub = Network.onConnect().subscribe(()=> {
        alert('network was connected :-)');
      });

      
    });
  }

```

However, this doesn't show up alert message at all. I tried with connection and without connection.

Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
ios-deploy version: Not installed
ios-sim version: Not installed
OS: OS X El Capitan
Node Version: v7.3.0
Xcode version: Xcode 8.1 Build version 8B62

**Comment by stenrdj** [comment]
Same here ! i tried using that code , it doesn't show anything !

**Comment by danielsogl** [comment]
@stenrdj I test this plugin with the docs given example a minute ago and I had no problems. 
Which native version have you installed?

**Comment by stenrdj** [comment]
Its wired !below my configuration :
`
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.10.0
Xcode version: Xcode 8.3.2 Build version 8E2002

`

**Comment by danielsogl** [comment]
Update to 3.10.3 and try it again

**Comment by stenrdj** [comment]
How that possible ,  npm view ionic-native showing this :  'dist-tags': { latest: '3.5.0', test: '2.2.8' }, ?

**Comment by danielsogl** [comment]
Change the version in your package.json file and run npm install

**Comment by stenrdj** [comment]
i tried , unfortunately doesn't work ! 
`npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.10.0
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: ionic-native@3.10.3
npm ERR! notarget Valid install targets:
npm ERR! notarget 3.5.0, 2.9.0, 2.8.1, 2.8.0, 2.7.0, 2.6.0, 2.5.1, 2.5.0, 2.4.1, 2.4.0, 2.3.2, 2.3.1, 2.3.0, 2.2.17, 2.2.16, 2.2.15, 2.2.14, 2.2.13, 2.2.12, 2.2.11, 2.2.10, 2.2.9, 2.2.8, 2.2.7, 2.2.6, 2.2.5, 2.2.4, 2.2.3, 2.2.2, 2.2.1, 2.2.0, 2.1.9, 2.1.8, 2.1.7, 2.1.6, 2.1.5, 2.1.4, 2.1.3, 2.1.2, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.3.27, 1.3.26, 1.3.25, 1.3.24, 1.3.23, 1.3.22, 1.3.21, 1.3.20, 1.3.19, 1.3.18, 1.3.17, 1.3.16, 1.3.15, 1.3.14, 1.3.13, 1.3.12, 1.3.11, 1.3.10, 1.3.9, 1.3.8, 1.3.7, 1.3.6, 1.3.5, 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.2.4, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.1, 1.1.0, 1.0.12, 1.0.11, 1.0.10, 1.0.9, 1.0.8, 1.0.7
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'ionic-hello-world'
npm ERR! notarget 

npm ERR! Please include the following file with any support request:`

**Comment by danielsogl** [comment]
@stenrdj you run the old ionic-native package.
Follow this guide, to upgrade to Ionic Native 3.x: https://github.com/ionic-team/ionic-native/blob/master/README.md

And run npm uninstall --save ionic-native to delete the old package.

**Comment by ArtKuz** [comment]
I have this problem. How I can resolve it? Problem on Android and iOS.

@ionic-native/core : 3.14.0
@ionic-native/network : 3.14.0
ionic (Ionic CLI) : 3.9.0
Cordova CLI : 7.0.1 
Ionic Framework : ionic-angular 3.6.0
ios-deploy : 1.9.1 
Node : v7.9.0
npm  : 4.2.0 
OS : macOS Sierra
Xcode : Xcode 8.3.3 Build version 8E3004b 

```js
this.platform.ready().then(() => {
  this.network.onDisconnect().subscribe(() => {
    console.log('network was disconnected :-(');
  });

  this.network.onConnect().subscribe(() => {
    console.log('network connected!');
  });

  console.log(this.network.onConnect()) // FromEventObservable
});
```

**Comment by Sharanagouda** [comment]
https://ampersandacademy.com/tutorials/materialize-css/ionic-2-framework-network-information-plugin-connectd-disconnected
