### ISSUE TITLE
WIP: Treeshakable

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic-native#1038]
Starting an issue to track making ionic-native treeshakable.

- [ ] Remove decorators
- [ ] Remove window/document references
- [ ] Test rollup for shaking on single plugins

**Comment by ruffiem** [comment]
Tree-shaking is always an interesting topic 👍 I was about to say "Closure" but then I saw the wildcard export on `index.ts` file...

**Comment by John-Luke** [comment]
Any update?

**Comment by ihadeed** [comment]
@John-Luke have you tried Ionic Native v3?

**Comment by mlynch** [comment]
We made lots of progress and have separated out modules. More info for the next release
