### ISSUE TITLE
Transpile fails (Cannot find type definition file for 'node')

### ISSUE THREAD

**Issue by Isigiel** [driftyco/ionic-native#1042]
Since the last ionic native update to 2.5.0 `ionic serve` stopped working.
![usvwct7 1](https://cloud.githubusercontent.com/assets/3612748/22692174/08a694ee-ed3e-11e6-82f1-a6b93c180244.png)

My system info is 
```
Ionic Framework: 2.0.0
Ionic Native: 2.5.0
Ionic App Scripts: 1.0.0
Angular Core: 2.2.1
Angular Compiler CLI: 2.2.1
Node: 7.4.0
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
```

Other then that everything seemed to work. I update ionic-native because my version apparently didn't yet support `Network.type`.

**Comment by bvx89** [comment]
Same problem here. Removing the first line referencing node in the three files (code-push.d.ts, file.d.ts and push.d.ts) fixed the error when building.

**Comment by Isigiel** [comment]
I reverted to an older version for now, don't really want to mess with source files of npm modules

**Comment by ihadeed** [comment]
Thanks for reporting this. I will look into it. For now `ionic-native@2.4.1` should be fine and it supports `Network.type`.

**Comment by ihadeed** [comment]
Both `build` and `serve` working fine with latest version of `ionic-native`. 

Could you please provide steps to reproduce this issue? or maybe an example project.

**Comment by Isigiel** [comment]
This is my project https://gitlab.com/pikandpeople/mobile-next
Just install the 2.5.0 version, that did it for me @ihadeed

**Comment by ihadeed** [comment]
@Isigiel I managed to get the same error with your project and also by creating a fresh project. I will debug and find out the cause. 

It's strange because I have an app here https://github.com/ihadeed/ionic-image-loader-example that I recently upgraded to 2.0.0 and it works well. The repo is at `ionic-native@2.4.1` but I tested with `2.5.0`.

**Comment by ihadeed** [comment]
@Isigiel ok I figured it out. It was a mistake I did when building `ionic-native` before releasing `2.5.0`. Not sure what it was but I fixed it and it works well now. Please update to `ionic-native@2.5.1`.

I apologize for the inconvenience this issue has caused you.

**Comment by Isigiel** [comment]
Thanks you very much for your time and quick support, I'll update right now
