### ISSUE TITLE
Observable error `no_such_method` on `Networl.onchange()` subscription

### ISSUE THREAD

**Issue by bgondy** [driftyco/ionic-native#1043]
Hi, I get the error message `no_such_method` when I try to subscribe to network changes :

```js
Network.onchange().subscribe(
  (v) => console.log(v),
  (err) => console.error(err) // {error: "no_such_method"}
);
```

I've tried to wait for platform ready state but I get the same error.

```js
this.platform.ready()
  .then(() => {
    Network.onchange().subscribe(
      (v) => console.log(v),
      (err) => console.error(err)
    );
  });
```

If it could help, I have the following in my `config.xml`:

```xml
    <engine name="android" spec="~6.1.2" />
    <plugin name="ionic-plugin-keyboard" spec="~2.2.1" />
    <plugin name="cordova-plugin-whitelist" spec="~1.3.1" />
    <plugin name="cordova-plugin-console" spec="~1.0.5" />
    <plugin name="cordova-plugin-statusbar" spec="~2.2.1" />
    <plugin name="cordova-plugin-device" spec="~1.1.4" />
    <plugin name="cordova-plugin-splashscreen" spec="~4.0.1" />
    <plugin name="cordova-sqlite-storage" spec="~2.0.1" />
    <plugin name="cordova-plugin-network-information" spec="~1.3.1" />
```

Maybe I'm doing something wrong or it is a case issue (`onchange` instead of `onChange`) regarding to other `Network` methods that seem to work as expected (such as `onConnect` and `onDisconnect`). Thanks for your help.

**Comment by ihadeed** [comment]
This is a bug with `ionic-native`. I will fix it as soon as I get a chance.

For now, you can do one of the following:

1. Use `onConnect()` and `onDisconnect()` methods.

2. Before you call `Network.onchange()` execute the following code:
```typescript
navigator.connection.onchange = 'any truthy value';
```
You will also need to put this at the top of your code to make solution # 2 work:
```typescript
declare var navigator: any;
```

**Comment by bgondy** [comment]
@ihadeed Thank you.

For now I've used solution # 1 (imho cleaner than # 2):

```js
Observable.merge(Network.OnConnect(), Network.onDisconnect())
    .subscribe(e => console.log(e), err => console.error(err));
```
