### ISSUE TITLE
writeExistingFile fails with PATH_EXISTS_ERR, implementation seems incorrect (includes workaround)

### ISSUE THREAD

**Issue by waynebloss** [driftyco/ionic-native#1044]
When I use the `File.writeExistingFile` method, it fails with a `PATH_EXISTS_ERR`.

Looking at the implementation of `writeExistingFile`, I see one line:

`return File.writeFile(path, fileName, text, { create: false });`

However, according to the help for `createFile`, I see that *The **replace** boolean value determines whether to replace an existing file with the same name. If an existing file exists and the replace value is false, **the promise will fail** and return an error.*

So, I changed my code to do the following and now overwriting existing files works:

```js
return $cordovaFile.writeFile(path, fileName, data, { create: false, replace: true });
```
*(I'm using Ionic v1, with Ionic-native v2.2.16)*

**Comment by ihadeed** [comment]
Thanks for reporting this. I will fix it soon.

The `create` option doesn't even do anything. It should just have `replace: true`.

The only options that matter are `append`, `replace` and `truncate`. See https://github.com/driftyco/ionic-native/blob/master/src/plugins/file.ts#L682-L683 and https://github.com/driftyco/ionic-native/blob/master/src/plugins/file.ts#L710
