### ISSUE TITLE
diagnostic plugin: add function getExternalSdCardDetails()

### ISSUE THREAD

**Issue by ghenry22** [driftyco/ionic-native#1045]
this function isn't currently available through ionic native, it is one of the only ways to actually get a handle on the sdcard on android devices so it would be great if this could be added to the ionic-native wrapper for the diagnostic plugin.

**Comment by ghenry22** [comment]
great I'll try this out!

**Comment by ihadeed** [comment]
@ghenry22 please update to `ionic-native@2.7.0`
