### ISSUE TITLE
3.0.0-alpha.1 requires RxJS 5.0.1 instead of 5.0.0-beta.12

### ISSUE THREAD

**Issue by FdezRomero** [driftyco/ionic-native#1046]
Hi there,

I'm trying `3.0.0-alpha.1` following the instructions in @mlynch's [blog post](http://blog.ionic.io/help-us-test-ionic-native-3-x/) and I noticed a version mismatch regarding RxJS:

- `ionic-angular@2.0.0` has a fixed dependency on `rxjs@5.0.0-beta.12`
- `ionic-native@3.0.0-alpha.1` requires a peer of `rxjs@^5.0.1`

I'm guessing that `rxjs@5.0.1`would work, but I'm sure Ionic has set a fixed version of RxJS for a good reason and I'm unaware of the possible side effects.

**Is it okay to change `rxjs@5.0.0-beta.12` for `rxjs@5.0.1`? If so, can you update the blog post?**

Thanks a lot and keep rocking!

**Comment by jsayol** [comment]
Just FYI, I'm currently on `rxjs@5.1.0` and everything works fine. I was also on `5.0.3` for a while with the same results.

There hasn't been any major or breaking changes at all since beta.12 so I think it's safe to upgrade. For reference: https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md

**Comment by FdezRomero** [comment]
Thanks @jsayol, I saw a bunch of breaking changes since beta 12 in their changelog so I decided to play it safe and ask here ;-)

**Comment by jsayol** [comment]
Well you're right, I forgot there were indeed some breaking changes. These don't seem to be affecting my app at all but caution is definitely required.

Probably the best thing to do here would be to match whatever version is being used in the ionic package. Ionic itself should upgrade to the latest stable version of RxJS (with proper testing) but I guess that discussion doesn't belong here :)

**Comment by ihadeed** [comment]
This is fixed now. Please update to latest version `3.0.0`.
