### ISSUE TITLE
ImagePicker.requestReadPermission promise resolves before user accepts

### ISSUE THREAD

**Issue by ankitjainOfficial** [driftyco/ionic-native#1050]
requestReadPermission promise resolves with 'OK' as soon as the request for permission option pops up.

How can I check, if the user allows or denies the permission, so that I can show a proper message, if the user denies, or move forward with the Image selection process if the user allows the permission.

I tried, calling the hasReadPermission again once the promise resolves. This is like an infinite loop. And the application freezes during the process.

Thanks,

**Comment by ankitjainOfficial** [comment]
I went through the plugin code, and it seems the issue lies with the plugin. Rather, not an issue, but the plugin states:

```
// This method executes async and we seem to have no known way to receive the result
// (that's why these methods were later added to Cordova), so simply returning ok now.
```

Thanks,

**Comment by jknisley** [comment]
For anyone who stumbles on this looking for a better solution, instead of using ImagePicker.requestReadPermission(), use Diagnostic.requestCameraAuthorization(). That won't resolve until the user has actually accepted or denied permissions, and upon acceptance will give you access to the camera and photo gallery.

**Comment by Godwack** [comment]
> For anyone who stumbles on this looking for a better solution, instead of using ImagePicker.requestReadPermission(), use Diagnostic.requestCameraAuthorization(). That won't resolve until the user has actually accepted or denied permissions, and upon acceptance will give you access to the camera and photo gallery.

This works only on Android, iOS doesn't provide both permissions.
