### ISSUE TITLE
'@ionic-native/barcodeScanner' is not in the npm registry.

### ISSUE THREAD

**Issue by yargomascarenhas** [driftyco/ionic-native#1055]
After the post in Ionic Blog with a title "Help us test Ionic Native 3.x", i try to update my application replace the ionic-native fot @ionic-native feature, in fact most part of my plugins like Camera and others is word nice but only one BarcodeScanner not in the npm when i try run npm intall in my project.

**Comment by ihadeed** [comment]
Currently, the package names match the directory names here: https://github.com/driftyco/ionic-native/tree/v3/src/%40ionic-native/plugins

So the Barcode Scanner plugin's package name is [`@ionic-native/barcodescanner`](https://www.npmjs.com/package/@ionic-native/barcodescanner).
