### ISSUE TITLE
ionic-native 3.0 naming inconsistency 

### ISSUE THREAD

**Issue by NoNameProvided** [driftyco/ionic-native#1058]
The naming of the packages is not consistent. Some works has `-` in them some is just written together. Do we have any reason for this?

Examples: 

Themeable browser: `cordova-plugin-themeablebrowser` vs `@ionic-native/themeable-browser`
Local Notfications: `...plugin.local-notification` vs `@ionic-native/localnotifications`

**Comment by ihadeed** [comment]
We plan on fixing this for the next release.
