### ISSUE TITLE
bug: Network.onConnect fires when app goes offline

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#1068]
_From @pjc2007 on February 13, 2017 5:9_

**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>When I set the phone into flight mode, I only ever get the onConnect() called, and never the onDisconnect().

Using the following code to test...

Network.onDisconnect().subscribe(() => {
      this.logger.debug('network was disconnected ');
      this.onOnlineStatusSubject.next(false);
    });

    Network.onConnect().subscribe(() => {
     this.logger.debug('network connected!');
     
     // If we have any problems here, see doco where they put in a delay before examining network type
     this.onOnlineStatusSubject.next(true) ;
    });</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#10412_

**Comment by wundo** [comment]
I think the title is misleading, I've done some testing locally and I do get onDisconnect() triggered, but never onConnect()

**Comment by wundo** [comment]
Any update?

**Comment by ihadeed** [comment]
I just tested this out using the latest version of plugin + ionic native, can't reproduce the issue.
