### ISSUE TITLE
Toast native not working

### ISSUE THREAD

**Issue by Lindstrom1989** [driftyco/ionic-native#107]
Getting "-----async gap-----Error" from browser_adapter.ts

Also getting in browser, can't interface with plugin.

**Comment by zhouhao27** [comment]
Doesn't work in iOS either. Also the **styling** is not supported.

**Comment by ihadeed** [comment]
@Lindstrom1989 Could you try again now with the latest release?

@zhouhao27 the styling has been added in the latest release.

**Comment by zhouhao27** [comment]
Thanks. I'll try.

**Comment by Lindstrom1989** [comment]
Yeah it's working now, not tried styles yet though

**Comment by liangminhua** [comment]
now,it 's not working

**Comment by liangminhua** [comment]
angular1 is not working

**Comment by bairathirahul** [comment]
same here. Angular1 version is not working.

**Comment by ihadeed** [comment]
@bairathirahul @liangminhua please open a new issue with steps to reproduce.
