### ISSUE TITLE
No error on ionic serve if remove ionic-native package for beta testing

### ISSUE THREAD

**Issue by mburger81** [driftyco/ionic-native#1073]
We are testing your @ionic-native/abc 3.0 alpha implementation

After removing ionic-native 2.4.1 from package.json, delete node_modules folder and reinstall all with npm install I can see no error on VSCODE for missing 'ionic-native' StatusBar and Splascreen in app.component.ts

We launch the app using ionic serve and there are no error only after open the app browser in browser we finally get an error

Runtime Error
Cannot find module "ionic-native"

Same thing for ionic emulate android

**Comment by ihadeed** [comment]
You need to import from @ionic-native/*

For example:

```typescript
import { Camera } from '@ionic-native/camera';

```

**Comment by mburger81** [comment]
That's what I'm doing!

in app.component.ts there are the standard 
`import { StatusBar, Splashscreen} from 'ionic-native';`

    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();
      Splashscreen.hide();
    });

but on `ionic serve` there is no error given

**Comment by ihadeed** [comment]
@mburger81 can you please share a minimal project demonstrating this issue? A Github repo link would be nice.

**Comment by mburger81** [comment]
I created a simple clean ionic project and removed `ionic-native 2.4.1` from **package.json**. After that I removed the `node_modules` folder and did a new `npm install`
So there is no `ionic-native` installed, but as you can see in app.component.ts there is used `StatusBar` and `Splashscreen` from `ioni-native` which is not installed anymore.
```
import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar, Splashscreen } from 'ionic-native';

import { HomePage } from '../pages/home/home';

@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  rootPage = HomePage;

  constructor(platform: Platform) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();
      Splashscreen.hide();
    });
  }
}
```

on running now ionic serve from terminal I get no error! But I think the builder should give an error or not? The app.component.ts could not find `import from ionic-native`. but there is now error.

On loading app in browser finally I get the error
```
Runtime Error
Cannot find module "ionic-native"
```

This should be more an error from ionic-cli than from ionic-native? Right?
Or is that by design, no error on `ionic serve`?

**Comment by longzheng** [comment]
I had the same problem.

I uninstalled ``ionic-native`` from npm which removed the folder in ``node_modules``. Then it caused issues at build complaining about cannot finding module.

I fixed it by keeping ``ionic-native`` with ``npm install ionic-native`` and not saving it to my ``package.json``

**Comment by rx4hvn** [comment]
@longzheng It's not saving into your package.json because your are not saving it. Use the command below to update package.json also.

`npm install ionic-native --save`
