### ISSUE TITLE
Transfer Plugin not found - 3.0.0-alpha.1

### ISSUE THREAD

**Issue by graphefruit** [driftyco/ionic-native#1074]
#### Short description of the problem:
I've tried to get `Transfer` to work with the latest native changes, but it doesn't work.
`Cannot find module "@ionic-native/transfer"`

Other modules can be found like: 
```
    "@ionic-native/statusbar": "3.0.0-alpha.1",
    "@ionic-native/splashscreen": "3.0.0-alpha.1",
    "@ionic-native/push": "3.0.0-alpha.1",
    "@ionic-native/googleanalytics": "3.0.0-alpha.1",
```

My code:
`import {Transfer} from '@ionic-native/transfer';`

package.json:
`"@ionic-native/transfer": "3.0.0-alpha.1",`

I've also tried to say `filetransfer` or also `file` but neither of them worked.

#### What behavior are you expecting?
Working import. 

**Which @ionic/app-scripts version are you using?**
3.0.0-alpha.1

Thanks in advance & Greetings
Graphefruit

**Comment by danirb** [comment]
This work for me:

package.json:
`    "@ionic-native/filetransfer": "3.0.0-alpha.1"`

import:
`     import { Transfer } from '@ionic-native/filetransfer';`

**Comment by graphefruit** [comment]
Okay, this issue just occures if I'm realy trying to access the module.
If I'm just importing, its working, but soon as I do:
`const fileTransfer = new Transfer();`
It crashes with the error `Cannot find module "@ionic-native/filetransfer"`

**Comment by danirb** [comment]
I use without problem, 
in /src/declarations.d.ts : 
`    declare module '*';`
or  try to install the plugin "ionic plugin add..."

**Comment by graphefruit** [comment]
Hmm thanks for the suggestions, I tried to remove and add the plugin again:
```
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-file 4.3.1 "File"
cordova-plugin-file-transfer 1.6.1 "File Transfer"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```
Didn't help.

Inside the declarations.d.ts this content already exists.

**Comment by danirb** [comment]
npm rebuild
npm install

**Comment by graphefruit** [comment]
@danirb  thanks, rebuild looked like was the key. Had already removed the node_modules folder and run npm install.

Now its working! 👍 
Thank you!
