### ISSUE TITLE
Integrate native plugin NativePageTransitions into ionic navigation & drawer

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic-native#1075]
Plugin:
http://ionicframework.com/docs/v2/native/nativepagetransitions/

Currently, my application drawer, and navigation `push` is felling choppy, and I saw that there is a native plugin for it. (I am using the side-nav application)

- Is there an integration guide? Docs are pretty lacking
- I found [this](https://forum.ionicframework.com/t/ionic-2-nativepagetransitions/69536/2) usage, but I really don't like it. It integrates the plugin into life cycle events?
- Is there a way to integrate into the native navigation?

**Comment by ihadeed** [comment]
Docs are updated now.
