### ISSUE TITLE
Degree of ngCordova API conformance strictness

### ISSUE THREAD

**Issue by rapropos** [driftyco/ionic-native#108]
Apologies if this is documented somewhere or if this isn't the proper way to raise this topic (as an issue), but are there rules as to how precisely ionic-native must mimic the API signature of previous ngCordova plugins?

As an example, the recent [File plugin addition](https://github.com/driftyco/ionic-native/pull/76) lists the lack of existence of `options.append` and `options.truncate` as the reason that `writeFile` has not yet been implemented. I assume this is referring to the following code in [the ngCordova version of the File plugin](https://github.com/driftyco/ng-cordova/blob/master/src/plugins/file.js):

```
        writeFile: function (path, fileName, text, replaceBool) {
          var q = $q.defer();

          if ((/^\//.test(fileName))) {
            q.reject('file-name cannot start with \/');
          }

          replaceBool = replaceBool ? false : true;

          var options = {
            create: true,
            exclusive: replaceBool
          };

          try {
            $window.resolveLocalFileSystemURL(path, function (fileSystem) {
              fileSystem.getFile(fileName, options, function (fileEntry) {
                fileEntry.createWriter(function (writer) {
                  if (options.append === true) {
                    writer.seek(writer.length);
                  }

                  if (options.truncate) {
                    writer.truncate(options.truncate);
                  }
```

As best as I can see, `options.append` and `options.truncate` can't ever be set, so they're basically dead code. They could be useful, though. So I was thinking that it would be possible to replace the `replaceBool`with an `options` object that can contain the boolean properties "replace", "append", and "truncate". For backwards compatibility, if a boolean is passed as `options`, it would be treated as a lone "replace" option. So calling code migrating from ngCordova would still work as expected, but new code targeting the ionic-native version could take advantage of more fine-grained control of options.

Is this sort of thing considered desirable, or do you want absolutely no deviation from the calling conventions that were established with ngCordova?

**Comment by ihadeed** [comment]
Hey sorry I missed this earlier.

Feel free to do anything as long as it matches this repo's style. There is no need to stick to ngCordova's conventions!
