### ISSUE TITLE
Ionic native file plugin is broken and does not work

### ISSUE THREAD

**Issue by cambronjay** [driftyco/ionic-native#1081]
- I created a new ionic 2 project 
- Added the ionic native file plugin  via npm ionic plugin add cordova-plugin-file
- Added the example code provided by the docs in my component

The plugin breaks the app when running in an emulator or on a device. 
A blank screen appears and the console will log either a type error or promise rejection in relation to
cordova.file.dataDirectory not being defined. It looks like the plugin expects a string when using any of the methods, but the directory is being passed as an object? Either way the plugin does not work at all.

**Comment by cambronjay** [comment]
It would appear that typings are missing somewhere for the ionic native file plugin and cordova. I noticed that File.resolveDirectoryUrl does not actually exist as a function anywhere etc. Logging cordova.file will work, but using the ionic native plugin will not.

**Comment by cambronjay** [comment]
Update: I found that if i set a variable as let filepath = cordova.file.dataDirectory
Then convert it to a string with let path = filepath.toString()
Then pass it to on of the methods like create directory it works. The docs are wrong and confusing for this plugin as it's looking for a string, but is always being passed in object.

**Comment by ihadeed** [comment]
@cambronjay `cordova.file.dataDirectory` is a string, it's not an object.

All plugins need to be used after device is ready. You can inject `Platform` in any component/service and then call `this.platform.ready().then(() => { // call plugin here }`
