### ISSUE TITLE
ionic native 3 . my app increse from 4.7 Mb to 6.84 Mb

### ISSUE THREAD

**Issue by medst** [driftyco/ionic-native#1085]
false . my app increse from 4.7 Mb to 6.84 Mb after using ionic-native 3 . as plugins i have : admon, network, splashscreen, statusbar, apprate, socialsharing

**Comment by mlynch** [comment]
Not sure what you're asking. Are you doing a prod build?

Technically, your bundle after v3 should be less because there's just less code. Are you sure you aren't still referencing the old ionic-native somewhere?

**Comment by medst** [comment]
no im not referencing the old ionic-native, i have deleted from my package, and yes i do prod build.
