### ISSUE TITLE
ScreenOrientation.orientation returns object

### ISSUE THREAD

**Issue by B-Stewart** [driftyco/ionic-native#1091]
I'm running into an issue where `ScreenOrientation.orientation` returns `{ angle: 0, onchange: null, type: "portrait-primary" }` instead of the typescript definition specified `"portrait-primary"` string. This wouldn't be a huge problem except that I am getting a transpile error while building because ionic-native typescript defs say that "Property 'type' does not exist on type 'string'" which makes sense because the def is not matching the actual.

According to `cordova plugin list` I am using `cordova-plugin-screen-orientation 2.0.0-dev "Screen Orientation"`
According to `config.xml` I am using `<plugin name="cordova-plugin-screen-orientation" spec="https://github.com/apache/cordova-plugin-screen-orientation"/>` (I was using the old repo, but then read that it was no longer maintained so I swapped, both had this issue).
I am using `ionic-native 2.5.1` (though the issue seemed present on 2.2.11 as well)

Any work around to either ignore the error or get the correct string call?

**Comment by ihadeed** [comment]
I just merged a PR to revert our API to support version 1.4.1 of the plugin.

Once v2.0.0 of `cordova-plugin-screen-orientation` is stable, I will update our API to support it.

**Comment by ruffiem** [comment]
@B-Stewart you can use

```TypeScript
ScreenOrientation.orientation['type']
```

until the API fully support the next version of the plugin

**Comment by matejamateusz** [comment]
@ruffiem Thank you very much for the workaround!

@ihadeed Can't you just make a fix for the current version cause I think device-orientation plugin is essential for mobile developers and it should work 100% with no workarounds. Cheers!

**Comment by ihadeed** [comment]
@matejamateusz the current latest version of `ionic-native` supports version `1.4.1` of the plugin. We will edit our wrapper to support `2.0.0` when it's stable.

**Comment by matejamateusz** [comment]
@ihadeed Indeed. Thank you!

**Comment by ihadeed** [comment]
Sorry I forgot to update this issue.

The latest version of Ionic Native 3.x supports the latest version of this plugin now.,
