### ISSUE TITLE
@ionic-native/app-version@3.1.0-alpha.1: dependency to @ionic-native/utils is missing

### ISSUE THREAD

**Issue by Ritzlgrmft** [driftyco/ionic-native#1094]
Therefore `npm install @ionic-native/app-version` produces 

```
Error: Cannot find module '@ionic-native/utils'
```

After installing `@ionic-native/utils`, I was able to install `@ionic-native/app-version` as well.

**Comment by mlynch** [comment]
Thanks, will be fixed in a release shortly
