### ISSUE TITLE
OneSignal getTags has race condition, promise is resolved only for the last call

### ISSUE THREAD

**Issue by NoNameProvided** [driftyco/ionic-native#1100]
Running the following code snippet: 
```ts
OneSignal.getTags().then(console.log);
OneSignal.getTags().then(console.warn);
```

will write the subscribed tags to the console with `console.warn`.

![screen shot 2017-02-20 at pm 4 40 19](https://cloud.githubusercontent.com/assets/4706265/23131702/4e8d3010-f78b-11e6-8e61-8227cfb99b81.png)

The expected behaviour would be to resolve both promise with the subscribed tags.

**Comment by NoNameProvided** [comment]
Running 
```ts
plugins.OneSignal.getTags(console.log, console.error);
plugins.OneSignal.getTags(console.warn, console.error);
```

Will write the tags to the console twice with `console.warn`, so the OneSignal plugins has the wrong behaviour. I have opened an issue there: OneSignal/OneSignal-Cordova-SDK/issues/158

I suggest keeping this ticket open to track the progress.

**Comment by NoNameProvided** [comment]
The answer in the linked repo confirms that for simplicity only one (the last) callback is stored. I am started the discussion about how to fix it, but at least this should be highlighted in the docs until it's gets fixed.

**Comment by ihadeed** [comment]
Closing since this is a plugin issue.

**Comment by NoNameProvided** [comment]
Some higlight in the docs would be nice, not? This is totally not the expected behaviour even if the underlying plugin causes this.

**Comment by ihadeed** [comment]
@NoNameProvided sure

Does this describe the "quirk" well:
> You must wait for `getTags` to resolve before calling it again, as the plugin will only process the last method call and discard any previous ones.

**Comment by NoNameProvided** [comment]
Yes, looks good!

**Comment by ihadeed** [comment]
Thanks @NoNameProvided just pushed a commit for that. It will be live in the next doc update.
