### ISSUE TITLE
media-plugin status events "this" is undefined within the callback method

### ISSUE THREAD

**Issue by ghenry22** [driftyco/ionic-native#1112]
This is an odd one and I can only assume that it is somehow related to zones or callbacks not being in the right zone but could be completely off.

Basically I listen for status updates from the media plugin, they arrive and I console.log them to verify, I see the status change as the media playback state change.

If I try to use the returned value from status or update any variables though the updates do not seem to be caught by change detection.

So for example if I want to show a "loading" image while a sound buffers and then change that to a "pause" image when status changes to 2 (or playing).  I receive the status update, I console.log it to verify it came through, update say this.status.  Nothing happens.

I have tried wrapping the change inside the callback for status with zone.run but it doesn't make any difference.

Just did some more testing it looks like within the callback method "this" is undefined, at least trying to just console.log this.anything prints undefined within the callback.

**Comment by ihadeed** [comment]
Can you share your code here?

Also it's worth noting that you should use arrow functions for these callbacks, and not regular functions. The moment you write `function() { }` you're basically creating a new scope, and when you call `this` it will refer to the function and not the class that it's in.

**Comment by ghenry22** [comment]
I'm writing function() etc...

I am actually just passing in the name of an existing function (ie this.doUpdate) but I guess that is basically doing the same as the above. I will rewrite it with an arrow function and see if that fixes and update.

Thanks, probably should have thought of trying that!
