### ISSUE TITLE
cordova-plugin-datepicker: repository maintainer inactive

### ISSUE THREAD

**Issue by marpstar** [driftyco/ionic-native#1114]
The repository for Ionic's cordova-plugin-datepicker has no active maintainer. I opened [an issue](https://github.com/VitaliiBlagodir/cordova-plugin-datepicker/issues/199) on that repository in August 2016 specifically asking if the maintainer is still active. 6 months later and still no response. 

We have our own fork with enhancements we needed, but what will the policy be moving forward for these types of situations?

**Comment by ihadeed** [comment]
If you've made major changes that will fix issues for everyone, you can share more details so we can review them. Then we could change our documentation to instruct developers to install the plugin from your repo/npm instead.
