### ISSUE TITLE
subscribe and unsubscribe

### ISSUE THREAD

**Issue by ninechung** [driftyco/ionic-native#1117]
`
constructor(platform: Platform) {
    this.platform.ready().then(() => {
      this.platform.pause.subscribe(() => {
        console.log('MessagePage App paused');
      });

      this.platform.resume.subscribe(() => {
        console.log('MessagePage App resume');
        });
      });
    });
  }

ionViewWillUnload() {
    this.platform.pause.unsubscribe();
    this.platform.resume.unsubscribe();
  }
`

throw an error when second construct class.
`exception nativeEvalAndFetch : ObjectUnsubscribedError: object unsubscribed`

**Comment by ihadeed** [comment]
This issue was moved to driftyco/ionic#10612
