### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by rapropos** [driftyco/ionic-native#112]
What is the process for adding tests for modifications or new plugins? Does one simply add things to test/app.js? I have some changes and additions to the File plugin that I would like to consider contributing, but I want to make sure that things are working properly and consistently with what has been contributed so far.

**Comment by ihadeed** [comment]
Hey Robert,

AFAIK there is no testing process as of now.  I did attempt to create one
at some point but it wasn't completed, as my approach had some problems
with it.

An ideal test would be to make sure that the Ionic native wrapper method is
invoking the plugin method.

When I test plugins, I usually load up a blank Ionic app on my Android
device that has all plugins installed. I make sure to include Ionic native
in there some how. Then I use chrome remote debug to access the plugins via
the console.

I would type in something like this in the console
`IonicNative.Dialogs.alert("....")`
