### ISSUE TITLE
Optional array of PayPalItem objects is of type string?

### ISSUE THREAD

**Issue by gujiman** [driftyco/ionic-native#1121]
Hi, for native PayPal plugin the 'items' should be an array of PayPalItem, but its defined as string??
 /**
   * Optional array of PayPalItem objects.
   */
  items: string;

https://github.com/driftyco/ionic-native/blob/master/src/plugins/pay-pal.ts#L196

**Comment by gujiman** [comment]
I got it working by making the following 3 changes:

1.  Change type String into Array: https://github.com/driftyco/ionic-native/blob/master/src/plugins/pay-pal.ts#L196

`items: Array<PayPalItem>;`

2. Make 'sku' optional: https://github.com/driftyco/ionic-native/blob/master/src/plugins/pay-pal.ts#L223

 `constructor(name: string, quantity: number, price: string, currency: string, sku?: string) { `

3. Make 'sku' optional:https://github.com/driftyco/ionic-native/blob/master/src/plugins/pay-pal.ts#L249

`sku?: string;`

--------------------------------------
**example Usage:**
```
...
let payment = new PayPalPayment("2.00", 'GBP', 'Description', 'sale');
let item1 = new PayPalItem("laptop", 1, '1.00', "GBP");
let item2 = new PayPalItem("tablet", 1, '1.00', "GBP");
payment.items = [item1, item2];
...
```

**Comment by ihadeed** [comment]
Fixed and will be available in the next release.

**Comment by gujiman** [comment]
Hi, also 'sku' needs to be made 'optional' as explained above. i.e:

2. Make 'sku' optional: https://github.com/driftyco/ionic-native/blob/master/src/plugins/pay-pal.ts#L223

 `constructor(name: string, quantity: number, price: string, currency: string, sku?: string) { `

3. Make 'sku' optional:https://github.com/driftyco/ionic-native/blob/master/src/plugins/pay-pal.ts#L249

`sku?: string;`
