### ISSUE TITLE
Adding ionic-native to index.html ionic 1

### ISSUE THREAD

**Issue by FarhanSaleem** [driftyco/ionic-native#1123]
Hi, 
  I am new to this plugin and came here wanting to work with ionic-plugin-deeplinks
example of using it with ionic 1 at https://github.com/driftyco/ionic1-deeplinks-demo/blob/master/www/js/app.js
 which i believe has a dependency on ionic-native....I have installed it with npm and it shows up under my installed node modules... I read i should include a link to the ionic.native.min.js file in my index.html which i have done as shown in my project pic which shows the location of the ionic-native module. I have also listed this module as a dependency in my app as follows 
    `var app = angular.module('letsbounce', [
  'ionic',
  'ionic.native',
  'ngCordova',
]);`
. I also tried '**ionic-native**' but its not working. It keeps telling me Failed to instantiate module ionic.native due to: Error: [$injector:nomod] Module 'ionic.native' is not available!  Can someone please point to me what im getting wrong here iv tried this for a few hours with no luck! :( your helps really appreciated! 
<img width="1037" alt="screen shot 2017-02-28 at 11 40 46 pm" src="https://cloud.githubusercontent.com/assets/8231145/23446344/8203769e-fe10-11e6-9100-7f7efafc20dc.png">

**Comment by ihadeed** [comment]
@FarhanSaleem copy `ionic.native.min.js` to your some folder inside `www`. For example: `lib/ionic.native.min.js`. 

When you serve you app from `www` directory, it is unable to access anything outside of there.
