### ISSUE TITLE
InAppBrowser not available in Project

### ISSUE THREAD

**Issue by flavordaaave** [driftyco/ionic-native#113]
I've installed ionic-native to my ionic (TS) project using `npm install ionic-native --save` and looking at my npm_modules folder I can see that `"version": "1.1.0"` is installed.

In my project, TypeScript complains that `ionic-native has no exported member called 'InAppBrowser' `.
I've looked into node_modules/ionic-native/dist/plugins and there I also didn't find the source file for the inappbrowser (on github I could see that there is a `inappbrowser.ts` file...

**Comment by ihadeed** [comment]
Hey @flavordaaave ,

The InAppBrowser plugin is not available in the NPM package yet. It should be there in the next release.

Meanwhile, you can clone the repo and run the commands `npm install && npm build_bundle` to get the latest compiled files.
