### ISSUE TITLE
Unable to get the device name

### ISSUE THREAD

**Issue by maruthi-menlo** [driftyco/ionic-native#1131]
Please let me know how to get device name from ionic-native.

import {Device} from 'ionic-native';

In above package we don't have device name. Please let me know how to get device name using angular2/ionic2

**Comment by ihadeed** [comment]
You mean device model?
```
import {Device} from 'ionic-native';

console.log(Device.model);
```

**Comment by maruthi-menlo** [comment]
Using cordova-plugin-device-name plugin I'm able to get the device name. Thanks for your time.
