### ISSUE TITLE
google-analytics-plugin

### ISSUE THREAD

**Issue by jasdf2351** [driftyco/ionic-native#1133]
Hi,
I'm wondering how long it'll be until the new version gets merged in to ionic-native, specifically this PR?
https://github.com/danwilson/google-analytics-plugin/pull/373
Thank you.

**Comment by ihadeed** [comment]
@jasdf2351 I don't see any API changes in that PR that we have to implement. 

You can just update the installed version of Google Analytics to latest version and it should work fine with our wrapper.

**Comment by jasdf2351** [comment]
@ihadeed thank you, I think I've misunderstood how the plugins work... I thought that the external repos had to be updated first and then you guys copy in the code, tweaking it to fit as you need to in your wrappers.

How do I reference the updated version and not use the one built in to ionic-native?
