### ISSUE TITLE
Safariviewcontroller callbacks not defined

### ISSUE THREAD

**Issue by aggarwalankush** [driftyco/ionic-native#1137]
Safariviewcontroller hide method has success and error callbacks https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller/blob/master/www/SafariViewController.js#L19

but it's not defined in ionic-native plugin
https://github.com/driftyco/ionic-native/blob/master/src/plugins/safari-view-controller.ts#L84

how can I use these callbacks?

**Comment by ihadeed** [comment]
The method returns back a promise that substitutes the callbacks. There was a mistake in the typings where it says it returns ` void` but it actually returns a Promise. I just fixed that here: https://github.com/driftyco/ionic-native/commit/27fdce7af2cdb7c0cc6b904a4cd832e8315c5ddd
