### ISSUE TITLE
bug: File.copyFile fails since ionic-native@2.6.0

### ISSUE THREAD

**Issue by hueper** [driftyco/ionic-native#1139]
**Since ionic-native@2.6.0**:

When I use the `File.copyFile` method and start with `ionic serve`, it fails with: 

"**Supplied parameters do not match any signature of call target.**"

I use `File.copyFile` like this:

```
File.copyFile(path, fileName, cordova.file.dataDirectory, newFileName)
  .then(success => {
    console.log('success');
  })
  .catch(err => {
    console.log('err');
  });
```
Atom says: "**Cannot invoke an expression whose type lacks a call signature**"

![image](https://cloud.githubusercontent.com/assets/6799184/23550188/151915dc-0010-11e7-8e41-0fff18865bc0.png)

**Possible fix:**
I guess this is due to this change:
https://github.com/driftyco/ionic-native/commit/c1748bbc283a867f3c0c91c9889de145b84779c3

A revert fixes this issue:
`static copyFile(path: string, fileName: string, newPath: string, newFileName: string): Promise<Entry|FileError>`

**Comment by NoNameProvided** [comment]
I can confirm this issue as well.

**Comment by ihadeed** [comment]
I will try to reproduce this. I don't think the commit you referenced is the issue though, the signature of the method was not changed. Only the return type changed.

**Comment by ihadeed** [comment]
Please update to 2.8.0
