### ISSUE TITLE
Dialogs plugin is incompatible with ionic serve

### ISSUE THREAD

**Issue by vejja** [driftyco/ionic-native#1140]
The Dialogs native-plugin for Ionic2 has no fallback behaviour when cordova.js is not loaded.
This crashes applications during the development phase in the browser, as soon as the native dialog is called.

It would be great if the plugin could default to standard browser-based alerts when developing with ionic-serve

**Comment by ihadeed** [comment]
`ionic serve` runs your app as a website, so any Cordova platform related stuff wont be available there.
