### ISSUE TITLE
cordovaPlugins package.json vs config.xml

### ISSUE THREAD

**Issue by sagivf** [driftyco/ionic-native#1143]
For a long time I have been confused by the fact that the plugins are defined in both places.
Also `ionic state` is not documented and it's not clear how it works.
It's not clear how to manage and upgrade your plugins.

**Comment by ihadeed** [comment]
Cordova CLI stores the plugin data in `config.xml`. When you run `ionic state save` it will store the plugin data in `package.json`.

**Comment by sagivf** [comment]
Thanks @ihadeed I guess this is more appropriate under the Ionic CLI, but I think it's worth handling under the Ionic Native umbrella, but I can open a ticket there.

- So the thing is that "cordovaPlugins" in the package.json don't have a version and the xml does.
I think this is something that should be addressed. Every now an then my build gets into broken state and it's very hard to tell who is the culprit and what is the best course of action.

I think it would be better if ionic even deprecated some of it's CLI Api's since it cases confusion.

I find the native integrations and build (especially IOS...) to be the hardest part in the my development. Ionic Native is a great step in the right direction but there is more that can be done.

Thanks again,
Sagiv Frankel

**Comment by ihadeed** [comment]
@sagivf yeah this matter would be an Ionic CLI issue. 

Here's a trick to lock down versions in `package.json`:

Instead of:
```
"cordovaPlugins": [
  "cordova-plugin-camera"
]
```

You can have:
```
"cordovaPlugins": [
  {
    "id": "cordova-plugin-camera",
    "locator": "cordova-plugin-camera@1.3.0"
  }
]
```
