### ISSUE TITLE
Calendar.requestReadWritePermission() works but does not resolve on Android

### ISSUE THREAD

**Issue by BSWG** [driftyco/ionic-native#1144]
The function does show the permission dialog on Android 6. But when pressing 'Allow' it does not resolve. So for my app when a user tries to add something to the users calendar, the user needs to press the 'Add' button twice. First asking permission and afterwards adding the event for real.

**Comment by ihadeed** [comment]
This doesn't seem like an issue with the Ionic Native wrapper.

Ionic Native is just a wrapper and it has no effect on how the plugin performs. Please seek help at the plugin's repo or at the Ionic Forums.

**Comment by c0bra** [comment]
@ihadeed The function takes a callback but it appears the typescript signature does not allow for one: https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/calendar/index.ts#L133
