### ISSUE TITLE
Ionic-native v3-injectable debug leftovers

### ISSUE THREAD

**Issue by Sh1d0w** [driftyco/ionic-native#1145]
Hey guys. Really appreciate your work on ionic native. We have been using @ionic-native@alpha-3 and so far it is working flawlessly and reduced our bundle size. This is great!

One thing that I want to mention is that when you are releasing something to the general public and want our help to test it (even in alpha) it is not good practice to leave debugging code into the release.

For example these lines:

https://github.com/driftyco/ionic-native/blob/v3-injectable/src/%40ionic-native/core/plugin.ts#L488
https://github.com/driftyco/ionic-native/blob/v3-injectable/src/%40ionic-native/core/plugin.ts#L491

Spams the console like a hell and it is something that the developer does not care for (unless developing ionic-native itself) and in most cases makes it harder for you to spot your own console.log's.

**Comment by ihadeed** [comment]
Just pushed a commit to fix this.

Effects will show in the next v3 release.
