### ISSUE TITLE
Ionic Native - PhotoViewer + PWA: doesn't work

### ISSUE THREAD

**Issue by chrisbenseler** [driftyco/ionic-native#1147]
#Is it possible to use PhtotoViewer in an PWA?
The browser outputs

> Error: exec proxy not found for :: PhotoViewer :: show

and nothings else happens.

**Comment by ihadeed** [comment]
@chrisbenseler the plugin doesn't have browser support: https://github.com/sarriaroman/photoviewer

With Ionic Native 3.1.x (3.1.0-rc.1 is the latest currently) you can override the PhotoViewer provider in your `NgModule`. In your custom provider you can use a JavaScript based library to open images. 

Also, have a look at this directive here: https://github.com/Riron/ionic-img-viewer/

**Comment by chrisbenseler** [comment]
Thanks @ihadeed I will take a look!
