### ISSUE TITLE
Ionic v1 version on Bower not being updated

### ISSUE THREAD

**Issue by shanesmith** [driftyco/ionic-native#1148]
Currently the latest version on bower is v2.0.3, while as of posting Ionic Native is at v2.8.0, it seems that bower isn't being updated.

There existed an issues for this at #448, which is closed but it seems the issue is not quite resolved.

**Comment by ihadeed** [comment]
Please use NPM instead. Ionic Native 2.x releases are not going to be updated often anyways so it shouldn't be a big inconvenience to copy & paste the files.
