### ISSUE TITLE
Add support for encoding barcode/qrcode in BarcodeScanner API

### ISSUE THREAD

**Issue by dmahapatro** [driftyco/ionic-native#115]
[Barcode scanner plugin in codova](https://github.com/phonegap/phonegap-plugin-barcodescanner#encoding-a-barcode) also provides support for encoding a barcode/qrcode, 
can this API `encode()` be added to `BarcodeScanner` in addition to `scan()`?

**Comment by tlancina** [comment]
Hey thanks for the issue.  Unfortunately `encode` crashes on Android due to a bug, so I didn't add it, but I guess we could and just document that it doesn't work on Android.

More info:
https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/174

**Comment by dmahapatro** [comment]
Thank You for the response. We can keep this open until there is a fix and just add the additional information to the docs, if feasible.
