### ISSUE TITLE
Email Composer fails on windows build

### ISSUE THREAD

**Issue by cheng1994** [driftyco/ionic-native#1150]
I'm attempting to build for windows running on emulator throws this error: 

```
Unhandled exception at line 3, column 7157 in ms-appx-web://com.ionicframework.gradelinkparent/www/build/polyfills.js

0x800a139e - JavaScript runtime error: module de.appplant.cordova.plugin.email-composer.EmailComposerProxy not found
```

Removing the Email Composer plugin fixes the problem and the build works fine. 

I'm running:
Angular 2.2.1
Ionic 2.1.0
Ionic-Native 2.4.1

**Comment by ihadeed** [comment]
This is an issue with the plugin. Please report it here: https://github.com/hypery2k/cordova-email-plugin
