### ISSUE TITLE
SQLite transaction not working

### ISSUE THREAD

**Issue by digaus** [driftyco/ionic-native#1152]
Currently trying to use the SQLite Native Plugin but cannot get a transaction to work... without the transaction filling the database works without any problems but when I wrap it in a transaction it does not work anymore.

The problem is that I do not get any error messages so I cannot really find the problem..

```
 this.platform.ready().then(() =>{
  
      this.db.transaction((tx) => {
        //Reaching this point
        for(let i=0;i<data.length;i++){
            let query = "INSERT INTO test (name, description, url) VALUES (?,?,?)";
            tx.executeSql(query, [data[i].value1, data[i].value2, data[i].value3]).then(() => {
              this.errHandler.showMsg('data added!'); //not called
            }, (err) => {
              this.errHandler.showMsg('Create Table Error!'); //not called
            });
        }
      }, () => {
          this.errHandler.showMsg('Transaction Success!'); //not called
      }, (error) => {
          this.errHandler.showMsg('Transaction Error!'+error.message); //not called
      });
});
```

**Comment by ihadeed** [comment]
What platform are you testing this on?

**Comment by digaus** [comment]
Windows 10 and Android... both not working with transactions.

**Comment by digaus** [comment]
Ok just managed to debug it with Visual Studios and getting the following error when using the transaction:

```
TypeError: Unable to get property 'then' of undefined or null reference
   at Anonymous function (ms-appx-web://com.ionicframework.httptest397144/www/build/main.js:21373:21)
   at SQLitePluginTransaction.prototype.start (ms-appx-web://com.ionicframework.httptest397144/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js:322:7)
   at Anonymous function (ms-appx-web://com.ionicframework.httptest397144/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js:145:11)
   at t.prototype.invokeTask (ms-appx-web://com.ionicframework.httptest397144/www/build/polyfills.js:3:9614)
   at onInvokeTask (ms-appx-web://com.ionicframework.httptest397144/www/build/main.js:36191:21)
   at t.prototype.invokeTask (ms-appx-web://com.ionicframework.httptest397144/www/build/polyfills.js:3:9614)
   at e.prototype.runTask (ms-appx-web://com.ionicframework.httptest397144/www/build/polyfills.js:3:7057)
   at invoke (ms-appx-web://com.ionicframework.httptest397144/www/build/polyfills.js:3:10827)
   at e.args[0] (ms-appx-web://com.ionicframework.httptest397144/www/build/polyfills.js:2:30114)
```

**Comment by digaus** [comment]
Got it sorted out! You should really add some details in the documentation...

```
this.platform.ready().then(() =>{
  
      this.db.transaction((tx) => {
        for(let i=0;i<data.length;i++){
            let query = "INSERT INTO test (name, description, url) VALUES (?,?,?)";
            tx.executeSql(query, [data[i].value1, data[i].value2, data[i].value3], () => {
              this.errHandler.showMsg('data added!');
            }, (err) => {
              this.errHandler.showMsg('Create Table Error!'); 
            });
        }
      }, () => {
          this.errHandler.showMsg('Transaction Success!');
      }, (error) => {
          this.errHandler.showMsg('Transaction Error!'+error.message);
      });
});
```

**Comment by Karthiks010** [comment]
Unable to get property 'executeSql' of undefined or null reference", message: "Unable to get property 'executeSql' of undefined or null reference", number: -2146823281, stack: "TypeError: Unable to get property 'executeSql' of undefined or null reference at Anonymous function (http://localhost:8100/build/main.js:170:13) at t (http://localhost:8100/build/polyfills.js:3:21503) at DatabaseProvider.prototype.createUser (http://localhost:8100/build/main.js:168:9) at HomePage.prototype.createUsers (http://localhost:8100/build/main.js:86:9) at Anonymous function (Function code:34:15) at handleEvent (http://localhost:8100/build/vendor.js:13963:87) at callWithDebugContext (http://localhost:8100/build/vendor.js:15472:9) at debugHandleEvent (http://localhost:8100/build/vendor.js:15059:5) at dispatchEvent (http://localhost:8100/build/vendor.js:10378:9) at Anonymous function (http://localhost:8100/build/vendor.js:11003:31)"}
description: "Unable to get property 'executeSql' of undefined or null reference"
message: "Unable to get property 'executeSql' of undefined or null reference"
number: -2146823281

**Comment by Karthiks010** [comment]
can any one help me out of this problem, please
