### ISSUE TITLE
rxjs dependency conflicts with core framework

### ISSUE THREAD

**Issue by rapropos** [driftyco/ionic-native#1155]
Ionic 2.2 tells us to upgrade our rxjs dependency to 5.0.1, but ionic-native is requesting 5.0.0-beta.12, which results in conflicting peer dependency complaints from npm. Are there any known problems using any particular parts of ionic-native with newer versions of rxjs?

**Comment by ihadeed** [comment]
We'll update the rxjs version here soon. It should be safe to ignore the ionic-native peer dependency warning and use rxjs@5.0.1

**Comment by masimplo** [comment]
In my case when doing `npm install` on my project ionic-native downloads rxjs5.0.1-beta.12 inside a node_modules folder inside the ionic-native folder and this result in conflicts in my code like:

```
public onKeyboardShow(): Observable<any> {
       L7:    return Keyboard.onKeyboardShow();

Type 'Observable<any>' is not assignable to type 'Observable<any>'. Two different types with this name  exist, but they are unrelated.
```

In order for my project to compile I have to manually delete the folder.

**Comment by ihadeed** [comment]
Just published `ionic-native@2.8.1` that solves this issue.

**Comment by peterpeterparker** [comment]
thx @ihadeed, did you did it too for ionic-native 3.0.0?

**Comment by ihadeed** [comment]
@peterpeterparker working on it, there's another issue that's open for that.

**Comment by peterpeterparker** [comment]
@ihadeed thx for the feedback and of course for working on it 👍

**Comment by ihadeed** [comment]
@peterpeterparker see https://github.com/driftyco/ionic-native/issues/1156#issuecomment-285710175
