### ISSUE TITLE
UIBackgroundModes on iOS

### ISSUE THREAD

**Issue by neoassyrian** [driftyco/ionic-native#1157]
hi guys, 

How do I set the UIBackgroundModes for the MediaPlugin so audio will play when the app is in the background/screen locked? 

I'm not sure if it is a cordova or an Ionic questions. 

I"m using Ionic 2 and the MediaPlugin (Ionic Native)

**Comment by ihadeed** [comment]
This would be a question to address at the plugin's repo. I don't think it's possible with this plugin though.
