### ISSUE TITLE
Improve PhotoViewer docs to tell us which platforms are supported 

### ISSUE THREAD

**Issue by dorontal** [driftyco/ionic-native#1159]
Most other ionic-native docs tell us in a standard section titled 'Supported Platforms' which platforms are supported.

I want to use the PhotoViewer ionic-native module with 'browser' platform but have no idea if that's supported - so I will look in the code.  You'll be saving people a lot of time with just a few words about supported platforms.

**Comment by ihadeed** [comment]
Just updated the PhotoViewer plugin along with many others.

I'll make sure all plugins have the platforms documented when I get some time. 

Feel free to submit pull requests to improve any plugin's documentation!
