### ISSUE TITLE
Plugin inapp purchasr no more maintained

### ISSUE THREAD

**Issue by speedfl** [driftyco/ionic-native#1160]
Hello

I just saw on the plugin in app purchase that this plugin is no more maintained (updated today)
It is not working anymore in newer version of ios
I know that it is not your working area but if inapp purchase do not work anymore I am pretty sure that ionic app building will decrease. And I don't want to see this. I love ionic  :D
Could you please see maybe with alexdisler if you can take it on your side
This is the one of the most important feature for app building.

https://github.com/AlexDisler/cordova-plugin-inapppurchase

Thanks a lot Ionic team

**Comment by mlynch** [comment]
Thanks for the heads up. Is there an announcement anywhere?

Also what issue are you seeing now in iOS? I agree this is an important component to have working.

**Comment by speedfl** [comment]
Hello.

The decomitionning has been committed on the readme by alexdisler some hours ago (first line of the readme)

Concerning newer version of ios it is in the list of issues.

What can we do T_T

**Comment by speedfl** [comment]
I think the highest priority is 
https://github.com/AlexDisler/cordova-plugin-inapppurchase/issues/119

As now almost all the new apple phones are using IOS 10.2.1

**Comment by matthieu80** [comment]
hi there,
Is it advised to switch to https://github.com/j3k0/cordova-plugin-purchase ?
thank you,
Matt

**Comment by speedfl** [comment]
Hello.

Any news on it ?

Thanks a lot

Best regards

**Comment by danielsogl** [comment]
Hey @speedfl,

I will take a look into this.

**Comment by speedfl** [comment]
Hello.

To be honnest I did not try on ios for the moment. I just wanted to warn because I was testing on android and I saw this update on the readme (which has disappeard).
If you tested and it is working you can close the issue. 
I will open one on this plugin repository if the issue appear :)

**Comment by ihadeed** [comment]
Closing this issue in favor of https://github.com/driftyco/ionic-native/issues/810
