### ISSUE TITLE
Plugin request: cordova-plugin-autostart

### ISSUE THREAD

**Issue by zealotzy** [driftyco/ionic-native#1163]
Hi,

I would like to have my app launch automatically when the system boots up(or reboot) in android. If this plugin could be added to ionic-native would be great:
https://github.com/ToniKorin/cordova-plugin-autostart

**Comment by danielsogl** [comment]
@zealotzy I added the plugin. Wait for the next release

**Comment by zealotzy** [comment]
@danielsogl Thank you very much!
