### ISSUE TITLE
Geolocation.getCurrentPosition not work

### ISSUE THREAD

**Issue by vladkostenko** [driftyco/ionic-native#1164]
Why is there this stub?

/**
     * Get the device's current position.
     *
     * @param {GeolocationOptions} options  The [geolocation options](https://developer.mozilla.org/en-US/docs/Web/API/PositionOptions).
     * @returns {Promise<Geoposition>} Returns a Promise that resolves with the [position](https://developer.mozilla.org/en-US/docs/Web/API/
     */
    **Geolocation.getCurrentPosition = function (options) { return; };**

**Comment by rapropos** [comment]
It is not a stub. If you look at the accompanying JavaScript, you will see that the `@Cordova` decorator is doing a lot of work behind the scenes. Please describe your actual problem including expected and observed behavior, not something as vague as "not work".

**Comment by vladkostenko** [comment]
Sorry. 
Geolocation.getCurrentPosition and Geolocation.watchPosition - work.
But ONLY if set geolocation options. 
Despite the fact that in the function description this parameter is not mandatory
