### ISSUE TITLE
AdMob events not firing

### ISSUE THREAD

**Issue by moldstadt** [driftyco/ionic-native#1165]
Hi.

I am trying to use the AdMob plugin to show reward videos.  I need to handle the onAdPresent() event to know if the reward video has been viewed.  I see the video, however, this event doesn't get called if I subscribe to it as follows:
<code>AdMob.onAdPresent().subscribe(val => console.log("onAdPresent(): " + val);</code>

Doing it this way works:
<code>document.addEventListener('onAdPresent', val => console.log("onAdPresent(): " + val));</code>

I have also tried subscribing to all other events using the first method, as well as for different types of ads (banner, interstitial), and they don't get fired either.

**Comment by ramoncarreras** [comment]
Yes. I'm facing this same issue with ionic-native **3.2.4**.

My system information:

> Cordova CLI: 6.5.0
> Ionic Framework Version: 2.2.0
> Ionic CLI Version: 2.2.1
> Ionic App Lib Version: 2.2.0
> Ionic App Scripts Version: 1.1.4
> ios-deploy version: 1.9.0
> ios-sim version: 5.0.11
> OS: macOS Sierra
> Node Version: v7.1.0
> Xcode version: Xcode 8.2.1 Build version 8C1002
