### ISSUE TITLE
Plugin request: cordova-plugin-health

### ISSUE THREAD

**Issue by Artfloriani** [driftyco/ionic-native#1168]
Seems like the only option to connect to Apple Health Kit and Google Health.

https://github.com/dariosalvi78/cordova-plugin-health

**Comment by ihadeed** [comment]
This plugin already exists in the latest version of Ionic Native. Just not documented yet.

See https://github.com/driftyco/ionic-native/blob/master/src/plugins/health.ts

**Comment by Artfloriani** [comment]
Amazing, thanks!
