### ISSUE TITLE
TODO: AdMob Free plugin

### ISSUE THREAD

**Issue by moldstadt** [driftyco/ionic-native#1170]
The current cordova-admob-pro plugin, which is included in ionic native, is not free to use. Is it possible to rather use [cordova-plugin-admob-free](https://github.com/ratson/cordova-plugin-admob-free), which is free and seems to have the same features?

**Comment by ihadeed** [comment]
@moldstadt where does it say that the `cordova-admob-pro` is a paid plugin?

**Comment by moldstadt** [comment]
It's in the readme:
https://github.com/floatinghotpot/cordova-admob-pro/blob/master/README.md#license
