### ISSUE TITLE
Update the signature of Cordova Plugin Camera Preview

### ISSUE THREAD

**Issue by riccardotreagles** [driftyco/ionic-native#1172]
Cordova Plugin Camera Preview is in 0.0.8. 27 Mar 2015

The master on git is in 0.9.0, with many useful features. and bug fixing.
https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview.git

So It will be useful update ionic-native with the new version of Cordova Plugin Camera Preview

**Comment by tordnilsen** [comment]
What to do in meantime?
I have installed 0.9.0 and get's a undefined error from Ionic 2
(plugin not installed, please install)

**Comment by riccardotreagles** [comment]
You can do:

ionic plugin add https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview.git

And then use (after the import in the .ts):

**declare var CameraPreview: any;** 

You should be able to use new methods on CameraPreview object.

**Comment by tordnilsen** [comment]
Hi, thanks for replying, but I can't get this to work. (It worked a few weeks ago, but then the plugin was named com.?? something in Ionic plugin list)
When I insert the declare I get a Typescript error (declaration conflict)
Could you please help me out?

$Ionic plugin list:
cordova-plugin-camera-preview 0.9.0 "cordova-plugin-camera-preview"

---
config.xml:
  <plugin name="cordova-plugin-camera-preview" spec="https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview.git" />

----

camera.ts:
import { CameraPreview, CameraPreviewRect  } from 'ionic-native';
...
CameraPreview.startCamera(
          cameraRect, 'back',   tapEnabled,   dragEnabled,     toBack,  alpha );

-----
Running on device
Debug gives me:
 Native: tried calling CameraPreview.startCamera, but the CameraPreview plugin is not installed.
pluginWarn @ main.js:357
main.js:362 Install the CameraPreview plugin: 'ionic plugin add cordova-plugin-camera-preview'

**Comment by riccardotreagles** [comment]
I think you have do not use
import { CameraPreview, CameraPreviewRect } from 'ionic-native';
It uses old package, old signature.

You have to use only the "declare var CameraPreview: any;",  and use the new signature:

CameraPreview.startCamera({x: 0, y: 0, width: window.screen.width, height: window.screen.height, camera: "front", toBack: false, tapPhoto: true, previewDrag: false});

as in the doc. https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview

**Comment by ihadeed** [comment]
Sorry forgot to update this issue. The signature has been updated, just make sure to install the plugin from the repo.
