### ISSUE TITLE
has no exported member 'AppUpdate'.

### ISSUE THREAD

**Issue by hrobar** [driftyco/ionic-native#1177]
Hello, 
sry for my english.
I install plugin http://ionicframework.com/docs/v2/native/appupdate/
and i add row in app.components.ts
`import { AppUpdate } from 'ionic-native';`

and start `ionic serve`

and show me  error `Module '"d:/androidapp/testAppUpdate/node_modules/ionic-native/dist/es5/index"' has no exported member 'AppUpdate'.`

**Comment by ihadeed** [comment]
This plugin was added in `ionic-native@2.6.0`. Please make sure you have that version or a later version installed.
