### ISSUE TITLE
Facebook browserInit error

### ISSUE THREAD

**Issue by root-io** [driftyco/ionic-native#1187]
When using the facebook plugin in a real android device, I have an error when `Facebook.browserInit` is called.
I also tried to put it inside a platform ready with no success.

```
Error: Uncaught (in promise): TypeError: Cannot read property 'apply' of undefined
```

Seems similar to #882 

```
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.10.0
Xcode version: Not installed

ionic-native 2.8.1
```

**Comment by ihadeed** [comment]
The `browserInit` method is deprecated now and you don't need to call it anymore.

The plugin will automatically init the Facebook SDK when you launch the app in Cordova Browser platform.

**Comment by root-io** [comment]
Nevermind, I fixed with `if (!platform.is('cordova')) {...`
