### ISSUE TITLE
v3-injectable screen-orientation plugin inconsistent returns

### ISSUE THREAD

**Issue by Sh1d0w** [driftyco/ionic-native#1194]
Using

    "@ionic-native/screen-orientation": "^3.1.0-rc.5"

When trying to access the `this.screen.orientation` it yields different results depending on the platform:

1. iOS `this.screen.orientation ` is string
2. Android `this.screen.orientation` is Object of type `ScreenOrientation` with class properties angle and type.

cc @ihadeed 

Ionic info:

```
 Your system information:

    Cordova CLI: 6.4.0 
    Ionic Framework Version: 2.2.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: 1.9.0 
    ios-sim version: 5.0.13 
    OS: macOS Sierra
    Node Version: v7.7.3
    Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by ihadeed** [comment]
You're probably testing with different version of the plugin.

`cordova-plugin-screen-orientation` version `2.0.0` was release two days ago and they made major changes to their API. 

The results you're getting on Android sound like `2.0.0` and iOS is `1.4.0`.

Ionic Native currently supports `1.4.0`. I'm going to update the API soon to support `2.0.0`.

**Comment by Sh1d0w** [comment]
@ihadeed Thanks for your reply. Seems I am using version 1.4.2 of this plugin, so it is unlikely this to be the problem?

```
cordova plugins
com.instabug.cordova.plugin 1.0.0 "instabug-cordova"
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 2.3.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-crop 0.3.1 "CropPlugin"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-file 4.3.1 "File"
cordova-plugin-file-transfer 1.6.1 "File Transfer"
cordova-plugin-globalization 1.0.5 "Globalization"
cordova-plugin-network-information 1.3.1 "Network Information"
cordova-plugin-screen-orientation 1.4.2 "Screen Orientation"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.2-dev "Cordova WKWebView Engine"
cordova-sqlite-storage 2.0.1 "Cordova sqlite storage plugin"
de.appplant.cordova.plugin.local-notification 0.8.5-dev "LocalNotification"
ionic-plugin-keyboard 2.2.1 "Keyboard"
me.tonny.cordova.plugins.multidex 0.1.0 "Cordova Multi Dex"
```

**Comment by ihadeed** [comment]
Sorry then I don't know what the problem is.

I suggest you wait for the next Ionic Native update and use version 2.0.0 which should be consistent.

**Comment by ihadeed** [comment]
@Sh1d0w please use latest `@ionic-native/*` version `3.1.0-rc.6`

**Comment by Sh1d0w** [comment]
@ihadeed Thanks. Unfortunately with rc6 now I get the following exception when trying to use the plugin methods:

```
console.error: EXCEPTION: Uncaught (in promise): TypeError: undefined is not an object (evaluating             'pluginInstance[methodName].apply') callCordovaPlugin
...
```

**Comment by Sh1d0w** [comment]
PS. I still use v1.4.2 of the screen orientation plugin, which is the version that is installed after I do:

`ionic cordova:plugin add cordova-plugin-screen-orientation`

Can you advise me how to install v2 of that plugin, since

`ionic cordova:plugin add cordova-plugin-screen-orientation@latest`

has no effect. Maybe I should add it directly from git? 

Thanks

**Comment by ihadeed** [comment]
Yes add it from git

**Comment by Sh1d0w** [comment]
@ihadeed All working perfectly. Thanks for the quick fix!
