### ISSUE TITLE
Feature Request: Email Composer Plugin

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic-native#12]
I would love to see the email composer as part of Ionic Native.  We use it in several apps and I bet a lot of other companies do too.  Super common use case to build a CSV of some data and let it be shared via email.  This plugin works great for attachments.

http://ngcordova.com/docs/plugins/emailComposer/

Happy to help if you'll accept the PR.  Gotta read through the code to see what's going on.

Thanks,
Dan

**Comment by tlancina** [comment]
Yeah would definitely love a PR. Check out https://github.com/driftyco/ionic-native/blob/master/DEVELOPER.md and https://github.com/driftyco/ionic-native/tree/master/src/plugins for some examples, and let me know if you have any questions/issues/feedback, thanks!

**Comment by cmanou** [comment]
This can be closed since #110 was merged, and 1.2.0 can be released?
