### ISSUE TITLE
Diagnostic.registerNFCStateChangeHandler doesn't exist

### ISSUE THREAD

**Issue by daviddbeasy** [driftyco/ionic-native#1201]
When trying to use this method in Diagnostic i have this error:
Property 'registerNFCStateChangeHandler' does not exist on type 'typeof Diagnostic'.

Tested with "ionic-native": versions 2.9.0, 2.8.1 and 2.4.1, even in a clean Ionic blank project.

My package.json file: 
{
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.4.8",
    "@angular/compiler": "2.4.8",
    "@angular/compiler-cli": "2.4.8",
    "@angular/core": "2.4.8",
    "@angular/forms": "2.4.8",
    "@angular/http": "2.4.8",
    "@angular/platform-browser": "2.4.8",
    "@angular/platform-browser-dynamic": "2.4.8",
    "@angular/platform-server": "2.4.8",
    "@ionic/storage": "2.0.0",
    "ionic-angular": "2.2.0",
    "ionic-native": "2.9.0",
    "ionicons": "3.0.0",
    "ng2-translate": "^5.0.0",
    "promise.prototype.finally": "^2.0.1",
    "rxjs": "5.0.1",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.7.2"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.1.4",
    "@types/promise.prototype.finally": "^2.0.0",
    "typescript": "2.2.1"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-console",
    "cordova-plugin-statusbar",
    "cordova-plugin-device",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard",
    "cordova-plugin-globalization",
    "cordova.plugins.diagnostic",
    "phonegap-nfc"
  ],
  "cordovaPlatforms": [],
  "description": "ProserviceApp: An Ionic project"
}

**Comment by ihadeed** [comment]
This method was added in `2.7.0` and should be available. Are you getting the error from the compiler or the IDE? 

If it's the IDE, maybe its indexes aren't updated properly.

**Comment by daviddbeasy** [comment]
I get the error in the Ide (Visual Studio and Visual Studio code), and in
the compiler when trying to execute the App with ionic serve or running it
in the App. I get the error even in a new blank project generated with the
ionic CLI, only changing the ionic-native lib version and executing it,
without opening the project in the IDE.

2017-03-20 20:10 GMT+01:00 Ibby Hadeed <notifications@github.com>:

**Comment by daviddbeasy** [comment]
Hi, have you tried to use the method
Diagnostic.registerNFCStateChangeHandler without any error? I can't still
use it.

2017-03-21 9:54 GMT+01:00 David Domínguez Briante <daviddbeasy@gmail.com>:

**Comment by daviddbeasy** [comment]
After updating to 3.2.1 the error has been solved. Thanks.

2017-03-23 9:55 GMT+01:00 David Domínguez Briante <daviddbeasy@gmail.com>:
