### ISSUE TITLE
[BUG] No Provider for Push!

### ISSUE THREAD

**Issue by iliraga** [driftyco/ionic-native#1208]
Hi there

I upgraded to the Ionic Native 3 stuff according to the blog-entry.

Now I'm constantly getting the error "No provider for push!" When running the app.

The relevant code is:

	import {Push, PushObject, PushOptions, NotificationEventResponse, RegistrationEventResponse} from '@ionic-native/push';
	// ... some boilerplate stuff here ...
	export class NotificationService {
	// ... some boilerplate stuff here ...

		constructor(private platform: Platform,
					private push: Push) { // <------
			console.log('Hello NotificationService Provider');
		}

	// ... some boilerplate stuff here ...

	}

The data from the ionic error window:

- Ionic Framework: 2.2.0
- Ionic App Scripts: 1.1.4
- Angular Core: 2.4.8
- Angular Compiler CLI: 2.4.8
- Node: 7.3.0
- OS Platform: macOS Sierra
- Navigator Platform: Iphone

I'm using the WKWebView. But I don't think that's relevant, because if i'm switching it off it still doesn't work.

I don't use the ionic cloud services.

Keep up the good work! Really appreciate it

**Comment by mlynch** [comment]
Make sure to add `Push` to your providers in `app.module.ts`:

```typescript
import { Push } from '@ionic-native/push';

// ...

providers: [ Push ]

**Comment by jadsalhani** [comment]
Maybe worth mentioning that this should be done for all plugin providers. I didn't find it mentioned in the native doc pages.

**Comment by ihadeed** [comment]
@jadsalhani it's mentioned here: http://ionicframework.com/docs/v2/native/#Add_Plugins_to_Your_App_Module

**Comment by jadsalhani** [comment]
Heh, Chrome was displaying the old cached version of the page...A hard reload did the trick. Talk about trusting your browser these days

Thanks!

**Comment by ihadeed** [comment]
@jadsalhani See https://github.com/driftyco/ionic-app-scripts/issues/825
