### ISSUE TITLE
No provider for Transfer

### ISSUE THREAD

**Issue by Mystearica** [driftyco/ionic-native#1209]
Hi!

I followed the example for the file transfer plugin, but doesn't matter what I try, everytime i get the error **No provider for Transfer**.

Any clue about what is causing this?

Thank you.

**Comment by mlynch** [comment]
Make sure to add the provider to your `@NgModule` per this example at the bottom: http://ionicframework.com/docs/v2/native/

**Comment by Mystearica** [comment]
Hi!

I had already the provider in @NgModule
  providers: [{ provide: ErrorHandler, useClass: IonicErrorHandler }, Storage, FileTransferProv]

But even adding Transfer (Just trying), the problem is still the same.

**Comment by ihadeed** [comment]
@Mystearica 
In `app.module.ts`: 
```typescript
import { Transfer } from '@ionic-native/transfer'; // import Transfer class

@NgModule({
  ...
  imports: [ ... , Transfer ], // add Transfer to imports
  ...
})
```

In your component or service:
```typescript
import { Transfer } from '@ionic-native/transfer';

constructor(private transfer: Transfer) { }

someMethod() { 

  const fileTransfer = this.transfer.create();
  fileTransfer.download(...);

}
```

**Comment by Mystearica** [comment]
@ihadeed 
Thank you!!
Problem solved!!

 I think the problem was this line: const fileTransfer = this.transfer.create();

In the documentation it says that you need this one: const fileTransfer: TransferObject = this.transfer.create();

Its the only thing I changed from what I have.

**Comment by ihadeed** [comment]
@Mystearica the method `this.transfer.create` returns an instance of `TransferObject`

**Comment by HimanshuHD** [comment]
Hi,

Using the same plugin, but getting some issues like,
1. TransferObject : No Export found for this in plugin definition.
2. this.tranfer.create(): does not exists on type Transfer.

One more query, for some plugins we don't need to declare any provider, and for some of them we need to give providers also. Can anyone explain me this please?

Thanks in advance.

**Comment by ihadeed** [comment]
@HimanshuHD 

Can you share you code?

As of  Ionic Native 3.1+, all plugin providers need to be imported in order for them to work.

**Comment by HimanshuHD** [comment]
This is my code where I m using plugin File Transfer.

`import { NavController, Platform } from 'ionic-angular';
import { Transfer, File } from 'ionic-native';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})

export class HomePage {

constructor(public navCtrl: NavController, private platform: Platform, private transfer: Transfer) {
    this.downloadContent();
}

downloadContent() {
        const manifestFilePathServer = "path-to-some-file";
        const manifestFilePathLocal = File.dataDirectory + "file.json";
        var headers = {
            'Connection': "keep-alive",
            'API-TOKEN': "apiToken",
            'Content-Type': 'application/json',
            'Authorization': 'Basic authToken'
        };
        this.transfer.download(manifestFilePathServer, manifestFilePathLocal, false, headers).then((res) => {
            console.log("Manifest File Downloaded...");
            console.info(res);
        }, (err) => {
            console.log("Error Downloading Manifest File.!");
        });
    }
}`

Plz check this.
1. I was not able to import TransferObject
2. I was not able to call this.transfer.create()

And I m using ionic v2.1.4, do I need to import providers for all plugins?

**Comment by ihadeed** [comment]
You are following Ionic Native 3.x usage and using Ionic Native 2.x. Please follow the documentation [here ](https://github.com/driftyco/ionic-native/blob/master/README.md) and [here](http://ionicframework.com/docs/native/) to get started with 3.x. 

If you want to keep using Ionic Native 2.x, you can find the documentation here: https://github.com/driftyco/ionic-native/blob/v2.x/src/plugins/filetransfer.ts#L116-L183

**Comment by HimanshuHD** [comment]
Thanks, I got the issue.

**Comment by Sampath-Lokuge** [comment]
Hi @ihadeed 
Can I have a solution for this [**Ionic native Transfer plugin's `file.dataDirectory` shows error**](https://stackoverflow.com/questions/44428434/ionic-native-transfer-plugins-file-datadirectory-shows-error)
