### ISSUE TITLE
Can't add contact 

### ISSUE THREAD

**Issue by mbakker96** [driftyco/ionic-native#121]
I want to make an option that costumers can add my company information as a new contact but when I run the code from the ionic website I get an error:

``` javascript 
Contacts.save({
    displayName: "Mr. Ionitron"
}).then((contact) => {}, (err) => {});
```

```
Uncaught EXCEPTION: Error during evaluation of "click"
ORIGINAL EXCEPTION: TypeError: ionic_native_1.Contacts.save is not a function
ORIGINAL STACKTRACE:
TypeError: ionic_native_1.Contacts.save is not a function
    at InformationPage.addContact (file:///android_asset/www/build/js/app.bundle.js:69105:34)
    at AbstractChangeDetector.ChangeDetector_InformationPage_0.handleEventInternal (viewFactory_InformationPage:2081:35)
    at AbstractChangeDetector.handleEvent (file:///android_asset/www/build/js/app.bundle.js:13432:30)
    at AppView.triggerEventHandlers (file:///android_asset/www/build/js/app.bundle.js:17614:37)
    at eval (viewFactory_InformationPage:2724:120)
    at file:///android_asset/www/build/js/app.bundle.js:33727:37
    at file:///android_asset/www/build/js/app.bundle.js:33099:87
    at ZoneDelegate.invoke (file:///android_asset/www/build/js/app.bundle.js:1405:30)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (file:///android_asset/www/build/js/app.bundle.js:16916:42)
    at ZoneDelegate.invoke (file:///android_asset/www/build/js/app.bundle.js:1404:36)
ERROR CONTEXT:
[object Object]
```

I also tried the way that was explained on the github page but that gived also differend error

**Comment by ihadeed** [comment]
Looking at the code, it looks like the correct function to use is `Contacts.create()` ... not `.save()` 

Will fix the documentation after some testing.

**Comment by henryosim** [comment]
having same problem

**Comment by ihadeed** [comment]
Hey @henryosim can you try using the `create()` method instead of `save()` ?

**Comment by henryosim** [comment]
Hi @ihadeed how do i apply the fix to my project please?

**Comment by ihadeed** [comment]
Hey just use create() instead of save?
(). It was just a documentation issue.

**Comment by henryosim** [comment]
it seems Im doing something wrong, could you please advise?

first i install the plugin and below is what i have  in my html and js files respectively:

`<ion-navbar *navbar>
  <ion-title>Directory</ion-title>
</ion-navbar>

<ion-content padding class="directory">
  <button  block (click)="createContact()">Create Contact</button>
</ion-content>`

`import {Page, NavController} from 'ionic-angular';
import {Contacts} from 'ionic-native';

/*
  Generated class for the DirectoryPage page.

  See http://ionicframework.com/docs/v2/components/#navigation for more info on
  Ionic pages and navigation.
*/
@Page({
  templateUrl: 'build/pages/directory/directory.html',
})
export class DirectoryPage {
  static get parameters() {
    return [[NavController]];
  }

  constructor(nav) {
    this.nav = nav;
  }

  createContact(){
    Contacts.create({
  displayName: "Mr. Ionitron"
}).then((contact) => {}, (err) => {});
  }
}
`

when i install app on phone no contact is created;

**Comment by ihadeed** [comment]
@henryosim I will look into the issue further when I get a chance. Thanks for your patience.

**Comment by ihadeed** [comment]
FYI @mbakker96 @henryosim I'm working on an alternative implementation of this plugin that should resolve your issues. Thanks for your patience.

**Comment by ihadeed** [comment]
@mbakker96 @henryosim The new wrapper for the Contacts plugin is merged now. Expect a new release by Monday, or clone the master branch.

Most problems should be fixed now.
