### ISSUE TITLE
Ionic deeplinks plugin have a wrong documentation

### ISSUE THREAD

**Issue by ValterSantosMatos** [driftyco/ionic-native#1215]
Hi there,

In the [ionic documentation ](http://ionicframework.com/docs/v2/native/ionic-deeplinks/) for the deeplinks plugin there is a reference to:

`$ npm install --save @ionic-native/ionic-deeplinks`

it should be:

`$ npm install --save @ionic-native/deeplinks`

Thanks,
Valter

**Comment by ihadeed** [comment]
Thanks, will fix soon.
