### ISSUE TITLE
[BUG] MediaPlugin.create does not fire any callback

### ISSUE THREAD

**Issue by ramoncarreras** [driftyco/ionic-native#1219]
I'm using ionic-native 3.1.1 and create() method of MediaPlugin class does not fire any callback.

Better explained in this [ionic forum topic](https://forum.ionicframework.com/t/mediaplayer-create-callbacks-not-fired/83805).

**Comment by neoassyrian** [comment]
Yep, that's hapening with me
The Media Plugin page on ionic native has disappeared too.

**Comment by ramoncarreras** [comment]
Yes. Another related topic:
https://forum.ionicframework.com/t/ionic-native-3-1-0-cordova-plugin-media-documentation/83665
