### ISSUE TITLE
Mocking support for Device plugin

### ISSUE THREAD

**Issue by dnmd** [driftyco/ionic-native#1221]
With the new Ionic Native 3.x awesomeness, support is added for plugin mocking. The Device plugin (most likely due to the static nature of the properties) does however, not work.

````javascript
// app.module.ts
providers: [
  { provide : Device, useClass : DeviceExt }
]
....

// device.ext.ts
import { Injectable } from '@angular/core';
import { Device } from 'ionic-native';

@Injectable()
export class DeviceExt extends Device {
    // always returns `null`
    uuid = Device.uuid || "c81a85a5-e2a1-4f3d-9c24-94fb7865b4a1";
}

**Comment by ihadeed** [comment]
`ionic-native` package is 2.x. We no longer use it in Ionic Native 3.x.

You need to install `@ionic-native/core` and `@ionic-native/device` then import `Device` from `@ionic-native/device`.

**Comment by dnmd** [comment]
@ihadeed , sorry for the typo's, that is indeed misleading. I've updated the sample. Extending the `Device` plugin does call the constructor from `DeviceExt`, however, it is not possible to "update" e.g. the uuid, since it will return `null` in the browser. Hope this clarifies it better.

**Comment by ihadeed** [comment]
Your class should look like this instead:
```ts
export class DeviceExt extends Device {

  uuid: 'someUUID';

   // or
   get uuid(): string { 
    return 'some-uuid';
   }

}
```
