### ISSUE TITLE
SpinnerDialog problem on ionic-native v3

### ISSUE THREAD

**Issue by petrot** [driftyco/ionic-native#1226]
Hi!

I updated my code to ionic-native v3. I got the following error: 
Error in :0:0 caused by: No provider for SpinnerDialog! 

Every other native components work with the new import method
e.g.
import { Network } from '@ionic-native/network';
instead of
import { Network } from 'ionic-native';

update: same problem with DeviceOrientation

**Comment by ihadeed** [comment]
Please follow the instructions here: http://ionicframework.com/docs/v2/native/#Add_Plugins_to_Your_App_Module

You need to add the provider to your NgModule

**Comment by petrot** [comment]
Thanks! I forgot this little think.. :)
