### ISSUE TITLE
googleanalytics, inappbrowser, splashscreen and statusbar not part of 3.2.1

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic-native#1229]
Hi,

googleanalytics, inappbrowser, splashscreen and statusbar support were and are still available in their version 3.0.0

These four aren't available in version 3.2.1 of ionic-native, why?

Best regards

**Comment by ihadeed** [comment]
The packages are re-named. They are now `google-analytics`, `in-app-browser`, `splash-screen` and `status-bar`.

Also worth noting that since Ionic Native 3.1.x, all packages export injectable providers instead of static classes. Please refer to the official Ionic Native docs for more information.

**Comment by peterpeterparker** [comment]
thx for the feedback @ihadeed

**Comment by peterpeterparker** [comment]
@ihadeed it works like a charm, thx!
