### ISSUE TITLE
Update NPM version

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic-native#1232]
https://www.npmjs.com/package/ionic-native still has 2.9.0, even though 3.1.0, 3.1.1, 3.2.0, 3.2.1 were released

**Comment by Screeze** [comment]
Since version 3 you have to add @ionic-native/core + each plugin which you need e.g. @ionic-native/admob.

**Comment by ihadeed** [comment]
As @Screeze said, `ionic-native` package is 2.x and anything under the `@ionic-native/*` scope is 3.x
