### ISSUE TITLE
[Documentation] MediaPlugin page has disappeared

### ISSUE THREAD

**Issue by theomathieubhvr** [driftyco/ionic-native#1234]
Hey, 

I think the title is clear enough ;)

I think last issues were solved here https://github.com/driftyco/ionic-native/pull/1220.

**Comment by sfaizanh** [comment]
[https://ionicframework.com/docs/v2/native/media/](https://ionicframework.com/docs/v2/native/media/)

**Comment by ihadeed** [comment]
It's fixed now. Thanks for reporting the issue.

**Comment by theomathieubhvr** [comment]
Thanks !
