### ISSUE TITLE
Screen Orientation undefined is not an object Exception

### ISSUE THREAD

**Issue by jcoon5026** [driftyco/ionic-native#1239]
I'm having an issue attempting to get the ScreenOrientation plugin to work properly. I've followed the suggestions in #472 and another that I can't recall at the moment, but it basically said to set a timeout on it. After following both of these steps, I'm still recieving this error 

>EXCEPTION: undefined is not an object (evaluating '__webpack_require__.i(__WEBPACK_IMPORTED_MODULE_0__util__["a" /* get */])(window, pluginObj.pluginRef)[methodName].apply')

My ionic info 

> Cordova CLI: 6.5.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.8
Node Version: v4.2.6
Xcode version: Not installed

My config.xml plugin

`<plugin name="cordova-plugin-screen-orientation" spec="~2.0.0" />`

My package.json dependency for this plugin:
> "@ionic-native/screen-orientation": "3.2.1"

The code that is calling it in the constructor of my class:

`this._platform.ready().then((res) => {
        setTimeout(() => {ScreenOrientation.lockOrientation('landscape')}, 1000);
    });`

Any suggestions would be greatly appreciated. Thanks

**Comment by ihadeed** [comment]
You need to inject `ScreenOrientation` and then call `this.screenOrientation.lockOrientation(...)`.

Please refer to the latest Ionic Native documentation for instructions on how to use Ionic Native 3.x

**Comment by jcoon5026** [comment]
I'm unable to npm install the Screen Orientation provided on this site:
https://ionicframework.com/docs/v2/native/screen-orientation

Is there something I'm not doing properly here, or is this an incorrect npm
install command?

**Comment by ihadeed** [comment]
This should work
```
$ npm install --save @ionic-native/screen-orientation
```

**Comment by jcoon5026** [comment]
Thank you. That worked for me well. Perhaps you could help with another
issue that I'm having. I'm using the ScreenOrientation to lock the screen
into landscape mode when I navigate to a specific page and unlock when I
leave that page. This renders and works properly with Android devices. With
IOS it isn't working properly. The orientation is locked in landscape, but
if I'm in portrait when I navigate the rendered page is rendered in
portrait mode not landscape. Same thing applies when I leave the page that
is locked in landscape mode. The page I navigate to is rendered in
landscape even if I'm holding the device in what should be portrait mode. I
have to tap the side of the device to get it to readjust itself. Any
thoughts? Here is the code I'm using to call it:

_platform.ready().then(() => {
>   if(this.capture) {
>     screenOrientation.lock('landscape');
>   }
> });
>
>
