### ISSUE TITLE
Issues in the documentation

### ISSUE THREAD

**Issue by Maziar-Fotouhi** [driftyco/ionic-native#1240]
@ihadeed 

http://ionicframework.com/docs/v2/native/3d-touch/

This page currently has this command for saving the package:
`npm install --save @ionic-native/3d-touch
`
but this is the actual folder:
`npm install --save @ionic-native/three-dee-touch
`
Thank you.

**Comment by Maziar-Fotouhi** [comment]
Just noticed two more issues in the documentation. **Sorry for being too picky. Just trying to help** in case these were missed.

Camera plugin does not have install scripts in documentation:
`http://ionicframework.com/docs/v2/native/camera/
`
`@ionic-native/camera
`
*******************************************************

I know I'm being super picky with this one but the word "in" in the installation scripts of "in-app-browser", is in blue:
`http://ionicframework.com/docs/v2/native/in-app-browser/
`
![image](https://cloud.githubusercontent.com/assets/12825530/24267304/db46fcd4-0fd7-11e7-92a8-491db20c60c6.png)

**Comment by sfaizanh** [comment]
`npm install --save @ionic-native/File` should be `npm install --save @ionic-native/file`
`npm install --save @ionic-native/Social Sharing` should be `npm install --save @ionic-native/social-sharing`
any many other have same issues

**Comment by ihadeed** [comment]
This is fixed now
