### ISSUE TITLE
Inappbrowser have no more the callback function?

### ISSUE THREAD

**Issue by Deharlan** [driftyco/ionic-native#1241]
I don't know anymore how to get a return in Inappbrowser when i use the executeScript(script: {file?: string, code?: string})

With this new update of the ionic-native-3x, changed the ways i get the return from this executeScript

**Comment by ihadeed** [comment]
According to the docs here http://ionicframework.com/docs/v2/native/in-app-browser/#executeScript it returns a Promise.

**Comment by Deharlan** [comment]
Could you make an example?

**Comment by ihadeed** [comment]
```
constructor(private iab: InAppBrowser) { }

someMethod() { 

const browser = this.iab.create('https://google.com');

const sub = browser.on('load').subscribe(() => {
  browser.executeScript({ code: 'console.log("hello world")' })
  .then(() => console.log('Executed script!'))
  .catch(e => console.log('error executing script'));
  sub.unsubscribe();
});

}

```

**Comment by Deharlan** [comment]
Thank you so much
