### ISSUE TITLE
Updated to ionic-native 3.2.1 now getting loads of typescript compile errors

### ISSUE THREAD

**Issue by daveshirman** [driftyco/ionic-native#1242]
Updated all required packages according to documentation.
Now getting transpile error all over the shop, e.g.:
```
Property 'requestRuntimePermission' does not exist on type 'typeof Diagnostic'. 
Property 'type' does not exist on type 'typeof Network'.
Property 'MediaType' does not exist on type 'typeof Camera'. 
Property 'hide' does not exist on type 'typeof SplashScreen'.
```

What is the documentation missing to make this correct? I followed exactly what it said to do [here:](https://ionicframework.com/docs/v2/native/) 

 Here's my package.json dependencies for reference:

```
  "dependencies": {
    "@angular/common": "2.4.8",
    "@angular/compiler": "2.4.8",
    "@angular/compiler-cli": "2.4.8",
    "@angular/core": "2.4.8",
    "@angular/forms": "2.4.8",
    "@angular/http": "2.4.8",
    "@angular/platform-browser": "2.4.8",
    "@angular/platform-browser-dynamic": "2.4.8",
    "@angular/platform-server": "2.4.8",
    "@ionic-native/camera": "^3.2.1",
    "@ionic-native/core": "^3.2.1",
    "@ionic-native/deeplinks": "^3.2.1",
    "@ionic-native/device": "^3.2.1",
    "@ionic-native/diagnostic": "^3.2.1",
    "@ionic-native/keyboard": "^3.2.1",
    "@ionic-native/network": "^3.2.1",
    "@ionic-native/splash-screen": "^3.2.1",
    "@ionic-native/status-bar": "^3.2.1",
    "@ionic-native/transfer": "^3.2.1",
    "@ionic/storage": "2.0.0",
    "@types/cordova-plugin-file-transfer": "0.0.3",
    "ionic-angular": "2.2.0",
    "ionicons": "3.0.0",
    "rxjs": "5.0.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.7.2"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.1.4",
    "@ionic/cli-build-ionic-angular": "0.0.3",
    "@ionic/cli-plugin-cordova": "0.0.9",
    "typescript": "2.0.9"
  },
```

Ionic info:
```
Davids-MacBook-Air:AddVideo2 daveshirman$ ionic info

  Your system information:

    Cordova CLI: 6.5.0 
    Ionic Framework Version: 2.2.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: 1.9.1 
    ios-sim version: 5.0.8 
    OS: OS X El Capitan
    Node Version: v6.10.0
    Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by daveshirman** [comment]
documentation wasn't clear enough that you now need to inject all your providers as with any other dependency, this wasn't the case before.

**Comment by ihadeed** [comment]
@daveshirman it does say that here https://ionicframework.com/docs/v2/native/#Add_Plugins_to_Your_App_Module

**Comment by daveshirman** [comment]
@ihadeed Actually no that's not what I meant.  I'm talking about the need to inject into the class itself.

e.g 

`constructor (public _Camera: Camera) { ... }` 

I've fixed it all now, just don't think the documentation was clear enough on this point.

**Comment by ihadeed** [comment]
@daveshirman that is also documented in the Usage section here: http://ionicframework.com/docs/v2/native/camera/

**Comment by daveshirman** [comment]
Camera was just an example. I meant in the main documentation guide. It is just a suggestion that it could be clearer for the benefit of others. That's all.

**Comment by ihadeed** [comment]
Thanks @daveshirman we'll work on improving the docs further. Any suggestions are  welcome.

**Comment by gotters** [comment]
I had exactly the same problem. left me totally confused. Thanks @daveshirman !!!
