### ISSUE TITLE
[ionic-native 3.2.2] File module size

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic-native#1244]
After having converted my project to Ionic Native 3.2.2 (thx again for that) I ran source-map-explorer to discover the result size of the libraries.

I turns out that that the File module is 3-4 bigger than other modules I use (see enclosed image). I understand that that module contains a little bit more methods than the others, but is there a way to spare codes?

Of course this isn't a bug, I just wanted to point out the size of that module, since as long as lazy loading isn't possible, the size of the app bundle has a huge impact on boot time.

<img width="1194" alt="capture d ecran 2017-03-24 a 10 05 59" src="https://cloud.githubusercontent.com/assets/16886711/24287322/834b42c2-1079-11e7-9159-6822593c4e13.png">

**Comment by ihadeed** [comment]
@peterpeterparker when you build your app with `--prod` flag, is the output file size still bigger than it would've been with Ionic Native 2.x ?

**Comment by peterpeterparker** [comment]
@ihadeed I really think it's better with Native 3.x (I'm using it since alpha version) respectively that the output file size is smaller, you guys did a great job!

Note: I didn't tried to generate the above report (generated after ionic serve) with --prod, because I just don't know how to generate the source map while running the --prod ;)

But still, according above report, the module File is really bigger than the other, that's why I was asking if there is a possibility to reduce it, every kb spared right now are a good win for every apps

**Comment by ihadeed** [comment]
@peterpeterparker that source map is showing you how big the source file is (`node_modules/@ionic-native/....`). 

When you build your app with the `--prod` flag it will uglify and treeshake the code and it ends up being much smaller than that.

**Comment by peterpeterparker** [comment]
@ihadeed so there is no way to explore the size of the ionic native bundle after building it with --prod?

and still, even if all module gonna be smaller, File still gonna be 3-4 bigger than the other, don't you think that should be improved?

**Comment by ihadeed** [comment]
@peterpeterparker I'm not aware of any way to check that. 

Not sure what you mean by the second part of your comment. Could you please elaborate?

**Comment by peterpeterparker** [comment]
@ihadeed I was just meaning that, even if the code is uglyfied and treeshaked during build, the output result may be the "same" respectively even compressed the module File may still weight 3-4 times more than the other modules

For example:

Before build

File 42kb (or 3 * Facebook or GA size)
Facebook 14kb
GA 13 kb

After build

File X kb (or 3 * Y)
Facebook Y kb
GA Y kb

**Comment by ihadeed** [comment]
@peterpeterparker oh I see what you mean.

AFAIK, tree shaking doesn't work so well with decorators. We use lots of decorators in Ionic Native and it causes the tree shaking processor to think that we actually need all the functions to be there. This is one of the reasons why we split the plugins into their own packages. 

We will definitely look into more ways to reduce the bundle size in the future. Rollup might improve, or we might find more ways to make our code to work better with Rollup.
