### ISSUE TITLE
Compatible w/o Ionic?

### ISSUE THREAD

**Issue by ehorodyski** [driftyco/ionic-native#1246]
One of the big draws for me to contribute to this library was it was moving Cordova plugins into TypeScript, with some extra love. 

It's been a while since I've been here last, and now I see that everything has been re-written for Angular 2 using Injectable providers. Will this code still provide other Cordova users, who aren't running Ionic, the ability to use typings?

**Comment by ihadeed** [comment]
Only the `ionic-native` package will provide that, which is 2.x. It will only be maintained to fix bugs and will not have any new plugins added to it.

Starting from Ionic Native 3.x it's going to support Angular 2.x+ apps only.

**Comment by ehorodyski** [comment]
Do you mind if I ask the reasoning behind this? 

In all fairness, my team has no interest in building anything Cordova-based without Ionic 2 going forward, but we have Ionic 1 apps currently in development and "global" components that we are trying to keep framework agnostic (of course, with the only caveat being that it's Cordova-based).

**Comment by mlynch** [comment]
@ehorodyski we still support that through ionic-native 2.x. We just want to focus 3.x and all new work on ionic native going forward for Ionic 2.x+ and Angular 2.x+

We will continue to fix and improve 2.x!

**Comment by ehorodyski** [comment]
@mlynch -- Thanks for the update. I understand the current prioritization of 3.x.

When it's time to start back up on 2.x, I'd love to help contribute, time permitting (who knows, maybe my job will bank me hours to help considering we use Cordova so heavily).

I think it's really important, as a Cordova and Ionic consumer, to try to align the efforts Cordova is currently committing to with Typescript typings with the work being done with Ionic Native. 

I'm an Ionic loyalist, but I'm a pragmatist first -- and if Ionic, for any reason I can't think of -- whether it's projects coming in from vendors (or in our case, even volunteers and members as a not-for-profit) or conflicting framework viewpoints or whatever, it's important to have the foundation Ionic Native provides at my disposal. 

Anyway, thanks for the response (and apologize for the outrage), and let me know how I can help efforts to decouple Ionic Native from the Ionic framework in the future. Would love to contribute more when available.

Best,
Eric
