### ISSUE TITLE
bug: Geocode instance non present

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-native#1249]
_From @Vito96 on March 24, 2017 15:36_

**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Geocode instance is not present in Geocoder (ionic-native).</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#10909_

**Comment by ihadeed** [comment]
@Vito96 `Geocoder` class is exported by the `@ionic-native/google-maps` package. It's injectable and has one instance method `geocode`.
