### ISSUE TITLE
Observable inside ".then" not being executed

### ISSUE THREAD

**Issue by SaloGala** [driftyco/ionic-native#126]
Good morning.
I scan a barcode successfuly with barcodescanner.ts plugin, inside the .then I want to make an Angular2 http call, but it never gets executed 

`
this.platform.ready().then(() => {

            BarcodeScanner.scan().then((imageData) => {

                // This part is never been executed
                this._GetURLService.getURL('UPC', imageData.text, 'Mexico', 'All').subscribe(
                    url => {
                        alert(url.requestURL);
                        this._GetItemService.getItem(url.requestURL).subscribe(
                            items => {

                            },
                            error => this.errorMessage = <any>error
                        );
                    },
                    error => {
                        alert('There was an error trying to contact the server');
                    }
                );

            }, (err) => {
                alert('There was a problem trying to use the camera');
            });

        }, (error) => {
            alert('There was a problem trying to use the camera');
        });
`

However if I take the part of the code is not executed outside of the plugin's ".then" it does work.

Thanks for your help.

**Comment by ihadeed** [comment]
What happens if you add a console log in your second line. Does any code get executed at all? or is it just that observable that doesn't work?
