### ISSUE TITLE
@ionic-native/splashscreen is not in the npm registry

### ISSUE THREAD

**Issue by javico2609** [driftyco/ionic-native#1261]
npm verb node v7.7.3
npm verb npm  v4.4.4
npm ERR! code E404
npm ERR! 404 Not found : @ionic-native/splashscreen
npm ERR! 404
npm ERR! 404  '@ionic-native/splashscreen' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'ICBancking'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by ihadeed** [comment]
Its renamed to `@ionic-native/splash-screen`

**Comment by javico2609** [comment]
ok, thx
