### ISSUE TITLE
How to pass custom params in to GoogleMapsMarkerOptions

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#1267]
_From @narayansikarwar on March 27, 2017 9:23_

There is no option to pass some custom data in to **GoogleMapsMarkerOptions** typescript wrapper. So we need some property for passing custom data to **GoogleMapsMarkerOptions** like **params**.
Because cordova native map plugin already have these options like
```
const GOOGLE = new plugin.google.maps.LatLng(37.422858, -122.085065);
map.addMarker({
  'position': GOOGLE,
  'myMsg': 'Hello'
}, function(marker) {
  alert(marker.get("myMsg"));
});
```

Here 'myMsg': 'Hello' is a custom parameter.

_Copied from original issue: driftyco/ionic#10929_

**Comment by ihadeed** [comment]
Hey @narayansikarwar

You can use the `get` and `set` methods to add custom data.

```ts
const map: GoogleMap = this.googleMaps.create(...);
map.addMarker({ position: GOOGLE })
  .then((marker: Marker) => marker.set('myMsg', 'Hello'));
```
