### ISSUE TITLE
Secure Storage: .create() Promise never resolved/rejected in browser

### ISSUE THREAD

**Issue by jonaszuberbuehler** [driftyco/ionic-native#1268]
Calling `secureStorage.create()` in browser (`ionic serve`) the returned Promise is never resolved/rejected when run in browser.

I'm using the following code:

```
this.platform.ready()
        .then(() => {
            this.secureStorage.create('test')
                .then(
                    data => console.log(data),
                    error => console.log(error))
        });
```

None of the callbacks gets ever called. The same works perfectly for all the other plugins I'm using.

Anything I'm missing here?

**Comment by ihadeed** [comment]
Sorry, the documentation is wrong/outdated. The plugin doesn't support the browser platform.

**Comment by jonaszuberbuehler** [comment]
@ihadeed Thanks for your answer. But in this case should't the Promise be rejected with a meaningful reason?

**Comment by ihadeed** [comment]
Just pushed a commit to fix that :)

**Comment by jonaszuberbuehler** [comment]
@ihadeed Awesome, thx :)
