### ISSUE TITLE
Error: Uncaught (in promise): ReferenceError: MarkerClusterer is not defined

### ISSUE THREAD

**Issue by AlFalahTaieb** [driftyco/ionic-native#1269]
I'm trying to build with Ionic 2 Gelocation + Clusters 

I always get this error :/ is there a solution ? 

`Runtime Error
Uncaught (in promise): ReferenceError: MarkerClusterer is not defined ReferenceError: MarkerClusterer is not defined at http://localhost:8100/build/main.js:82961:17 at t.invoke (http://localhost:8100/build/polyfills.js:3:9655) at Object.onInvoke (http://localhost:8100/build/main.js:36410:37) at t.invoke (http://localhost:8100/build/polyfills.js:3:9606) at e.run (http://localhost:8100/build/polyfills.js:3:7019) at NgZone.run (http://localhost:8100/build/main.js:36279:62) at HomePage.initializeMap (http://localhost:8100/build/main.js:82921:19) at HomePage.loadMaps (http://localhost:8100/build/main.js:82844:18) at http://localhost:8100/build/main.js:82831:63 at t.invoke (http://localhost:8100/build/polyfills.js:3:9655) at Object.onInvoke (http://localhost:8100/build/main.js:36410:37) at t.invoke (http://localhost:8100/build/polyfills.js:3:9606) at e.run (http://localhost:8100/build/polyfills.js:3:7019) at http://localhost:8100/build/polyfills.js:3:4661 at t.invokeTask (http://localhost:8100/build/polyfills.js:3:10284)`

**Comment by ihadeed** [comment]
From what I see in the stack trace, this doesn't look like an Ionic Native issue.
