### ISSUE TITLE
SQLite plugin: echoTest() and deleteDatabase() fails

### ISSUE THREAD

**Issue by bjakubiak** [driftyco/ionic-native#1275]
When ran on SQLiteObject it throws

> TypeError: plugin.constructor.getPluginRef is not a function. (In 'plugin.constructor.getPluginRef()', 'plugin.constructor.getPluginRef' is undefined)

I ran it on iOS device, @ionic-native/sqlite versions from 3.1.0 to 3.3.0.

Maybe both echoTest() and deleteDatabase() methods should belong to SQLite class rather than to SQLiteObject?

**Comment by ihadeed** [comment]
Are you using `@ionic-native/core@3.2.4` ?

If so, please update that package, as that version has a bug.

**Comment by ihadeed** [comment]
Just checked, you're right the methods should be part of the SQLite class. I will fix this soon.
