### ISSUE TITLE
@ionic-native/sqlite forced into AMBIGUOUS call

### ISSUE THREAD

**Issue by gabrielmuresan** [driftyco/ionic-native#1280]
The typescript definition for sqlite requires the user to use `SQLiteDatabaseConfig` when opening a new database, but the cordova plugin decides that this is AMBIGUOUS call because location AND iosDatabaseLocation properties must be specified.
```
export interface SQLiteDatabaseConfig {
    /**
     * Name of the database. Example: 'my.db'
     */
    name: string;
    /**
     * Location of the database. Example: 'default'
     */
    location: string;
    /**
     * iOS Database Location. Example: 'Library'
     */
    iosDatabaseLocation: string;
}
```

the plugin only understands only when one or the other are present

**Comment by ihadeed** [comment]
Thanks, I'll fix this now.
