### ISSUE TITLE
Firebase plugin says "plugin not installed" but plugin is installed already

### ISSUE THREAD

**Issue by aamir1995** [driftyco/ionic-native#1283]
**System info:**
Cordova CLI: 6.0.0
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.8.1
Xcode version: Not installed
Ionic Native Version: @ionic-native/core": 3.1.0

**Description:**
The ionic native plugin for Firebase is installed but after creating a build with ionic build android --prod it says the plugin is not installed, also removed platform and tried again.

![image](https://cloud.githubusercontent.com/assets/10736453/24409772/a50cf774-13ea-11e7-8c95-77344c0cd8be.png)

**Comment by ihadeed** [comment]
You're calling the plugin before `deviceready` has fired. 

Wrap your call with `this.platform.ready().then(() => { ... });`
