### ISSUE TITLE
SocialSharing: Add missing methods (setIPadPopupCoordinates)

### ISSUE THREAD

**Issue by FdezRomero** [driftyco/ionic-native#1288]
Hi there!

I noticed there are some missing methods in the SocialSharing plugin, especially `setIPadPopupCoordinates`, which is needed to specify the position and size of the button the user has pressed so that the sharing popup on iPad can be positioned according to Apple's guidelines. And as you all know, not doing this may be a reason for app rejection.

Would also be a good opportunity to review and add all the other missing methods. You can check them here: https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/blob/master/www/SocialSharing.js

Thanks!

**Comment by danielsogl** [comment]
Hey @FdezRomero,

I added the method. Wait for the next release.

**Comment by FdezRomero** [comment]
Great! Thanks @danielsogl 👍  I was going to submit a PR but I don't fully understand (yet) the inner workings of the changes made in 3.x.
