### ISSUE TITLE
Upgrading to version 3 results in @ionic-native/network folder empty of js files

### ISSUE THREAD

**Issue by amerzad** [driftyco/ionic-native#1290]
And also a truncated package.json file.
I tried several versions, and also tried to clear the npm cache, but no success.

**Comment by rashnk** [comment]
Due to major changes in native3 several issues when adding a plugin to existing project, i fixed by creating new starter project and copied existing src folder, added plugins again, also inject in module.ts,

**Comment by ramoncarreras** [comment]
Same problem here. I had to downgrade to 3.3.2 version.

**Comment by FdezRomero** [comment]
Which version of `npm` are you guys using?

You can also get around this by listening to the `online` and `offline` events on `window`, which is a web standard and works in Cordova if you have `cordova-plugin-network-information` installed. Plus it will work in a PWA with the same code:

```ts
window.addEventListener('offline', () => this.onOffline(), false);
window.addEventListener('online', () => this.onOnline(), false);
```

Remember to use `declare var window;` before the class so TypeScript won't complain.

**Comment by amerzad** [comment]
Node v6.10.0
Npm 3.10.10

**Comment by FdezRomero** [comment]
@amerzad Looks good. I have the same node/npm version and no problems with other plugins on 3.4.2 (I'm using this one through `window` as in my previous comment).

Are you using other `@ionic-native` packages on 3.4.2? Do they also fail?

**Comment by ihadeed** [comment]
Update to the latest version of the plugin and it should work fine.

This was an issue in 3.4.1 I think.
 
Sorry for not mentioning this in release notes. I'll update it when I get a chance.
