### ISSUE TITLE
Ionic 2 App Preferences gives Plugin Not Installed

### ISSUE THREAD

**Issue by danielflippance** [driftyco/ionic-native#1299]
I'm using Ionic 2 and have installed the AppPreferences plugin and it's prerequisites as per the docs. When calling fetch I receive a "plugin not installed" error similar to this issue with Ionic 1 https://github.com/driftyco/ionic-native/issues/438. 

Here's how I installed:

    $ ionic plugin add cordova-plugin-app-preferences
    $ npm install --save @ionic-native/app-preferences

Fetch the preferences:

    import { AppPreferences } from '@ionic-native/app-preferences';
    constructor(
      private appPreferences: AppPreferences,
    ...
    let fetchRes = this.appPreferences.fetch('mysetting');
    console.log('++ fetchRes: ' + JSON.stringify(fetchRes));

Returns:

    {"error":"plugin_not_installed"}

Calling with a promise returns ".then is not a function":

        this.appPreferences.fetch('mysetting').then(function(res) {

The plugin is listed in package.json:

    "dependencies": {
      ...
      "@ionic-native/app-preferences": "^3.4.2",
    ...
    "cordovaPlugins": [
      "cordova-plugin-app-preferences",

And config.xml

    <plugin name="cordova-plugin-inappbrowser" spec="~1.7.0"/>

I've included it in app.module.ts

    import { AppPreferences } from '@ionic-native/app-preferences';
    @NgModule({
    ...
    providers: [
      AppPreferences, 

It shows up under /node_modules:

![screen shot 2017-03-29 at 11 35 40 am](https://cloud.githubusercontent.com/assets/5957235/24470530/09573418-1474-11e7-9f5f-dafc5c1e0490.png)

    {
      "name": "@ionic-native/app-preferences",
      "version": "3.4.2",

and /plugins:

![screen shot 2017-03-29 at 11 35 52 am](https://cloud.githubusercontent.com/assets/5957235/24470547/14c2085a-1474-11e7-864a-87c171b9da11.png)

    {
      "name": "cordova-plugin-app-preferences",
      "version": "0.99.3",

The header of my index.html looks like this:

    <head>
      <meta charset="UTF-8">
      <title>Ionic App</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
      <meta name="format-detection" content="telephone=no">
      <meta name="msapplication-tap-highlight" content="no">

      <link rel="icon" type="image/x-icon" href="assets/icon/favicon.ico">
      <link rel="manifest" href="manifest.json">
      <meta name="theme-color" content="#4e8ef7">
      
      
      <script src="cordova.js"></script>

      

      <link href="build/main.css" rel="stylesheet">

    </head>

There is no reference to any of the @ionic-native plugins here but the others seem to work fine: eg: inappbrowser, so I suppose that is not needed for Ionic 2.

**Comment by danielflippance** [comment]
Strangely I notice that .store does work with no error, and the promise is returned correctly:

    this.appPreferences.store('mysetting', 'thenewvalue')
    .then(function(value) { //This gets successfully called });

**Comment by danielflippance** [comment]
I've installed 3.4.3 and .fetch() now returns: 
    
    {"__zone_symbol__state":false,"__zone_symbol__value":"plugin_not_installed"}

**Comment by ihadeed** [comment]
`.fetch()` returns a promise now.

**Comment by danielflippance** [comment]
Thanks. I'm now seeing an error when .then() is called:

    this.appPreferences.fetch('mysetting').then(function(res) {
      alert('++ Fetch succeeded res: ' + JSON.stringify(res)); 
    }, function(err) {
      alert('++ Fetch err: ' + JSON.stringify(err));
    });

Outputs:

    ++ Fetch err: "plugin_not_installed"

**Comment by danielflippance** [comment]
Solved by waiting for platform ready:

    platform.ready().then(() => { .this.appPreferences.fetch().then()... }

**Comment by loertle** [comment]
For browser try: first "ionic cordova build browser" and after that "ionic cordova run  browser".
Helped me.

**Comment by BinaryBlock** [comment]
> For browser try: first "ionic cordova build browser" and after that "ionic cordova run browser".
> Helped me.

This worked for me!!! Thank you.
