### ISSUE TITLE
Google maps mobile sdk

### ISSUE THREAD

**Issue by iBasit** [driftyco/ionic-native#13]
There is no support for this, can you please add it. 

It is so difficult to get mobile sdk up and running.

**Comment by ihadeed** [comment]
This is an interesting plugin ...

I just checked it out, and I was looking at this: https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map

Seems like the plugin doesn't rely on static functions, but relies on class functions instead. My understanding is that the Ionic Native is written to call the plugin's static functions only. 

Any thoughts @tlancina ?

**Comment by tlancina** [comment]
Yeah I'm not sure about this, we have the same issue with the Contacts plugin to some extent as well.  We could add it and just expose the properties of the plugin: https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/www/googlemaps-cdv-plugin.js#L2537-L2584, but I can't think of a good way for us to wrap the callbacks on the instantiated Map object.

**Comment by dmackerman** [comment]
Personally, implementing the Google Maps JS SDK is super simple. Even more so with NG2 now that we don't have to worry about `$digest`. I've never understood why you'd want the "native" component over just implementing a much more flexible `Component` with the raw Google JS SDK.

**Comment by mlynch** [comment]
Would love to expose a native control here if possible!

**Comment by ihadeed** [comment]
This would be another plugin related to issue https://github.com/driftyco/ionic-native/issues/86

**Comment by iBasit** [comment]
@dmackerman Native Map is a lot faster then JS SDK. Performance is beautiful with native map. Native map also brings some other functionality instantly, where we would have to create thous functionalities with JS SDK, like location pointer. 

I have used both SDK on ionic2 and native is 100% better in my opinion.

**Comment by ihadeed** [comment]
Looks & feels great, the Ionic Native wrapper works now for this plugin. Will complete the API for version 1.3.0
![screenshot_20160429-224618](https://cloud.githubusercontent.com/assets/13794420/14933434/bad9f9d8-0e5c-11e6-8122-2d7ed0b0950c.png)

**Comment by ndrrsn** [comment]
@ihadeed please review this issue [#161](https://github.com/driftyco/ionic-native/issues/161)
