### ISSUE TITLE
Ionic SecureStorage: Running on Android Uncaught Syntax Error "_native: Can't resolve all parameters..."

### ISSUE THREAD

**Issue by amymarsh4work** [driftyco/ionic-native#1300]
After moving to ionic-native 3 core and reinstalling the SecureStorage plugin, I'm getting the following error (below). The project won't even load onto the phone. Things I've tried that didn't help:
- Changed code to match example in documentation
- Included SecureStorage and SecureStorageObject in providers array in app.module.ts
- Installed in a fresh, empty project created last week
- Used both versions 3.1.0 and 3.3.0 of core and plugin
- Deleted node_modules and did npm install

I could repro the problem in all cases. I'm out of ideas now, so I'm reporting it.

**package.json**
"dependencies": {
    "@angular/common": "2.4.8",
    "@angular/compiler": "2.4.8",
    "@angular/compiler-cli": "2.4.8",
    "@angular/core": "2.4.8",
    "@angular/forms": "2.4.8",
    "@angular/http": "2.4.8",
    "@angular/platform-browser": "2.4.8",
    "@angular/platform-browser-dynamic": "2.4.8",
    "@angular/platform-server": "2.4.8",
    "@ionic-native/core": "3.3.0",
    "@ionic-native/secure-storage": "3.3.0",
    "@ionic-native/splash-screen": "3.3.0",
    "@ionic-native/status-bar": "3.3.0",
    "@ionic/storage": "2.0.0",
    "ionic-angular": "2.3.0",
    "ionicons": "3.0.0",
    "rxjs": "5.0.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.7.2"
  }

**Ionic Info:**
Cordova CLI: 6.1.1 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 7.3 Build version 7D175

**Error:** 
Uncaught Syntax Error > _nativeError: Can't resolve all parameters for SecureStorageObject: (?). at v (file:///android_asset/www/build/polyfills.js:3:4864) at SyntaxError.BaseError [as constructor] (file:///android_asset/www/build/main.js:136720:27) at new SyntaxError (file:///android_asset/www/build/main.js:12515:16) at CompileMetadataResolver._getDependenciesMetadata (file:///android_asset/www/build/main.js:27393:31) at CompileMetadataResolver._getTypeMetadata (file:///android_asset/www/build/main.js:27268:26) at CompileMetadataResolver._getInjectableMetadata (file:///android_asset/www/build/main.js:27256:21) at CompileMetadataResolver.getProviderMetadata (file:///android_asset/www/build/main.js:27498:40) at file:///android_asset/www/build/main.js:27456:49 at Array.forEach (native) at CompileMetadataResolver._getProvidersMetadata (file:///android_asset/www/build/main.js:27423:19) at CompileMetadataResolver.getNgModuleMetadata (file:///android_asset/www/build/main.js:27107:50) at JitCompiler._loadModules (file:///android_asset/www/build/main.js:73859:64) at JitCompiler._compileModuleAndComponents (file:///android_asset/www/build/main.js:73819:52) at JitCompiler.compileModuleAsync (file:///android_asset/www/build/main.js:73785:21) at PlatformRef_._bootstrapModuleWithZone (file:///android_asset/www/build/main.js:53628:25)

**Comment by ihadeed** [comment]
You only need to inject `SecureStorage`. You shouldn't inject `SecureStorageObject`.

**Comment by amymarsh4work** [comment]
Ibby,
Thanks for your prompt reply. I removed SecureStorageObject from the providers array and it worked fine. :)
- Amy
