### ISSUE TITLE
Plugin request: phonegap-mobile-accessibility

### ISSUE THREAD

**Issue by dorgold** [driftyco/ionic-native#1304]
Hey,

I would love to see https://github.com/phonegap/phonegap-mobile-accessibility added to ionic-native. This is a plugin which exposes the phone accessibility properties in cordova.

**Comment by danielsogl** [comment]
@dorgold I added this plugin. Wait fore the next release

**Comment by dorgold** [comment]
@danielsogl awesome! thanks for your effort!
