### ISSUE TITLE
App Preferences & ionic package build 

### ISSUE THREAD

**Issue by recyclethis** [driftyco/ionic-native#1310]
I believe that cordova-plugin-app-preferences does not work properly with ionic package build. To generate your preferences pane you configure your preferences in a app-settings.json file which I believe is not uploaded to the ionic package servers. The sneaky thing is, the plugin uses a default app-settings.json file if it cannot find the developer configured one so you get a preferences panel in the settings app, but it's not the what you want. I know this is more an issue with ionic package and not the plugin itself, but it might save someone some time if it was documented (if this wild theory is confirmed by someone who knows a little bit more about the package system).

**Comment by ihadeed** [comment]
See https://github.com/apla/me.apla.cordova.app-preferences#preferences-interface-generator

The plugin creates `app-settings.json` for you in the root directory of your app, see here: https://github.com/ihadeed/ionic-native-playground/blob/master/app-settings.json

Just modify that file.

**Comment by recyclethis** [comment]
Thanks Iadeed. My point was that it seems the ionic package system doesn't upload that file to the build servers, so while you do get a preference pane generated, it is always the sample settings installed by the plugin and any changes to the app-settings.json file are not included in the build. It seems to be an issue with the ionic package system and not this plugin, but it would be great if someone else could confirm this behavior. I've given up and gone in another direction for this app, since I don't have access to a Mac to build locally.
