### ISSUE TITLE
No decorator to set listener

### ISSUE THREAD

**Issue by flyingfisher** [driftyco/ionic-native#1312]
I have a method, need to convert to observable.

method:  setNotificationListener()
this method only take one param, to pass a function to receive notification.
e.g.  setNotificationListener(data => console.log('notification', data));

How can I convert it to observable?
I tried following decorator options:
1.
    observable: true
    successIndex: 0  (try both with and without this)
2.
    event: 'notification'
    eventObservable: true

None of upper success.
I have to use raw plugin method, and it is suceeded.

Please help me.

**Comment by ihadeed** [comment]
If it takes one callback, there's no need to set successIndex or errorIndex.
