### ISSUE TITLE
FileChooser plugin not installed

### ISSUE THREAD

**Issue by luckylooke** [driftyco/ionic-native#1316]
Following steps here: https://ionicframework.com/docs/native/file-chooser/
I am getting **"plugin_not_installed"**

I am calling `fileChooser.open()` in button click handler, so platform is ready. I was also trying to encapsulate into `platform.ready().then(...)`, didnt help.

I have had similar problem with barcodescanner, I have fixed it by adding a line into config.xml:
`<plugin name="phonegap-plugin-barcodescanner" spec="~6.0.5">`

So I was trying
  `<plugin name="cordova-filechooser" spec="0.0.0"/>`
and also
 ` <plugin name="com.megster.cordova.FileChooser" spec="0.0.0"/>`

I am testing app in Ionic View, many thanks

Ionic version: 2.2.2
Cordova version: 6.5.0
@ionic-native/core: 3.4.4
@angular/core: 2.4.8

**Comment by bvx89** [comment]
Have you tried to remove/add plugin again? Have you verified that the plugin has been included in your platform code? If you're using ionic-native 3, have you added the native plugin in app.module.ts as a provider?

**Comment by luckylooke** [comment]
😇 I am so sorry, my fault.. I didnt realise that FileChooser plugin is not included in Ionic View App bundle.. see here: https://docs.ionic.io/tools/view/

I am sorry.. @bvx89 Thanks you for reply anyway!
