### ISSUE TITLE
admob plugin not working on ios

### ISSUE THREAD

**Issue by logicerpsolution** [driftyco/ionic-native#1318]
i have created and integrated my admob id and plugin in my app but when i build it for ios and run on simulator it shows nothing .....
do i also need firebase admob sdk for ios to work it properly??

**Comment by ihadeed** [comment]
I tested the regular Admob plugin on an iPad device recently and it worked fine. Not sure if it's supposed to work on a simulator or not.

Which plugin are you having issues with? Admob or Admob Free? I will try to test it when I get a chance.
