### ISSUE TITLE
New version of google-analytics-plugin incompatible with latest Ionic Native

### ISSUE THREAD

**Issue by rodneyjoyce** [driftyco/ionic-native#1319]
Hello,

My Ionic cloud builds started failing this morning with no source code change on my side.

It looks like a new breaking change was made in 1.7.6 with the GetVar method - https://github.com/danwilson/google-analytics-plugin/blob/master/browser/UniversalAnalyticsProxy.js

This causes this error:

![image](https://cloud.githubusercontent.com/assets/3522966/24617543/d2f764ee-1859-11e7-8cf7-62d5d97a54fe.png)

To fix it, I had to pin the previous version of GA plugin to 1.7.5 in the Config.xml - the cloud build then worked...

**Comment by fredroo** [comment]
i also have this problem

**Comment by rodneyjoyce** [comment]
Ok, did the fix above work for you?

**Comment by danielsogl** [comment]
Hey @rodneyjoyce,

I will take a look into this changes.
