### ISSUE TITLE
 Error in import and Brazil currency

### ISSUE THREAD

**Issue by fredroo** [driftyco/ionic-native#1320]
IN: https://ionicframework.com/docs/native/paypal/
this right way to import: import { PayPal, PayPalPayment, PayPalConfiguration } from '@ionic-native/paypal';

and BRL currency not work, but paypal cordova plugin work with BRL currency

**Comment by ihadeed** [comment]
Not sure what you mean. Please submit a new issue and fill out the issue template with more details.
