### ISSUE TITLE
Native Google Maps code example error

### ISSUE THREAD

**Issue by SKempin** [driftyco/ionic-native#1322]
The example code on https://ionicframework.com/docs/native/google-maps/ has an error on line:
``` const marker: Marker = map.addMarker(markerOptions)```

which creates the following error:

``` 
Type 'Promise<void>' is not assignable to type 'Marker'. Property '_objectInstance' is missing in type 'Promise<void>'.

**Comment by SKempin** [comment]
For anyone in need of a [temporary fix](http://stackoverflow.com/questions/43162460/type-promisevoid-is-not-assignable-to-type-marker-property-objectinstan/43204192?noredirect=1#comment73494052_43204192), remove the `Marker` variable.

```const marker = map.addMarker(markerOptions)```

**Comment by Barathwaja** [comment]
temporarily I removed const marker. plus map is not coming also this **map.one(GoogleMapsEvent.MAP_READY).then(() => console.log('Map is ready!'));** event is not fired. Is there any example other than ionic provided? or anyone worked with the ionic example and came ??

**Comment by ihadeed** [comment]
@Barathwaja see this component: https://github.com/ihadeed/ionic-native-playground/blob/master/src/components/google-map/google-map.ts

**Comment by Barathwaja** [comment]
Thanks mate. Let me try.. @ihadeed
