### ISSUE TITLE
Deeplink `cordova_not_available`

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic-native#1326]
> Got a deeplink that didn't match cordova_not_available

When doing: (on serve)
```
this.deepLinks.route(routes).subscribe((match) => {
    // match.$route - the route we matched, which is the matched entry from the arguments to route()
    // match.$args - the args passed in the link
    // match.$link - the full link data
    console.log("Successfully matched route", match);
}, (noMatch) => {
    // Report to rollbar
    Rollbar.info("deepLinks no match - " + noMatch.$link);

    // nomatch.$link - the full link data
    console.error("Got a deeplink that didn\'t match", noMatch);
});
```

**Comment by ihadeed** [comment]
I'll try to reproduce this when I get a chance.

In the meanwhile, could you try something like this:
```ts
this.deeplinks.routeWithNavController(this.navCtrl, {
          '/': 'home',
          '/event/:eventId': 'EventPage',
          '/events': 'EventsPage',
          '/place/:placeId': 'PlacePage',
          '/places': 'places'
        }).subscribe((match) => {
            // console.log('Matched route', match)
          }, (nomatch) => {
            // console.log('Mismatch route', nomatch);
          });
```

**Comment by ihadeed** [comment]
@AmitMY is this still an issue? I haven't had the chance yet to reproduce it... Deeplinking not working at all on my end (native and framework).

**Comment by AmitMY** [comment]
No, this one is solved.. forgot to close it
Foolish me ran it in serve, not in browser platform

**Comment by jellebrouwer** [comment]
Hi,
I had the same issue. I understand it doesn't work with `ionic serve`?

**Comment by AmitMY** [comment]
@jellebrouwer Correct.
For serve support for routing, use the `segment` on `IonicPage`.
https://ionicframework.com/docs/api/navigation/IonicPage/

It does not function the same, but close enough
