### ISSUE TITLE
YoutubeVideoPlayer not working in ionic serve

### ISSUE THREAD

**Issue by wodka** [driftyco/ionic-native#1328]
The moment I try to inject YoutubeVideoPlayer in a Page it breaks.

and it would be nice to point people to https://github.com/JonSmart/CordovaYoutubeVideoPlayer because this fork works on newer android versions as well

```
NoProviderError {_nativeError: Error: No provider for YoutubeVideoPlayer!
    at v (http://localhost:8100/build/polyfills.js:3:4864…, keys: Array(1), injectors: Array(1), constructResolvingMessage: function
```

**Comment by ihadeed** [comment]
The error is saying that you haven't imported `YoutubeVideoPlayer` provider into your app's module. Please follow the Ionic Native docs for more information on installing plugins.

**Comment by wodka** [comment]
This is the thing -> it is importet and working in an emulator / a real device

the error is just showing up in ionic serve

**Comment by ihadeed** [comment]
Ok I'll try to reproduce this when I get a chance.

**Comment by wodka** [comment]
It stopped happening on my system, closing it
