### ISSUE TITLE
[AppPreferences] store should accept string, number, boolean

### ISSUE THREAD

**Issue by EbilPanda** [driftyco/ionic-native#1334]
as stated in the title - AppPreference-Plugin accepts `string, number, boolean` as inputs, as stated [here](https://github.com/apla/me.apla.cordova.app-preferences#notes)

currently it only accepts string as keys and value, so if I define an value (e.q. boolean -> toogle-type in app-settings.json) and want to change it in code, the saved type will be changed to string and the preference-screen will not work anymore because the type is not as expected

solution:

change

```
store(dict: string, key: string, value?: string): Promise<any>;
```

to

```
store(dict: string, key: string|number|boolean, value?: string|number|boolean): Promise<any>;
```

(key must be same because of overloading...)

**Comment by danielsogl** [comment]
Hey @EbilPanda,

I implemented your suggestions.
