### ISSUE TITLE
How to deregister Diagnostic.registerNFCStateChangeHandler

### ISSUE THREAD

**Issue by daviddbeasy** [driftyco/ionic-native#1337]
After calling to diagnostic.registerNFCStateChangeHandler, the handler is called when the NFC status changes. Bug, how can be removed the handler if for some reason i don't want to be notified again? In the documentation it's said "Pass in a falsey value to de-register the currently registered function.". What is a "falsey value" if the function diagnostic.registerNFCStateChangeHandler only accept a function as the only one parameter?

And what happens if a new call to register is done without registering the previous one?

**Comment by dpa99c** [comment]
[Definition of a falsey value](https://developer.mozilla.org/en-US/docs/Glossary/Falsy)

If in doubt, [look at the source code](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/www/android/diagnostic.js#L1292)

**Comment by lilian131** [comment]
like :
`this._diagnostic.registerLocationStateChangeHandler((state) => {})`
do 
`this._diagnostic.registerLocationStateChangeHandler(false)`
