### ISSUE TITLE
No provider for GoogleMaps!

### ISSUE THREAD

**Issue by gbelmm** [driftyco/ionic-native#1339]
code:

import {
 GoogleMaps,
 GoogleMap,
 GoogleMapsEvent,
 LatLng,
 CameraPosition,
 MarkerOptions,
 Marker
} from '@ionic-native/google-maps';

error in web/device

No provider for GoogleMaps!
(anonymous) @ /Users/gbelmm/workspace/ionic2/hostify/node_modules/ionic-angular/navigation/nav-controller-base.js:115
t.invoke @ polyfills.js:3
onInvoke @ /Users/gbelmm/workspace/ionic2/hostify/node_modules/@angular/core/@angular/core.es5.js:4351
t.invoke @ polyfills.js:3
n.run @ polyfills.js:3
(anonymous) @ polyfills.js:3
t.invokeTask @ polyfills.js:3
onInvokeTask @ /Users/gbelmm/workspace/ionic2/hostify/node_modules/@angular/core/@angular/core.es5.js:4342
t.invokeTask @ polyfills.js:3
n.runTask @ polyfills.js:3
a @ polyfills.js:3
invoke @ polyfills.js:3
/Users/gbelmm/workspace/ionic2/hostify/node_modules/@angular/core/@angular/core.es5.js:1291 ERROR Error: Uncaught (in promise): Error: No provider for GoogleMaps!

  "dependencies": {
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/compiler-cli": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@ionic-native/core": "^3.4.2",
    "@ionic-native/device": "^3.4.2",
    "@ionic-native/geolocation": "^3.4.2",
    "@ionic-native/google-maps": "^3.4.4",
    "@ionic-native/splash-screen": "^3.4.2",
    "@ionic-native/status-bar": "^3.4.2",
    "@ionic/storage": "2.0.1",
    "imgcache.js": "^1.1.1",
    "ionic-angular": "3.0.0-201704061529",
    "ionicons": "3.0.0",
    "rxjs": "5.1.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.0",
    "typescript": "~2.2.1"
  },

plugins

cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-file 4.3.2 "File"
cordova-plugin-file-transfer 1.6.2 "File Transfer"
cordova-plugin-geolocation 2.4.2 "Geolocation"
cordova-plugin-googlemaps 1.4.0 "phonegap-googlemaps-plugin"
cordova-plugin-splashscreen 4.0.2 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.2-dev "Cordova WKWebView Engine"
cordova-sqlite-storage 2.0.2 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"

**Comment by tobiasmuecksch** [comment]
I have the same issue for GoogleAnalytics!

**Comment by tobiasmuecksch** [comment]
Example code to reproduce this issue
```
import { GoogleAnalytics } from '@ionic-native/google-analytics';

@Injectable()
export class Analytics {
constructor(public ga: GoogleAnalytics){}
}
``

**Comment by tobiasmuecksch** [comment]
@gbelmm Your issue is very incomprehensible. Please use markdown to tidy it up and make it more readable. No one will help us if issues look like this.

**Comment by tobiasmuecksch** [comment]
StatusBar is broken too

**Comment by tobiasmuecksch** [comment]
@gbelmm You have to add GoogleMaps to the providers array in your `app.module.ts` file.

**Comment by tobiasmuecksch** [comment]
@gbelmm If that worked for you, please close this issue. Thank you :-)

**Comment by gbelmm** [comment]
yes worker
 Thank you :-)
