### ISSUE TITLE
Ionic native : Image picker not working.

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-native#1341]
_From @rijin-newage on April 6, 2017 15:43_

Hello, 

I can't use ionic native **Image picker** plugin with **BackgroundMode** plugin.

No error is showing, but when i am calling getPictures function, it is giving an empty array as response before choosing any pics, after choosing pics it does't giving any response.

This issue is fixed when i removed BackgroundMode plugin. 

I'm using the latest version of ionic 2 framework (2.2.0)

Thank you

_Copied from original issue: driftyco/ionic#11095_

**Comment by ihadeed** [comment]
This doesn't seem like an issue with the Ionic Native wrapper.

Ionic Native is just a wrapper and it has no effect on how the plugin performs. Please seek help at the plugin's repo or at the Ionic Forums.
