### ISSUE TITLE
Property 'setItem' does not exist on type 'typeof NativeStorage'

### ISSUE THREAD

**Issue by Ranhiru** [driftyco/ionic-native#1343]
I am trying to upgrade an Ionic 2 app to Ionic 3 and came across a weird situation where suddenly `NativeStorage` doesn't seem to have any of the static methods that was present earlier. (setItem, getItem, remove)

My method looks like
```
  saveLocally() {
    NativeStorage.setItem(USER, this.toJSON());
  }
```

The error is 

```
[16:36:39]  typescript: src/models/user-model.ts, line: 35
            Property 'setItem' does not exist on type 'typeof NativeStorage'.

      L34:  saveLocally() {
      L35:    let setUserDataPromise = NativeStorage.setItem(USER, this.toJSON());
```

I have done 
```
ionic plugin add cordova-plugin-nativestorage
npm install --save @ionic-native/native-storage
```

and the file has `import { NativeStorage } from '@ionic-native/native-storage';` at the top.

My `package.json` has 

`"@ionic-native/native-storage": "^3.4.4"` under `dependencies`

What was changed from Ionic 2 to 3 to prevent this from compiling ? Any help would be appreciated.

**Comment by darthdie** [comment]
Ionic-native 3 changed to using providers. You now inject the plugins and use them that way, rather than via static methods.

https://github.com/driftyco/ionic-native#basic-usage

**Comment by danielsogl** [comment]
Hey @Ranhiru, can you close this issue?

**Comment by gdesplin** [comment]
@darthdie I see this was the solution, but I don't understand how to implement it. The link wasn't to helpful to me. When we 'inject' the native storage plugin and I want to use it in a provider file like I already was, how do i do this? My code looks like
```
import { NativeStorage } from '@ionic-native/native-storage';
...
 constructor(public http: Http, public storage: NativeStorage) {
 
  }
...
 this.storage.get('token').then((value) => {```

**Comment by darthdie** [comment]
You are already doing it correctly. Is it giving you an error?

**Comment by gdesplin** [comment]
I was giving me an error. I did figure out the issue. I was using this.storage.get('token')... But now it the latest version of native storage the you use getItem instead of just get i.e. this.storage.getItem('token')... Thanks for responding.
