### ISSUE TITLE
Should I wait for platform.ready before calling native?

### ISSUE THREAD

**Issue by aggarwalankush** [driftyco/ionic-native#1349]
Ionic native 3 docs(https://ionicframework.com/docs/native/status-bar/) doesn't show requirement to wait for platform.ready() before calling native plugins. Is it required or not?

```
constructor(public platform: Platform,
              public statusBar: StatusBar) {
    platform.ready().then(() => {   // should i wait for this
      statusBar.styleDefault();
    });
  }
```

**Comment by royipressburger** [comment]
All plugin are available after `deviceReady`. you can also see in the plugin docs:
https://github.com/apache/cordova-plugin-statusbar/blob/master/README.md

**Comment by ihadeed** [comment]
@aggarwalankush to keep docs cleaner and less repetitive we don't include the platform.ready() part, but yes you should wait for `deviceready` to fire before doing anything.
