### ISSUE TITLE
How to use mocks properly in dev and prod.

### ISSUE THREAD

**Issue by royipressburger** [driftyco/ionic-native#1350]
Hi. 

I started to implement mock to all the plugins I use, It all works great both in `dev` and in `prod`.
The problem is that in `prod` mode I have to comment out the line of the providers.
`{provide: Camera, useClass: CameraMock}`

How can we do this more dynamically without commenting out on each build?

**Comment by dtaalbers** [comment]
You can try [this](https://www.joshmorony.com/automating-mocks-in-ionic-native-3-x/). I managed to set up like the example and works OK.

**Comment by ihadeed** [comment]
@royipressburger see http://stackoverflow.com/questions/39535386/how-to-check-if-angular-2-app-is-running-in-production-or-dev for inspiration
