### ISSUE TITLE
youtube video player not working on android > 6

### ISSUE THREAD

**Issue by wodka** [driftyco/ionic-native#1352]
Hi, the default youtube video player is not updated any more. 

OLD: https://github.com/Glitchbone/CordovaYoutubeVideoPlayer
NEW: https://github.com/JonSmart/CordovaYoutubeVideoPlayer

the new one is working with newer android versions and has a callback to know when the video was finished.

**Comment by danielsogl** [comment]
@wodka,

I will take a look into the new updated repo

**Comment by jayeshanandani** [comment]
Can we release and merge this please? Not able to use plugin due to non-availability of the 5.0 android API key.

**Comment by danielsogl** [comment]
@jayeshanandani just run cordova plugin add https://github.com/JonSmart/CordovaYoutubeVideoPlayer.git

We didn't change the wrapper just the source.

And read the addition config steps for Android > 5.0: https://github.com/JonSmart/CordovaYoutubeVideoPlayer

**Comment by jayeshanandani** [comment]
Thanks @danielsogl that worked.
Thanks @ihadeed  for merging this.
