### ISSUE TITLE
Please add the BluetoothSerial plugin

### ISSUE THREAD

**Issue by stickystyle** [driftyco/ionic-native#136]
I'm trialing an Ionic2 rewrite of an app that is currently written in Kivy, and one of main things the app needs is bluetooth serial access (not BLE). For this it looks like the only cordova plugin avaiable is https://github.com/don/BluetoothSerial. I don't see the plugin listed in http://ngcordova.com/docs/plugins, but is is listed in http://ngcordova.com/build/ so I'm guessing that was just an oversight?

**Comment by ihadeed** [comment]
Anything that you see on `ngCordova` site/repo does not relate to `Ionic Native`. They are two separate packages.

We can still add this plugin to Ionic Native though :)
