### ISSUE TITLE
Upgrade to @ionic-native/core 3.4.4 plugin not installed on --prod build

### ISSUE THREAD

**Issue by FredBaine** [driftyco/ionic-native#1361]
I am getting a couple of plugin not installed warnings and 1 Error in console when I use "ionic run android --prod", but do not get them when I use "ionic run android" without the --prod flag.

Console output
![image](https://cloud.githubusercontent.com/assets/3266293/24930098/f18ca1e2-1ecd-11e7-876f-5764b439f855.png)

Config.xml
![image](https://cloud.githubusercontent.com/assets/3266293/24930314/b68e3050-1ece-11e7-970f-c7e052854a2a.png)

package.json
[package.json.pdf](https://github.com/driftyco/ionic-native/files/914654/package.json.pdf)

**Comment by yurik94** [comment]
👍 👍 👍 
 Same issue here since a few days :( I can't use properly Native Storage with --prod flag

**Comment by yurik94** [comment]
@FredBaine You should at least install this
`npm install --save @ionic-native/native-storage`

and I think you should remove the ionic storage module from npm
