### ISSUE TITLE
BarcodeScanner torchButton locks up app when using option showTorchButton:true

### ISSUE THREAD

**Issue by wkande** [driftyco/ionic-native#1366]
BarcodeScanner torchButton locks up app when using option showTorchButton:true. Scanner works fine until you click the Torch button provided. The native plugin appears to be calling setTorchModeOnWithLevel with an invalid torch mode.

iOS 10.2 iPad mini 4

"@ionic-native/barcode-scanner": "^3.4.4"

"name": "phonegap-plugin-barcodescanner",
  "version": "6.0.5"

```this.barcodeScanner.scan({showTorchButton:true}).then```

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: OS X El Capitan
Node Version: v6.9.4
Xcode version: Xcode 8.2.1 Build version 8C1002
```

--------------- Xcode error -----------------------------------
2017-04-12 07:48:00.091710 Warehouse[8809:6946979] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureDevice setTorchModeOnWithLevel:error:] The passed torchLevel 340282346638528859811704183484516925440.000000 is not supported - use -isTorchModeSupported: to discover valid torch modes'

*** First throw call stack:
(0x18e2811b8 0x18ccb855c 0x195a45c2c 0x100094ad0 0x18ed7e46c 0x18e22f1d8 0x18e22eeec 0x18e22e7a8 0x18e22c3a4 0x18e15a2b8 0x18fc0e198 0x19419a7fc 0x194195534 0x100075d78 0x18d13d5b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by ihadeed** [comment]
This doesn't seem like an issue with the Ionic Native wrapper.

Ionic Native is just a wrapper and it has no effect on how the plugin performs. Please seek help at the plugin's repo or at the Ionic Forums.
