### ISSUE TITLE
BluetoothSerial automatically disconnecting after 20+ seconds

### ISSUE THREAD

**Issue by bot101** [driftyco/ionic-native#1367]
I am currently writing an android app that communicates with an arduino device over bluetooth using the HC-06 nluetooth module. The device connects successfully but disconnects after about 20 seconds and calls the `BluetoothSerial.connect().subscribe()` error callback.I couldn't find a solution on Google or Stackoverflow, or anywhere else on the internet.

**Comment by ihadeed** [comment]
This doesn't seem like an issue with the Ionic Native wrapper.

Ionic Native is just a wrapper and it has no effect on how the plugin performs. Please seek help at the plugin's repo or at the Ionic Forums.
