### ISSUE TITLE
issue(docs): install plugin with --save param

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic-native#1385]
Currently, all the docs give an example on how to install a plugin:

For example:
```
$ ionic plugin add cordova-plugin-media
$ npm install --save @ionic-native/media
```

I *strongly* suggest that the `ionic plugin add` command has a `--save` parameter as well so that the plugin is added to the config.xml file. 

For teams that pull a project from source control and add a platform, many of the required plugins will not be installed as without the `--save` parameter cordova will not download and install them.

**Comment by jaufgang** [comment]
This is especially important since the behaviour has changed...  `ionic plugin add` used to update the config.xml automatically without `--save`, but now it is required, so it really should be explicit in the docs.
