### ISSUE TITLE
media plugin - duration of mediaObject always unknown

### ISSUE THREAD

**Issue by AleFons** [driftyco/ionic-native#1390]
MediaObject.getDuration() seems to always return -1.

I'm creating a file and then creating a mediaObject to record on them; I wouldn't expect getDuration() on a mediaObject that was just made - even after calling stopRecord() on it - to work, but then it also doesn't work if I create a new mediaObject and call getDuration() again.

**Comment by ihadeed** [comment]
Looks like the Ionic Native implementation of the plugin is correct. This must be an issue with the plugin itself.

Please seek help at the plugin's repo or the Ionic forums.
