### ISSUE TITLE
Missing disableWebViewOptimizations method in Background Mode

### ISSUE THREAD

**Issue by nonamez** [driftyco/ionic-native#1393]
As described at https://github.com/katzer/cordova-plugin-background-mode there is special method `disableWebViewOptimizations` which is specified for my case - I need to send position every x time in background but nothing happens when app is minimized but the method doesn't exists in the wrapper.

**Comment by danielsogl** [comment]
Hey @nonamez,
thank you for opening this issue.
I added the method!
