### ISSUE TITLE
Can't resolve all parameters for MediaObject: (?) Android 7.0

### ISSUE THREAD

**Issue by baksagimm** [driftyco/ionic-native#1394]
I get this error whenever media plugin is used:
"Uncaught Error: Can't resolve all parameters for MediaObject: (?).", source: file:///android_asset/www/build/main.js (93297)

"ionic-angular": "3.0.1",
"@ionic-native/media": "^3.5.0",
cordova-plugin-media@latest
cordova platform android@latest
android 7.0

Tested with ionic 3 media plugin doc example code.

**Comment by baksagimm** [comment]
I found out I should not add MediaObject in Providers in app.module.ts

**Comment by lukewduncan** [comment]
do you only need the `MediaPlugin` to get the plugin working?
