### ISSUE TITLE
List all loaded plugins

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic-native#1396]
I am using many plugins in my application, and I realised that sometimes, when I make changes, my team not necessarily run prepare, or I forgot to save the plugins in the `config.xml`, so we build an app without all of the plugins.

I want to create a page, that lists all of the plugins, and their status: Loaded/Not Loaded.

I have a list of all plugin names (cordova-plugin-x) and I can manually inject all of the plugins if I have to.

How can I check if a plugin is loaded or not?

Relevant empty forum thread: https://forum.ionicframework.com/t/check-if-plugin-is-loaded/85909

**Comment by ihadeed** [comment]
1. Wait for `platform.ready()`
2. Call the static method `installed()` on any plugin. Example: `(<any>Camera).installed()`. It will return `true` if the plugin is loaded.

**Comment by AmitMY** [comment]
@ihadeed Thanks!

**Comment by AmitMY** [comment]
@ihadeed Are plugins being loaded for `serve`?
I though plugin only work in a platform, not in serve, however, it shows me this list:
![image](https://cloud.githubusercontent.com/assets/5757359/25248088/a0b8bcc0-2615-11e7-89a8-1e06a5cb4b3a.png)

This is my source:
```
platform.ready().then(() =>
    this.plugins.forEach(plugin =>
        this.loadedPlugins.push({plugin, isInstalled: (<any>plugin).installed()})
    ));
```

**Comment by ihadeed** [comment]
@AmitMY if the `pluginRef` exists, `installed()` will return true. Geolocation exists on browsers, and `Vibration` uses `navigator` as it's main object so it returns `true` even though the plugin doesn't actually exist.
