### ISSUE TITLE
ionic-native has the wrong pluginRef for flurry-analytics

### ISSUE THREAD

**Issue by gregavola** [driftyco/ionic-native#1399]
Hey there,

For this plugin:
https://github.com/driftyco/ionic-native/blob/master/src/%40ionic-native/plugins/flurry-analytics/index.ts#L105

The `pluginRef` should be:  `FlurryAnalytics` or `plugin.FlurryAnalytics` per this:
https://github.com/blakgeek/cordova-plugin-flurryanalytics/blob/d80e8e84dd78e695089ea9f8b8cd5357a928326a/plugin.xml#L14

**Comment by wajdiii** [comment]
I had this issue "plugin_not_installed" when I try to build my app on iOS

**Comment by danielsogl** [comment]
Hey @gregavola,
thank you for opening this issue.
I fixed the wrong pluginRef.
