### ISSUE TITLE
Temporary add to documentation

### ISSUE THREAD

**Issue by FrancescoMussi** [driftyco/ionic-native#1401]
Can you please make a temporary add to the **Camera Preview** plugin [documentation](https://ionicframework.com/docs/native/camera-preview/)?

Following that installation instructions the plugin won't install.
As long as the plugin is in beta this is the proper way to install it:

`ionic plugin add https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview.git`

Otherwise it will give the following error:

`plugin_not_installed`

![image](https://cloud.githubusercontent.com/assets/5312907/25267034/075b3a0a-267c-11e7-80a0-dd292ff67c33.png)

Reference: [#277](https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/issues/277)

**Comment by danielsogl** [comment]
Hey @FrancescoMussi,

I think you can close this issue because the installation instruction was added to the docs

> Requires Cordova plugin: https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview.git. For more info, please see the Cordova Camera Preview docs.
