### ISSUE TITLE
Firebase real time database support

### ISSUE THREAD

**Issue by Sampath-Lokuge** [driftyco/ionic-native#1404]
Hi,
Can we have a real-time database support for the below plugin? Thanks.

http://ionicframework.com/docs/native/firebase/

**Comment by danielsogl** [comment]
Hey @Sampath-Lokuge,
for this kind of usage, you should use the official [Angularfire2 package](https://github.com/angular/angularfire2) from the Firebase Team.

**Comment by ihadeed** [comment]
@Sampath-Lokuge 
I would go with what @danielsogl suggested. If you wish to have a native plugin added with that functionality, please provide a repository that we can have a look at.

**Comment by Sampath-Lokuge** [comment]
Hi @ihadeed 
Sorry I didn't get exactly what you mean? There is a repository which doesn't have real-time database support. That repo is mentioned on your doc also.That is this: https://github.com/arnesson/cordova-plugin-firebase. Is that what you need or what?

**Comment by ihadeed** [comment]
@Sampath-Lokuge 

I meant that the current plugin doesn't support real-time database functionality. Unless if you find a plugin with that functionality, we wouldn't be able to add it here. Ionic native is just a wrapper for Cordova plugins.

**Comment by Sampath-Lokuge** [comment]
Oh.. got it.Hope there is no such plugin yet.I'l try with the Angularfire2. Thanks @ihadeed

**Comment by stormwin** [comment]
https://github.com/blakgeek/cordova-plugin-firebase-database

**Comment by Sampath-Lokuge** [comment]
Oh.. It is there.Have you used that plugin @stormwin ?

**Comment by stormwin** [comment]
I created my own plugin where i merged current firebase plugin and database plugin in one. Then i created my own ionic-native plugin for that..

**Comment by Sampath-Lokuge** [comment]
Oh.. Is it working properly? Can we have more info about that? @stormwin
