### ISSUE TITLE
Native SplashScreen problem on iOS 9.3.5

### ISSUE THREAD

**Issue by petrot** [driftyco/ionic-native#1406]
My code works well on Android and iOS10, but on iOS 9.3.5 the app freeze on the splash screen . I read old bug reports on the phonegap site, but I didn't find fix for this problem. Is there any known solution?

My config:
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.4
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.3.2 Build version 8E2002

Platform:
android 6.2.1
 ios 4.3.1

**Comment by ihadeed** [comment]
Seems like an issue with the plugin and not with the Ionic Native implementation.
