### ISSUE TITLE
error with npm run build

### ISSUE THREAD

**Issue by nicobytes** [driftyco/ionic-native#1408]
Hello!

I tried to run ```npm run build``` but show error:

![screen shot 2017-04-23 at 1 12 02 pm](https://cloud.githubusercontent.com/assets/7611944/25317545/a25f95e6-2848-11e7-9d3a-720dea61825d.png)
 
the error is in contacts/index.ts

![screen shot 2017-04-23 at 1 10 45 pm](https://cloud.githubusercontent.com/assets/7611944/25317548/ba26543a-2848-11e7-9a60-4863539268ba.png)

this is not Contact type for default: one possible fix is:

![screen shot 2017-04-23 at 5 19 45 pm](https://cloud.githubusercontent.com/assets/7611944/25317569/13609c0e-2849-11e7-97b0-2fd06511c75b.png)

**Comment by nicobytes** [comment]
Also in file/index.ts

![screen shot 2017-04-23 at 5 27 59 pm](https://cloud.githubusercontent.com/assets/7611944/25317632/4726aaaa-284a-11e7-880d-85ed97e8f67f.png)

I only follow the steps in https://github.com/driftyco/ionic-native/blob/master/DEVELOPER.md:

1. Fork of ionic-native
1. npm run build

I only want contribute in this project with a pull request, add this function in mixpanel plugin:

![screen shot 2017-04-23 at 5 30 32 pm](https://cloud.githubusercontent.com/assets/7611944/25317647/ab88107e-284a-11e7-9db7-7d1ae4708b4a.png)

**Comment by steegi** [comment]
Master and 3.6.1 seem to be broken. I switched to 3.5.0 which works fine.

**Comment by danielsogl** [comment]
Fixed with commit 134eab2dcc43cbf00aa5b63c06516dfdbe5e4636

Can you close it @nicobytes?
