### ISSUE TITLE
Ionic 1 project with Typescript external modules

### ISSUE THREAD

**Issue by ddennis** [driftyco/ionic-native#141]
I am working on a Ionic 1 project using Typescript external modules with browserify.

When i import 
    `import {Toast} from 'ionic-native' `

I get alot of errors regarding Promise:
     `.../node_modules/rxjs/CoreOperators.d.ts(89,67): Error TS2304: Cannot find name 'Promise'.`

and
`.../node_modules/ionic-native/node_modules/rxjs/observable/FromObservable.d.ts(7,51): Error TS2304: Cannot find name 'Iterator'.`

I have also tried installing and importing 'rxjs' but no luck.
Am i missing a d.ts/typings file? or what is the problem?

**Comment by ihadeed** [comment]
If you are on Ionic 1 you can import `ngCordova` as an Angular 1 module and use it in your app. Alternatively, you may also call the plugins through `window.IonicNative`. Example: `IonicNative.Toast.show(...);`

I hope that helped.

**Comment by ddennis** [comment]
Thank you for taking the time to help out, i might be missing something, but i know about ngCordova but if i understand correctly ionic-native will be the way forward.

Since i am using browserify, with typescript external modules and specifically only import the Toast plugin i am not able to reference a global `ionicNative.Toast.show()`. Sorry for not being more precise, i have installed ionic-native from npm and am now trying to just import the single Toast plugin.

The problem seems to be that i was missing the es6-shim definition file, 
[as mentiond in this thread](https://github.com/ReactiveX/RxJS/issues/592) the es6-shim definition is included with angular 2, which could be why you havent had the problem.

Thanks

**Comment by ihadeed** [comment]
If you import the ionic native bundle JS file into your index.html you will
be able to access the plugins via IonicNative variable or ngCordova module.

I haven't tested the ngCordova module method personally, but from the look
of the code in index.ts it should work!

ngCordova and ionic native are separate, you are right. But the angular 1
module for Ionic native  is being exported as ngCordova. (Again, just what
I understand from reading the code, haven't tested it personally)

**Comment by ddennis** [comment]
Ok - Thanks.
