### ISSUE TITLE
native-file get file meta data

### ISSUE THREAD

**Issue by Ross-Rawlins** [driftyco/ionic-native#1411]
Hi

The plugin has a function called resolveLocalFilesystemUrl() that returns the files meta data but ionic native implementation is not returning the size property. Please can we add this?

**Comment by ihadeed** [comment]
You need to call the method `.file()` to get this data. Example:
```
this.file.resolveLocalFilesystemUrl(...)
  .then((file: FileEntry) => {
    file.file(meta => console.log(meta), error => console.log(error));
  });
```

**Comment by totovelo10** [comment]
FileEntry did'nt match with my code so I write that

this.file.resolveLocalFilesystemUrl(fileUrl).then(
          (file) =>{
            file.getMetadata((meta) => console.log(meta), error => console.log(error))
          }

        )

**Comment by huynhnv** [comment]
Hello,
How can I get size and modificationTime of file.
I use:
if(this.platform.is('android')) {
          this.path =this.file.externalApplicationStorageDirectory;
          this.file.listDir(this.path,'files').then((files:any) =>{
            files.map((val)=>{
                  if(val.isFile){
		    this.meta = [];
		    let Fsize=0;
		    let modifydate= '';
		    val.resolveLocalFilesystemUrl(val.nativeURL).then(
		          (file) =>{
		            	file.getMetadata((metadata) => {
					Fsize= metadata.size; // Get file size
					modifydate = metadata.modificationTime;	
					this.meta.push(Fsize);
					this.meta.push(modifydate);
					
				}, error => console.log(error))
		          }
		        );
	 	    
		    this.latestConvertion.unshift({
	                name: val.name,
	                path : val.nativeURL,
		        modifydate: this.meta[1],
		        Fsize: this.meta[0]
	            });
		    
              }
            })
          }).catch(error=> console.log(JSON.stringify(error)));
      }

**Comment by DensetsuOtoko** [comment]
> You need to call the method `.file()` to get this data. Example:
> 
> ```
> this.file.resolveLocalFilesystemUrl(...)
>   .then((file: FileEntry) => {
>     file.file(meta => console.log(meta), error => console.log(error));
>   });
> ```

thanks, it saves me.
