### ISSUE TITLE
GoogleMap.panBy not implemented

### ISSUE THREAD

**Issue by vosecek** [driftyco/ionic-native#1413]
panBy for maps is not implemented

**Comment by danielsogl** [comment]
Hey @vosecek,
this method is implemented as you can see here: https://github.com/driftyco/ionic-native/blob/master/src/%40ionic-native/plugins/google-maps/index.ts

```ts
  @CordovaInstance({ sync: true })
  panBy(): void { }
```

**Comment by ihadeed** [comment]
The method was just updated in 3.7.0 as well to add the missing parameters.
