### ISSUE TITLE
issue(docs): examples should inject public variables

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic-native#1414]
The ionic team recommends that all variables are injected into the constructors using the `public` variable. This is to make sure that there are no NGC errors.

In the examples in the ionic-native docs, I suggest making the examples where the plugins are injected into the constructors `public` instead of `private`.

**Comment by rapropos** [comment]
I totally disagree with this. Only properties accessed by templates need to be public, and ionic-native plugins are very rarely, if ever, interacted with by templates directly.

**Comment by ihadeed** [comment]
AFAIK `public` is only needed when the variable is being used in the template or by another class. I never experienced any issues by using `private`.
