### ISSUE TITLE
native-storage missing NativeStorage.keys function

### ISSUE THREAD

**Issue by tedliang-asahi** [driftyco/ionic-native#1415]
This function [NativeStorage.getItem("reference_to_value", \<success-callback>, \<error-callback>) ](https://github.com/TheCocoaProject/cordova-plugin-nativestorage#retrieving-all-keys) is missing on the @ionic-native/native-storage wrapper.

Is it intentional? or it's a new feature that is not yet covered by the wrapper?

**Comment by danielsogl** [comment]
Hey @tedliang-asahi, the requested methods are implemented. Check the latest native release.
But I added the missing keys() method.

**Comment by tedliang-asahi** [comment]
Great! Thanks for the update

**Comment by wesleywouters** [comment]
@ihadeed keys seems to be removed again in native-storage 3.6.0 in the npm repository.
