### ISSUE TITLE
feature(local notifications): offical phonegap plugin released

### ISSUE THREAD

**Issue by danielsogl** [driftyco/ionic-native#1417]
The PhoneGap team just released an official local notifications plugin as you can read here: https://blog.phonegap.com/release-of-phonegap-local-notification-plugin-bc7f480b6fd6

I would recommend implementing this then the actually used unofficial plugin.

Here is the repo: https://github.com/phonegap/phonegap-plugin-local-notification

If I find time I will create a PR for this plugin.

**Comment by John-Luke** [comment]
I've looked the official plugin and I saw that the unofficial plugin is more complete than the official

**Comment by ihadeed** [comment]
I vote to add it as `local-notifications-2` or `phonegap-local-notifications`. I don't think we should replace the existing plugin.

I agree with @John-Luke, the plugin seem to have less functionality than the "unofficial" plugin.

**Comment by danielsogl** [comment]
I will create a PR for this plugin.

I think the name phonegap-local-notifications is okay
