### ISSUE TITLE
image-picker can not build on ionic-native/core 3.4.2

### ISSUE THREAD

**Issue by mene078** [driftyco/ionic-native#1426]
I'm using "@ionic-native/core": "^3.4.2" and try to add image-picker plugin
But got the error msg about IonicNativePlugin, tried to search around about it but unfortunately.
the error message from building not give that much that I can trace more about it.
What should I do next?

```
typescript: node_modules/@ionic-native/image-picker/index.d.ts, line: 1
Module '"..../node_modules/@ionic-native/core/index"' has no exported member 'IonicNativePlugin'.
```

**Comment by ihadeed** [comment]
Sorry I forgot to change the core package dependency in the new release. Please update @ioniv-native/core to 3.6.0

**Comment by mene078** [comment]
That's solved all. thank you so much.

**Comment by wbmedia** [comment]
thanks! mate this solution works for me 💯  :)

**Comment by danielsogl** [comment]
@mene078 can you close it?
