### ISSUE TITLE
Allow higher minor&fix version of Angular in package.json of Ionic  Native

### ISSUE THREAD

**Issue by astec** [driftyco/ionic-native#1427]
Is there any reason to pin `devDependencies` to a strict Angular version?

Can you make it `"@angular/compiler": "^4.0.2"`? For example Ionic v3.1 has "4.0.2" for all Angular packages. Same as it's done for `zone.js`.

Would it harm if Ionic packages are bounded just by a specific major and a minimum minor versions and we can upgrade dependencies to bug fixes & minor updates without warnings?

```
{
  "name": "ionic-native",
  "version": "3.6.1",
  "devDependencies": {
    "@angular/compiler": "4.0.0",
    "@angular/compiler-cli": "4.0.0",
    "@angular/core": "4.0.0",
    "zone.js": "^0.8.4"
  },
}
```

**Comment by rapropos** [comment]
What impact does ionic-native's `devDependencies` have on end users?
