### ISSUE TITLE
Diagnostic -plugin no exported member 'IonicNativePlugin'

### ISSUE THREAD

**Issue by ewilys** [driftyco/ionic-native#1428]
Hi, 

I'm new to Ionic2 and I've got a problem with the diagnostic cordova plugin. I added the plugin with : import { Diagnostic } from '@ionic-native/diagnostic'; (+ added as a provider of my component and, to the constructor + my package.json is updated to the good version)
, nevertheless I got a TypeScript error with the import saying : 
"Module '"~/testIonic/node_modules/@ionic-native/core/index"' has no exported member 'IonicNativePlugin'."

from this line : import { IonicNativePlugin } from '@ionic-native/core';
of this file :~/testIonic/node_modules/@ionic-native/diagnostic/index.d.ts

My system information:

 ordova CLI: 6.5.0
Ionic Framework Version: 3.1.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.9.0
Xcode version: Not installed

Do you have any idea why I have this problem ?
thank you

**Comment by aneeskodappana** [comment]
same error here.
have you fix this @ewilys 
getting this error on installing camera native plugin and network native plugin too

**Comment by ewilys** [comment]
Yes, I was trying to fix another problem and it appears that my ; '@ionic-native/core' in 'dependencies' in my package.json wasn't at the good version so  I changed it to : "@ionic-native/core": "^3.6.0". 

Then do :
rm -rf node_modules/
npm cache clean
npm install

And it should work now. Hope it will help you

**Comment by aneeskodappana** [comment]
it works, thanks @ewilys
