### ISSUE TITLE
@ionic-native/network plugin not working

### ISSUE THREAD

**Issue by aneeskodappana** [driftyco/ionic-native#1429]
```
Module '"C:/Users/anees/network/node_modules/@ionic-native/core/index"' has no exported member 'IonicNativePlugin'.
```

![capture](https://cloud.githubusercontent.com/assets/25400284/25479939/5a149c90-2b64-11e7-97c1-4db5b3ff722a.PNG)

```
// home.ts
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { Network } from '@ionic-native/network';
@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public navCtrl: NavController, private network: Network) {
  	// watch network for a disconnect
		let disconnectSubscription = this.network.onDisconnect().subscribe(() => {
		  console.log('network was disconnected :-(');
		});
  }

}


```
also add to the providers array in app.module.ts

**Comment by aceoliver** [comment]
Make sure the version of "@ionic-native/core" and "@ionic-native/network" are the same.

See package.json

**Comment by adairborba** [comment]
+1 
The same version:

"@ionic-native/core": "3.5.0",
"@ionic-native/network": "3.5.0",

**Comment by aneeskodappana** [comment]
Ah it works. Thanks @adairborba @aceoliver

**Comment by nicoisz** [comment]
how do you resolved it?

**Comment by aneeskodappana** [comment]
@nicoisz install @ionic-native/core@latest

**Comment by brouviere** [comment]
@nicoisz and @aneeskodappana  i had to uninstall first before it works:
npm uninstall --save @ionic-native/core
then
npm install --save @ionic-native/core@latest

**Comment by PedroDiniz** [comment]
@brouviere 

I did the process of uninstalling and installing --save.

Now I'm getting this error:

C:\nodejs\apps\corretorOK>npm install --save @latest
npm ERR! addLocal Could not install C:\nodejs\apps\corretorOK\@latest
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "@latest"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! path C:\nodejs\apps\corretorOK\@latest
npm ERR! code ENOENT
npm ERR! errno -4058


npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\nodejs\apps\corretorOK\@latest'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\nodejs\apps\corretorOK\@latest'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\nodejs\apps\corretorOK\npm-debug.log

**Comment by ihadeed** [comment]
@PedroDiniz you need to add the package name to the command. Not just npm install --save by itself. 

I believe they were suggesting that you run
npm i --save @ionic-native/network@latest @ionic-native/network@latest
