### ISSUE TITLE
Plugin Request: Native Ringtones

### ISSUE THREAD

**Issue by 8BallBomBom** [driftyco/ionic-native#1430]
Would it be possible to add this plugin to Ionic Native?
https://github.com/TongZhangzt/cordova-plugin-native-ringtones

Pretty useful for people creating communication apps that need the ability to play a ringtone.

**Comment by danielsogl** [comment]
Hey @8BallBomBom,
I will have a look into this plugin

**Comment by 8BallBomBom** [comment]
Thanks @danielsogl
