### ISSUE TITLE
Getting ts error on plugin Shake

### ISSUE THREAD

**Issue by tordnilsen** [driftyco/ionic-native#1431]
Hi!
I'm getting this error when compiling with the native Shake plugin. (https://ionicframework.com/docs/native/shake/)
----------
[14:57:24]  typescript: C:/dev/node_modules/@ionic-native/shake/index.d.ts, line: 1
            Module '"C:/dev/node_modules/@ionic-native/core/index"' has no exported member
            'IonicNativePlugin'.
       L1:  import { IonicNativePlugin } from '@ionic-native/core';
       L2:  import { Observable } from 'rxjs/Observable';
[14:57:24]  ionic-app-script task: "build"
[14:57:24]  Error: Failed to transpile program
Error: Failed to transpile program

Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build
-----

**Comment by rapropos** [comment]
Upgrade @ionic-native/core to at least 3.6.0.

**Comment by tordnilsen** [comment]
Worked.
Thanks.
