### ISSUE TITLE
BUG: Native Flurry not working: plugin is not installed

### ISSUE THREAD

**Issue by sifang** [driftyco/ionic-native#1433]
All Flurry calls fail with message similar to this, on device (ionic run android):
"Native: tried calling FlurryAnalyticsPlugin.init, but the FlurryAnalyticsPlugin plugin is not installed."

All calls are wrapped with Platform.ready().

Here is my environment:
Cordova CLI: 6.5.0
Ionic Framework Version: 3.1.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.3.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v7.8.0
Xcode version: Xcode 8.1 Build version 8B62

And the plug-in is installed.
[ionic plugin list]
...
cordova-plugin-flurry-analytics 1.2.1 "Flurry Analytics"
...

Please help!

**Comment by wajdiii** [comment]
I had the same issue!

**Comment by sifang** [comment]
@wajdiii 
I'd still like to see Ionic Native team fix this, 
because Flurry is the most popular stats tool for Mobile development.
It'd be a shame that Flurry does not work on Ionic.

My *non-ideal* work-around is to use the cordova plugin directly, via Javascripts.
Please let me know if you need a code example.

**Comment by wajdiii** [comment]
Hi @sifang thanks for you answer! Can you send me an exemple please? 
I'm stuck because Google analytics is not working too, the app can't build for android.

**Comment by crawft** [comment]
I also have this issue on the Diagnostic plugin, so it's clearly something more fundamental:

```
Native: tried calling Diagnostic.isRemindersAuthorized, but the Diagnostic plugin is not installed.
Install the Diagnostic plugin: 'ionic plugin add cordova.plugins.diagnostic'
```

**Comment by adairborba** [comment]
+1
And in the plugin BackgroundMode.

**Comment by sifang** [comment]
@wajdiii Here is my sample code, hope it helps

`import(s)...

declare var FlurryAnalytics;

@Injectable()
export class MMDStatsService {
  flurry: any;
  
  constructor(...) {
    // create a new instance
    this.flurry = new FlurryAnalytics({
        // requried
        appKey: <your api key here>,
        // optional
        reportSessionsOnClose: true,
        enableLogging: true
    });
  }
  
  track(eventName:string, eventProperties?:{}) {
    if (this.platform.is('cordova')) {
      // this.flurry.logEvent(eventName, eventProperties);
      this.flurry && this.flurry.logEvent(eventName, eventProperties, function() {
          // console.log('Flurry logged event');
      }, function(err) {
          console.error(['Flurry failed: ', err]);
      });
    }
  }`

**Comment by wajdiii** [comment]
Thanks @sifang I did the same work-around with window.plugins.FlurryAnalytics...
Hope they will fix that quickly because this work-around cause a performance issue.

**Comment by ihadeed** [comment]
The wrapper was written incorrectly. It is now fixed in 3.7.0.

Please update to latest `@ionic-native/flurry-analytics` and follow the documentation here (until the official docs are updated): http://ionic-site-staging.herokuapp.com/docs/native/flurry-analytics/

**Comment by sifang** [comment]
Thank you @ihadeed

**Comment by kashyapbhansali** [comment]
I am still facing this problem. Any idea how to fix it?
