### ISSUE TITLE
Has no exported Member 'IonicNativePlugin'

### ISSUE THREAD

**Issue by iknox27** [driftyco/ionic-native#1434]
Module "node_modules/@ionic-native/diagnostic/index.d.ts, line: 1
Module '"node_modules/@ionic-native/core/index"' has no exported member IonicNativePlugin'.
L1:  import { IonicNativePlugin } from '@ionic-native/core';

**Comment by ihadeed** [comment]
Please update @ionic-native/core to at least 3.6.0

**Comment by mastarenee** [comment]
Running the below did the job for me after I updated I got the same error so turns that I needed to completely remove it first.

npm uninstall --save @ionic-native/core
npm install --save @ionic-native/core@latest

**Comment by AugustoAleGon** [comment]
Thanks for this solution. I had the same issue.

**Comment by ajeans** [comment]
Same here, upgrading to 3.6.1 fixed the issue.

**Comment by jalbertos** [comment]
same! thanks!

**Comment by blackpr** [comment]
@mastarenee  thanks!

**Comment by chandanch** [comment]
@ihadeed please update the package.json as well. In the [ChangeLog](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md) its still showing 3.4.2

**Comment by ihadeed** [comment]
Will do! Sorry about that

**Comment by mahmoudtokura** [comment]
@mastarenee Worked like a charm, thanks

**Comment by sleever** [comment]
Thanks a lot!

**Comment by klaus82** [comment]
Thanks a lot! Work fo me too!

**Comment by jeff235255** [comment]
thanks mate, it worked for me

**Comment by Rameswar143** [comment]
npm install npm@latest -g

**Comment by divyanshuchat** [comment]
This should help too - npm install –-save @ionic-native/core@latest

**Comment by happycrappie** [comment]
Tried running npm install --save @latest, it won't work.

npm-debug:
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   '@latest' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData @latest
8 silly fetchOtherPackageData @latest
9 silly cache add args [ '@latest', null ]
10 verbose cache add spec @latest
11 silly cache add parsed spec Result {
11 silly cache add   raw: '@latest',
11 silly cache add   scope: null,
11 silly cache add   escapedName: null,
11 silly cache add   name: null,
11 silly cache add   rawSpec: '@latest',
11 silly cache add   spec: 'C:\\Users\\happycrappie\\Projects\\myApp\\@latest',
11 silly cache add   type: 'local' }
12 error addLocal Could not install C:\Users\happycrappie\Projects\myApp\@latest
13 silly fetchPackageMetaData Error: ENOENT: no such file or directory, open 'C:\Users\happycrappie\Projects\myApp\@latest'
13 silly fetchPackageMetaData     at Error (native)
13 silly fetchPackageMetaData  error for @latest { Error: ENOENT: no such file or directory, open 'C:\Users\happycrappie\Projects\myApp\@latest'
13 silly fetchPackageMetaData     at Error (native)
13 silly fetchPackageMetaData   errno: -4058,
13 silly fetchPackageMetaData   code: 'ENOENT',
13 silly fetchPackageMetaData   syscall: 'open',
13 silly fetchPackageMetaData   path: 'C:\\Users\\happycrappie\\Projects\\myApp\\@latest' }
14 silly rollbackFailedOptional Starting
15 silly rollbackFailedOptional Finishing
16 silly runTopLevelLifecycles Finishing
17 silly install printInstalled
18 verbose stack Error: ENOENT: no such file or directory, open 'C:\Users\happycrappie\Projects\myApp\@latest'
18 verbose stack     at Error (native)
19 verbose cwd C:\Users\happycrappie\Projects\myApp
20 error Windows_NT 10.0.16193
21 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "@latest"
22 error node v6.10.2
23 error npm  v3.10.10
24 error path C:\Users\happycrappie\Projects\myApp\@latest
25 error code ENOENT
26 error errno -4058
27 error syscall open
28 error enoent ENOENT: no such file or directory, open 'C:\Users\happycrappie\Projects\myApp\@latest'
29 error enoent ENOENT: no such file or directory, open 'C:\Users\happycrappie\Projects\myApp\@latest'
29 error enoent This is most likely not a problem with npm itself
29 error enoent and is related to npm not being able to find a file.
30 verbose exit [ -4058, true ]
`

**Comment by philipgriffin** [comment]
Executing these two commands worked for me:
```

npm uninstall --save @ionic-native/core
npm install --save @ionic-native/core@latest
```

**Comment by ihadeed** [comment]
It's `npm i --save @ionic-native/core@latest` .. not just ` npm i --save @latest`
