### ISSUE TITLE
[DOCS IMPROVE] Ionic native Google Maps

### ISSUE THREAD

**Issue by trbsi** [driftyco/ionic-native#1444]
As stated here I had a problem with Google Maps. I was using code from this page https://forum.ionicframework.com/t/google-maps-marker-not-showing/88383 but I couldn't get it to work.

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.1.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.6
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v4.4.3
```

Here is my whole code for the latest ionic and Google Maps plugin, it's working perfectly.

.ts file:
```
import { Component,  AfterViewInit } from '@angular/core';
import { NavController } from 'ionic-angular';

import {
 GoogleMaps,
 GoogleMap,
 GoogleMapsEvent,
 LatLng,
 CameraPosition,
 MarkerOptions,
 Marker
} from '@ionic-native/google-maps';

import { GoogleMapsLatLng } from 'ionic-native';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage implements AfterViewInit  {

	map: GoogleMap;

	constructor(public navCtrl: NavController) 
	{
		
	}

	// Load map only after view is initialized
	ngAfterViewInit() {
		this.loadMap();
	}

	loadMap() 
	{
		 // make sure to create following structure in your view.html file
		 // and add a height (for example 100%) to it, else the map won't be visible
		 // <ion-content>
		 //  <div #map id="map" style="height:100%;"></div>
		 // </ion-content>
	  	let location = new GoogleMapsLatLng(-34.9290,138.6010);
 
        this.map = new GoogleMap('map', {
          'backgroundColor': 'white',
          'controls': {
            'compass': true,
            'myLocationButton': true,
            'indoorPicker': true,
            'zoom': false
          },
          'gestures': {
            'scroll': true,
            'tilt': true,
            'rotate': true,
            'zoom': true
          },
          'camera': {
            'latLng': location,
            'tilt': 0,
            'zoom': 15,
            'bearing': 50
          }
        });

		this.map.on(GoogleMapsEvent.MAP_READY).subscribe(() =>
		{
			console.log('Map is ready!');
			this.map.addMarker({
				'position': location,
				'visible': true,
				'title': "nesto",
				'markerClick': function(marker) {
					marker.showInfoWindow();
				}
			});

		});
	 }

}
```

For any questions I'll be watching this topic.

**Comment by MTechDE** [comment]
Hey, 
thank you for opening an Issue here. I will look into this.

**Comment by MTechDE** [comment]
Hey, 
thank you for opening this Issue. Can you tell me, if you only had problems with the marker or with the whole documentation of this plugin?

**Comment by trbsi** [comment]
I had a problem with a whole documentation so I had to use my solution to make it work. Also very important inside `this.map.on(GoogleMapsEvent.MAP_READY).subscribe((){})` you should add stuff like new marker or positioning maps camera to a specific coordinates, so basically after map is loaded

**Comment by MTechDE** [comment]
Okay fine.
Is this part required for the plugin to work?

`this.map = new GoogleMap('map', { ... });`

If i find some time today, I will rework the plugin doc.

**Comment by trbsi** [comment]
That's right

**Comment by obermoserkitz** [comment]
Absolutely nothing is working if i use the doc for google-maps.
in iOS it shows only a black blank div
and even with the "const marker:" stuff in the end it gives me an error.
please fix the docs, this plugin is unuseable.

**Comment by ihadeed** [comment]
@obermoserkitz https://github.com/driftyco/ionic/issues/7205#issuecomment-230977122
