### ISSUE TITLE
bug: ionic start is not downloading the latest

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#1459]
_From @abusharaf on May 3, 2017 17:10_

**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>if you start a new ionic application for example the below:-

ionic start sqlite-project blank

it will create a project but when you run this:-

npm install --save @ionic-native/sqlite as per the docs, it will not install correctly as the ionic-native version is not the latest one (3.6.1), it's actually 3.4.2</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#11498_

**Comment by jgw96** [comment]
_From @MTechDE on May 3, 2017 17:50_

Maybe that is a problem with your npm cache.

If you run `npm install --save @ionic-native/sqlite@latest` you should get the latest release

**Comment by danielsogl** [comment]
@abusharaf can you close it? I updated the app-base repo to match the latest ionic-native release 3.6.1

**Comment by abusharaf** [comment]
Yah, I've checked it today and it was getting the latest updates, many thanks this will save a lot of confusion for the beginners :)

**Comment by danielsogl** [comment]
@jgw96 can you close this issue?
