### ISSUE TITLE
bug: typescript File override

### ISSUE THREAD

**Issue by akz92** [driftyco/ionic-native#1460]
The File class definition makes it impossible to cast a file as a blob.

Using Typescript's File definition makes the following work:
```
declare const file: File;

const blob = file as Blob;
```

When using IonicNative's File definition it stops working.

**Comment by ejiyuan** [comment]
+1

**Comment by ihadeed** [comment]
@akz92 can you provide sample code demonstrating what you're trying to do?

**Comment by ihadeed** [comment]
Nevermind, I figured out what you're looking for. I will create an interface named `IFile` that follows the Web API spec and extends `Blob`.

**Comment by airstep** [comment]
So, how to use and separate File from typescript and File constructor from plugin. Bcz now code going throght File contructor from plugin bu I need to go throught typescript dom type....
