### ISSUE TITLE
Missing functions on camera-preview

### ISSUE THREAD

**Issue by mikewagz** [driftyco/ionic-native#1462]
Hi, there are some functions listed in the [documentation](https://ionicframework.com/docs/native/camera-preview/) that aren't implemented in the actual ionic-native plugin yet:

getFocusMode()
setFocusMode(focusMode)
getSupportedFocusModes()
getFlashMode()

Is it possible to get these in there?  This plugin has great potential once fully-featured.

Also, it would be great if you could add the [tapToFocus()](https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview#taptofocusxpoint-ypoint-successcallback-errorcallback) function as well.

Thanks!

**Comment by danielsogl** [comment]
Hey @mikewagz,

I will take a look into this.

**Comment by danielsogl** [comment]
@mikewagz,
the functions are now added. Wait for the next release.

**Comment by mikewagz** [comment]
@danielsogl Thank you for the speedy response!
