### ISSUE TITLE
How to check a media id is loaded or not?

### ISSUE THREAD

**Issue by samever7** [driftyco/ionic-native#1464]
As title, when I using native-audio plugin, I need to test whether one of my media id is already loaded.

I checked our docs but no api can do this kind of job.

Is there any chance that we add this kind of api?

Or could anyone pls that let me know the right usage of this plugin to avoid duplicated loading for medias?

Thank you all~

**Comment by rapropos** [comment]
This seems like a better fit for [the support forums](https://forum.ionicframework.com/).

**Comment by samever7** [comment]
ok then~

I'll close this one.
