### ISSUE TITLE
@ionic-native/touch-id - method didFingerprintDatabaseChange is missing

### ISSUE THREAD

**Issue by SquadraCorse** [driftyco/ionic-native#1466]
Since some time 'cordova-plugin-touch-id' supports the check to see if fingerprint database has changed. They exposed the method `didFingerprintDatabaseChange` for it. 

But the native ionic plugin doesn't expose this. Now i can't check it, doing the Ionic way. Can you please add this?

**Comment by danielsogl** [comment]
I will have a look into this.
