### ISSUE TITLE
Add tslint

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-native#148]
Please add tslint using the following config: https://github.com/driftyco/ionic/blob/2.0/tslint.json

**Comment by ihadeed** [comment]
@adamdbradley is there a way to automatically fix everything? like `fixmyjs` for JavaScript.

**Comment by adamdbradley** [comment]
Whoa that was fast, thanks! Yeah I'm not sure if there is an autofix way of doing the updates. Thanks for cleaning it all up!!

**Comment by ihadeed** [comment]
@adambradley
Turned out tslint integrates with editors. So it was easier to spot the
errors.
