### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by SebastianSchirmer** [driftyco/ionic-native#1489]
The plugin cordova-plugin-safariviewcontroller (https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller) offers the options "barColor" and "controlTintColor" to be passed in to the show method.

However, ionic-native/safari-view-controller, respectively the "SafariViewControllerOptions" interface does not specify these 2 options but option "toolbarColor" which the plugin doesn't offer.

My question is if and how the different options are connected.
1) Am I right with my assumption that the ionic-native "toolbarColor" option value is passed to the plugin as its "barColor" option value?
2) Is the plugin option "controlTintColor" just not supported by ionic-native? Or will a value for this option passed to the plugin but derived from any other option set for ionic-native?

Thanks very much for any clarification on this,
Sebastian

**Comment by danielsogl** [comment]
Hey @SebastianSchirmer,

I will take a look into this.

**Comment by danielsogl** [comment]
I added the missing options.

Thank you for creating that issue

**Comment by SebastianSchirmer** [comment]
Thanks very much for adding the options. I checked the plugin source as well and found out that "toolbarColor" is used for Android only whereas "barColor", "tintColor" and "controlTintColor" are used for iOS only.
