### ISSUE TITLE
Typescript Error Cannot find name 'Observable' in @ionic-native/geolocation 

### ISSUE THREAD

**Issue by elnemr84** [driftyco/ionic-native#1492]
Hi,
I'm using Ionic 2 and trying to use @ionic-native/geolocation, when I do ionic:serv  on my project I got this Error:
Cannot find name 'Observable'.

![image](https://cloud.githubusercontent.com/assets/13181429/25774711/3d2163e2-3295-11e7-8282-e9a0086cc268.png)

I'm using the below packages:

"dependencies": {
    "@angular/common": "4.0.2",
    "@angular/compiler": "4.0.2",
    "@angular/compiler-cli": "4.0.2",
    "@angular/core": "4.0.2",
    "@angular/forms": "4.0.2",
    "@angular/http": "4.0.2",
    "@angular/platform-browser": "4.0.2",
    "@angular/platform-browser-dynamic": "4.0.2",
    "@ionic-native/core": "3.6.1",
    "@ionic-native/splash-screen": "3.4.2",
    "@ionic-native/status-bar": "3.4.2",
    "@ionic/storage": "2.0.1",
    "ionic-angular": "3.1.1",
    "ionicons": "3.0.0",
    "rxjs": "^5.3.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "^0.8.5"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.4",
    "typescript": "~2.2.1"
  },

Thank you in advance.

**Comment by danielsogl** [comment]
You should upgrade your native code package to 3.6.1
And I can't see the geolocation package.are you sure you installed it correctly?

**Comment by elnemr84** [comment]
Hi @danielsogl , 
it's already upgraded to 3.6.1 as shown in my dependencies.
And yes geolocation plugin is installed correctly.

**Comment by danielsogl** [comment]
Sorry I meand the other native plugins but I can't see your geolocation plugin in your package.json

**Comment by elnemr84** [comment]
Hi @danielsogl ,

This is my package.json file content:
```
{
  "author": "",
  "cordovaPlatforms": [],
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-console",
    "cordova-plugin-statusbar",
    "cordova-plugin-device",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard",
    "cordova-plugin-geolocation"
  ],
  "dependencies": {
    "@angular/common": "4.0.2",
    "@angular/compiler": "4.0.2",
    "@angular/compiler-cli": "4.0.2",
    "@angular/core": "4.0.2",
    "@angular/forms": "4.0.2",
    "@angular/http": "4.0.2",
    "@angular/platform-browser": "4.0.2",
    "@angular/platform-browser-dynamic": "4.0.2",
    "@ionic-native/core": "3.6.1",
    "@ionic-native/splash-screen": "3.4.2",
    "@ionic-native/status-bar": "3.4.2",
    "@ionic/storage": "2.0.1",
    "ionic-angular": "^3.1.1",
    "ionicons": "3.0.0",
    "rxjs": "^5.3.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "^0.8.5"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.4",
    "typescript": "~2.2.1"
  },
  "homepage": "",
  "name": "Wakeb",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve",
    "watch": "ionic-app-scripts watch"
  },
  "-vs-binding": {
    "ProjectOpened": [
      "ionic:build",
      "ionic:serve"
    ]
  }
}

```

**Comment by elnemr84** [comment]
I didn't add @ionic-native/geolocation into my dependencies, it's working now after adding it, Thank you.
