### ISSUE TITLE
Please add support for cordova-plugin-appminimize

### ISSUE THREAD

**Issue by naveedahmed1** [driftyco/ionic-native#1500]
Hi,

Please add support for support for https://github.com/tomloprod/cordova-plugin-appminimize as it seems to be a useful plugin.

**Comment by danielsogl** [comment]
Hey @naveedahmed1,
I will implement this plugin later this week.

**Comment by danielsogl** [comment]
@naveedahmed1 will be added in the next release: https://github.com/driftyco/ionic-native/pull/1501
