### ISSUE TITLE
FileReader undefined

### ISSUE THREAD

**Issue by jseter** [driftyco/ionic-native#1513]
What is the correct way to use FileReader in the current ionic native?  If i use the following syntax then FileReader is undefined (possibly because the plugin has not been loaded yet at the moment the import was called).
import { FileReader } from '@ionic-native/file';

It works if I bypass the import and manually declare it; using it after the device ready event.

**Comment by ihadeed** [comment]
Please refrain from importing `FileReader` into your project and just call it directly. The class `FileReader` that we have is just a declaration and it's not supposed to be defined in runtime.
