### ISSUE TITLE
Web Intent listed in Ionic Native no longer available

### ISSUE THREAD

**Issue by bergben** [driftyco/ionic-native#1517]
The Web Intent listed in the [Ionic Native docs](https://ionicframework.com/docs/native/web-intent/) does no longer exist.

There are some forks of it, but none of them are maintained anymore. 

The only related repository that is relatively fresh is 
https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent

Also related may be links on my SO question: http://stackoverflow.com/questions/43712312/make-ionic-app-appear-in-share-list-and-receive-data?noredirect=1#comment74777543_43712312

**Comment by danielsogl** [comment]
@bergben I will take a look at the plugin.

**Comment by danielsogl** [comment]
@bergben I added the changes and the new source. Wait for the next release

**Comment by bergben** [comment]
Awesome @danielsogl, thanks!
