### ISSUE TITLE
AppMinimize plugin doesnt seem to work as expected

### ISSUE THREAD

**Issue by naveedahmed1** [driftyco/ionic-native#1528]
I have below code in my component but it doesn't seem to work

```
this.backButton = this.platform.registerBackButtonAction(() => {
            this.appMinimize.minimize().then(
                success => console.log('Closed'),
                err => console.log('Something went wrong')
            );
        });
```

It doesn't minimize app when back button is pressed.

**Comment by danielsogl** [comment]
Hey @naveedahmed1, I will check that problem later. Maybe I did something wrong.

**Comment by ihadeed** [comment]
Just fixed it in https://github.com/driftyco/ionic-native/commit/10d61c21c29252495b9a72a118795af400771a0b .. should be fixed in next patch release.
