### ISSUE TITLE
Bluetooth Serial plugin device disconnect is not firing error callback

### ISSUE THREAD

**Issue by WHarris22** [driftyco/ionic-native#154]
I have some code which connects to a Bluetooth device which works as expected but when the device disconnects the error callback does not get called. 

Here is the code I am using...

```
BluetoothSerial.connect(device.id).then((response) => {
                            console.log('bluetooth serial success callback: ' + response);
                            //this._successCallback(response);
                        }, (err) => {
                            console.log('bluetooth serial error callback: ' + err);
                            //this._errorCallback(err);
                        });
```

I'd like to add that the error callback does get called when there is an error attempting to connect to a device, it just doesn't seem to get called when a connection disconnects.

Is there any reason for this?

**Comment by ihadeed** [comment]
Thanks @WHarris22 for opening this issue.

We will probably have to change the return type of the `connect` function to be an Observable instead of a Promise. That should solve the issue. Will fix in next release.
