### ISSUE TITLE
Native Media plugin does not work on Android or iOS - fails without error

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#1542]
_From @brettdorrans on May 12, 2017 10:39_

**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Playing audio from local filesystem using cordova-plugin-media 3.0.1 doesn't work on Android/iOS, with no error messages logged.

**Expected behavior:**

Audio should play.

**Steps to reproduce:**

Create blank Ionic 2 app (have not tested with Ionic 3), install cordova-plugin-media. Add an mp3 file to the assets folder, then attempt to load from the filesystem. Audio will play in the browser, but not when deployed to a device.

iOS and Android will call the onSuccess callback, but no audio will play.

**Related code:**
My code to play as follows:
```
private playSound(file: string, mediaObject: MediaObject) {
    const onStatusUpdate = (status) => console.log(status);
    const onSuccess = () => console.log('Media init successful.');
    const onError = (error) => console.log(error.message);

    mediaObject = this.media.create('./assets/sounds/' + file, onStatusUpdate, onSuccess, onError);
    let duration = mediaObject.getDuration();

    mediaObject.play();
    // Clear resources after finished playing
    setTimeout(() => {
      mediaObject.release();
    }, duration * 2);
  }
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.4
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

_Copied from original issue: driftyco/ionic#11630_

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. Are you using `ionic-native` ?

**Comment by jgw96** [comment]
_From @brettdorrans on May 12, 2017 14:42_

Hi, thanks for responding.

I am using ionic-native/media@3.7.0 following the docs provided here: https://ionicframework.com/docs/native/media/

I managed to get audio playing using Native Audio - I suspect the Media plugin isn't playing nice with paths on device targets?

I think this might be better reported in the ionic-native repo - but I'm not sure!

Cheers
Brett

**Comment by jgw96** [comment]
Thanks for the info! Yeah, since this is an ionic-native issue I am going to move this issue over to that repo. Thanks for using Ionic!

**Comment by ghenry22** [comment]
Hi please try and update to the latest ionic-native and follow the example in the docs.  There were a couple of versions that introduced some issues with media but the v3.8.0 is working fine and the docs are up to date for how to use media now as well.  I can confirm it works fine on both Android and iOS.

**Comment by viniciostorres** [comment]
After three entire days of suffering, I have discovered the necessity of 'file://android_asset/www/' before the pathname of sound file. None of relative paths presented in examples of documentation works on android in my experience.

**Comment by RalfViellieber** [comment]
To see the real used path on your device, you may do something like
	this.nativeAudio.preloadComplex(key, asset, 1, 1, 0)	
	.then((onSuccess) => {
	        // alert("preload ok");
	      }, (onError) => {
	        alert("Error in preload:" +onError + " " + key + " " +asset);
	      });

**Comment by MrDrProfX** [comment]
For me, the solution was to delay preloading the sounds using setTimeout.
