### ISSUE TITLE
Radio buttons not being checked when using mfp plugin login functionality.

### ISSUE THREAD

**Issue by sruthakeerthikotla** [driftyco/ionic-native#1547]
When the MobileFirst Platforms plugin cordova-plugin-mfp 's WLAuthorizationManager.login() function is used, the radio buttons are not getting checked. The stack trace between a working app and an app that does not work show that a call to the "onInvokeTask" in the main.js is not being made from the polyfills.js. (The sample app can be found in the issue mentioned here : http://stackoverflow.com/questions/43726154/unable-to-toggle-between-radio-button-after-authenticating-user-using-mfp-8-0 ). Have attached the 2 logs with and without login. Also when debug points are added to slow down the running of the main.js at various points, the checkboxes are getting checked properly. 
<img width="240" alt="withlogin logs" src="https://cloud.githubusercontent.com/assets/21327252/26027960/053d7ee8-3835-11e7-8c70-18b0f7da4854.png">
<img width="246" alt="withoutlogin logs" src="https://cloud.githubusercontent.com/assets/21327252/26027964/0be71506-3835-11e7-8a80-4a2129df491a.png">

**Comment by ihadeed** [comment]
This is not a plugin that we support at Ionic Native. I suggest seeking help at the plugin's repo.

**Comment by sruthakeerthikotla** [comment]
I have added a time delay of millisecond to the below function that ionic creates in the main.js and the checkboxes selections are rendered properly.

```
function test2()
{
    setTimeout(function(){ 
    }, 1);  

}
/**
 * @param {?} view
 * @return {?}
 */
function checkAndUpdateView(view) {
    try{
    if( view.component.navCtrl._ids == 1 && view.component.navCtrl.id == "n4"
    )
    {
        test2();
    }
        
    }catch(e)
    {
    }
Services.updateDirectives(view, 0 /* CheckAndUpdate */);
    .......
```

Doesn't this mean that there is a threads synchronization in ionic view rendering? 
If this is not an ionic issue, does that mean that ionic is incompatible with other 3rd part plugins?
