### ISSUE TITLE
File Plugin toInternalURL is missing

### ISSUE THREAD

**Issue by troyanskiy** [driftyco/ionic-native#1560]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Entry interface does not have `toInternalURL` method
`Property 'toInternalURL' does not exist on type 'Entry'. `

`toInternalURL` should be on Entry inerface
**Expected behavior:**

To resolve path with in internal url Ex: `cdvfile://localhost/library-nosync/`

**Comment by xiaomiwujiecao** [comment]
check out this url, [File System](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/index.html) ,on the bottpm part, there are some instructions
