### ISSUE TITLE
Google Maps scroll  issue

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#1563]
_From @joesleiman on May 15, 2017 14:13_

**Ionic version: 3.2.0** 

**I'm submitting a  bug report**  

**Current behavior:**

**Expected behavior:**

it should the  mao still fix at his position
**Steps to reproduce:**
`<div #map id="map"></div>`
+ same" loadmap()" function as in the documentation.
i'm using it inside <ion-slide>

**Other information:**

- when i scroll the app where the map exist. the map scroll too , and there is a delay when it scrolled.
 

- **another issue** : if i have a select tag like (**ion-select**) above the map directly , then i click on the drop down to open a modal that have options, the modal open in the center of the page above the map , i can't choose any of the options . when i click on the option it look like i click on the map, it doing zoom .
same if i scroll and stop scrolling when the map appear under the header of the page , the back button can't clicked.

- **another issue**: i used it inside <ion-slide> because i'm using wizard form so when i click on next button to go to next slide, a part of the map appear on the second slide. i can decrease the width but it have to not appear. because on first slide appear 100% without touching the border-right of the app .

_Copied from original issue: driftyco/ionic#11676_

**Comment by ihadeed** [comment]
This isn't an issue with the Ionic Native wrapper. You should post this at the Ionic forums or the plugin's repo.

**Comment by joesleiman** [comment]
can you guide me or give the url where should i post it ?

**Comment by ihadeed** [comment]
The repo url is posted our official docs page https://ionicframework.com/docs/native/google-maps/

**Comment by joesleiman** [comment]
no i mean where i can submit this issue. i already used the same plugin native by ionic

**Comment by ihadeed** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues ...

**Comment by joesleiman** [comment]
ok, thank you :)
