### ISSUE TITLE
DeviceOrientation not work on some device

### ISSUE THREAD

**Issue by petrot** [driftyco/ionic-native#1569]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
My users recognized, that the Device Orientation plugin not works on some device (e.g. Samsung Galaxy J5 (2016), and some Huawei models).

Is there any known bug about it?

**Other information:**
I found this issue: [cordova-plugin-device-orientation](https://github.com/apache/cordova-plugin-device-orientation/pull/34)

**Comment by danielsogl** [comment]
Hey @petrot,
because ionic-native just wraps the Cordova plugins, we can't resolve this issue by our side.

**Comment by petrot** [comment]
ok, thanks!
