### ISSUE TITLE
Please add support for getActiveSession in cordova-plugin-linkedin

### ISSUE THREAD

**Issue by naveedahmed1** [driftyco/ionic-native#1570]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
The cordova-plugin-linkedin has a method getActiveSession to get the Active Session through which we can retrieve access token.

But it seems that '@ionic-native/linkedin doesnt have its support yet.

Can you please review and update?

Ref: https://www.npmjs.com/package/cordova-plugin-linkedin

**Comment by ihadeed** [comment]
Sure @naveedahmed1 

For now you can do the following:
```
LinkedIn.getPlugin().getActiveSession(onSuccess, onError);
```
