### ISSUE TITLE
Datepicker minuteInterval not working

### ISSUE THREAD

**Issue by aidan2129** [driftyco/ionic-native#1576]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

Minute intervals are not appearing on native android clock.
Try to set the minute interval on @ionic-native/date-picker

**Expected behavior:**

Instead of the minutes showing as 1 2 3 4 5 it should be 5 10 15 20 25
**Steps to reproduce:**
set the minuteInterval on datepicker options in my case i had it set to 5.

**Related code:**

```
this.datePicker.show({
                date: this.today,
                mode: 'time',
                is24Hour: true,
                minDate: this.today,
                androidTheme: this.datePicker.ANDROID_THEMES.THEME_HOLO_DARK,
                minuteInterval: 5,
})

```

**Other information:**

**package.json info:**

**Comment by ihadeed** [comment]
I think this would be an issue with the plugin and not Ionic Native. I suggest you review their documentation and issues at their repo https://github.com/VitaliiBlagodir/cordova-plugin-datepicker

**Comment by aidan2129** [comment]
@ihadeed Just found out this feature only works on ios i think this should be noted in the docs here also http://ionicframework.com/docs/native/date-picker/

**Comment by danielsogl** [comment]
@aidan2129 from the plugin page: 

> DatePicker Plugin for Cordova/PhoneGap 4.0 (iOS and Android and Windows)

**Comment by aidan2129** [comment]
@danielsogl the minuteInterval feature is not supported on android that is what my problem is :) 

> minuteInterval - iOS
> 
> Interval between options in the minute section of the date picker.
> 
> Type: Integer
> 
> Default: 1

**Comment by danielsogl** [comment]
Ah okay, now I understand the problem.
We should add this to the docs.
