### ISSUE TITLE
Camera will not launch, defaults to Gallery

### ISSUE THREAD

**Issue by georgechapman** [driftyco/ionic-native#1578]
**I'm submitting a ...**
[x ] bug report
[ ] feature request

**Current behavior:**
When i launch the camera even though i am using `sourceType : this.camera.PictureSourceType.CAMERA,` it launches the Camera folder from the Gallery view

**Expected behavior:**
The Camera should launch

**Steps to reproduce:**

**Related code:**

```
  public takePicture() {
    this.camera.getPicture({
      destinationType : this.camera.DestinationType.DATA_URL,
      sourceType : this.camera.PictureSourceType.CAMERA,
      encodingType: this.camera.EncodingType.JPEG,
      quality : 75,
      targetWidth: 1000,
      targetHeight: 1000,
      allowEdit : false,
      saveToPhotoAlbum: false
    }).then(imageData => {
      this.base64Image = "data:image/jpeg;base64," + imageData;
    }, error => {
      console.log("ERROR -> " + JSON.stringify(error));
    });
  }
```

**Other information:**
I Just upgraded to the CLI 3.1.2

**package.json info:**

```json
        "@angular/common": "4.1.0",
        "@angular/compiler": "4.1.0",
        "@angular/compiler-cli": "4.1.0",
        "@angular/core": "4.1.0",
        "@angular/forms": "4.1.0",
        "@angular/http": "4.1.0",
        "@angular/platform-browser": "^4.1.0",
        "@angular/platform-browser-dynamic": "4.1.0",
        "@ionic-native/barcode-scanner": "^3.8.0",
        "@ionic-native/camera": "^3.9.2",
        "@ionic-native/contacts": "^3.8.0",
        "@ionic-native/core": "3.7.0",
        "@ionic-native/splash-screen": "3.7.0",
        "@ionic-native/status-bar": "3.7.0",
        "@ionic-native/vibration": "^3.8.0",
        "@ionic/storage": "2.0.1",
        "angularfire2": "^2.0.0-beta.8",
        "cordova-android": "^6.2.3",
        "cordova-browser": "^4.1.0",
        "cordova-plugin-camera": "^2.4.1",
        "ionic-angular": "3.2.1",
```

**Comment by ihadeed** [comment]
Just tested on Android 6.x, using latest versions of: Ionic Framework, Ionic CLI, Ionic Native and Camera plugin. I wasn't able to reproduce this issue. 

I doubt that this is an Ionic Native issue. Try this out and let me know if you get the same result, replace your code with this:
```ts
Camera.getPlugin().getPicture({
      destinationType : this.camera.DestinationType.DATA_URL,
      sourceType : this.camera.PictureSourceType.CAMERA,
      encodingType: this.camera.EncodingType.JPEG,
      quality : 75,
      targetWidth: 1000,
      targetHeight: 1000,
      allowEdit : false,
      saveToPhotoAlbum: false
    }, imageData => {
      this.base64Image = "data:image/jpeg;base64," + imageData;
    }, error => {
      console.log("ERROR -> " + JSON.stringify(error));
    });
```

**Comment by georgechapman** [comment]
Thanks @ihadeed

Unfortunately I'm getting exactly the same behaviour; opens the gallary bypassing the camera.

Interesting side note is that the gallery opens in the "Recent" folder and then flicks to the "Camera" folder.

I'm testing this on a One+Two running  Android 6.0.1 so liet me test it this morning on another device and see what happens...

**Comment by ihadeed** [comment]
@georgechapman ok then this is not an Ionic Native issue.

Try updating both your plugin and your android platform.
```
cordova plugin rm cordova-plugin-camera
cordova platform rm android
cordova platform add android@latest
cordova plugin add cordova-plugin-camera@latest
```

If you're still experiencing issues then I suggest that you report this to Apache at their issue tracker. (you can find the link in the plugin's repo).

**Comment by Ross-Rawlins** [comment]
I am running the latest android and also getting this issue. Did you figure out how to resolve it?
