### ISSUE TITLE
requestAuthorization in Health-Kit wrong Parameter Description

### ISSUE THREAD

**Issue by Hanfrey** [driftyco/ionic-native#1586]
**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request

**Current behavior:**
The HealthKit Native Wrapper wants an HealthKitOptions for requestAuthorization.

**Expected behavior:**
Should be an Object with Array of supported types like 
```
{
          readTypes: ['HKQuantityTypeIdentifierDietaryFatTotal'],
          writeTypes: ['HKQuantityTypeIdentifierDietaryFatTotal']
        }
```
**Steps to reproduce:**

**Related code:**

```
 /**
 * Ask some or all permissions up front
 * @param options {HealthKitOptions}
 * @returns {Promise<any>}
 */
  @Cordova()
  requestAuthorization(options: HealthKitOptions): Promise<any> { return; }

  /**
 * Formatted as yyyy-MM-dd
 * @returns {Promise<any>}
 */
```

**Other information:**

**package.json info:**

```json
insert the content here
```

@danielsogl

**Comment by ihadeed** [comment]
@Hanfrey are you using the latest version of `@ionic-native/health-kit` ?

**Comment by Hanfrey** [comment]
@ihadeed installed today, so i think yes, but anyway the wrong Code is in this master. 

https://github.com/driftyco/ionic-native/blob/master/src/%40ionic-native/plugins/health-kit/index.ts

**Comment by ihadeed** [comment]
How is the code wrong?

The method takes an object as parameter. If you look at the object's interface you can see that it accepts [`readTypes`](https://github.com/driftyco/ionic-native/blob/master/src/%40ionic-native/plugins/health-kit/index.ts#L79) and [`writeTypes` ](https://github.com/driftyco/ionic-native/blob/master/src/%40ionic-native/plugins/health-kit/index.ts#L114) which are set to `any`.. meaning you can provide anything including an array.

**Comment by Hanfrey** [comment]
You are right, VS Code blamed about the object till I casted it to any, and I didn't except that having everything in one object is now a thing. Sorry and thanks for opening my eyes.
