### ISSUE TITLE
LinkedIn plugin Broken Promises

### ISSUE THREAD

**Issue by ihadeed** [driftyco/ionic-native#1587]
_From @popovicidinu on May 19, 2017 13:11_

Hi. 

I have an issue with this plugin on a project I'm working. No matter what call I make via the plugin, the promise always looks like this: {"__zone_symbol__state":null,"__zone_symbol__value":[]}

global packages:

    @ionic/cli-utils : 1.1.2
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.1.2
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.2.1

System:
    Node       : v6.10.2
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 

_Copied from original issue: zyra/cordova-plugin-linkedin#14_

**Comment by ihadeed** [comment]
Are you calling `.then()` on the promise?

**Comment by ihadeed** [comment]
_From @popovicidinu on May 19, 2017 13:33_

I'm doing something like this:

`this.linkedIn.login(['r_basicprofile', 'r_emailaddress'], false)
      .then( (success) => {
         // trying to console log here
      })
      .catch( (error) => {
        console.log(error);
    });
`

The problem is that nothing is outputting, no errors, nothing. When my function is being called, I do see the LinkedIn loading splashscreen for a bit, but after that it disappears.

**Comment by ihadeed** [comment]
@popovicidinu Are you testing this in the browser or on a device?

**Comment by popovicidinu** [comment]
On an android device, Pixel XL. I know this plugin doesn't work on browser.

**Comment by ihadeed** [comment]
@popovicidinu do you have the LinkedIn app installed? I see you're passing `false` as the second parameter, which means that if the app isn't installed it will not prompt the user to install it.

**Comment by popovicidinu** [comment]
@ihadeed Yes, I have the LinkedIn app installed. I tried with true also, same result.

**Comment by ihadeed** [comment]
@popovicidinu just tested the plugin on Android 6.x and it works fine. Did you add your package ID and key hash to the LinkedIn Developer dashboard?

**Comment by popovicidinu** [comment]
@ihadeed Yes, I added the package name and the key hash in the LinkedIn Developer dashboard. 

I'm running Android 7.1.2 on my phone. I'll try to emulate and see what's happening.

**Comment by ihadeed** [comment]
@popovicidinu 
Nevermind, I can confirm that it doesn't resolve the promise (or call the callback method). Seems like an issue with the plugin.

Let's move the convo back to https://github.com/zyra/cordova-plugin-linkedin/issues/14 .. Sorry about that.
