### ISSUE TITLE
firebaseui-auth plugin

### ISSUE THREAD

**Issue by FallenRiteMonk** [driftyco/ionic-native#1589]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request

**Current behavior:**
In order to authenticate with firebase one has to use multiple separate plugins ([facebook](https://ionicframework.com/docs/native/facebook/), [twitter connect](https://ionicframework.com/docs/native/twitter-connect/), [google plus](https://ionicframework.com/docs/native/google-plus/),...) in combination with [angularfire2](https://github.com/angular/angularfire2) in order to be able to support authentication cross platform.

**Expected behavior:**
I would like to write a plugin with native support that simplifies firebase authentication using either [firebase-ui-auth](https://github.com/firebase/FirebaseUI-Android/blob/master/auth/README.md) or the plain firebase sdk's.

**Other information:**
I would like to know your opinion of if it makes more sense to use the firebaseui or the plain sdk approach?

As also already explained in the [original issue](https://github.com/driftyco/ionic/issues/11731):
I know of the [firebase plugin](https://ionicframework.com/docs/native/firebase/) with native support, but this plugin does not and will not implement authentication according to its [issue79](https://github.com/arnesson/cordova-plugin-firebase/issues/79)

**Comment by stormwin** [comment]
Plain SDK approach is the best. But you can anytime reuse code from firebase-ui-auth or any other firebase projects like messaging, crashreport, realtime-database if you need some examples or instructions.
I am also looking for good firebase-auth plugin. I found one (https://github.com/blakgeek/cordova-plugin-firebase-auth-google) but it is not working

**Comment by FallenRiteMonk** [comment]
I found this one: https://github.com/jsayol/cordova-plugin-firebase-sdk
This seems to be at a pretty good state, the only drawback is that it only supports android and since I have no experience with ios nor the possibility to even learning it (no mac) I can not contribute anything in that direction to it.

**Comment by patrickmcd** [comment]
While you linked to the [Android version of FirebaseUI](https://github.com/firebase/firebaseui-android), there is also a [Web version](https://github.com/firebase/firebaseui-web/).

The repo for the web version notes that it:

> is not yet supported in non-browser environments (Cordova, React Native, Ionic...)

The "not yet" suggests to me a future in which this is the version we'd be able to use with Ionic, rather than native plugins for each platform. You might inquire if that's a better place to contribute.

**Comment by ihadeed** [comment]
To submit a feature request, you need to provide us with a link to a Github repository or an NPM package for a Cordova plugin. 

I'm closing this issue but feel free to keep the conversation going. If you manage to write a plugin for this feature then we can create an Ionic Native wrapper for it.
