### ISSUE TITLE
Cannot find module "ionic-native" - Trying out Facebook Native Authentication

### ISSUE THREAD

**Issue by scorpion-3** [driftyco/ionic-native#1593]
Hello Folks, 

I am very new to Ionic 2 and have been breaking my head into trying out native Facebook login authentication, I have tried few approaches below, and got no where ! 

- When I tried `import {Facebook} from 'ionic-native';` I get the **"Cannot find module "ionic-native""** error, however I can access the login method by using this `Facebook.login(['email'])` in my code. 

- When I tired `import {Facebook} from '@ionic-native/facebook';` [I have this installed using `npm install @ionic-native/facebook --latest --save` ] , I am unable to access the login method and I get this error **Typescript Error
Property 'login' does not exist on type 'typeof Facebook'.**

Can some one please direct me to a correct approach ??. 

Runtime Error
Cannot find module "ionic-native"
Stack
Error: Cannot find module "ionic-native"
    at Object.<anonymous> (http://localhost:8100/build/main.js:55660:7)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:74450:77)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:74188:73)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:111876:70)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at http://localhost:8100/build/main.js:66:18
    at http://localhost:8100/build/main.js:69:10

Ionic Framework: 3.2.1
Ionic Native: ^3.5.0
Ionic App Scripts: 1.3.7
Angular Core: 4.1.0
Angular Compiler CLI: 4.1.0
Node: 6.10.2
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Comment by ihadeed** [comment]
Please read the following doc page to understand how Ionic Native 3.x works: https://ionicframework.com/docs/native/

Also have a look at the usage section of this page https://ionicframework.com/docs/native/facebook/

**Comment by joselevelsup** [comment]
Also this has come up. [Link to Issue](https://github.com/jeduan/cordova-plugin-facebook4/issues/501)
I commented on the issue but was unsure if I should ask on their repo or on Ionic-Native. I performed the same steps as @scorpion-3 
I am also using the example code that is provided on Ionic Native website.

**Comment by scorpion-3** [comment]
Thanks for the responses, I eventually figured out that native version was the issue. Currently I switched to ionic-native 2.5.1 and it works fine.
