### ISSUE TITLE
Expose `browserInit` method

### ISSUE THREAD

**Issue by xthilakx** [driftyco/ionic-native#160]
I'm just trying to get my feet into Ionic2, Angular2 and TypeScript. One of the greatest reason for using Ionic2 is the ability of code once and run it everywhere. I'm currently building an app that exclusively uses Facebook for authentication, and it's important for me to be able to test on a browser. `cordova-plugin-facebook4` plugin has a `browserInit` method that isn't exposed by Ionic Native. 

Are there plans to expose a way to provide browser fallback support? I'm trying to shorten the code/test cycle.

**Comment by nnixaa** [comment]
Same here, is there any specific reason to not include browserInit method? Thanks in advance.

**Comment by ihadeed** [comment]
Will be available in the next release.
