### ISSUE TITLE
cordova-plugin-market breaks build

### ISSUE THREAD

**Issue by danielflippance** [driftyco/ionic-native#1604]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
After installing cordova-plugin-market, the /www/build folder only contains two files. The following files are missing: main.css, main.css.map, main.js, main.js.map

When running the app with 'ionic run android -lsc --device' this results in 404 errors when the app is run.

**Expected behavior:**
Correct files in /www/build

**Steps to reproduce:**
After I install cordova-plugin-market running the app via 'ionic run android -lsc --device' succeeds but the build folder only contains two files so the app fails with several 404 errors. The build output concludes with the following. There are no errors in the rest of the build output:

    BUILD SUCCESSFUL

    Total time: 25.622 secs

    Built the following apk(s): 
	..../platforms/android/build/outputs/apk/android-debug.apk

    ANDROID_HOME=~/Library/Android/sdk

    JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home

    Skipping build...

    Built the following apk(s): 
	..../platforms/android/build/outputs/apk/android-debug.apk

    Using apk: ..../platforms/android/build/outputs/apk/android-debug.apk

    Package name: com.blah.blah

    LAUNCH SUCCESS

The build folder is virtually empty

    /www/build
        polyfills.js
        sw-toolbox.js

If I remove cordova-plugin-market and re-run, the /www/build looks correct:

    /www/build
        main.css
        main.css.map
        main.js
        main.js.map
        polyfills.js
        sw-toolbox.js

**Other information:**
Ionic info

    Cordova CLI: 6.5.0 
    Ionic CLI Version: 2.2.3
    Ionic App Lib Version: 2.2.1
    ios-deploy version: 1.9.1 
    ios-sim version: 5.0.13 
    OS: OS X El Capitan
    Node Version: v6.10.0
    Xcode version: Xcode 8.2.1 Build version 8C1002

**package.json info:**

```json
  "dependencies": {
    "@angular/common": "4.0.2",
    "@angular/compiler": "4.0.2",
    "@angular/compiler-cli": "4.0.2",
    "@angular/core": "4.0.2",
    "@angular/forms": "4.0.2",
    "@angular/http": "4.0.2",
    "@angular/platform-browser": "4.0.2",
    "@angular/platform-browser-dynamic": "4.0.2",
    "@angular/platform-server": "4.0.2",
    "@ionic-native/action-sheet": "^3.6.1",
    "@ionic-native/app-preferences": "^3.6.1",
    "@ionic-native/app-version": "^3.6.1",
    "@ionic-native/camera": "^3.6.1",
    "@ionic-native/core": "^3.4.2",
    "@ionic-native/file": "^3.6.1",
    "@ionic-native/http": "^3.6.1",
    "@ionic-native/in-app-browser": "^3.6.1",
    "@ionic-native/market": "^3.10.3",
    "@ionic-native/media-capture": "^3.6.1",
    "@ionic-native/screen-orientation": "^3.6.1",
    "@ionic-native/social-sharing": "^3.6.1",
    "@ionic-native/splash-screen": "^3.6.1",
    "@ionic-native/status-bar": "^3.9.2",
    "@ionic-native/toast": "^3.8.1",
    "@ionic-native/transfer": "^3.6.1",
    "@ionic-native/video-editor": "^3.6.1",
    "@ionic/storage": "2.0.1",
    "compare-versions": "^3.0.0",
    "ionic-angular": "3.1.0",
    "ionic-native": "^2.9.0",
    "ionicons": "3.0.0",
    "portfinder": "^1.0.13",
    "raven-js": "^3.15.0",
    "reflect-metadata": "^0.1.10",
    "rxjs": "5.1.1",
    "setimmediate": "^1.0.5",
    "sw-toolbox": "3.4.0",
    "zone.js": "^0.8.5"
  },
  "devDependencies": {
    "@angular/cli": "^1.0.4",
    "@ionic/app-scripts": "1.3.4",
    "@types/jasmine": "^2.5.47",
    "jasmine": "^2.6.0",
    "jasmine-core": "^2.6.2",
    "jasmine-ts": "^0.1.2",
    "karma": "^1.7.0",
    "karma-chrome-launcher": "^2.1.1",
    "karma-jasmine": "^1.1.0",
    "karma-phantomjs-launcher": "^1.0.4",
    "karma-typescript": "^3.0.2",
    "rollup-plugin-replace": "^1.1.1",
    "typescript": "~2.2.1"
  },
  "cordovaPlugins": [
    "es6-promise-plugin"
  ],
  "cordovaPlatforms": [
    "ios",
    {
      "platform": "ios",
      "version": "",
      "locator": "ios"
    }
  ],
```

Config.xml
```
  ....
  <plugin name="com.xmartlabs.cordova.market" spec="~1.1"/>
</widget>
```

**Comment by ihadeed** [comment]
Doesn't seem like an issue with Ionic Native. I suggest you create an issue at the plugin's repo instead.

**Comment by danielflippance** [comment]
Thanks - https://github.com/xmartlabs/cordova-plugin-market/issues/17
