### ISSUE TITLE
Missing file : node_modules/ionic-native/dist/esm/index.js

### ISSUE THREAD

**Issue by MrVibe** [driftyco/ionic-native#1607]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

The file is missing from latest 3.10.3 causing this error : 
ENOENT: no such file or directory, open '/node_modules/ionic-native/dist/esm/index.js
**Expected behavior:**

The file should be present.

**Steps to reproduce:**

From ionic 2.2.1 project, upgrading angular to 4.1.2

**Related code:**
app.module.ts
```
import { IonicStorageModule } from '@ionic/storage';
import { PhotoViewer } from '@ionic-native/photo-viewer';
```

**Other information:**

**package.json info:**

```json
{
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/animations": "^4.1.2",
    "@angular/common": "^4.1.2",
    "@angular/compiler": "^4.1.2",
    "@angular/compiler-cli": "^4.1.2",
    "@angular/core": "^4.1.2",
    "@angular/forms": "^4.1.2",
    "@angular/http": "^4.1.2",
    "@angular/platform-browser": "^4.1.2",
    "@angular/platform-browser-dynamic": "^4.1.2",
    "@angular/platform-server": "^4.1.2",
    "@angular/router": "^4.1.2",
    "@ionic-native/core": "^3.10.3",
    "@ionic-native/photo-viewer": "^3.10.3",
    "@ionic-native/transfer": "^3.10.3",
    "@ionic/storage": "^2.0.1",
    "dragula": "^3.7.2",
    "ionic-angular": "3.3.0",
    "ionic-cache": "^2.0.1",
    "ionic-native": "^3.5.0",
    "ionicons": "3.0.0",
    "ng2-dnd": "^4.0.2",
    "ng2-dragula": "^1.3.1",
    "rxjs": "5.1.1",
    "sw-toolbox": "3.6.0",
    "typescript": "^2.3.3",
    "zone.js": "0.8.11"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.1.0",
    "typescript": "2.0.9"
  },
  "cordovaPlugins": [
    "cordova-plugin-statusbar",
    "cordova-plugin-whitelist",
    "cordova-plugin-console",
    "cordova-plugin-splashscreen",
    "cordova-plugin-device",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [
    "ios",
    {
      "platform": "ios",
      "version": "",
      "locator": "ios"
    }
  ],
  "description": "wplms: An Ionic project"
}
```

I am not sure if I fully understand the issue but this issue has completely stopped work on my app for days now. Any help/guidance is appreciated.

**Comment by danielsogl** [comment]
You installed the old ionic native package.
Run npm uninstall --save ionic-native

**Comment by danielsogl** [comment]
And you also installed native 3.10.3 but the latest release is 3.10.2

**Comment by MrVibe** [comment]
@danielsogl: Thanks a lot for response. I have now installed the latest one 3.10.2 but the error persists, the file is still missing.

**Comment by MrVibe** [comment]
finally I resolved this issue by installing an older version of ionic-native : npm install --save ionic-native@2.2.6

All of a sudden ionic and angular makes such breaking changes. It really really sucks !

**Comment by danielsogl** [comment]
You don't understand my answer. You installed now the old ionic native package again. Uninstall it as I told you and read the documentation for the new ionic native 3.x releases.

**Comment by MrVibe** [comment]
Yes, I will try that later when I have completed development of my app. If I try it now, I am afraid, I will lose the motivation to use ionic altogether.

**Comment by MrVibe** [comment]
@danielsogl: Thanks a lot for helping out ! Have a good day ! :)
