### ISSUE TITLE
LocalNotification not accepting array as input for schedule (Typescript)

### ISSUE THREAD

**Issue by Artfloriani** [driftyco/ionic-native#167]
When trying to schedule multiple notifications using LocalNotification, typescript is throwing the following error:

```
TypeScript error: Error TS2345: Argument of type 'any[]' is not assignable to parameter of type 'Notification'.
  Types of property 'every' are incompatible.
    Type '(callbackfn: (value: any, index: number, array: any[]) => boolean, thisArg?: any) => boolean' is not assignable to type 'string'.
```

I tried creating an Interface of the Notification object but still shows this error. The scheduling works correctly, so I guess this is a ionic-native issue.

**Comment by ihadeed** [comment]
Hey @Artfloriani thanks for opening the issue.

Can you provide the code you are using to add multiple notifications?

I tested it recently using the [code here](https://github.com/driftyco/ionic-native/issues/130) and it worked fine...

**Comment by Artfloriani** [comment]
Sorry, my mistake. I just update ionic-native and it got rid of the error. I was finding strange that on the implementation it was supposed to accept arrays. Thank you for the reply.

**Comment by ihadeed** [comment]
No problem. Glad you got it to work @Artfloriani
