### ISSUE TITLE
Screenshot issues

### ISSUE THREAD

**Issue by Langstra** [driftyco/ionic-native#169]
I ran into an issue with the Screenshot plugin

When calling 
```
Screenshot.URI().then((imageData) => {
    //do something with imageData
})
```
It got the error message 
```
Error: Uncaught (in promise): null
```

I created a demo to show what I did:
https://github.com/Langstra/ionicNativeDemo

**Comment by ihadeed** [comment]
Thanks for pointing out the issue @Langstra

**Comment by JoaoFMachado** [comment]
i have stumbled upon this issue, is there a current fix?
