### ISSUE TITLE
diagnostic plugin

### ISSUE THREAD

**Issue by beachygreg** [driftyco/ionic-native#17]
Is anyone working on adding the diagnostic plugin? I not I need it so am keen to add it.

https://www.npmjs.com/package/cordova.plugins.diagnostic

**Comment by tlancina** [comment]
@beachygreg PR's welcome! Take a look at [the developer guide](https://github.com/driftyco/ionic-native/blob/master/DEVELOPER.md) and https://github.com/driftyco/ionic-native/tree/master/src/plugins for some examples, and let me know if you have any questions/issues/feedback!

**Comment by beachygreg** [comment]
@tlancina Took me a while to get around to doing this but working on it now. I added the code as per the guide but can not see any doc on how to build the project. Let me know and I can add it to the doc for any other typescript noobs like me...

**Comment by ihadeed** [comment]
You can build the project by running `npm run build_bundle `

**Comment by ghenry22** [comment]
https://github.com/driftyco/ionic-native/commit/2aa25969f7390fa9a5a23b17dc3d08a00255fa6d

Does this commit effectively close this issue?

**Comment by ihadeed** [comment]
Yes it does @ghenry22 , thanks!
