### ISSUE TITLE
Geolocation Observable (and others?) no longer compatible with Ionic2 beta7 .map() broken.

### ISSUE THREAD

**Issue by arlowhite** [driftyco/ionic-native#170]
**ionic info**

> Cordova CLI: 6.1.1
> Ionic Framework Version: 2.0.0-beta.7
> Ionic CLI Version: 2.0.0-beta.25
> Ionic App Lib Version: 2.0.0-beta.15
> OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04 LTS 
> Node Version: v5.11.1
"rxjs": "5.0.0-beta.6",

ionic-native 1.2.1, which has dependency: { rxjs: '5.0.0-beta.2' },

I think rxjs needs to be updated in ionic-native?

In Ionic2 beta6 I had a shared Observable derived from **Geolocation.watchPosition()** like this.
```typescript
import {Geolocation} from 'ionic-native';
import {Observable} from "rxjs/Rx";
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/share';
```

I want to process watchPosition() so I map() and share()
this.myObs$ is returned from my service.
_I simplified the code, Position is an interface I created._
```typescript
this.myObs$ = Geolocation.watchPosition({maximumAge: 30000, enableHighAccuracy: true}).map(position => {
      let newPosition: Position = {};
      // processing done here
      return newPosition;
    }).share();
```
This code, which worked previously (Ionic beta6), now has this TypeScript error after upgrading to beta7:
```
Error:(37, 5) TS2322: Type 'Observable<Position>' is not assignable to type 'Observable<Position>'.
 Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.
```
I tried bumping my project's rxjs to 5.0.0-beta.7 (from beta.6), but this didn't resolve the TypeScript error.
In any case, TypeScript still compiles with the error, so it's more of a warning.

However, when running the app. I get a runtime error:
```
EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in :0:0
ORIGINAL EXCEPTION: TypeError: ionic_native_1.Geolocation.watchPosition(...).map is not a function
```

This does not affect all Observables. For example, this works just fine:
```typescript
      Observable.interval(500).map(num => num**2).subscribe(val => {
        console.log('val', val);
      });
```

**Comment by ihadeed** [comment]
Would you say this is related to your previous issue #164 ?

**Comment by arlowhite** [comment]
@ihadeed No, #164 is something else related to Geolocation in the desktop browser (the plugin implementation itself maybe). I rewrote this code as a custom Observable to avoid .map() and still see the Chrome unsubscribe error.

In my node_modules, I just bumped ionic-native's rxjs to beta.6 in its package.json and replaced its copy of rxjs.
This TypeScript error went away
```
TypeScript error: /home/awhite/Code/Point97/wwf-app/app/services/geolocation.ts(37,96): Error TS2339: Property 'map' does not exist on type 'Observable<Geoposition>'.
```

But now, during ionic serve I see a slightly different form of the error:
```
Error TS2339: Property 'map' does not exist on type 'Observable<Geoposition>'.
```

So I'm fairly certain rxjs needs to be updated in ionic-native to be compatible with Ionic2 beta7. I'm going to checkout ionic-native and do a proper rebuild rather than this node_module hack and report back.

**Comment by ihadeed** [comment]
Ok I will look into this in a bit once I'm done fixing `EmailComposer` plugin. Thinking to set `rxjs` as a peerDependency instead of a dependency. This way it will just use whatever you have there from ionic-angular dependencies

**Comment by arlowhite** [comment]
Ok, so I did:

1. clone ionic-native
2. "rxjs": "5.0.0-beta.6" in package.json
3. npm install
4. npm run build_bundle
5. copy dist to $MYPROJECT/node_modules/ionic-native/dist
6. node_modules/ionic-native/node_modules/rxjs is still the copy of rxjs beta.6 I made earlier.

However, I still see errors at runtime with **ionic serve**
```
TypeScript error: /home/awhite/Code/Point97/wwf-app/app/services/geolocation.ts(37,96): Error TS2339: Property 'map' does not exist on type 'Observable<Geoposition>'.
TypeScript error: /home/awhite/Code/Point97/wwf-app/node_modules/ionic-native/dist/plugins/emailcomposer.d.ts(1,23): Error TS2307: Cannot find module './types/email.type.ts'.
```
(the email error is new, not sure if something is wrong with how I built or if someone is working on some new email code in master)

And in the app's console, the same error:
**ORIGINAL EXCEPTION: TypeError: ionic_native_1.Geolocation.watchPosition(...).map is not a function**

Not sure if I need to do something else for the ionic-native build to work, but I'll let you setup the peerDependency. Let me know when you create a branch and I can test it against my application code.

**Comment by ihadeed** [comment]
I got that `map` error while using other observables, even outside of ionic-native. I think it's happening after a recent Angular update. My apps seem to work fine even with that runtime error.

As for the email error, I just fixed it now.

**Comment by ihadeed** [comment]
The issue should be fixed in next release (or clone & build master)
