### ISSUE TITLE
Geolocation.watchPosition() Observable does not start emitting when GPS turned on after subscribe.

### ISSUE THREAD

**Issue by arlowhite** [driftyco/ionic-native#171]
This is a minor (low-priority) issue, but currently on Android if you subscribe to watchPosition while the GPS is off, it does not start emitting a position when you turn GPS on unless you leave the App and switch back.

To verify that this isn't particular to my project, I created a new starter for testing:

1. ionic start testproject sidemenu --v2 --ts
2. ionic info
 > Cordova CLI: 6.1.1
> Ionic Framework Version: 2.0.0-beta.7
> Ionic CLI Version: 2.0.0-beta.25
> Ionic App Lib Version: 2.0.0-beta.15
> OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04 LTS 
> Node Version: v5.11.1

3.  ionic-native version is 1.2.1
4. ionic plugin add cordova-plugin-geolocation    _(version 2.2.0)_
5. In platform.ready, log position: 
```typescript
      Geolocation.watchPosition().subscribe(pos => {
        console.log('pos', pos);
      });
```

**ionic run android**

I am using a Samsung Galaxy S6 device (Marshmallow 6.0.1)

Starting the app with GPS already on works as expected.

When I start with GPS initially off, then turn-on GPS from Android's swipe-down settings, the Observable never starts emitting when I stay within the app.

If I go Home, then back to the Ionic app, sometimes it will start emitting, but not always. Based on the log, I know it's not reloading the App when it works, instead the Android OS is occasionally updating the location on the Android Home screen and triggering the subscription when I return to the Ionic App.

If I switch to Google Maps, then back to the Ionic App, this guarantees that the subscription will start emitting.

With **enableHighAccuracy: true**, simply switching to the Home screen and back to the App will trigger the existing subscription to emit. However, just staying within the App after turning GPS on will never see a position emitted from the subscription.

Creating a new subscription after turning-on GPS will immediately get a position. So developers will need to add a refresh GPS button, or manually re-subscribe every few seconds until a position is retrieved, which isn't ideal.

I think developers would expect the subscription to emit a position shortly after the user turns-on the GPS.

**Comment by ihadeed** [comment]
Did you try to watch the position using the plugin API instead of ionic-native wrapper?

**Comment by arlowhite** [comment]
No, just the ionic-native Geolocation.watchPosition() Observable. This isn't high-priority for me. (I added a Refresh GPS button to my app) But I wanted to record my Android research since I've been testing GPS behavior on my device. This could be Marshmallow only behavior, I haven't had time to test what JellyBean does. I suppose the [geolocation docs](http://ionicframework.com/docs/v2/native/geolocation/) could mention this though. Something like:

> If your user turns-on GPS while in the Ionic App, the subscription may or may not start to emit a position depending on the device. You may need to create a new watchPosition() subscription after GPS is turned on.

**Comment by ihadeed** [comment]
I asked just because I can't see how the `ionic-native` wrapper can cause this issue. Thought it might be a bug with the plugin itself.

**Comment by ihadeed** [comment]
Hey there

I just did some tests and found out that this is caused by the Geolocation API itself, and not by Ionic-native.

Watching position when GPS is off doesn't send anything (unless if there is a recent position stored in the phones memory).

I wonder if there is a way to prompt the user to turn the GPS on if `watchPosition` is unable to get location.

**Comment by arlowhite** [comment]
Ok, should I create an issue with the plugin project after I test again with the plugin API?
Or were you planning on creating an issue?

**Comment by ihadeed** [comment]
I suggest you open an issue with Apache.
