### ISSUE TITLE
Calendar plugin .listCalendars() type def should be Promise<any> not void.

### ISSUE THREAD

**Issue by origin1tech** [driftyco/ionic-native#172]
It returns a promise currently what I see is :void in the type definitions.

Going over this plugin quite thoroughly at the moment happy to create some PR's as these little things show up if there are any others. 

If I'm missing something that's cool too, but appears that this should be of type Promise.
https://github.com/driftyco/ionic-native/blob/master/src/plugins/calendar.ts#L274

**Comment by ihadeed** [comment]
Thanks @origin1tech
