### ISSUE TITLE
Compatible with Ionic 1.x?

### ISSUE THREAD

**Issue by kentr** [driftyco/ionic-native#173]
There are a lot of clues that Ionic Native is only for Ionic `2.x`, but since the Ionic Native version is at `1.2.x` I wanted to double-check.

Does Ionic Native work with Ionic `1.x`?

**Comment by ihadeed** [comment]
Hey @kentr 

You can use `ionic-native` with any Cordova application.

To use it in Ionic 1 follow these steps:

- Copy `ionic.native.min.js` to your www directory (you can copy the non-minified version if you wish)
- Add that bundle file to your index.html (See https://github.com/ihadeed/ionic1-ionic-native-example/blob/master/www/index.html#L21-L22)
- Use the plugins and their functions through the global variable `IonicNative` (See https://github.com/ihadeed/ionic1-ionic-native-example/blob/master/www/js/app.js#L28-L34)

Best of luck!

**Comment by Tiagojdferreira** [comment]
If you are using es6 you can do like ionic 2
