### ISSUE TITLE
SQLite detect when ready

### ISSUE THREAD

**Issue by bayssmekanique** [driftyco/ionic-native#174]
The SQLite constructor uses a promise internally, so the instance returned by the constructor is not immediately available for use.  There is no `onReady` method, or any way to detect that the instance has been initialized.  Is there a process for detecting this?

Ex: 
```
this.db = new SQLite({ name: this.dbName, location: this.dbLocation });
this.db.transaction((tx) => {
	tx.executeSql(
		'CREATE TABLE IF NOT EXISTS ' + this.tables.history + ' ('
		+ 'id INT PRIMARY KEY     NOT NULL, '
		+ 'start          INT     NOT NULL, '
		+ 'duration       INT     NOT NULL, '
		+ 'energy         INT     NOT NULL, '
		+ 'avg_power      INT     NOT NULL, '
		+ 'session_obj    TEXT'
		+ ');'
	);
})
	.then(() => { console.log('TX OK') })
	.catch((e) => { console.log(e) });
```
Results in:
```
OPEN database: test.db
app.bundle.js:997 TypeError: Cannot read property 'transaction' of undefined(…)
```

**Comment by ihadeed** [comment]
- Are you waiting for `ondeviceready` to fire?
- Are you testing on a device/emulator?

**Comment by bayssmekanique** [comment]
I am waiting for `platform.ready()` before initializing, and I am finding this error on real hardware (both iOS and Android).

For the moment, I am wrapping the sql calls in a timeout with a 100ms delay after the database is opened, and this is solving the problem, but this is obviously not ideal.

**Comment by ihadeed** [comment]
Hey I just tested your code and didn't have any problems.

Using Ionic Native 1.2.4 with `cordova-sqlite-storage` plugin version 1.4.1

**Comment by ihadeed** [comment]
I will close this for now.

Please test again with the latest plugin + ionic-native versions.

If you still have issues reopen and provide steps to reproduce.

Thanks!

**Comment by bayssmekanique** [comment]
Yes, this seems to be a larger issue I'm seeing across the board where plugins aren't loaded when `platform.ready()` is called.  I am still having this issue, but I think it might be an issue with how plugins are loaded in general.
