### ISSUE TITLE
EmailComposer Issue with Ionic2 beta 7

### ISSUE THREAD

**Issue by Pekes317** [driftyco/ionic-native#175]
Using the isAviable method produces a promise undefined error. There's a thread in the ionic forum.

import {EmailComposer} from 'ionic-native';

EmailComposer.isAvailable().then((available) =>{
 if(available) {
   //Now we know we can send
 }
});

**Comment by Pekes317** [comment]
Forum URL:

https://forum.ionicframework.com/t/email-composer-error/52659

**Comment by ihadeed** [comment]
Hey there

Thanks for opening an issue.

The email plugin is currently not working, it's an issue from the plugin
developer.  Waiting on the developer to fix the plugin before fixing the
ionic native implementation (if there are any problems with it).

Thanks for your patience.

**Comment by Pekes317** [comment]
Thank you, I used a different plugin, cordova-plugin-email, and I was able to get it to work using just the open method. I tested the isAvailable  method, did get the error, but the available param is undefined. So it looks like it is probably the other plugin having an issue as you said.  

Other plugin Git - https://github.com/hypery2k/cordova-email-plugin.git

**Comment by ihadeed** [comment]
Thanks I will check out the plugin soon. If it's good maybe we can use it
instead of the other one.

**Comment by ihadeed** [comment]
@Pekes317 it looks like an outdated fork (of a fork) of the plugin that we are currently using. 

I'm waiting on the original developer to respond to an issue that I created for now (Ref: https://github.com/katzer/cordova-plugin-email-composer/issues/212). If he doesn't respond I think I will fork his repo and try to fix the app and implement better ways that integrate better with ionic-native.

Also, by looking at the issues posted in their repo, it looks like the `isAvailable` function implementation isn't compatible with the current version of one of the technologies involved in the process. See https://github.com/katzer/cordova-plugin-email-composer/issues/209

**Comment by Bouzmine** [comment]
I found a workaround for this. You can use method `shareViaEmail` of plugin `SocialSharing`. The only difference is that arguments are ordered instead of being in an object and there's no `isHtml` property.

**Comment by Sampath-Lokuge** [comment]
Above Native plugin is not working at all.
This is the only solution we have now: 

https://ionicframework.com/docs/native/social-sharing/#shareViaEmail
