### ISSUE TITLE
local notifications & push notifications : multiple actions

### ISSUE THREAD

**Issue by Poketchu** [driftyco/ionic-native#176]
Hello there,

Submitting a feature request to you today.
Could you add to the possibility to add "actions" (or buttons if you prefer) to local and/or puush notifications, as it was made in this cordova plugin : https://github.com/elizabethrego/cordova-plugin-local-notifications

It seems that this functionnality was merged in the katzer's cordova localnotifications plugin, and I think it could be really intersting to have it in ionic-native too.

Keep up the good work !
Regards,
Poketchu

**Comment by Poketchu** [comment]
... Maybe... Up ?

**Comment by ihadeed** [comment]
Thanks for the request. Will add this.

**Comment by ihadeed** [comment]
I just had a look at that link again, and just realized it's not katzer's plugin. Maybe we should wait until it's implemented there to ensure stability.
