### ISSUE TITLE
Do not import "rxjs/Rx"

### ISSUE THREAD

**Issue by hlehmann** [driftyco/ionic-native#178]
Importing directly from `rxjs/Rx` will cause by browserify and other compilers to add all the rxjs library witch is quite big.

In order to improve loading time it would be nicer to import only needed components:
```
import {Observable} from "rxjs/Observable";
// eventually if some operators are required
import "rxjs/add/operator/combineLatest";
```

**Comment by ihadeed** [comment]
Wouldn't browserify (or alternatives) import only the `Observable` module out of that file?

It was done to resolve this issue here: https://github.com/driftyco/ionic-native/issues/170

I tried importing the `map` operator like how you demonstrated with `combineLatest` and that didn't work. 

I will try to use `combineLatest` and see if that works.

**Comment by hlehmann** [comment]
Well, combineLatest was just an example.
After reviewing #170 I think this issue was due to ionic-angular and ionic-native had distinct constraints for rxjs (beta-6 and beta-2) so ionic-native download it's own rxjs so that's why we have `Type 'Observable<Position>' is not assignable to type 'Observable<Position>'` because there are two pointer of two different classes.

I would say that's now fixed because now there is no more conflict `"dependencies": {": "^5.0.0-beta.6}`. But to be sure it will not happen again you should put rxjs into peerDependencies.

**Comment by hlehmann** [comment]
Well the `peerDependencies` is not mandatory, just the ^ will avoid further conflict

**Comment by hlehmann** [comment]
Well forget the peerDependencies, it seems not used any more by the angular team. We just need to be sure there is no conflict between constraints in ionic-angular and ionic-native. `^`5.0.0-beta.6 should be enough.

**Comment by ihadeed** [comment]
Yeah I think the `^` is good enough. I remember I saw a notice in the CLI that peerDependencies will not be installed automatically if they don't exist. Which wouldn't be a good think for `ionic-native` in case someone is using it with a non-ionic project.

I will revert it back when I get a chance.
