### ISSUE TITLE
Add Support For In App Purchase Plugin

### ISSUE THREAD

**Issue by Chuckv01** [driftyco/ionic-native#181]
It would be great to have support for the in app purchase plugin: https://github.com/j3k0/cordova-plugin-purchase

Keep up the great work!

**Comment by Bouzmine** [comment]
+1

**Comment by Bouzmine** [comment]
@ihadeed I'd need that for my app, is there an ETA ?

**Comment by ihadeed** [comment]
@Bouzmine It looks like a large plugin. No ETA at the moment.

**Comment by Chuckv01** [comment]
@Bouzmine I put this declaration at the top of the typescript file that uses the IAP plugin:

declare var store: any;

That will prevent undefined typescript errors from clogging things up.

**Comment by biesbjerg** [comment]
This seems easier to support (and also to use?)
https://github.com/AlexDisler/cordova-plugin-inapppurchase

**Comment by ch-weiss** [comment]
#biesbjerg It looks nice but it does not support the Windows platform. Maybe mobile is not that interesting anymore but why not Windows Universal for any Windows Client (there you have a huge market with almost no additional effort)
