### ISSUE TITLE
Typings fix needed for Toast duration - Easy one.

### ISSUE THREAD

**Issue by origin1tech** [driftyco/ionic-native#182]
Ionic native Toast message type definition has "duration" as a string. I believe this should be a "number"

see: https://github.com/driftyco/ionic-native/blob/master/src/plugins/toast.ts#L12

happy to start creating PR's I'm finding quite a few of these as it turns out.  Just let me know.

**Comment by ihadeed** [comment]
Thanks for pointing it out

PRs are appreciated!
