### ISSUE TITLE
Calendar gives error when running hasReadWritePermission

### ISSUE THREAD

**Issue by mbakker96** [driftyco/ionic-native#184]
Hello,

I want to check of the user has read and write permission but when i run it I get a error. 

```typescript
checkCalendarPermission(): void {
    Calendar.hasReadWritePermissions().then((msg) => {console.log(msg)}, (err) => {console.log(err)});
}
```

It should give  true but I get a error that he could not find something when I run it on my Iphone.

**Comment by mbakker96** [comment]
is this a issue in ionic-native or in the [phonecap-calendar](https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin) plugin?

**Comment by ihadeed** [comment]
Your scenario seems like it's a problem with the plugin. But to be sure, we have to test the original plugin directly without using the ionic native wrappers.

**Comment by ihadeed** [comment]
@mbakker96 The issue was from `ionic-native`. There's an extra `s` at the end of the function name. It should be `hasReadWritePermission()`. Will be fixed in next release!
