### ISSUE TITLE
Media Plugin success, error, status handling

### ISSUE THREAD

**Issue by ghenry22** [driftyco/ionic-native#186]
Noticed in the code that there is a TODO for handling these.  Is there any progress on this or any hints as to how it could be handled?

I need these call backs when using the media plugin to know the current loading/playback status and whether it was successful or not.

**Comment by ihadeed** [comment]
Don't remember why I left it as a TODO and didn't handle them. I will definitely revisit that at some point and complete it.

From a quick look:

1. The original plugin is instantiated by using the following code:
```javascript
var media = new Media(src, mediaSuccess, [mediaError], [mediaStatus]);
```

Ideally we would want mediaSuccess and mediaError to be bundled into a promise, and mediaStatus to output via an observable.

Theoretically, the following should work as a quick fix:
```typescript
@Plugin(...)
export class Media {

// add two new properties
  status: Observable<any>;
  init: Promise<any>;

  constructor(src: string) {
// edit constructor
    let res, rej, next;
    this.init = new Promise<any>((resolve, reject) => { res= resolve; rej = reject;});
    this.status = new Observable((observer) => { next = observer.next; });
    this._objectInstance = new Media(src, res, rej, next);
  }

}
```

You can apply the fix yourself or wait for an official fix. To apply the fix yourself:
Clone repo -> edit `media.ts` -> run `npm run build_bundle` -> use the new `dist` directory in your project (`node_modules/ionic-native/dist`)

**Comment by ghenry22** [comment]
I'll test it out as you suggest and see submit a PR if I get it working and tested successfully

Thanks for the quick feedback

**Comment by ihadeed** [comment]
thanks @ghenry22

**Comment by ghenry22** [comment]
I have success and error working, returning a promise and have updated the docs in the header with examples on how to use.  Hopefully have status working and updated doc today as well then will put in a PR.

**Comment by ihadeed** [comment]
Great. Thanks!

**Comment by ghenry22** [comment]
I have a fork here with the updates.
https://github.com/ghenry22/ionic-native/tree/fix-%23186

I get success and error results returned as promises just fine and I have added to the doc in the header comment for these.

But no matter what I do I never seem to get anything in the observable.

I have this code in my app to subscribe to the observable but nothing ever gets logged to the console so I am not sure if I have screwed something up.  Have spent a day looking into it and have no clue at the moment.:
      this.media.status.subscribe(data => {
        console.log(data);
      });

a simple console.log of this.media.status shows me that it is an observable so that seems right.  Just never seem to get any data into it.

**Comment by ihadeed** [comment]
@ghenry22 I just had a similar issue while fixing up the google maps plugin.

It seems like `observer.next` doesn't work that way, you can't just pass it as a callback function. You would need something like this:
```typescript
  // Properties
  private _objectInstance: any;
  status: Observable<any>;
  init: Promise<any>;

  // Methods
  /**
   * Open a media file
   * @param src {string} A URI containing the audio content.
   */
  constructor (src: string) {
    let res, rej, next;
    this.init = new Promise<any>((resolve, reject) => {res = resolve; rej = reject;});
    this.status = new Observable((observer) => {
        next = (data) => { observer.next(data); };
    });
    this._objectInstance = new Media(src, res, rej, next);
  }
```

**Comment by ghenry22** [comment]
Cool thanks, I'll try it out over the weekend and update.  I'm happy to write some examples for the docs on the ionic site as well, should I just include this in the where the current examples are in the comment block in this file or should I submit docs elsewhere?

**Comment by ghenry22** [comment]
Unfortunately still the same, subscriber never sees any data.  it should see an update when the media plugin moves between states, it's pretty easy to test because changing between paused and playing should trigger status updates between status=2 (playing) and status=3 (paused).

I have limited time playing with observables unfortunately so it's hard to tell where things are going wrong.

**Comment by ihadeed** [comment]
@ghenry22 editing the comment blocks will automatically update `ionic-site` (takes some time for the ionic team to push the updates to the production site)

I'll clone your repo and do some tests.

**Comment by ghenry22** [comment]
I've been working on my app for the last few days and can confirm that the success and error handling is working well on both Android and iOS.

A couple of quirks worth noting:

iOS
You can easily replace an existing media object with a new one and it releases the underlying resource from the old object.

Create a media object and start playing
this.media.create(src)
this.media.play

Then create a new media object and it replaces the existing one and stops any playback in progress
this.media.create(src2) 

There seems to be no need to call this.media.release()

iOS will trigger the success callback only on completion of playback of the file or stream.

Android
You will need to manually release the underlying media resources.  If you follow the iOS example above you will end up with 2 sounds playing and you will only have an object referencing one of them.

On android make sure to run this.media.release() when you are done with a media object.

Android will trigger the success callback on release() OR on completion of playback of the file or stream.

**Comment by ihadeed** [comment]
Hey @ghenry22,

If the code works fine now it would be a good idea to submit a PR. You can add those quirks to the JSDocs of the plugin so they will be available for everyone.

**Comment by ghenry22** [comment]
I'll put in a PR that handles success and error and the notes above, but status is still not getting any updates,  better something than nothing though!

**Comment by ihadeed** [comment]
Yeah for sure. I will look into the status after you submit the PR and see if I can make it work!

Thanks @ghenry22

**Comment by ghenry22** [comment]
PR submitted with updated doc.  Added more comprehensive usage examples.

I'm not sure that getDuration() and getCurrentPosition() should be async though.  I think these should probably sync functions.  They return instantly and it's not like they are doing any heavy lifting, it feels like wrapping them in promises just adds unnecessary complexity.

**Comment by uzumakinaruto123** [comment]
@ghenry22  I need to status for looping .  can you help with status callback ? 

```
this.file.status.subscribe(data => {
        console.log('status is '+data);
      });
```

this does not work.

I decided to edit media.ts.  but i have definition files  `.d.ts` and not `.ts` .

I have latest ionic-native 1.3.20


Thanks ! Help is appreciated.

**Comment by ghenry22** [comment]
@ihadeed - I remember we didn't have status events working with the first implementation with observables but I have no idea why status events weren't being sent/received.  Perhaps you could take a quick look at the code around the status events now that ionic-native has moved along so much it might be something really obvious.

**Comment by ihadeed** [comment]
Just pushed a commit that will be available in the next release, should fix the issue, if not please open a new issue and let me know.

**Comment by cozzbie** [comment]
I'm a little confused here. Am I to use `mediaplugin = new MediaPlugin(src);` or `media = new Media(src);` because I am trying to grab the `src` after an operation and it seems to only be exposed via the `_objectInstance: Media` api.

**Comment by cozzbie** [comment]
Also please...what location is the `src` on the device after recording iOS and Android? I have tested both the data and temp directories but the file doesn't exist.

**Comment by ghenry22** [comment]
best to read up on the media plugin docs for examples and info about where things are stored by default.  To use the ionic-native wrapper just follow the ionic-native docs.  The ionic forums are also a good place for questions.  Commenting on a long closed issue about something else entirely is probably not going to get much response.
