### ISSUE TITLE
unable to locate ionic-native module / missing dist in master

### ISSUE THREAD

**Issue by apurva3000** [driftyco/ionic-native#19]
I recently updated the ionic-native module using npm install ionic-native --save and it updated to 1.0.10. But I noticed there's dist folder now missing which throws a lot of errors now while trying to locate this module and unable to find it finally.

**Comment by tlancina** [comment]
Oop looks like there was a bad release, can you try 1.0.11?

**Comment by apurva3000** [comment]
Thanks! It works now.

**Comment by tlancina** [comment]
Yeah thanks for the heads up! Going to close now, but let us know if you're having any more issues.
