### ISSUE TITLE
_ionicNative.GoogleMaps) is not a function

### ISSUE THREAD

**Issue by wwallace** [driftyco/ionic-native#193]
Version 1.2.4:
import {GoogleMaps, GoogleMapsEvent} from 'ionic-native';

let map = GoogleMaps('map');
map.on(GoogleMapsEvent.MAP_READY).subscribe(() => console.log("Map is ready!"));

results in  error    Uncaught TypeError: (0 , _ionicNative.GoogleMaps) is not a function

**Comment by ihadeed** [comment]
Hey @wwallace 

I see two mistakes with that code:
1. It's `GoogleMap` not `GoogleMaps` ... (sorry if you are following out dated docs, it will be updated soon)
2. You must create a new instance like this: `let map = new GoogleMaps(...);`

So your code should look like this:
```typescript
import {GoogleMap, GoogleMapsEvent} from 'ionic-native';

...

let map = new GoogleMap('map');
map.on(GoogleMapsEvent.MAP_READY).subscribe(() => console.log("Map is ready!"));
```
