### ISSUE TITLE
Support for plugin SafariViewController

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic-native#195]
I'd like support for plugin [SafariViewController](https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller) which implements the new iOS 9 SafariViewController, a faster and beautifuler alternative to InAppBrowser.

**Comment by Bouzmine** [comment]
Thanks for such a quick response. I just wanted to flag that there's an error in the doc for this wrapper. In the options, `url` is written `utl`.

**Comment by ihadeed** [comment]
Thanks @Bouzmine will fix it soon.
