### ISSUE TITLE
Background Mode 

### ISSUE THREAD

**Issue by pniraula** [driftyco/ionic-native#197]
May be I shouldn't post it in here but I couldn't get any help else where.
I m creating wrapper for Background mode plugin https://github.com/katzer/cordova-plugin-background-mode 
I went through docs to create wrapper but I am unable to use it. Here's the link to the wrapper I have created. 
https://github.com/pniraula/ionic-native/blob/master/src/plugins/backgroundmode.ts
While testing it on android, I get plugin_not_installed error. I did some research and searched in Ionic Forum but I couldn't find any help. Any help would be really appreciated.

**Comment by ihadeed** [comment]
Hey

I just looked at your code.

You need to change this line:
```
  pluginRef: 'cordova.plugin.background-mode',
```
to this:
```
  pluginRef: 'cordova.plugins.backgroundMode',
```

Usually if the `pluginRef` you define isn't accessible, ionic native will assume that you don't have the plugin installed in your project.

the `pluginRef` for that plugin is documented here: https://github.com/katzer/cordova-plugin-background-mode#usage

**Comment by pniraula** [comment]
Yeah that did the trick. Thank you for your help.
