### ISSUE TITLE
Both in-app purchase plugins appear to be unstable

### ISSUE THREAD

**Issue by Aaron-Sterling** [driftyco/ionic-native#1992]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[x ] feature request

**Current behavior:**
Both in-app purchase native plugins appear to be unstable. Please see [this thread](https://forum.ionicframework.com/t/in-app-purchases-plugin-vs-in-app-purchases-2/102906) on the Ionic forum.

**Expected behavior:**
A stable way to connect an Ionic app to Android and Apple in-app purchases.

**Steps to reproduce:**
Please see linked thread.

**Other information:**
As I stated in the thread, I'd be willing to pay for a consistently supported plugin for this task. Perhaps it's something you can/should fold into an Ionic paid membership? But I'd either like a supported free plugin, or one I could pay a one-time $25 fee for or whatever. This seems like a significant revenue stream issue, and I'd like it guaranteed resolved somehow.  And sadly I don't have the experience with Cordova payments to offer help on the code body itself, though I'd be happy to help if there's a way I can.
```

**Comment by thielCole** [comment]
Hey @Aaron-Sterling , I am having a similar issue. I was able to get InAppPurchase2 (ionic name) working fairly well but I'm sure that there would be some real stability issues because Apple always seems to break something every update.
