### ISSUE TITLE
Base64ToGallery is not working

### ISSUE THREAD

**Issue by zhaoshengjun** [driftyco/ionic-native#212]
Tested in 2.0.0-beta.25. 

When using ionic-native, it's not working. The error is "base64ToGallery can not find on Base64ToGallery".

When use cordova.base64ToGallery, it's working.

I changed the base64togallery.js in ionic-native by removing prototype, it's working. So I assume it's a bug and needs to be fixed.

**Comment by ihadeed** [comment]
Thanks for pointing it out. The problem is that the function is not marked as static. 

This will be resolved in the next release.

**Comment by anujmpec** [comment]
Is it fixed now ?  i am trying with this._base64ToGallery.base64ToGallery  ()   and getting  ERROR Error: Uncaught (in promise): TypeError: Cannot read property '_base64ToGallery' of undefined
