### ISSUE TITLE
Add support for the cordova paypal plugin

### ISSUE THREAD

**Issue by Ashar99** [driftyco/ionic-native#216]
Hopefully if it has a native wrapper it will be able to work in Ionic 2.

**Comment by ihadeed** [comment]
Can you provide a link for the plugin?

**Comment by Ashar99** [comment]
GITHUB : https://github.com/paypal/PayPal-Cordova-Plugin
NPM : https://www.npmjs.com/package/com.paypal.cordova.mobilesdk

**Comment by ihadeed** [comment]
Thanks
