### ISSUE TITLE
Unable to compile 1.3.0 with RxJS issues

### ISSUE THREAD

**Issue by dkobia** [driftyco/ionic-native#222]
I upgraded to `1.3.0` from `1.2.4` and immediately having issues with RxJS Operators in the Angular2 HTTP Client

```
Property 'map' does not exist on type 'Observable<Response>'.
```

with: 
```
this.http.post('http://www.mytest.com/api', body)
  .map(res => res.json())
  .subscribe(
    data => {},
    error => {},
    () => console.log('Create Feedback Complete')
  );
```

Might it have anything to do with the Cordova HTTPD plugin you added? Trying to look through commits to see what else changed.

**Comment by ihadeed** [comment]
Can you check what version of rxjs is installed on your ionic project?

This error shouldn't happen since the rxjs version is the same for both
1.2.4 and 1.3.0.

More info would definitely help us debug this :)

**Comment by dkobia** [comment]
This is with the demo conference app and the angular2 http-client. It seems the only way to make the error go away with 1.3.0 is by performing the import again in every page/component where `map` is called re:

```
import {Observable} from 'rxjs/Rx';
import 'rxjs/add/operator/map';
```

**Comment by dkobia** [comment]
Closing this for now. I'll just import the `map` operator manually as shown below when including Http from Angular. It just seems odd however that this issue started with `1.3.0` and not before.

```
import {Http} from '@angular/http';
import {Observable} from 'rxjs/Observable';
import 'rxjs/add/operator/map';
```

**Comment by davidefavia** [comment]
Thank you @dkobia, same problem here upgrading `ionic-native` from version `1.2.4` to `1.3.21`, I resolved it manually importing all the needed operators as you suggested.
Here below my `ionic info` result for reference:

```
Cordova CLI: 6.3.1
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.10.1
Xcode version: Xcode 7.3 Build version 7D175 
```
