### ISSUE TITLE
Add support for iBeacon plugin

### ISSUE THREAD

**Issue by waifung0207** [driftyco/ionic-native#223]
Thanks team for the repo. Hopefully will see the iBeacon plugin (also included in [ngCordova](http://ngcordova.com/docs/plugins/beacon/)) migrated to Ionic Native as well.

**Comment by 05bca054** [comment]
+1

**Comment by piuen0** [comment]
Thanks Ionic team, we need this function badly, would be great if iBeacon plugin can be updated soon.

**Comment by ihadeed** [comment]
This has been added, and is currently available in the npm package version 1.3.3
