### ISSUE TITLE
Globalization not working (TS project)

### ISSUE THREAD

**Issue by Mobius77x** [driftyco/ionic-native#226]
I added the Globalization plugin and imported it in my app.ts (import {Globalization} from 'ionic-native';
) without Visual Code complaining (i.e. successful install).

However, Visual Code is not recognising globalization when typing navigator.globalization (Property 'globalization' does not exist on type 'Navigator')

**Comment by Bouzmine** [comment]
I think you should use the `Globalization` object you just imported. To use use `getPreferredLanguage()`, do 
```javascript
Globalization.getPreferredLanguage().then(lang => {
 // use lang.value
});
```

**Comment by ihadeed** [comment]
As @Bouzmine said, you need to use the Globalization object that you imported from `ionic-native`.

While using `ionic-native` there is usually no need to try and access the plugin through it's original reference. You just need the plugin to be installed, so `ionic-native` does the talking for you.
