### ISSUE TITLE
Add new implementation for File plugin

### ISSUE THREAD

**Issue by ihadeed** [driftyco/ionic-native#233]
This issue is just for reference and as a reminder.

New file implementation is in the dev branch. Commit URL: https://github.com/driftyco/ionic-native/commit/b1caab316a2d8f2ef10d8b3c6054aba63437823d

---

- Add missing functionality
- Test
- List as a breaking change in next release

**Comment by ghenry22** [comment]
Any chance of this getting merged in soon?  I'm waiting on this before implementing file based functionality in my app

**Comment by ihadeed** [comment]
I can't remember what needs to be done here. I think there is some missing
functionality.

I'm waiting to have sometime to add the missing functions and then we can
merge it.

If you want to use it as-is I can help you by updating the branch and
building a custom bundle that you can use, which has this plugin included.
