### ISSUE TITLE
Cannot use MediaPlugin in browser

### ISSUE THREAD

**Issue by canhnht** [driftyco/ionic-native#243]
I am trying to use [MediaPlugin](http://ionicframework.com/docs/v2/native/mediaplugin/) in browser but I get this error
```
EXCEPTION: Error: Uncaught (in promise): ReferenceError: Media is not defined
```
when I create new instance of MediaPlugin like this:
```
let file = new MediaPlugin('audio/music1.mp3');
```
I don't know how to fix it.

**Comment by ghenry22** [comment]
Media plugin needs to be run on a real device

**Comment by canhnht** [comment]
Oh, I see. If I use [Web Media API](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement), can I run app on both browser and device?

**Comment by ghenry22** [comment]
You can use html5 audio tag but it has some trade offs, like background audio in your app may not work on android.  You could write your code though to say if the platform is Cordova use the media plugin, else use html5.  That then depends on your writing create, play, pause etc methods to cater to the differences between the media plugin and the html5 audio API.  It's pretty straight forward but you'd have to consider if it's worth the effort depending on what your target platform is.

This ticket could probably be closed as its not an ionic-native issue.

**Comment by ghenry22** [comment]
just so you know ionic-native is a wrapper for various Cordova plugins so you need to have a supported Cordova platform and device and install the plugin as well as ionic-native.

**Comment by canhnht** [comment]
Thanks a lot for your support.
