### ISSUE TITLE
"plugin_not_installed" error using "Barcode Scanner" wrapper

### ISSUE THREAD

**Issue by elluminatte** [driftyco/ionic-native#244]
Hello.
I get the "plugin_not_installed" error using "Barcode Scanner" (on iOS and Android).
This is my code:
```javascript
import {Component} from "@angular/core";
import {Platform, Alert, NavController} from 'ionic-angular';
import {BarcodeScanner} from 'ionic-native';

@Component({
  templateUrl: 'build/pages/home/home.html'
})
export class HomePage {
  constructor(private platform: Platform, private navController: NavController) {
    this.platform = platform;
    this.navController = navController;
  }

  scan() {
    this.platform.ready().then(() => {
      BarcodeScanner.scan().then((barcodeData) => {
        this.navController.present(Alert.create({
          title: "Scan Results",
          subTitle: barcodeData.text,
          buttons: ["Close"]
        }));
      }, (err) => {
        this.navController.present(Alert.create({
          title: "Attention!",
          subTitle: err,
          buttons: ["Close"]
        }));
      });
    });
  }
}
```

Plugin is correctly installed:
typing
```bash
ionic plugin add phonegap-plugin-barcodescanner
```
in the terminal returns:
```bash
Plugin "phonegap-plugin-barcodescanner" already installed on android.

Plugin "phonegap-plugin-barcodescanner" already installed on browser.

Plugin "phonegap-plugin-barcodescanner" already installed on ios.
```

I get this error only with Barcode Scanner wrapper. i tried to substitute it with Camera wrapper - it works perfect.
Some additional info:
```bash
$ node -v
v5.12.0
$ npm -v
3.8.6
$ ionic info
Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04 LTS 
Node Version: v5.12.0
```
Hope you will help me with this problem.
Regards, Nikolay

**Comment by ihadeed** [comment]
Hey there,

I had a quick look at the plugin wrapper and the latest version of the plugin. I can't see a reason why the plugin would have this issue.

Could you try and do the following, at the top of your app's main file add the following:
```typescript
declare var cordova: any;
console.log("barcodeScanner exists: " + !!cordova.plugins.barcodeScanner);
```
Then compile & run on your device. and check your console output to see if that variable exists in memory.

Alternatively you may just interact with the console and try to see if `cordova.plugins.barcodeScanner` exists. 

This will help narrow down the issue from being plugin related or `ionic-native` related. If that variable exists in memory then we know that `ionic-native` is having trouble communicating with the plugin.

**Comment by keithdmoore** [comment]
I'm currently using ionic-native 1.2.2 and https://github.com/phonegap/phonegap-plugin-barcodescanner.git#5.0.0.  I am not seeing this issue.  I have not tried ionic-native 1.3.  Looks like 1.3 is missing this commit:  https://github.com/driftyco/ionic-native/commit/18b86e8c461d183f2a5abf33d85e3184fe57ccaa
That could be the problem.

**Comment by ihadeed** [comment]
You're right @keithdmoore .. Thanks for pointing it out!

**Comment by ihadeed** [comment]
@elluminatte please update to `ionic-native@1.3.1` and let me know if you still have issues.

**Comment by elluminatte** [comment]
@ihadeed i'm on ionic-native@1.3.1 now and get this error: "PushNotification is not defined" in my app.bundle.js. But i don't import or use push plugin anywhere

**Comment by elluminatte** [comment]
i've commented "__metadata('design:returntype', PushNotification)" line in my app.bundle.js (as ad-hoc solution for PushNotification problem) and tried to scan barcode. I get this error in console:
```bash
Native: tried calling BarcodeScanner.scan, but the BarcodeScanner plugin is not installed.
Install the BarcodeScanner plugin: 'ionic plugin add phonegap-plugin-barcodescanner'
```
Typing 
```js
cordova.plugins.barcodeScanner
```
in console returns
```bash
TypeError: undefined is not an object (evaluating 'cordova.plugins.barcodeScanner')
```

**Comment by elluminatte** [comment]
@keithdmoore i'm on ionic-native 1.2.2 and https://github.com/phonegap/phonegap-plugin-barcodescanner.git#5.0.0 now and i still get this error.

**Comment by elluminatte** [comment]
this is my code for Camera plugin test:
```js
import {Component} from "@angular/core";
import {Page, Platform, Alert, NavController} from 'ionic-angular';
import {Camera} from 'ionic-native';


@Component({
  templateUrl: 'build/pages/home/home.html'
})
export class HomePage {
  constructor(private platform: Platform, private navController: NavController) {
    this.platform = platform;
    this.navController = navController;
  }

  scan() {
    this.platform.ready().then(() => {
      let  options = {
        quality : 75
      };
      Camera.getPicture(options).then((imageData) => {
        let base64Image = "data:image/jpeg;base64," + imageData;
      }, (err) => {
      });
    });
  }
}
```
As you can see, its equal to BarcodeScanner sample, but this example works perfect. What's wrong with BarcodeScanner?

**Comment by elluminatte** [comment]
Hi there
I got this issue when i was trying to run my app in Phonegap Developer App (is it bug?).
Barcode scanner plugin and wrapper work perfectly if app is built for some platform.
Thanks for help!

**Comment by luckylooke** [comment]
I came to same problem with ionic 2.2.1.. I have to put manualy a barcodescanner entry into config.xml like I have mentioned [here](https://github.com/driftyco/ionic-native/issues/651#issuecomment-288991987) in #651

**Comment by mrqc** [comment]
I had the problem, that i called the scan method in the ionViewCanEnter() of my root controller and it seemed that the plugin was not read at this time to start.
