### ISSUE TITLE
Push Plugin: Add `clearAllNotifications` method and return promises/observables

### ISSUE THREAD

**Issue by FdezRomero** [driftyco/ionic-native#250]
Hey there!

I started using the Push plugin and noticed that is missing the newer [clearAllNotifications](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushclearallnotificationssuccesshandler-errorhandler---ios-android-only) method.

I also noticed that the ionic-native wrapper is using the plugin's success and error callbacks instead of returning a promise/observable as it happens with most of the other plugins, which is confusing considering the docs say plugins return either of these.

Any chance to add this missing method and use promises/observables instead of callbacks? I'm guessing there are people already using this plugin so it should keep supporting the callbacks and return a promise/observable if none is specified.

Thanks!

**Comment by ihadeed** [comment]
Hey,

Thanks for pointing it out.

We will have to rewrite the Push plugin using the `@CordovaInstance` wrapper in order to achieve that functionality. I guess we can add that to the road map (no set date, though).

**Comment by FdezRomero** [comment]
Thanks @ihadeed! Looking forward to it as many apps use this plugin.

**Comment by FdezRomero** [comment]
Hi @ihadeed!

Any news on adding the missing [push.clearAllNotifications()](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushclearallnotificationssuccesshandler-errorhandler---ios--android-only) method to the Push plugin?

Thanks!

**Comment by FdezRomero** [comment]
Thanks @ihadeed! :+1:
