### ISSUE TITLE
Requiring PushNotification after upgrade to 1.3.1

### ISSUE THREAD

**Issue by chrisbenseler** [driftyco/ionic-native#251]
I have upgraded an Ionic (v2) project with ionic-angular 1.3.1
When the app is installed on the device, the following error is thrown:

> Uncaught ReferenceError: PushNotification is not defined

but this plugin has neber been added to my project. If I downgrade to 1.3.0 there's no error.

inic info:

> Cordova CLI: 6.1.1
> Gulp version:  CLI version 3.9.1
> Gulp local:   Local version 3.9.1
> Ionic Version: 2.0.0-beta.9
> Ionic CLI Version: 2.0.0-beta.23
> Ionic App Lib Version: 2.0.0-beta.13
> OS: Distributor ID:	LinuxMint Description:	Linux Mint 17.3 Rosa 
> Node Version: v5.7.0

**Comment by ihadeed** [comment]
Sorry about that, `tsconfig` was miss configured. Just release 1.3.2, please update your project and let me know if you are still experiencing issues.

**Comment by chrisbenseler** [comment]
@ihadeed updated, it's ok now! :-)
