### ISSUE TITLE
Use GoogleMaps js api as fallback in browser

### ISSUE THREAD

**Issue by fmsouza** [driftyco/ionic-native#253]
In my use case, I had to stop using the `ionic serve` command because my main interaction was to avigate from a search view to a map view. When I click in the option to go to the map, the application stops because `window.plugin is not defined`.

I think it would be very useful for those cases to be able to use GoogleMaps javascript API as a fallback when the native maps plugin is not available.

**Comment by ihadeed** [comment]
Hey there,

I agree, we should have some sort of fallback or error handling so you can continue to develop your app using the serve feature.

We can easily let it process the function only if the plugin is defined (which is how other `ionic-native` plugins work). As for your suggestion (having a JS fallback), I'm not so sure if it will be compatible that way. We have to make sure that the method names match a 100% for it to be an easy process. Also, since the plugin uses native SDK, it will require the user to load the Google Maps JavaScript library in order for it to work.

**Comment by fmsouza** [comment]
Unfortunately, the js and Android libs are a little different since the beginning, in terms of methods and namings. Some methods  AFAIK it would be a very manual work to get it done making sure everything is working alright, but it's possible like in this example:

```javascript
// native plugin

var mapDiv = document.getElementById("map_canvas");
var mapConfig = {
  'backgroundColor': 'white',
  'mapType': plugin.google.maps.MapTypeId.HYBRID
};

var map = plugin.google.maps.Map.getMap(mapDiv, mapConfig);
```

```javascript
// js web library

var mapDiv = document.getElementById("map_canvas");
var mapConfig = {
  center: {lat: -34.397, lng: 150.644},
  scrollwheel: false,
  zoom: 8
};
var map = new google.maps.Map(mapDiv, mapOptions);
```

If you keep the work based on `Promises` and `Observables`, as it is being done in the current `ionic-native` module implementation, I think it can be abstracted without much effort.

But about the need to load the Google Maps js lib, I believe (not completely sure) the lib can be imported right from the module code dynamically, just like it's done for Facebook and Google Analytics libs, for example. In those cases, I've already had an experience involving importing a js lib right after instantiating a class. I'll test it soon to ensure my words and will attach a snippet with the example here if I succeeed.

**Comment by ihadeed** [comment]
I opened an issue with the plugin's developers and they said they want to keep their focus on native SDKs  and they're not interested in adding JavaScript fallback. 

This sort of functionality isn't something that suits the purpose of `ionic-native` either. I think it has to be a separate wrapper with it's own NPM package that depends on ionic-native (or not).

I think the idea is doable and I do think that it is useful, at least for development purposes.
