### ISSUE TITLE
File.listDir doesn't work on Android 4.4

### ISSUE THREAD

**Issue by teledemic** [driftyco/ionic-native#254]
Seems fine on newer devices / emulators, but my 4.4 test device and 4.4 emulator both fail. I get a promise catch with just the object { "code": "JSON error }

I am accessing the cordova plugin directly to get the cache directory. My call looks like this:
```
File.listDir(cordova.file.cacheDirectory, "slides").then(list => {
  //do stuff with list
}).catch(err => {
  //receives err = { "code": "JSON error } in Android 4.4
}
```

Happens on ionic-native 1.2.4 and 1.3.2

**Comment by ihadeed** [comment]
File plugin is currently being rewritten. This issue should be resolved once the new plugin wrapper is released. I'll keep this open so you get notified when the plugin is published.
