### ISSUE TITLE
SafariViewController.show not working

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic-native#255]
I can't make SafariViewController.show method to work. Here's the stacktrace I copied from Xcode : 

> 2016-06-29 22:14:25.587 Metho2[4452:1399806] EXCEPTION: Error: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'util_1.get(window, pluginObj.pluginRef)[methodName].apply')
2016-06-29 22:14:25.587 Metho2[4452:1399806] ERROR: EXCEPTION: Error: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'util_1.get(window, pluginObj.pluginRef)[methodName].apply')
2016-06-29 22:14:25.588 Metho2[4452:1399806] ERROR: STACKTRACE:
2016-06-29 22:14:25.588 Metho2[4452:1399806] ERROR: resolvePromise@file:///var/containers/Bundle/Application/AD54A78C-CB17-4BC3-BD71-198F577E9A17/Metho2.app/www/build/js/zone.js:538:41
ZoneAwarePromise@file:///var/containers/Bundle/Application/AD54A78C-CB17-4BC3-BD71-198F577E9A17/Metho2.app/www/build/js/zone.js:587:32
getPromise@file:///var/containers/Bundle/Application/AD54A78C-CB17-4BC3-BD71-198F577E9A17/Metho2.app/www/build/js/app.bundle.js:89142:27
wrapPromise@file:///var/containers/Bundle/Application/AD54A78C-CB17-4BC3-BD71-198F577E9A17/Metho2.app/www/build/js/app.bundle.js:89159:23
file:///var/containers/Bundle/Application/AD54A78C-CB17-4BC3-BD71-198F577E9A17/Metho2.app/www/build/js/app.bundle.js:89267:31
value@file:///var/containers/Bundle/Application/AD54A78C-CB17-4BC3-BD71-198F577E9A17/Metho2.app/www/build/js/app.bundle.js:89317:66
SourceModalBookPage@file:///var/containers/Bundle/Application/AD54A78C-CB17-4BC3-BD71-198F577E9A17/Metho2.app/www/build/js/app.bundle.js:1053:61
createInternal
create@file:///var/containers/Bundle/Application/AD54A78C-CB17-4BC3-BD71-198F577E9A17/Metho2.app/www/build/js/app.bundle.js:34584:35
create@file:///var/containers/Bundle/Application/AD54A78C-CB17-4BC3-BD71-198F577E9A17/Metho2.app/www/build/js/app.bundle.js:34796:48
create@file:///var/containers/Bundle/Application/AD54A78C-CB17-4BC3-BD71-198F577E9A17/Metho2.app/www/build/js/app.bundle.js:33813:42
createComponent@file:///var/containers/Bundle/Application/AD54A78C-CB17-4BC3-BD71-198F577E9A17/Metho2.app/www/build/js/app.bundle.js:35004:51
file:///var/containers/Bundle/Application/AD54A78C-CB17-4BC3-BD71-198F577E9A17/Metho2.app/www/build/js/app.bundle.js:58473:62
invoke@file:///var/containers/Bundle/Application/AD54A78C-CB17-4BC3-BD71-198F577E9A17/Metho2.app/www/build/js/zone.js:323:34
onInvoke@file:///var/containers/Bundle/Application/AD54A78C-CB17-4BC3-BD71-198F577E9A17/Metho2.app/www/build/js/app.bundle.js:40038:47
invoke@file:///var/containers/Bundle/Application/AD54A78C-CB17-4BC3-BD71-198F577E9A17/Metho2.app/www/build/js/zone.js:322:43
run@file:///var/containers/Bundle/Application/AD54A78C-CB17-4BC3-BD71-198F577E9A17/Metho2.app/www/build/js/zone.js:216:50
file:///var/containers/Bundle/Application/AD54A78C-CB17-4BC3-BD71-198F577E9A17/Metho2.app/www/build/js/zone.js:571:61
invokeTask@file:///var/containers/Bundle/Application/AD54A78C-CB17-4BC3-BD71-198F577E9A17/Metho2.app/www/build/js/zone.js:356:43
onInvokeTask@file:///var/containers/Bundle/Application/AD54A78C-CB17-4BC3-BD71-198F577E9A17/Metho2.app/www/build/js/app.bundle.js:40029:51
invokeTask@file:///var/containers/Bundle/Application/AD54A78C-CB17-4BC3-BD71-198F577E9A17/Metho2.app/www/build/js/zone.js:355:55
runTask@file:///var/containers/Bundle/Application/AD54A78C-CB17-4BC3-BD71-198F577E9A17/Metho2.app/www/build/js/zone.js:256:58
drainMicroTaskQueue@file:///var/containers/Bundle/Application/AD54A78C-CB17-4BC3-BD71-198F577E9A17/Metho2.app/www/build/js/zone.js:474:43
g@file:///var/containers/Bundle/Application/AD54A78C-CB17-4BC3-BD71-198F577E9A17/Metho2.app/www/build/js/es6-shim.min.js:11:1440
file:///var/containers/Bundle/Application/AD54A78C-CB17-4BC3-BD71-198F577E9A17/Metho2.app/www/build/js/es6-shim.min.js:11:1370
promiseReactionJob@[native code]
2016-06-29 22:14:25.590 Metho2[4452:1399806] ERROR: Unhandled Promise rejection: undefined is not an object (evaluating 'util_1.get(window, pluginObj.pluginRef)[methodName].apply') ; Zone: angular ; Task: Promise.then ; Value: TypeError: undefined is not an object (evaluating 'util_1.get(window, pluginObj.pluginRef)[methodName].apply')
2016-06-29 22:14:25.590 Metho2[4452:1399806] ERROR: error JSON.stringify()ing argument: TypeError: JSON.stringify cannot serialize cyclic structures.

This happens after calling : 
```js
SafariViewController.isAvailable().then(avail => {
      if (avail) {
        SafariViewController.show({
          url: this.url
        });
      }
    });
```

I debugged `isAvailable` is not the problem.

**Comment by ihadeed** [comment]
Just noticed a few mistakes with the wrapper.

Please update to `ionic-native@1.3.5` and try again.

**Comment by F1ow** [comment]
Thanks @ihadeed, works for me!

**Comment by ihadeed** [comment]
thanks for your feedback @F1ow 

I will close this for now. Let me know if you're still having issues @Bouzmine
