### ISSUE TITLE
Printer plugin doesn't work

### ISSUE THREAD

**Issue by ramoncarreras** [driftyco/ionic-native#256]
Hi, 
I'm trying to use Printer plugin with no luck. I'm using this code:
```
Printer.print('<h1>HELLO WORLD</h1>')
    .then(
        () => console.log('success Print'),
        (err) => console.log('error Print', err)
     );
```

xCode shows me this error:
> 2016-06-30 16:04:56.317 myapp[267:58628] -[NSNull objectForKey:]: unrecognized selector sent to instance 0x392cb9e0
> 2016-06-30 16:04:56.318 myapp[267:58628] *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: -[NSNull objectForKey:]: unrecognized selector sent to instance 0x392cb9e0

I'm using ionic-native version 1.3.1

My system information:

> Cordova CLI: 6.2.0
> Gulp version:  CLI version 1.2.1
> Gulp local:   Local version 3.9.1
> Ionic Framework Version: 2.0.0-beta.10
> Ionic CLI Version: 2.0.0-beta.32
> Ionic App Lib Version: 2.0.0-beta.18
> ios-deploy version: 1.8.6 
> ios-sim version: 5.0.8 
> OS: Mac OS X El Capitan
> Node Version: v5.11.1
> Xcode version: Xcode 7.3 Build version 7D175

**Comment by ihadeed** [comment]
Hey there,

This issue looks like a problem with the plugin itself, not the wrapper we created.

I suggest you post your issue at the plugin's repository instead.

**Comment by ramoncarreras** [comment]
Ok @ihadeed. Thanks!
