### ISSUE TITLE
Add the options argument for BarcodeScanner.scan() method

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#260]
_From @andreafoorlan on July 1, 2016 10:22_

BarcodeScanner native component is based on phonegap-plugin-barcodescanner plugin, which accepts an object of options as argument in its scan method in order to change the default camera selected and a bunch of other settings.

It would be nice to have the same chance in Ionic 2:

BarcodeScanner.scan({..options passed to native plugin scan method...}).then(...)

_Copied from original issue: driftyco/ionic#7156_

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this is an issue with Ionic-Native and not the ionic framework i will be moving this issue over to that repo. Thanks for using Ionic!

**Comment by ihadeed** [comment]
This already exists.

**Comment by andreafoorlan** [comment]
Please update the documentation too, if it already exists:
http://ionicframework.com/docs/v2/native/barcode-scanner/

Thank you for your support, 
Andrea

**Comment by ihadeed** [comment]
@andreafoorlan Just pushed a commit, it will be visible on the next docs update

**Comment by andreafoorlan** [comment]
Thank you :)
