### ISSUE TITLE
Google Maps Cannot be load on after navController.push()

### ISSUE THREAD

**Issue by lthh89vt** [driftyco/ionic-native#266]
Hi.

I'm having issue with getting GoogleMap to display, so not sure if I did anything wrong.

If I set the GoogleMap Component to be root page, it works fine.
But as soon as I put it part of sub page so people have to navigate to it, it stopped working

navController.push(GoogleMapPage);

GoolgeMap is loaded afterViewInit

Have tried GapDebug and it seems to does something, however, it stopped after settings the background-color to rgba(0,0,0,0) on <div id='map'></div>

Any hint would be very appreciated!!!!

**Comment by lthh89vt** [comment]
I've found out what happen.

The Native Google Maps seems to display on root element so all the pages has to set to `background-color: rgba(0,0,0,0)` to make all element transparent in order to show the map

However, after doing `navController.push(Page)` , it created 2 **ion-page** elements. The active one is transparent and the previous one is not which makes it showed on top of the google map.

So I'm fixing this by using in CSS

```
ion-nav ion-page.show-page {
  visibiliy: hidden
}
ion-nav ion-page.show-page:last-of-type {
  visibility: visible
}
```

Hope it will help someone.

**Comment by CardosoGit** [comment]
Which version of  ionic you used? I also have this problem, but with native maps.

**Comment by lthh89vt** [comment]
My ionic version is 2.0.0-beta.32

And I thought this GoogleMap Plugin is also using Native Maps. ^_^

**Comment by CardosoGit** [comment]
@lthh89vt could you quote the Ionic Info?

**Comment by CardosoGit** [comment]
My problem is with the tabs.

**Comment by lthh89vt** [comment]
Oopps. Sorry, here it is!

```
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS:
Node Version: v4.4.5
```

I guessed tab will be the same as multiple pages.

The way I work it out is using [GapDebug](https://www.genuitec.com/products/gapdebug/) to see which HTML Elements are there, then found multiple `ion-page` which some doesn't have `background-color: rgba(0,0,0,0)`
tab might use `ion-tabs` and `ion-tab` instead
