### ISSUE TITLE
Uncaught ReferenceError: plugin is not defined when reopening app

### ISSUE THREAD

**Issue by fmsouza** [driftyco/ionic-native#269]
I'm running an app which has a native `Google Maps` instance loaded in a secondary screen.

I first open it, it runs very well.
Then I press "back button" until it closes. Ok.
When I try to open the app again, it blows up with the following error in the console:

```
07-04 23:35:04.626 16199 16199 I chromium: [INFO:CONSOLE(84012)] "Uncaught ReferenceError: plugin is not defined", source: file:///android_asset/www/build/js/app.bundle.js (84012)
07-04 23:35:04.791 16199 16199 I chromium: [INFO:CONSOLE(78470)] "DEVICE READY FIRED AFTER", source: file:///android_asset/www/build/js/app.bundle.js (78470)
```

I checked the file `app.bundle.js` in the line `84012`, as mentioned in the console, and it is the one which instantiates `plugin.google.maps.LatLng` class in the following code:
```javascript
var GoogleMapsLatLng = (function () {
    function GoogleMapsLatLng(lat, lng) {
        this.lat = lat;
        this.lng = lng;
        this._objectInstance = new plugin.google.maps.LatLng(lat, lng); // this line, 84012
    }

    ...

}());
exports.GoogleMapsLatLng = GoogleMapsLatLng;
```

Also, as displayed in the log, it seems that the plugin is trying to be inited before the platform is ready on the device.

## Dependencies

```json
  "dependencies": {
    "@angular/common": "2.0.0-rc.3",
    "@angular/compiler": "2.0.0-rc.3",
    "@angular/core": "2.0.0-rc.3",
    "@angular/platform-browser": "2.0.0-rc.3",
    "@angular/platform-browser-dynamic": "2.0.0-rc.3",
    "@angular/http": "2.0.0-rc.3",
    "es6-shim": "0.35.0",
    "ionic-angular": "2.0.0-beta.10",
    "ionic-native": "1.2.4",
    "ionicons": "3.0.0",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "0.6.12"
  },
```

## ionic info
```
Cordova CLI: 6.2.0
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v6.2.2
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by fmsouza** [comment]
Project's source code: https://github.com/RioBus/ionic

**Comment by ihadeed** [comment]
Hey there,

According to your stack trace it looks like the ondeviceready fired 165ms after your code tried creating a latlng instance. 

My best guess is that `plugin` wasn't defined yet and your app tried calling it. 

Can you find out where that method is called and wrap it with a `platform.onReady().then(..)` .. or just the usual `ondeviceready` event listener. 

Let me know if the issue is from the usage or from the way the wrapper is written.

Thanks

**Comment by fmsouza** [comment]
I think it may be a problem in the wrapper, because this is the flow of the app:

1. Load the Search view, which has components which leads to the map view with data when clicked.
2. When the map view is loaded (always with data) it displays a map component with the markers.

The error explodes when the app is opened after I close it with `backbutton`, which always happens when my displayed view is the Search view, which is always the stack root. This flow blows:

1. Open the app. I'm in search view. Nothing about maps here.
2. `backbutton` and close the app.
3. Open the app without clean it from 'recents'. It should open the search view, but it explodes the mentioned error in the console while in the splashscreen.

**Comment by fmsouza** [comment]
I just did some more testing in my code to check your suggestions and make sure the problem is not my code. I did some logs in every place I was using the `LatLng` plugin through `ionic-native` to identify where were the code going through in my flow, to discover if it was being accessed before expected in my code and none of the places I placed `console.log`s were executed when the app was opened.

**Comment by ihadeed** [comment]
Can you recreate the issue using the plugin's original methods? 

If the issues are still happening, then it could be a problem with Angular2/Ionic, we might need to place some code in the `OnInit` or `AfterViewChecked` ...

If the issues don't occur using the plugin's original API then I think we can be certain that it's an ionic-native issue.
