### ISSUE TITLE
Docs Audit

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic-native#271]
Currently docs need a lot of attention. 
There's a lot of extra classes that are getting parsed as docs that shouldn't be

Contacts plugin for example 
https://github.com/driftyco/ionic-native/commit/38cea9da27600d5338203efb005ef6a29d4a378d

And the google maps plugin.
- [x] go through code base and properly format docs. If they don't need any documentation, add the `@private` tag to them. Only thing that should have docs are classes with `@Plugin`
- [ ] Make sure that parameters and returns are typed and have a detailed descriptions
- [x] Move inline code examples to either `@usage` or `@advanced` tags.

cc @ihadeed

**Comment by ihadeed** [comment]
Adding `@private` in the docs is causing the IDE to think that the property/method is actually private. Can we think of an alternative?

**Comment by mhartington** [comment]
Hmm, it shouldn't be doing that. 

```javascript
/**
 * @private
 */
static methodName(){}
```

All this does is tells dgeni, the docs parser to not generate documentation for this method. It shouldn't actually change the method.

**Comment by ihadeed** [comment]
It doesn't change the method, but when the IDE checks the JSDocs it thinks
that the method is private.

Regards,
*Ibrahim Hadeed*
(647) 624-5170

-

*DISCLAIMER: *This email and any files transmitted with it are confidential
and intended solely for the use of the individual or entity to whom they
are addressed. If you have received this email in error please notify the
system manager. This message contains confidential information and is
intended only for the individual named. If you are not the named addressee
you should not disseminate, distribute or copy this e-mail. Please notify
the sender immediately by e-mail if you have received this e-mail by
mistake and delete this e-mail from your system. If you are not the
intended recipient you are notified that disclosing, copying, distributing
or taking any action in reliance on the contents of this information is
strictly prohibited.

**Comment by mhartington** [comment]
Which IDE? Let me test it out.

**Comment by ihadeed** [comment]
Using webstorm heere



-

*DISCLAIMER: *This email and any files transmitted with it are confidential
and intended solely for the use of the individual or entity to whom they
are addressed. If you have received this email in error please notify the
system manager. This message contains confidential information and is
intended only for the individual named. If you are not the named addressee
you should not disseminate, distribute or copy this e-mail. Please notify
the sender immediately by e-mail if you have received this e-mail by
mistake and delete this e-mail from your system. If you are not the
intended recipient you are notified that disclosing, copying, distributing
or taking any action in reliance on the contents of this information is
strictly prohibited.

**Comment by beders** [comment]
Also consider adding #446

**Comment by ehorodyski** [comment]
How does one go about requesting updating the [IonicNative](https://ionicframework.com/docs/v2/native/) documentation? I thought it was built automatically through comments, but maybe it isn't?

**Comment by ihadeed** [comment]
@ehorodyski the docs are rendered from the comments, that specific page you linked to is part of the `ionic-site` repo.

**Comment by ehorodyski** [comment]
@ihadeed - Thank you. After looking at that repo I now understand.
