### ISSUE TITLE
ionic 4 camera

### ISSUE THREAD

**Issue by bibhu-padhy** [driftyco/ionic-native#2735]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
when i took a picture it always shows a broken img .i tried with the ionic3 with the same code its working im getting the image but not working with the ionic 4

**Comment by giacomocerquone** [comment]
The template you saw when you submitted this issue aren't there for glory. Can you please describe better your problem? With code maybe?
