### ISSUE TITLE
Social Sharing plugin has incorrect return values

### ISSUE THREAD

**Issue by rtomchinsky** [driftyco/ionic-native#275]
The SocialSharing class has `void` return type for `share` and `shareViaTwitter`, instead of the expected `Promise<any>`, which breaks code using TypeScript. Is there a reason for this or is it a bug?

https://github.com/driftyco/ionic-native/blob/master/src/plugins/socialsharing.ts#L34
https://github.com/driftyco/ionic-native/blob/master/src/plugins/socialsharing.ts#L64

**Comment by ihadeed** [comment]
thanks for pointing it out!
