### ISSUE TITLE
Network plugin, unnecessary Connection class? 

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic-native#278]
Not sure why the network plugin as a connection class.

Safe the say, it can be removed

https://github.com/driftyco/ionic-native/blob/master/src/plugins/network.ts#L79

**Comment by keithdmoore** [comment]
It's necessary.  To determine the connection type

**Comment by keithdmoore** [comment]
Please back out the commit

**Comment by keithdmoore** [comment]
Did you not look at the sample code?

**Comment by mhartington** [comment]
Yes I saw the sample, but it just doesn't seem necessary. 

The current implementation requires an extra class import, but you don't need it.

**Comment by keithdmoore** [comment]
it's necessary if you want to see what kind of connection you have.  Otherwise, it wont compile.  What is the big deal with leaving it?

**Comment by ihadeed** [comment]
I agree that it's necessary.... it's easier to type `2g` than to import `Connection` and type `Connection.CELL_2G`

**Comment by keithdmoore** [comment]
I totally disagree with this decision!  I don't like hard-coding constants that can easily be provided by the framework!

**Comment by mhartington** [comment]
Yes, @keithdmoore you have made that clear already [here](https://github.com/driftyco/ionic-native/commit/6229d4932e5c09c98781229177136f51b1ff71f1#commitcomment-18230217).

As stated, it's one less step, and isn't required to make the plugin actually work. No need for code that doesn't actually do anything other than return strings.
