### ISSUE TITLE
BackgroundMode missing cordova plugin

### ISSUE THREAD

**Issue by matheo** [driftyco/ionic-native#279]
Following: http://ionicframework.com/docs/v2/native/background-mode/

When tried to execute:
```
$ ionic plugin add de.appplant.cordova.plugin.background-mode
```
It throws:
```
Error: Registry returned 404 for GET on https://registry.npmjs.org/de.appplant.cordova.plugin.background-mode
```

Seems that we may use this:
```
$ ionic plugin add cordova-plugin-background-mode
```

**Comment by ihadeed** [comment]
The plugin we are supporting is this one here: https://github.com/katzer/cordova-plugin-background-mode

If you are having trouble pulling their npm package please open an issue at the repo link above.

**Comment by matheo** [comment]
@ihadeed yes, I know, I meant the error on the documentation.
I will open a pull request on the main `ionic` repo fixing the instructions.

**Comment by ihadeed** [comment]
Oh I see, my apologies for misunderstanding. 

The docs has to be fixed here, I will do that shortly.

**Comment by ihadeed** [comment]
Thanks again!
