### ISSUE TITLE
Add Geocoding to Google Maps plugin

### ISSUE THREAD

**Issue by GuelorEmanuel** [driftyco/ionic-native#280]
Is there any methods for cordova-plugin-googlemaps for performing Geocoding as shown here "https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Geocoder"

**Comment by ihadeed** [comment]
No I missed that functionality. Will be added later.

**Comment by GuelorEmanuel** [comment]
@ihadeed 
Thank you, how long will this take?

**Comment by ihadeed** [comment]
See https://github.com/driftyco/ionic-native/pull/292

Added it, just haven't tested it yet. Not sure how that class works.

**Comment by GuelorEmanuel** [comment]
@ihadeed 
Cool, thanks. Going to test the method and see how its goes.

**Comment by mifkys** [comment]
I tried to use this method in my Ionic-2 app:
`Geocoder.geocode(req);`
and get many errors in console:
> EXCEPTION: Error: Uncaught (in promise): ReferenceError: 'plugin' is undefined
   EXCEPTION: Error: Uncaught (in promise): ReferenceError: 'plugin' is undefined
   browser_adapter.js (77,1)
   STACKTRACE:
   browser_adapter.js (77,1)
   Error: Uncaught (in promise): ReferenceError: 'plugin' is undefined
   at resolvePromise (http://localhost:8100/build/js/zone.js:538:26)
   at ZoneAwarePromise (http://localhost:8100/build/js/zone.js:587:18)
   at Geocoder.geocode (http://localhost:8100/build/js/app.bundle.js:82532:9)
   at Anonymous function (http://localhost:8100/build/js/app.bundle.js:64:13)
   at ZoneDelegate.prototype.invoke (http://localhost:8100/build/js/zone.js:321:14)
   at onInvoke (http://localhost:8100/build/js/app.bundle.js:35145:25)
   at ZoneDelegate.prototype.invoke (http://localhost:8100/build/js/zone.js:321:14)
   at Zone.prototype.run (http://localhost:8100/build/js/zone.js:216:18)
   at Anonymous function (http://localhost:8100/build/js/zone.js:571:18)
   at ZoneDelegate.prototype.invokeTask (http://localhost:8100/build/js/zone.js:354:18)
   browser_adapter.js (77,1)

> Unhandled Promise rejection: 'plugin' is undefined ; Zone: angular ; Task: Promise.then ; Value: ReferenceError: 'plugin' is undefined
zone.js (461,14)
   "Unhandled Promise rejection:"
   "'plugin' is undefined"
   "; Zone:"
   "angular"
   "; Task:"
   "Promise.then"
   "; Value:"
   {
      [functions]: ,
      __proto__: { },
      description: "'plugin' is undefined",
      message: "'plugin' is undefined",
      name: "ReferenceError",
      number: -2146823279,
      stack: "ReferenceError: 'plugin' is undefined
   at Anonymous function (http://localhost:8100/build/js/app.bundle.js:82533:13)
   at ZoneAwarePromise (http://localhost:8100/build/js/zone.js:584:30)
   at Geocoder.geocode (http://localhost:8100/build/js/app.bundle.js:82532:9)
   at Anonymous function (http://localhost:8100/build/js/app.bundle.js:64:13)
   at ZoneDelegate.prototype.invoke (http://localhost:8100/build/js/zone.js:321:14)
   at onInvoke (http://localhost:8100/build/js/app.bundle.js:35145:25)
   at ZoneDelegate.prototype.invoke (http://localhost:8100/build/js/zone.js:321:14)
   at Zone.prototype.run (http://localhost:8100/build/js/zone.js:216:18)
   at Anonymous function (http://localhost:8100/build/js/zone.js:571:18)
   at ZoneDelegate.prototype.invokeTask (http://localhost:8100/build/js/zone.js:354:18)"
   }

> Error: Uncaught (in promise): ReferenceError: 'plugin' is undefined
zone.js (463,10)
   {
      [functions]: ,
      __proto__: { },
      description: "Uncaught (in promise): ReferenceError: 'plugin' is undefined",
      message: "Uncaught (in promise): ReferenceError: 'plugin' is undefined",
      name: "Error",
      promise: { },
      rejection: { },
      stack: "Error: Uncaught (in promise): ReferenceError: 'plugin' is undefined
   at resolvePromise (http://localhost:8100/build/js/zone.js:538:26)
   at ZoneAwarePromise (http://localhost:8100/build/js/zone.js:587:18)
   at Geocoder.geocode (http://localhost:8100/build/js/app.bundle.js:82532:9)
   at Anonymous function (http://localhost:8100/build/js/app.bundle.js:64:13)
   at ZoneDelegate.prototype.invoke (http://localhost:8100/build/js/zone.js:321:14)
   at onInvoke (http://localhost:8100/build/js/app.bundle.js:35145:25)
   at ZoneDelegate.prototype.invoke (http://localhost:8100/build/js/zone.js:321:14)
   at Zone.prototype.run (http://localhost:8100/build/js/zone.js:216:18)
   at Anonymous function (http://localhost:8100/build/js/zone.js:571:18)
   at ZoneDelegate.prototype.invokeTask (http://localhost:8100/build/js/zone.js:354:18)",
      task: { },
      zone: { }
   }

**Comment by mifkys** [comment]
On android amulator (genymotion) with enabled gps this code 
`this.platform.ready().then(() => {
			let req = {
				'position': {
					'lat': 55.75,
					'lng': 38.87
				}
			}
			Geocoder.geocode(req).then((resp) => {console.log(resp)})
		});`
return empty array

**Comment by sudharsanmit** [comment]
The class is wrongly named. It should be reverseGeocoder and not geocoder. Also, will it not be better to have it standalone or coupled with Geolocation since it Geolocation) doesn't need a plugin installed and will work both in web and device eventhough being native? You can support multiple providers for reverse geocode if standalone.

**Comment by mgarciadash** [comment]
Hello,
Could you showme an example of Geocoding for IONIC 2, been trying without success.

Thanks in advance.

**Comment by mifkys** [comment]
```
import { Geocoder, Geolocation } from 'ionic-native';
export class HomePage {
...
	getUserLocation () {
		// Определяем текущие координаты
		this.platform.ready().then(() => {
			Geolocation.getCurrentPosition({timeout: 3000}).then(
				(resp) => {
					let req = {
						position: {
							lat: resp.coords.latitude,
							lng: resp.coords.longitude
						}
					}
					// Определяем название города
					Geocoder.geocode(req).then(
						(res) => {
							// do something
						}
					);
				}, 
				(err) => {
				}
			);
		});
	}
...
}
```

**Comment by mgarciadash** [comment]
Thank You for your quick answer.

I copied and paste your example but didnt work.

In getCurrentPosition() im getting empty error {}  (then not enter to Geocoder section)

And isolate geocode() returns emty array  []

this.platform.ready().then(() => {
	let req = {
		position: {
			lat: 40.7127837,
			lng: -74.00594130000002
		}
	}
	Geocoder.geocode(req).then(
		(res) => {
			console.log(res);
		}
	);
});


Tensting on Device (Android 6.0.1)
Environment:  Ionic  2.1.14, node v7.2.1, cordova  6.4.0

**Comment by mifkys** [comment]
I have the app in Play Market with this code and all works. Are you install cordova google maps plugin with api key?

**Comment by mgarciadash** [comment]
Yes, i've tried with:

`cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="MY_API_KEY" --variable API_KEY_FOR_IOS="MY_API_KEY"`

`ionic plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="MY_API_KEY" --variable API_KEY_FOR_IOS="MY_API_KEY"`

Even with:

`ionic plugin add https://github.com/phonegap-googlemaps-plugin/cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="MY_API_KEY" --variable API_KEY_FOR_IOS="MY_API_KEY"`

`cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="MY_API_KEY" --variable API_KEY_FOR_IOS="MY_API_KEY"`


Before, every time I run:

```
cordova plugin rm cordova-plugin-googlemaps
cordova plugin rm com.googlemaps.ios
```

**Comment by sudharsanmit** [comment]
Goelocation is already part of ionic-native module. You can see the docs
for examples too. A Cordova plugin itself will not be necessary I believe.

On Wednesday, January 11, 2017, mgarciadash <notifications@github.com>
wrote:
> Yes, i've tried with:
>
> cordova plugin add cordova-plugin-googlemaps --variable
API_KEY_FOR_ANDROID="MY_API_KEY" --variable API_KEY_FOR_IOS="MY_API_KEY"
>
> ionic plugin add cordova-plugin-googlemaps --variable
API_KEY_FOR_ANDROID="MY_API_KEY" --variable API_KEY_FOR_IOS="MY_API_KEY"
>
> Even with:
>
> ionic plugin add
https://github.com/phonegap-googlemaps-plugin/cordova-plugin-googlemaps
--variable API_KEY_FOR_ANDROID="MY_API_KEY" --variable
API_KEY_FOR_IOS="MY_API_KEY"
>
> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps
--variable API_KEY_FOR_ANDROID="MY_API_KEY" --variable
API_KEY_FOR_IOS="MY_API_KEY"
>
> Before, every time I run:
>
> cordova plugin rm cordova-plugin-googlemaps
> cordova plugin rm com.googlemaps.ios
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/8wGp6Q_etj0Y1EgbJBQtXe7-0d8jgHxiuEr7lgaXmD2xnLlur8eMdK4Vpi7-MCdknQzojtLTe_Oah40HWE4W9ee3GON4IkmX0r_dNMfaNtHHZ8Rtbo395WqcxrN9I3bV0EK9zfOZyM8hL0FjL6BWxxbbVbK-kw=s0-d-e1-ft#https://github.com/notifications/beacon/AP-IYb9_GUYHJ9gZzjj1_dL1Nw5U1nPDks5rRRIxgaJpZM4JI0Cy.gif>

**Comment by mgarciadash** [comment]
Ok, began from zero...

I removed the plugin i had with:

```
cordova plugin rm cordova-plugin-googlemaps
cordova plugin rm com.googlemaps.ios
```

Then tried and nothing.

Also i checked Enabled APIs in console.developers.google and enable:

```
- Google Maps Android API
- Google Maps Geocoding API
- Google Maps Geolocation API
- Google Maps SDK for IOS
```

And i added the plugin again using:

`cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="MY_API_KEY" --variable API_KEY_FOR_IOS="MY_API_KEY"`

And everything works now !

**Comment by mgarciadash** [comment]
Also notice that not works on emulator nor device -livereload   :O

**Comment by janand4** [comment]
@mgarciadash,  I did the same steps as mentioned above and I still get an empty array for res : this.platform.ready().then(() => {
let req = {
position: {
lat: 40.7127837,
lng: -74.00594130000002
}
}
Geocoder.geocode(req).then(
(res) => {alert(res);
}
);
});


I am running this code on iOS emulator and ionic view. How did you test out the output?

**Comment by josepena0409** [comment]
Just as an FYI for people looking at this issue. When running on an emulator, it will not work. You need to run this on your mobile device. The [Geocoder grpc fails in android studio emulator.](https://issuetracker.google.com/issues/64418751) bug has been identified.
