### ISSUE TITLE
Ionic 2, InAppBrowser.js, errors when building to Android

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#285]
_From @tomgallagher on July 9, 2016 16:50_

Hi

I'm trying to track down why it is that I cannot get the InAppBrowser to just open on single click.

I've added the plugin, and included this line:

`import {InAppBrowser} from 'ionic-native';`

then a simple InAppBrowser.open just to check. Not working.

I'm having a look at the Ionic Native source code, InAppBrowser.js, and my code editor is highlighting 2 errors in the code at:

line 5 - expected a conditional and saw an assignment
`else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;`

line 26 - InAppbrowser is a function
`InAppBrowser = __decorate([`

I'm new to Ionic, and to betas in general, but I thought I should report this as I can't get it to work.

Tom

_Copied from original issue: driftyco/ionic#7254_

**Comment by jgw96** [comment]
Hello! As this is an issue with ionic-native and not the ionic framework I will be moving this issue to that repo. Welcome to the world of Ionic!

**Comment by ihadeed** [comment]
We would need more data to work with here. Such as a more detailed stack trace and maybe steps to reproduce.

I think it's worth mentioning that you need to wrap all method calls with `ondeviceready` event listener. Which is `platform.onReady().then(()=> { ... })` in ionic 2

**Comment by tomgallagher** [comment]
Hi thanks very much for getting back.

Do you mean:

`import {Platform} from 'ionic-angular';`
`this._platform.ready().then( () => { 
        this.win = InAppBrowser.open("http://www.google.com", "_blank", "location=true");
    });`

I'm going to struggle producing a stack trace as I'm developing on Cloud9 and can only test by compiling an apk and uploading it to a device.

Are there any working examples of InAppBrowser around that you know of?

I just need to make sure I'm doing stuff right at the basic level.

Thanks 

Tom

**Comment by tomgallagher** [comment]
So is this the right basic approach with Ionic 2 native?

`this._platform.ready().then( () => { 
                
         InAppBrowser.open( "http://www.google.com", "_blank", "EnableViewPortScale=yes" ).then( () => { 
                  console.log('browser open');
         });
                
});`

**Comment by tomgallagher** [comment]
OK - this issue was causing me problems.

https://github.com/driftyco/ionic-cli/issues/359

Could you still let me know if the above syntax is right? So should the InAppBrowser be in an Observable?

**Comment by tomgallagher** [comment]
And the answer to whether it should be in an observable is no.

At the moment, there only seems to be the single InAppBrowser.open command. the Cordova plugin has event listeners and execute script? Can I access these functions? If not, is there any chance these could be added to ionic native?

**Comment by ihadeed** [comment]
Here's the syntax:

```typescript
import {InAppBrowser, InAppBrowserRef} from 'ionic-native';

...

let browser: InAppBrowserRef = InAppBrowser.open(url, target, options);
browser.show();
browser.close();
browser.addEventListener(type, callback);
browser.executeScript(script, callback);
browser.insertCSS(script, callback);
```

This plugin will be rewritten soon to provide better and more complete functionality. The new version of the wrapper will eliminate all callbacks and replace them with Promises instead.

**Comment by tomgallagher** [comment]
Thanks very much for your help. I'd never have sorted that out on my own.

I'm sorry to say I'm not using Typescript yet.

This OK for JS?

`InAppBrowserRef = InAppBrowser.open( this.homeURL, "_blank", "EnableViewPortScale=yes" );
this.browser = InAppBrowserRef;`

**Comment by tomgallagher** [comment]
Hi again

`Error in Success callbackId: InAppBrowser328033122 : TypeError: Cannot call method 'executeScript' of undefined cordova.js?ionicCachebuster=2199:312
Uncaught TypeError: Cannot call method 'executeScript' of undefined`

I'm trying to execute a remote script, then execute a piece of code in the callback, like this:

`this.homeURL = this._currentUserData.getUserHomeURL();     
InAppBrowserRef = InAppBrowser.open( this.homeURL, "_blank", "EnableViewPortScale=yes" );
this.browser = InAppBrowserRef;`
                
Once the InAppBrowser finishes loading, on each page, load remote script that collects web address and puts it in the browser's local storage:

 `this.browser.addEventListener( "loadstop", function() { this.browser.executeScript( { file:  "mysiteURL/mobileClick.js" }, function() { console.log("Mobile Click loaded"); });`

Start an interval to check the contents of local storage for the relevant address and return to the model.

`window.checkStart = setInterval( function() { this.browser.executeScript( {  code: "window.localStorage.getItem('address')" }, function( value ) { console.log("Entering Storage Check Loop"); var signal = value[0]; if (signal !== "") { this.browser.executeScript( { code: "window.localStorage.getItem('address')" }, function( value ) { this.task.address = value[0] });  } });                 
}, 200); );`

Sorry about the formatting...

Does that look OK to you? I've tested the code in a browser environment and it was all fine.

Thanks for the help.

Tom

**Comment by tomgallagher** [comment]
So the problem I'm having is defining the browser in plain Javascript in such a way that I can reference it later. I've usually managed this by defining it in the constructor but that's not working.

Any help gratefully received...

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
