### ISSUE TITLE
Adding PinDialog plugin to ionic-native

### ISSUE THREAD

**Issue by tamerbak** [driftyco/ionic-native#286]
Is there any intention to add this plugin (http://ngcordova.com/docs/plugins/pinDialog/) to ionic-native ?

**Comment by tamerbak** [comment]
Thank you @ihadeed

**Comment by tamerbak** [comment]
@ihadeed how to implement the last version of ionic-native with this modification ? I'm on the last version 1.3.4 but can not see the plugin...

**Comment by ihadeed** [comment]
It's not published yet. I'll publish a new release when I get a chance.

In the meanwhile you can clone the master branch, run npm install to
install dependencies.. then run "npm run build" to generate a new dist
directory.
