### ISSUE TITLE
Methods should return always a Promise, also when Cordova or the plugin is not available

### ISSUE THREAD

**Issue by Ritzlgrmft** [driftyco/ionic-native#294]
Par example, look at the method

    static getCurrentPosition(options?: GeolocationOptions): Promise<Geoposition> { return; }

It declares to return always a Promise object. But that is not true. If either Cordova or the plugin is not available, just an object with a property named `error` is returned.

I would prefer, that ionic-native returns in such a case just a rejected Promise. That would make my coding much easier. 

With the current implementation, I have to check if the returned value is really a Promise. Only then I can use methods like `then()` on it. Otherwise I would get unexpected errors at least while testing in the browser.

**Comment by mlynch** [comment]
Good call, we should do this (surprised we didn't do that from the start...)

**Comment by ihadeed** [comment]
This should do the trick: https://github.com/driftyco/ionic-native/commit/a1f47a7e88785d9837bb5858c5af6a8ec04efad5

**Comment by ihadeed** [comment]
@Ritzlgrmft  I just checked, in case of an error it still returns a promise that rejects with the error message `plugin_not_installed` or `cordova_not_available` ..

Can you provide steps to reproduce a case where it returns back an object instead of a promise?

Thanks

**Comment by Ritzlgrmft** [comment]
I created a new Ionic project with `ionic start ... --v2 --typescript`, updated `ionic-native` to the newest version and added to platform.ready:

    try {
      IBeacon.enableDebugLogs()
        .then(() => { 
          alert('success'); 
        }).catch(reason => { 
          alert('failed: ' + reason); 
        });
    } catch (e) { 
      alert('error: ' + e); 
    }

Maybe this happens because of the sync option?

**Comment by ihadeed** [comment]
Yes it's because of the `sync` option.

The `IBeacon` plugin is kinda a special case ... the original plugin itself returns the promise, not ionic-native. So we can't really play with that, unless if we implement your suggestion in #241 which will require modifying the plugin and `plugin.ts`.

**Comment by ihadeed** [comment]
FYI: https://github.com/driftyco/ionic-native/pull/304
