### ISSUE TITLE
Add cordova-plugin-file-opener2 in ionic-native

### ISSUE THREAD

**Issue by annalyntabmore** [driftyco/ionic-native#295]
Can someone help me to add this https://github.com/pwlin/cordova-plugin-file-opener2 in ionic-native? thanks.

**Comment by ihadeed** [comment]
how is this different than `cordova-plugin-file` ?

**Comment by annalyntabmore** [comment]
I'm using it to open a file.

**Comment by ihadeed** [comment]
I understand. Aren't you able to do that using the `file` plugin? see here: 
https://github.com/driftyco/ionic-native/blob/00793fd3ff0ece518bfe99425b67c291688b34b3/src/plugins/file.ts#L290-L315

It's not merged yet, but I believe it should give you the functionality you need.

**Comment by annalyntabmore** [comment]
Ok I'm gonna try this.thank you :)

**Comment by ihadeed** [comment]
Would be great if you can download the `npm` package attached with that PR and test it.

**Comment by ghenry22** [comment]
The file plugin let's you access files directly within your app.  This lets you open files in the default system.app from.within your app.

If display an image in your app vs
Open the image in the native image gallery

Could be useful.in some scenarios to throw pdf files for example.out to a pdf reader rather than opening them in the app.

**Comment by eddyng8** [comment]
Is there a timeline on when this FileOpener2 plugin be added to ionic native? 
In the meantime, is there another way of using the plugin without ionic-native?

**Comment by ihadeed** [comment]
@eddyng8 
No timeline at the moment.

To use without Ionic Native, do the following:
1. Install plugin
2. In every page that you need to call the plugin, add this to the top of the page `declare var cordova: any;`
3. Use the plugin via `cordova.plugins.fileOpener2` variable.
