### ISSUE TITLE
Ionic Push don't work on ionic v2

### ISSUE THREAD

**Issue by Macstyg** [driftyco/ionic-native#296]
```
        var push = Push.init({
          android: {
            senderID: "my-gcm-project_number"
          },
          ios: {
            alert: "true",
            badge: true,
            sound: 'false'
          },
          windows: {}
        });
        push.on('registration', (data) => {
          this.doAlert(data.registrationId.toString());
        });
        push.on('notification', (data) => {
          console.log(data);
          alert("Hi, Am a push notification");
        });
        push.on('error', (e) => {
          console.log(e.message);
        });
```
'registration' event don't triggers on phone and data.registrationId is null.
This don't work on ionicView app and also after building .apk and run on android device. 

Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: Not installed
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v5.7.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by mhartington** [comment]
Push support for ionic 2 is still a work in progress. 

http://blog.ionic.io/ionic-platform-update/

**Comment by Macstyg** [comment]
Oh, i see. Maybe you have some expected dates?
