### ISSUE TITLE
How do I use the LatLngBounds class in Ionic 2?

### ISSUE THREAD

**Issue by CardosoGit** [driftyco/ionic-native#298]
I would like to take the center of multiple markers.

**Comment by ihadeed** [comment]
```typescript
import {GoogleMapsLatLngBounds, GoogleMapsLatLng} from 'ionic-native';

...


let southwest: GoogleMapsLatLng = new GoogleMapsLatLng(<lat>, <lng>);
let northeast: GoogleMapsLatLng = new GoogleMapsLatLng(<lat>, <lng>);

let bounds: LatLngBounds = new GoogleMapsLatLngBounds(southwest, northeast);
// do stuff with our bounds object now

```

**Comment by CardosoGit** [comment]
I can not use this way:

`var points = [
  new plugin.google.maps.LatLng(41.79883, 140.75675),
  new plugin.google.maps.LatLng(41.799240000000005, 140.75875000000002),
  new plugin.google.maps.LatLng(41.797650000000004, 140.75905),
  new plugin.google.maps.LatLng(41.79637, 140.76018000000002),
  new plugin.google.maps.LatLng(41.79567, 140.75845),
  new plugin.google.maps.LatLng(41.794470000000004, 140.75714000000002),
  new plugin.google.maps.LatLng(41.795010000000005, 140.75611),
  new plugin.google.maps.LatLng(41.79477000000001, 140.75484),
  new plugin.google.maps.LatLng(41.79576, 140.75475),
  new plugin.google.maps.LatLng(41.796150000000004, 140.75364000000002),
  new plugin.google.maps.LatLng(41.79744, 140.75454000000002),
  new plugin.google.maps.LatLng(41.79909000000001, 140.75465),
  new plugin.google.maps.LatLng(41.79883, 140.75673)
];
var latLngBounds = new plugin.google.maps.LatLngBounds(points);

map.animateCamera({
  'target' : latLngBounds
});`

**Comment by CardosoGit** [comment]
I changed the constructor in googlemap.js . Thus I can use as described in the above example.

```
function GoogleMapsLatLngBounds(arrayLatLng) {
        this._objectInstance = new plugin.google.maps.LatLngBounds(arrayLatLng);
    }
```

**Comment by ihadeed** [comment]
thanks @CardosoGit

**Comment by CardosoGit** [comment]
gratefull!

**Comment by mmazloum** [comment]
If I may, you also have the animate camera option that should be able to take a GoogleMapsLatLngBounds as target parameter as well as GoogleMapsLatLng.

Cordova maps plugin has this feature available. Am saying this in the right place or should I create a new issue ? (sorry I'm quiet new to ionic).

**Comment by arielgelbard** [comment]
has this issue been fixed? It appears CardosoGit solution was never merged...

**Comment by arielgelbard** [comment]
@mmazloum
