### ISSUE TITLE
Add cordova-plugin-nativestorage plugin

### ISSUE THREAD

**Issue by murraybauer** [driftyco/ionic-native#299]
https://github.com/TheCocoaProject/cordova-plugin-nativestorage

Currently there is only a File plugin for Ionic Native.

This plugin supports key/value storage natively for iOS & Android and has a browser fallback to HTML5 LocalStorage

There are many issues with using HTML5 LocalStorage in Cordova/mobile browsers.

Sure there are other lots of local db wrappers for indexDB, webSQL etc, but none as simple as key/value like localStorage that actually works.

There is an ng-cordova wrapper for Ionic 1, not Ionic 2 :-(

**Comment by ihadeed** [comment]
Added and is available as of ionic-native@1.3.5
