### ISSUE TITLE
Error: Uncaught (in promise): ReferenceError: plugin is not defined

### ISSUE THREAD

**Issue by KaushikRay** [driftyco/ionic-native#303]
<img width="827" alt="screen shot 2016-07-16 at 12 23 13 am" src="https://cloud.githubusercontent.com/assets/6602443/16889997/06081fbe-4aeb-11e6-9f16-59bce362a722.png">
Hello,

I have just started learning mobile technologies. Started with simple project in Ionic 2 / Ang 2

Now I am trying to use google maps plugin without success and gets the above error.

included code for import

`import {GoogleMap, GoogleMapsEvent} from 'ionic-native';`

Then in code

```
initializeApp() {
    this.platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();
      let map = new GoogleMap('google_maps');

    });
  }
```

But it always gives the above mentioned error.

My versions -

package.json
```

{
  "dependencies": {
    "@angular/common": "2.0.0-rc.3",
    "@angular/compiler": "2.0.0-rc.3",
    "@angular/core": "2.0.0-rc.3",
    "@angular/platform-browser": "2.0.0-rc.3",
    "@angular/platform-browser-dynamic": "2.0.0-rc.3",
    "@angular/http": "2.0.0-rc.3",
    "es6-shim": "^0.35.0",
    "ionic-angular": "2.0.0-beta.10",
    "ionic-native": "1.3.2",
    "ionicons": "3.0.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "^0.6.12"
  },
  "devDependencies": {
    "del": "2.2.0",
    "gulp": "3.9.1",
    "gulp-watch": "4.3.5",
    "ionic-gulp-browserify-typescript": "2.0.0",
    "ionic-gulp-fonts-copy": "^1.0.0",
    "ionic-gulp-html-copy": "^1.0.0",
    "ionic-gulp-sass-build": "^1.0.0",
    "ionic-gulp-scripts-copy": "^2.0.0",
    "ionic-gulp-tslint": "^1.0.0",
    "tslint-ionic-rules": "^0.0.3",
    "run-sequence": "1.1.5"
  },
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [
    "ios",
    {
      "platform": "ios",
      "version": "",
      "locator": "ios"
    }
  ],
  "name": "myionic2project",
  "description": "MyIonic2Project: An Ionic project"
}

```

> Installed platforms:
>   ios 4.1.1

**Ionic info**

Your system information:

> 
> Cordova CLI: 6.2.0
> Gulp version:  CLI version 3.9.1
> Gulp local:   Local version 3.9.1
> Ionic Framework Version: 2.0.0-beta.10
> Ionic CLI Version: 2.0.0-beta.32
> Ionic App Lib Version: 2.0.0-beta.18
> ios-deploy version: Not installed
> ios-sim version: 5.0.8 
> OS: Mac OS X El Capitan
> Node Version: v4.4.2
> Xcode version: Xcode 7.3.1 Build version 7D1014 

Please let me know what I am doing wrong here? THanks

**Comment by KaushikRay** [comment]
I also tried using 1.2.4 in package.json and then npm install with no use. Am I missing any dependency here?

**Comment by ihadeed** [comment]
Do you have the plugin installed? I don't see it in package.json

**Comment by KaushikRay** [comment]
Yes,, I used the command  - cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_IOS="actual key" --variable API_KEY_FOR_ANDROID="actual key". Do i need to explicitly add it to package.json.. I have changed package.json. Updated in original question

**Comment by ihadeed** [comment]
No you don't have to have it there. I was just checking.

Are you running on the browser?

One of the inconveniences of this plugin is that it doesn't have browser
fallback. You need to run it on a real device.

**Comment by KaushikRay** [comment]
Ohh I see..Can it be done in an emulator? like android avd or ios simulator?

**Comment by ihadeed** [comment]
Yes
