### ISSUE TITLE
TODO: Powermanagement Plugin (wake lock)

### ISSUE THREAD

**Issue by ihadeed** [driftyco/ionic-native#312]
https://github.com/Viras-/cordova-plugin-powermanagement

**Comment by heukirne** [comment]
option that are already in native:
- http://ionicframework.com/docs/v2/native/background-mode/
- http://ionicframework.com/docs/v2/native/insomnia/

**Comment by keithdmoore** [comment]
@heukirne what is your point with mentioning the other plugins?  I am about to need the power mgmt plugin.  I need to submit a pull request to add the ability to do a PARTIAL_WAKE_LOCK for Android.

**Comment by keithdmoore** [comment]
By the way, the http://ionicframework.com/docs/v2/native/background-mode is toxic in that the Apple App store WILL reject your app if you use it.  If you use it for Android but still support the iOS platform, you might consider removing the iOS implementation or use `plugman` and only install the Android version
