### ISSUE TITLE
getLoginStatus in Facebook plugin does not work

### ISSUE THREAD

**Issue by joshuamorony** [driftyco/ionic-native#32]
The `getLoginStatus` method for the Facebook Connect plugin does not work, however other methods (login, logout, api) do work.

### Steps to Reproduce:

1. Generate new project 
2. Set up Ionic Native `npm install ionic-native --save`
3. Set up application on developers.facebook.com
4. Install Facebook connect plugin: `ionic plugin add cordova-plugin-facebook4 --variable APP_ID="AppId" --variable APP_NAME="AppName"`
5. Import 'Facebook' and access `getLoginStatus` method.

Results in the promise rejecting with:

`{error: "plugin_not_installed"}`

and warnings:

```
[Warning] Native: tried calling Facebook.getLoginStatus, but the Facebook plugin is not installed. (app.bundle.js, line 63314)
[Warning] Install the Facebook plugin: 'cordova plugin add cordova-plugin-facebook4' (app.bundle.js, line 63319)
```

### Plugins Installed:

```
cordova-plugin-facebook4 1.6.3 "Facebook Connect"
cordova-plugin-inappbrowser 1.2.1 "InAppBrowser"
cordova-sqlite-storage 0.8.4-dev "Cordova sqlite storage plugin (core version)"
```

```
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.2
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.5
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v4.2.2
Xcode version: Xcode 7.2 Build version 7C68
```

**Comment by ihadeed** [comment]
Are you testing on device or browser?

**Comment by joshuamorony** [comment]
My mistake - was trying to call the plugin too early! (before platform.ready() had fired)
