### ISSUE TITLE
Geolocation watchPosition parameters seem incorrect

### ISSUE THREAD

**Issue by joshgarwood** [driftyco/ionic-native#322]
Hi there!

In using the Geolocation.watchPosition() method, it seems as though the ionic-native implementation of this is passing the options in as the second parameter, where the geolocation api is expecting an "onError" function.   This results in the following error:

**TypeError: Failed to execute 'watchPosition' on 'Geolocation': The callback provided as parameter 2 is not a function.**

**Comment by ihadeed** [comment]
The commit I just pushed should fix that issue.

**Comment by joshgarwood** [comment]
Great!  Will this be available in a new ionic-native build?  Or should I clone the current branch and reference it locally until a new build is released?

**Comment by ihadeed** [comment]
I'll release a new build now since we have enough updates.

**Comment by ihadeed** [comment]
Done 🎉
