### ISSUE TITLE
Camera plugin - cannot get static members

### ISSUE THREAD

**Issue by marcinwadon** [driftyco/ionic-native#325]
Static members of `Camera` class isn't accessible:
`Camera.DestinationType`, `Camera.EncodingType`, `Camera.MediaType`, `Camera.PictureSourceType`, `Camera.PopoverArrowDirection`, `Camera.Direction`

Should be public but are private by default

PR #326

**Comment by ihadeed** [comment]
The `@private` in docs just prevents the docs generator from documenting them. They are public static properties of the `Camera` class

**Comment by marcinwadon** [comment]
Thanks for the info. I'll remember

**Comment by BioPhoton** [comment]
I'm not able to use the "public properties that are private in docs" im my project.

You should remove @private in the docs. Or is there another way to be able to have autocomplete in my IDE??
