### ISSUE TITLE
TODO: Mixpanel plugin

### ISSUE THREAD

**Issue by ZiFFeL1992** [driftyco/ionic-native#327]
https://github.com/samzilverberg/cordova-mixpanel-plugin

**Comment by ihadeed** [comment]
I saw this earlier, wasn't sure if it's popular enough. 

What do they do anyways? Analytics?

**Comment by ZiFFeL1992** [comment]
Yes, we are planning to replace Google Analytics in favor of mixpanel.

**Comment by bschellekens** [comment]
Hi All,

I'm just reading this comment, but I would be fond of this integration!

**Comment by ihadeed** [comment]
The plugin was already added awhile ago.
