### ISSUE TITLE
Where to put interfaces [debate]

### ISSUE THREAD

**Issue by ZiFFeL1992** [driftyco/ionic-native#328]
After the refactor I've seen that there is a bit of 'chaos' on where to put the interfaces, some of them are on the top, others between functions and some others at the bottom.

While this keep growing we should think how to short this in order to keep this as cleaner as possible and easily maintainable.

I don't really care where to put them, maybe in our case might be better to have them at the bottom because we can use the top for description docs.

Also I can handle this when we get an agreement :)

**Comment by ihadeed** [comment]
I vote to have them at the bottom of each page. This way when people open up the declaration file they will see the plugin's docs as the first thing in there.

**Comment by ihadeed** [comment]
@ZiFFeL1992 I think we can go ahead and move all interfaces to the bottom, seems like no one has an objection.

**Comment by mhartington** [comment]
@ihadeed sounds like a plan! I'll keep a look out during the doc clean up.
