### ISSUE TITLE
Plugins missing some data

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic-native#33]
Seems some plugins are missing data, like repo url

http://ionicframework.com/docs/v2/native/AppRate/

**Comment by ihadeed** [comment]
I'll update what's missing and submit a PR.

**Comment by tlancina** [comment]
Do we need repo URL? I'm not sure what it was originally for, I think it
could probably safely removed and just documented.

**Comment by mhartington** [comment]
We can do that. It was my understanding that at some point down the road, we'd thrown an error telling the user if the plugin wasn't included and provide the necessary data on how to add it. 


If thats some ways off, for sure, we can ditch the extra info and just hardcode stuff in dgeni comments

**Comment by ihadeed** [comment]
It does throw an error if it was unable to call the pluginRef .. It would
output the value in `plugin` property if that happens.

**Comment by tlancina** [comment]
Ah yeah, for now it shows the plugin id and command to install it: https://github.com/driftyco/ionic-native/commit/c48a851d877f1ca6a8252e2af36e00f9717993f4.

Going to close, since I think for now it's good, but we can revisit this if there is a case where more info is needed for plugins.
