### ISSUE TITLE
Google Plus Support

### ISSUE THREAD

**Issue by jspenc72** [driftyco/ionic-native#330]
I would like to use this GooglePlus module:

```bash
http://ionicframework.com/docs/v2/native/google-plus/
https://github.com/driftyco/ionic-native/blob/master/src/plugins/google-plus.ts
```
however it is excluded from 1.3.7 when installed via npm 

```bash
$ npm installionic-native --save
```
and index.js seems to be empty when I install from github directly with: 

```bash
$ npm install https://github.com/driftyco/ionic-native
```

Can you provide instructions for compiling the plugins from the src or how to install the nightly build version?

**Comment by jspenc72** [comment]
Better yet, can you provide a @latest or @nightly version that would include this?

**Comment by jspenc72** [comment]
Was able to get this working by 
1. cloning the repo
2. run npm install to add dependencies
3. run npm run build
4. copy the contents of dist folder created in step 3 to ./node_modules/ionic-native/

Hopefully this helps someone.

**Comment by ZiFFeL1992** [comment]
https://github.com/driftyco/ionic-native/blob/master/DEVELOPER.md#testing-your-changes

**Comment by ihadeed** [comment]
I double checked, it is being exported. Not sure why you're not able to import it.

Update to `ionic-native@1.3.8` and let me know if you still have issues.
