### ISSUE TITLE
sqlite best practice

### ISSUE THREAD

**Issue by sfabriece** [driftyco/ionic-native#338]
I'm working on an ionic2 app. So far everything is going well. But I'm still in doubt about the best practices for using the sqlite plugin.

Should I always call platform.ready, How do I instantiate the first time and so on....

Examples would be appreciated. Thanks

**Comment by mbakker96** [comment]
maybe is this a solution for you: 

[http://ionicframework.com/docs/v2/api/platform/storage/SqlStorage/](http://ionicframework.com/docs/v2/api/platform/storage/SqlStorage/)

I use it also in my application

**Comment by sfabriece** [comment]
Thanks @mbakker96 . I use that too. But I lack examples of implementation that show the best practices for using it. Thanks what I'm looking for. If you a reference project I can look at that would be awesome.

**Comment by ihadeed** [comment]
You should wait for `ondeviceready` the first time you create the database, no need to call it every time you do a transaction afterwards.

As for the usage, follow the Native docs example:

```ts
import { SQLite } from 'ionic-native';
 
// wrap this with ondeviceready or platform.ready()
let db = new SQLite();
db.openDatabse({
  name: 'data.db',
   location: 'default' // the location field is required
 }).then(() => {
 db.executeSql('create table danceMoves(name VARCHAR(32))', {}).then(() => {

  }, (err) => {
     console.error('Unable to execute sql', err);
   })
 }, (err) => {
   console.error('Unable to open database', err);
 });
 ```

I personally wouldn't be able to help you beyond this point as I haven't used the plugin thoroughly yet.

AFAIK the SqlStorage that's bundled with Ionic Framework 2 has browser fallback to WebSQL. This plugin lacks this feature, which means you will be stuck developing on a device/emulator whenever you need to use the database.

**Comment by sfabriece** [comment]
Thanks, It's a little bit more clear. I'll update this thread with whatever experiences I encounter.
