### ISSUE TITLE
cannot pass in options to Geolocation.getCurrentPosition()

### ISSUE THREAD

**Issue by jasonwaters** [driftyco/ionic-native#34]
This code fails:
```
let options = {maximumAge: 0, timeout: 10000, enableHighAccuracy: true};
Geolocation.getCurrentPosition(options).then(...)
```

Gives an error about the first parameter not being a function.  Am I doing it wrong?

**Comment by tlancina** [comment]
Thanks for the issue, looks like it might be a bug. The `@Cordova` decorator should have `callbackOrder: 'reverse'`.

**Comment by thiphariel** [comment]
Sorry to "reopen" that, but when this fix will be pushed to npm ?

Thanks.

**Comment by ihadeed** [comment]
@thiphariel 
Not sure when are they planning to publish a new release to NPM.

But here is an unofficial release that includes that fix: 
https://www.dropbox.com/s/wizomnu75jv30yz/ionic-native-nightly-dist.zip?dl=0

Please note that it _might_ be unstable due to some untested plugins.
