### ISSUE TITLE
FacebookLoginResponse interface not exported

### ISSUE THREAD

**Issue by matheo** [driftyco/ionic-native#344]
Hi
I built my own services to wrap the use of the native Auth plugins, and I was struggling with a Typescript error when I typed my service, with a message of incompatibility between `FacebookLoginResponse` and the one I built myself `FacebookResponse`.

I've tried to get `FacebookLoginResponse` but I see that `ionic-native` only exports the `Facebook` class and no its interface. Could you guys make it available please?
TIA

**Comment by ihadeed** [comment]
Yes I'm aware of that. You can actually import it from `facebook.d.ts` in the latest ionic-native version. 

The next version will fix this issue. I'll keep this open for reference.

**Comment by matheo** [comment]
Thanks! :D
