### ISSUE TITLE
cordova inappbrowser plugin should use a background thread

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#353]
_From @allen8300 on July 25, 2016 7:21_

I met with following error when trying to open pdf with inappbrowser plugin:

"UIPDFPageRenderOperation object 0x1589ec570 overreleased while already deallocating; break on objc_overrelease_during_dealloc_error to debug"

I tried different ways on google, but none work.

 

_Copied from original issue: driftyco/ionic#7418_

**Comment by jgw96** [comment]
_From @ghenry22 on July 25, 2016 7:40_

probably better to log this against the inappbrowser cordova plugin, this doesn't look like an ionic issue.

**Comment by ihadeed** [comment]
This is an issue with the plugin and not with it's Ionic Native wrapper.
