### ISSUE TITLE
The "minDate" option in DatePicker should accept number as the type

### ISSUE THREAD

**Issue by hwguyguy** [driftyco/ionic-native#354]
According to the document in `cordova-plugin-datepicker`

> minDate is a Date object for iOS and a millisecond precision unix timestamp for Android, so you need to account for that when using the plugin. Also, on Android, only the date is enforced (time is not).

[https://github.com/VitaliiBlagodir/cordova-plugin-datepicker#mindate---ios-android-windows](https://github.com/VitaliiBlagodir/cordova-plugin-datepicker#mindate---ios-android-windows)

The "minDate" option should be a number on Android.

**Comment by mlynch** [comment]
That's a weird one since the type is more of an `any`, and it's regrettable that plugin takes platform-specific arguments.
