### ISSUE TITLE
Uncaught TypeError: $cordovaTransfer.upload is not a function

### ISSUE THREAD

**Issue by felipetoffolo1** [driftyco/ionic-native#357]
HI,
i have a question.
I'm trying to use ionic native in my Ionic 1 project.
 but when it try
 ` $cordovaTransfer.upload()` 
i receive the errro
`Uncaught TypeError: $cordovaTransfer.upload is not a function`

here is my code

`      cordovaUpload: function (file, objectType, fileName, chunkMode) {

        chunkMode | (chunkMode = false);

        var container = this.fileContainer(objectType);

        var options = {
          fileKey: "file",
          fileName: fileName,
          chunkedMode: chunkMode,
          mimeType: "image/jpg"
        };

        
        $cordovaTransfer.upload(file, CONFIG.urlApi + '/api/containers/' + container + '/upload',  options).then(function(data){
        return data;  
        });

      }`

**Comment by ihadeed** [comment]
Hey there,

This plugin (along with a few others) are instance based. You need to do something like the following:
```javascript
var transfer = new $cordovaTransfer();
transfer.upload(...);
```

**Comment by felipetoffolo1** [comment]
Hi @ihadeed thank you for the answer.
But i tried that one and got a error too
`cordova.js:314 Uncaught TypeError: $cordovaTransfer is not a constructor`

**Comment by ihadeed** [comment]
@mlynch can you have a look at this when you get a chance?

**Comment by mlynch** [comment]
Ah, perhaps the instance based stuff isn't correctly abstracted for ng1...

**Comment by ihadeed** [comment]
@felipetoffolo1 can you try to use the plugin via the global variable `IonicNative`.. 
example:

```javascript
var transfer = new IonicNative.Transfer();
transfer.upload(...)
```

**Comment by raykin** [comment]
@ihadeed tried your latest example, but doesn't work

**Comment by mlynch** [comment]
The constructor isn't getting carried over, fixing now
