### ISSUE TITLE
Device plugin error

### ISSUE THREAD

**Issue by ZiFFeL1992** [driftyco/ionic-native#36]
Hello!

I'm getting the following error while using Device plugin:
![image](https://cloud.githubusercontent.com/assets/5492960/13640440/f0f9de7c-e614-11e5-8075-2260c4eab83e.png)

If I call it from window.device it works as expected. I have the import from 'ionic-native' at the top of my js file.
Is there anything I'm doing wrong?

Thanks!

**Comment by ihadeed** [comment]
Looking at the definition it looks like you should call it by simply
calling the property device.

Example: `let device = Device.device;`

Then call sub properties, examples: `device.uuid;` , `device.model;`

**Comment by ZiFFeL1992** [comment]
Yup, that was the key, but the documentation is confuses me:

http://ionicframework.com/docs/v2/native/Device/

Thanks for the help.

**Comment by ihadeed** [comment]
@ZiFFeL1992 glad I could help. Thanks for pointing out the wrong docs.
