### ISSUE TITLE
CameraPreview (may) use the wrong repo

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-native#360]
CameraPreview (http://ionicframework.com/docs/v2/native/camerapreview/) mentions that it uses this GitHub repo: https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview - but that repo says it is no longer being worked on and suggests using https://github.com/westonganger/cordova-plugin-camera-preview/tree/skanygin

**Comment by mhartington** [comment]
> Then we can get it merged back to master on this repo.

I doesn't seem that there's much consensus on what plugin is the "working" one. 
Will test out each on and confirm.

**Comment by cfjedimaster** [comment]
Fair point - I missed his last bit about 'merging back'.
