### ISSUE TITLE
Cordova-Geolocation - Error in Success callbackId with watchPosition option

### ISSUE THREAD

**Issue by Oreonax** [driftyco/ionic-native#362]
Hi,

I try to use an option on watchposition like this:
`this.geosubscription = Geolocation.watchPosition({enableHighAccuracy: true }).subscribe(position => {
});`

But I get that on android: `On android I get the following error: Error in Success callbackId: Geolocation189843865 : TypeMismatchError: The type of an object was incompatible with the expected type of the parameter associated to the object.`

Am I miss using watchposition ? Is this a bug ?

Thanks in advance

[Related post on ionic forum](https://forum.ionicframework.com/t/watchposition-subscribe-where-are-the-options/58628)

**Comment by ihadeed** [comment]
Can you try this again using the latest version of `ionic-native` ?
