### ISSUE TITLE
Diagnostics support doesn't tell you what to import

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-native#364]
The Ionic Native docs don't always tell you what to import and should be consistent. So for ex, http://ionicframework.com/docs/v2/native/diagnostic/, does not tell you want to import. I tried to import Diagnostics and it didn't work. Of course, it took me just a second to figure out it was Diagnostic, but that should be documented.

**Comment by mlynch** [comment]
Looks like the fix for this landed. Ionic docs will update on the next build.
