### ISSUE TITLE
Readme: ionic-native vs ngCordova and $scope.$apply

### ISSUE THREAD

**Issue by mirkonasato** [driftyco/ionic-native#367]
The readme currently says that for [Angular 1](https://github.com/driftyco/ionic-native#angular-1):

> Ionic Native works as a stand-in for ngCordova. In many cases, the usage is identical, but we import ionic.native instead of ngCordova as our module.

That doesn't seem very accurate: looks like with ionic-native you always need to wrap updates in `$scope.$apply`. That's usually not required with ngCordova because it uses the $q service.

**Comment by ihadeed** [comment]
Should be fixed in next release.

**Comment by mirkonasato** [comment]
Tried 1.3.10 but I still need `$scope.$apply` with e.g. `$cordovaCamera.getPicture()`.

Maybe it's because #378 says it's a "partial fix"?
