### ISSUE TITLE
Google Map doesn't show

### ISSUE THREAD

**Issue by mmazloum** [driftyco/ionic-native#368]
I've tried to add the ionic native google map component, every console logs print data as if everything was ok but no map is displayed. fails with angular rc4, ionic2 beta 10

Tried with https://github.com/ihadeed/ionic-native-playground.git, i get the same trouble, everything installs and starts fine but after ionic emulate ios when I try to display the map I get a white screen instead. fails with the basic settings of the project

I'm working on a Mac, any ideas ?

**Comment by mhartington** [comment]
Hey there, can you provide a demo or some git repo that has the issue. A simple blank app starter page will do.

**Comment by Kayrohinc** [comment]
Hello! I have the same issue,  try to open simple test in android-catch error
```
> /PhoneStatusBar( 1192): setSystemUiVisibility vis=8000 mask=ffffffff oldVal=0 newVal=8000 diff=8000
> D/WindowManager(  813): stopFreezingDisplayLocked: !mDisplayFrozen 
> W/SurfaceFlinger(  235): couldn't log to binary event log: overflow.
> V/WindowManager(  813): Checking app orientation: AppWindowToken{13f7f50c token=Token{38e9583f ActivityRecord{3c104c5e u0 com.ionicframework.personalbuilder815132/.MainActivity t1389}}}
> V/WindowManager(  813): Done at AppWindowToken{13f7f50c token=Token{38e9583f ActivityRecord{3c104c5e u0 com.ionicframework.personalbuilder815132/.MainActivity t1389}}} -- full screen, return -1
> D/PhoneStatusBar( 1192): hiding the MENU button
> D/PhoneStatusBar( 1192): setSystemUiVisibility vis=8600 mask=ffffffff oldVal=8000 newVal=8600 diff=600
> D/PhoneStatusBar( 1192): hiding the MENU button
> I/Timeline( 9250): Timeline: Activity_idle id: android.os.BinderProxy@180d076 time:47979907
> D/PowerManagerService(  813): jjf sign: mProximityScreenOfftag = false
> D/PowerManagerService(  813): jjf sign: useProximitySensor = false, mProximityScreenOfftag = false
> D/PowerManagerService(  813): updateScreenStateLocked: mDisplayReady=true, policy=3, mWakefulness=1, mWakeLockSummary=0x0, mUserActivitySummary=0x1, mBootCompleted=true
> V/WindowManager(  813): setAppVisibility(Token{2d8b7a96 ActivityRecord{86cb5b1 u0 com.zte.lqsoft.launcher/com.lqsoft.launcher.LiveLauncher t1185}}, visible=false): mNextAppTransition=0xffffffff hidden=true hiddenRequested=true
> I/chromium( 9250): [INFO:CONSOLE(24672)] "Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.", source: file:///android_asset/www/build/js/app.bundle.js (24672)
> V/WLAN_PSA(  272): NL MSG, len[048], NL type[0x11] WNI type[0x5050] len[028]
> V/WLAN_PSA(  272): NL MSG, PID: 272
> I/chromium( 9250): [INFO:CONSOLE(33659)] "EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in :0:0
> I/chromium( 9250): ORIGINAL EXCEPTION: ReferenceError: plugin is not defined
> I/chromium( 9250): ORIGINAL STACKTRACE:
> I/chromium( 9250): ReferenceError: plugin is not defined
> I/chromium( 9250):     at new GoogleMap (file:///android_asset/www/build/js/app.bundle.js:73664:32)
> I/chromium( 9250):     at new HomePage (file:///android_asset/www/build/js/app.bundle.js:53:19)
> I/chromium( 9250):     at DebugAppView._View_HomePage_Host0.createInternal (HomePage_Host.template.js:15:24)
> I/chromium( 9250):     at DebugAppView.AppView.create (file:///android_asset/www/build/js/app.bundle.js:25639:21)
> I/chromium( 9250):     at DebugAppView.create (file:///android_asset/www/build/js/app.bundle.js:25832:44)
> I/chromium( 9250):     at ComponentFactory.create (file:///android_asset/www/build/js/app.bundle.js:24953:36)
> I/chromium( 9250):     at file:///android_asset/www/build/js/app.bundle.js:46545:49
> I/chromium( 9250):     at ZoneDelegate.invoke (file:///android_asset/www/build/js/zone.js:323:29)
> I/chromium( 9250):     at Object.NgZoneImpl.inner.inner.fork.onInvoke (file:///android_asset/www/build/js/app.bundle.js:30467:41)
> I/chromium( 9250):     at ZoneDelegate.invoke (file:///android_asset/www/build/js/zone.js:322:35)
> I/chromium( 9250): ERROR CONTEXT:
> I/chromium( 9250): [object Object]", source: file:///android_asset/www/build/js/app.bundle.js (33659)
> I/chromium( 9250): [INFO:CONSOLE(33659)] "STACKTRACE:", source: file:///android_asset/www/build/js/app.bundle.js (33659)
> I/chromium( 9250): [INFO:CONSOLE(33659)] "Error: Uncaught (in promise): EXCEPTION: Error in :0:0
> I/chromium( 9250): ORIGINAL EXCEPTION: ReferenceError: plugin is not defined
> I/chromium( 9250): ORIGINAL STACKTRACE:
> I/chromium( 9250): ReferenceError: plugin is not defined
> I/chromium( 9250):     at new GoogleMap (file:///android_asset/www/build/js/app.bundle.js:73664:32)
> I/chromium( 9250):     at new HomePage (file:///android_asset/www/build/js/app.bundle.js:53:19)
> I/chromium( 9250):     at DebugAppView._View_HomePage_Host0.createInternal (HomePage_Host.template.js:15:24)
> I/chromium( 9250):     at DebugAppView.AppView.create (file:///android_asset/www/build/js/app.bundle.js:25639:21)
> I/chromium( 9250):     at DebugAppView.create (file:///android_asset/www/build/js/app.bundle.js:25832:44)
> I/chromium( 9250):     at ComponentFactory.create (file:///android_asset/www/build/js/app.bundle.js:24953:36)
> I/chromium( 9250):     at file:///android_asset/www/build/js/app.bundle.js:46545:49
> I/chromium( 9250):     at ZoneDelegate.invoke (file:///android_asset/www/build/js/zone.js:323:29)
> I/chromium( 9250):     at Object.NgZoneImpl.inner.inner.fork.onInvoke (file:///android_asset/www/build/js/app.bundle.js:30467:41)
> I/chromium( 9250):     at ZoneDelegate.invoke (file:///android_asset/www/build/js/zone.js:322:35)
> I/chromium( 9250): ERROR CONTEXT:
> I/chromium( 9250): [object Object]
> I/chromium( 9250):     at resolvePromise (file:///android_asset/www/build/js/zone.js:538:32)
> I/chromium( 9250):     at file:///android_asset/www/build/js/zone.js:574:18
> I/chromium( 9250):     at ZoneDelegate.invokeTask (file:///android_asset/www/build/js/zone.js:356:38)
> I/chromium( 9250):     at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (file:///android_asset/www/build/js/app.bundle.js:30458:41)
> I/chromium( 9250):     at ZoneDelegate.invokeTask (file:///android_asset/www/build/js/zone.js:355:43)
> I/chromium( 9250):     at Zone.runTask (file:///android_asset/www/build/js/zone.js:256:48)
> I/chromium( 9250):     at drainMicroTaskQueue (file:///android_asset/www/build/js/zone.js:474:36)
> I/chromium( 9250):     at XMLHttpRequest.ZoneTask.invoke (file:///android_asset/www/build/js/zone.js:426:22)", source: file:///android_asset/www/build/js/app.bundle.js (33659)
> I/chromium( 9250): [INFO:CONSOLE(461)] "Unhandled Promise rejection:", source: file:///android_asset/www/build/js/zone.js (461)
> I/chromium( 9250): [INFO:CONSOLE(463)] "Error: Uncaught (in promise): EXCEPTION: Error in :0:0
> I/chromium( 9250): ORIGINAL EXCEPTION: ReferenceError: plugin is not defined
> I/chromium( 9250): ORIGINAL STACKTRACE:
> I/chromium( 9250): ReferenceError: plugin is not defined
> I/chromium( 9250):     at new GoogleMap (file:///android_asset/www/build/js/app.bundle.js:73664:32)
> I/chromium( 9250):     at new HomePage (file:///android_asset/www/build/js/app.bundle.js:53:19)
> I/chromium( 9250):     at DebugAppView._View_HomePage_Host0.createInternal (HomePage_Host.template.js:15:24)
> I/chromium( 9250):     at DebugAppView.AppView.create (file:///android_asset/www/build/js/app.bundle.js:25639:21)
> I/chromium( 9250):     at DebugAppView.create (file:///android_asset/www/build/js/app.bundle.js:25832:44)
> I/chromium( 9250):     at ComponentFactory.create (file:///android_asset/www/build/js/app.bundle.js:24953:36)
> I/chromium( 9250):     at file:///android_asset/www/build/js/app.bundle.js:46545:49
> I/chromium( 9250):     at ZoneDelegate.invoke (file:///android_asset/www/build/js/zone.js:323:29)
> I/chromium( 9250):     at Object.NgZoneImpl.inner.inner.fork.onInvoke (file:///android_asset/www/build/js/app.bundle.js:30467:41)
> I/chromium( 9250):     at ZoneDelegate.invoke (file:///android_asset/www/build/js/zone.js:322:35)
> I/chromium( 9250): ERROR CONTEXT:
> I/chromium( 9250): [object Object]", source: file:///android_asset/www/build/js/zone.js (463)
> I/chromium( 9250): [INFO:CONSOLE(67897)] "DEVICE READY FIRED AFTER", source: file:///android_asset/www/build/js/app.bundle.js (67897)
> V/StatusBar( 9250): Executing action: styleDefault
> D/qdlights(  813): set_breath_light_locked mode 0, colorRGB=FF000000, onMS=0, offMS=0
```
source-
https://drive.google.com/file/d/0BzSmlz9GIqFtV1RreTg5NlMtR2s/view?usp=sharing

**Comment by mmazloum** [comment]
@mhartington the project is a bit massive and the geolocation map is part of a form screen flow, i'll try to find out more precise clues. And if I don't find I'll build a blank starter.

I've have a question : do I have to test native plugins like this on phones or should it work on mac OS emulator ?

However if it can help : 

Here is my constructor : (assuming I don't need to wait on "platform ready" since the app is already started)
`  constructor(private appService: AppService, private _nav: NavController) {

    this.map = new GoogleMap('gmap');
    this.map.on(GoogleMapsEvent.MAP_READY).subscribe(() => console.log('Map is ready!'));

    console.log("gmap is ", this.map);
    let myPosition = new GoogleMapsLatLng(this.latitude, this.longitude);

    console.log("My position is", myPosition);
    let markerOptions: GoogleMapsMarkerOptions = {
          position: myPosition,
          title: 'Custom thing'
      };
  }`

Here are my imports : `import { GoogleMap, GoogleMapsEvent, GoogleMapsMarkerOptions, GoogleMapsLatLng } from 'ionic-native/dist/plugins/googlemaps';`

and here is the html part : 
`<ion-header>
    <ion-navbar primary>
        <button menuToggle>
            <ion-icon name="menu"></ion-icon>
        </button>
        <ion-title>Lieux disponible</ion-title>
        <ion-buttons end>
          <button secondary solid (click)="presentConfirm()">
            Valider
          </button>
        </ion-buttons>
    </ion-navbar>
</ion-header>


<ion-toolbar>
    <ion-searchbar [(ngModel)]="searchInput" (input)="getLocations($event)" (placeholder)="placeHolder"></ion-searchbar>
</ion-toolbar>


<ion-content class="map">
    <div id="gmap" style="height: 100%;"></div>
</ion-content>


<ion-toolbar position="bottom">
    <ion-buttons>
        <button primary>
            <ion-icon name="ios-navigate-outline"></ion-icon>
        </button>
        <button primary [navPush]="homePage">
            <ion-icon name="ios-home-outline"></ion-icon>
        </button>
    </ion-buttons>
    <ion-buttons end>
        <button grey [navPush]="[listPage, locations]">
            Liste
            <ion-icon name="ios-list-outline"></ion-icon>
        </button>
    </ion-buttons>
</ion-toolbar>`

**Comment by mmazloum** [comment]
if it can help here is what I see in the debug console from androïd : 
![image](https://cloud.githubusercontent.com/assets/3626499/17330328/becef976-58c6-11e6-89a5-74989c2e6b8a.png)

**Comment by mmazloum** [comment]
@mhartington I get the same problem with @ihadeed native googlemaps starter project, I'm launching my app on a Iphone 6 (latest OS) or Galaxy S6 (lolipop), if you just need my projects settings (package.json, typings, etc...) tell me I'll create the same conf. in another git project but I don't think it comes from here.

Thanks.

**Comment by lthh89vt** [comment]
I had the similar issue and hope you can find the solution in [driftyco/ionic#7205](https://github.com/driftyco/ionic/issues/7205)

**Comment by mmazloum** [comment]
I @lthh89vt, thanks for the link, I've re-installed the plugin, and added the css trick explained in driftyco/ionic#7205, but the previous screen (before nav push) freezes on half of the screen + map doesn't disply between ionic component but behind.

**Comment by mmazloum** [comment]
hi, just to let you know, I get this display on a lolipop S6 edge + Ionic2 beta 10, + RC4 @lthh89vt, @mhartington: 
![image](https://cloud.githubusercontent.com/assets/3626499/17418766/7ea0f540-5a9a-11e6-8f10-b8a04591d972.png)

it seems there is a css trouble between ionic and ionic native maps plugin.

**Comment by mmazloum** [comment]
finally did this to remove to previous page overlay : 
`
  ionViewWillEnter() {
    document.querySelector('.transport-page').setAttribute("hidden", "");
  }

  ionViewWillLeave() {
    document.querySelector('.transport-page').removeAttribute("hidden");
  }
`

**Comment by ZiFFeL1992** [comment]
https://github.com/driftyco/ionic/issues/7205

We should add this to ionic-native documentation or add the fix to scss file...

**Comment by juanf9224** [comment]
This is happening to me too, im  on android, i have the api key right, sha1 fingerprint right, but the map just doesn't load, only this appears: 
![7961682608157261056-account_id 1](https://cloud.githubusercontent.com/assets/9439694/17821530/16377ba0-6620-11e6-8c35-31908f6a542a.png)
Apis are enabled, wich by the way were renamed to **"Google Maps Android API"** instead of **"Google Maps Android API v2"**.

the css fix doesnt work on android, i followed the steps in this repo: [https://github.com/aaronksaunders/ionic2GMapNative](url) and then cloned it and tested on the device but the same problem occured, is this plugin not suppose to work yet?? i think im gonna use the javascript sdk for the meantime until this plugin gets fix for android.

**Comment by ihadeed** [comment]
Closing this since it's not an `ionic-native` issue.

**Comment by dit1994** [comment]
i am experiencing the same problem. mine it displays the map the disappears and be like "Opps! something went wrong" please help

**Comment by edwincqu** [comment]
Tenia el mismo problema, lo solucione instalando de nuevo el plugin
1: ionic cordova plugin add cordova-plugin-googlemaps
2: npm install --save @ionic-native/google-maps@4.8.2
3: luego config.xml
<preference name="GOOGLE_MAPS_ANDROID_API_KEY" value="my key" />
<preference name="GOOGLE_MAPS_IOS_API_KEY" value="my key" />

<plugin name="cordova-plugin-googlemaps" spec="2.6.2">
        <variable name="PLAY_SERVICES_VERSION" value="15.0.1" />
        <variable name="ANDROID_SUPPORT_V4_VERSION" value="27.+" />
</plugin>
