### ISSUE TITLE
Support using ionic-native as a library when implementing a custom Cordova plugin?

### ISSUE THREAD

**Issue by tomsun** [driftyco/ionic-native#37]
I like your `@Plugin` and `@Cordova` decorators!

Would it make sense to let them be importable into another project?

Use-case: niche Cordova-plugins built with Cordova-style callbacks, where it wouldn’t make sense to bundle their Promise-enabling TypeScript wrappers in `ionic-native` due to them being obscure, private, app-specific, not-generally-useful, whatever, but where `ionic-native`’s conventions would still make a lot of sense.

This is actually quite seamless with npm and ES6 imports:

`import {Plugin, Cordova} from 'ionic-native/src/plugins/plugin’;`

...assuming: 

npm install --save https://github.com/driftyco/ionic-native.git#1334f60b681fa5440174ca984d5a3a8b2d2814e6

No longer works with master though, due to this commit from a few days ago: https://github.com/driftyco/ionic-native/commit/2330670661c06078d0fb941812628f05c3ec2b92

**Comment by tlancina** [comment]
I think this a great idea, we can definitely export everything in plugin.ts.

**Comment by tomsun** [comment]
Great!

Btw, just realized it is also possible to import from the latest official package, with a slightly different path:
`nom install --save ionic-native`
`import {Plugin, Cordova} from 'ionic-native/dist/plugins/plugin' `

Exposing them in `dist/index.js` under a more official-sounding path would be nice though.

**Comment by tlancina** [comment]
Should be able to import things like `Cordova` and `Plugin` from `'ionic-native'` in the next release.

**Comment by tomsun** [comment]
sweet! thanks
