### ISSUE TITLE
blowser does not support camera

### ISSUE THREAD

**Issue by huangfeihong1860** [driftyco/ionic-native#3727]
// 定义拍照事件
     takePhoto(){
      this.platform.ready().then(() => {
      // 设置选项
      const options: CameraOptions = {
        quality: 100,    //照片质量
        destinationType: this.camera.DestinationType.DATA_URL,
        sourceType: this.camera.PictureSourceType.CAMERA,
        encodingType: this.camera.EncodingType.JPEG,
        allowEdit: false,
        mediaType: this.camera.MediaType.PICTURE
      }
  
      // 获取图片
      this.camera.getPicture(options).then((imageData) => {
        // 获取成功
        let base64Image = 'data:image/jpeg;base64,' + imageData;
        this.images.unshift({
          src:base64Image
        })
      }, (err) => {
        console.log('获取图片失败');
      });
    }); // end platform.ready
    }
insert the output from ionic info here
```
blowser does not support camera


ionic 6
angular11
cordova10
ionic cordova plugin add cordova-plugin-camera
npm install @ionic-native/camera
import { Camera, CameraOptions } from '@ionic-native/camera/ngx';

constructor(private camera: Camera) { }

...


const options: CameraOptions = {
  quality: 100,
  destinationType: this.camera.DestinationType.FILE_URI,
  encodingType: this.camera.EncodingType.JPEG,
  mediaType: this.camera.MediaType.PICTURE
}

this.camera.getPicture(options).then((imageData) => {
 // imageData is either a base64 encoded string or a file URI
 // If it's base64 (DATA_URL):
 let base64Image = 'data:image/jpeg;base64,' + imageData;
}, (err) => {
 // Handle error
});

**Comment by jcesarmobile** [comment]
If a plugin is not working, then you should report the problem on the plugin repository. 

ionic-native just make it easier to use cordova plugins in Ionic apps, but if they don't work fine there is nothing we can do about it.
