### ISSUE TITLE
inAppBrowser - windows platform

### ISSUE THREAD

**Issue by daniele-sartiano** [driftyco/ionic-native#377]
When I use the inAppBrowser plugin on my smartphone (windows 10) with windows platform, I obtain this error:

The app can’t use script to load the http://MY_SERVER_URL url because the url launches another app. Only direct user interaction can launch another app.

The code is:

     `uri = encodeURI('http://MY_SERVER_URL');
      var ref = ionic_native_1.InAppBrowser.open(uri, '_self', 'location=no');`

Are there some problem?

**Comment by ihadeed** [comment]
This is an issue with the plugin/platform and not with Ionic Native.

Try `_system` instead of `_self`. 

See: https://github.com/apache/cordova-plugin-inappbrowser/blob/master/www/windows8/InAppBrowserProxy.js#L49

**Comment by daniele-sartiano** [comment]
Thx!
