### ISSUE TITLE
Ionic2 - Unable to setup SQLStorage (_ionicNative.Storage is not a constructor)

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#379]
_From @HamzaLJ on July 30, 2016 14:41_

I'm trying to setup SqlStorage in my Ionic2 app, but I was not lucky enough to do so as I am receiving the following error:

I following the documentation, but that didn't work!

> _ionicNative.Storage is not a constructor

    import {SqlStorage, Storage, StatusBar} from 'ionic-native';
    
    SaveInfo(){

    this.storage = new Storage(SqlStorage, { name: 'userInfo' });
  
    return this.http.get(this.postUrl, {search:params})
                   .subscribe(
                     data => {
    
         this.storage.set('userName', 'TestUser');
         this.storage.set('userType', 'VIP');
    
    });

Cordova CLI: 6.3.0
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 7.3.1 Build version 7D1014 

_Copied from original issue: driftyco/ionic#7481_

**Comment by ihadeed** [comment]
That way of using the SQL storage is not supported by ionic native. That is
the implantation that's included with the ionic framework itself.

Simply importing Storage and SQLite from ionic-angular instead of
ionic-native should fix it.

**Comment by mlynch** [comment]
Yep, Storage is part of Ionic Framework proper.
