### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by johannds** [driftyco/ionic-native#380]
I've tried installing this as per the docs, but it doesn't inject the script into my index.html. Due to this, I cannot reference the lib in my code.

**Comment by ihadeed** [comment]
Are you using ionic 1 or 2?

**Comment by johannds** [comment]
@ihadeed I'm on v1. Just saw that I need to copy the file manually and reference it. I've copied it to /lib/ionic-native/ and plugged it into my index.html manually. Works now! :smile:
