### ISSUE TITLE
 Pls update Google maps and (maybe) all other documentation for ionic native 

### ISSUE THREAD

**Issue by Kayrohinc** [driftyco/ionic-native#382]
Hello!  It will be great, if you update all information for ionic native plugins, maybe people will have less questions. For examples:  in docs-
```
// somewhere in your component
let map = new GoogleMap('elementID');

map.on(GoogleMapsEvent.MAP_READY).subscribe(() => console.log('Map is ready!'));
```
in real life  
map.on(GoogleMapsEvent.MAP_READY).subscribe(() => console.log('Map is ready!')); doesn't work , but 
```

    GoogleMap.isAvailable().then(() => {

this.map.one(GoogleMapsEvent.MAP_READY).then((data)=>{console.log("t"+data);
	
});
  
  }
```
works well...  
also...  I try to use `$ ionic plugin add cordova-plugin-googlemaps` -catch  404 error..

**Comment by ZiFFeL1992** [comment]
The first piece of code is working on my project, can you provide more info please?

**Comment by ihadeed** [comment]
thanks I just updated the docs
