### ISSUE TITLE
Please add “cordova-plugin-file-opener2” plugin into ionic-native，Thanks！

### ISSUE THREAD

**Issue by iraychen** [driftyco/ionic-native#387]
**# Please add “cordova-plugin-file-opener2” plugin into ionic-native，Thanks！**

I use the Ionic2 beta10  version development app, you can use the FileTransfer plug-in to download the PDF file, but how to call the local application to open the PDF file?

To search for **# "cordova-plugin-file-opener2" this plugin can call the local application to open the file**, in beta6 JS version can directly use this plugin to open the file, but the default the latest beta10 is ts template, the TS to develop, need plugin will turn into TS version can be used. "Typings search file" no TS version of "cordova-plugin-file-opener2" this plugin. So how to call it in the TS?

Or how to turn "cordova-plugin-file-opener2" into a TS version of the plugin to typings?

**Comment by ramonsan** [comment]
Functions of cordova-plugin-file-opener2 are integrated in file plugin as @ihadeed said in [#295](https://github.com/driftyco/ionic-native/issues/295). 

There is a PR [#283](https://github.com/driftyco/ionic-native/pull/283), but not merged yet.
