### ISSUE TITLE
ask for permission for contacts on iOS 10

### ISSUE THREAD

**Issue by mbakker96** [driftyco/ionic-native#390]
My Iphone (ios 10) crasht when using the Contact plugin becease of privacy issue. 

It has to request permission to read / write to the contacts.

see [issue](https://github.com/apache/cordova-plugin-contacts/pull/131) on contact repo for more info.

errorlog: 
```bash
2016-08-04 13:17:02.216101 Clockwise[2001:583092] [access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSContactsUsageDescription key with a string value explaining to the user how the app uses this data.
(lldb) 
```

**Comment by ihadeed** [comment]
I'm not sure how this is an ionic-native issue, are we missing a wrapper that requests the required permissions?

**Comment by kamok** [comment]
@ihadeed A key has to be auto generated. See here: https://stackoverflow.com/questions/39566952/cordova-info-plist-nscamerausagedescription-key-is-missing.

Can you guys ensure that it is for your plugins so we don't have to manually run into this problem?

**Comment by kamok** [comment]
@ihadeed https://stackoverflow.com/questions/39415895/app-rejected-due-to-missing-usage-descriptions-xcode8. I can set the value for the key manually. But this should be automatic I think when we build. Prompt us in the cli to input some string for that key.
