### ISSUE TITLE
Review whether Toast uses observables or Promises

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic-native#395]
Some of the methods of `Toast` use observables (for example, `show`), but usage feels more appropriate for a `Promise`. Perhaps we should revise that?

**Comment by ihadeed** [comment]
The Toast plugin uses the success callback to notify that the Toast was successfully displayed, and also to notify the app that the user tapped the toast. See https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin#receiving-a-callback-when-a-toast-is-tapped

**Comment by walkingriver** [comment]
Is it required to unsubscribe once those two events have occurred? Does the subscription vanish on its own? Or will one callback handle every toast shown during the app's lifetime?

**Comment by mlynch** [comment]
Right now you do have to subscribe for the operation to start, which I think is regrettable. Filing an issue now

**Comment by walkingriver** [comment]
Right, I imagine you should be able to fire-n-forget. That was my mistake early on. @ihadeed, couldn't you accomplish the same thing with then/finally? The subscribe metaphor feels forced when there are only three possible outcomes, and no repeats (unless that assumption is wrong).
