### ISSUE TITLE
MediaCapture TypeScript Missing

### ISSUE THREAD

**Issue by sbryfcz** [driftyco/ionic-native#396]
From the media capture example: http://ionicframework.com/docs/v2/native/media-capture/

Typescript seems to fail when running these examples. It doesnt look like ionic native doesn't export MediaCapture. 

Maybe this was checked in prematurely?

**Comment by ihadeed** [comment]
Can you share the errors that you are getting?

The plugin is exported here https://github.com/driftyco/ionic-native/blob/master/src/index.ts#L107

**Comment by maxx0r** [comment]
Are you sure your ionic-native version is at >=1.3.5 ?

**Comment by sbryfcz** [comment]
Odd. I fired up my project today and things seem to be working. Maybe it was an issue with Visual Studio code. Oh well. Thanks for your help (and awesome library).
