### ISSUE TITLE
Are you accepting contributions?

### ISSUE THREAD

**Issue by ihadeed** [driftyco/ionic-native#4]
Hi there,

I'm currently working on my own library that gives me functionality similar to ngCordova for Ionic 2 ... Just simplifying plugin calls.

I thought I could help build Ionic-native instead of building my own thing and I was wondering if you are accepting contributions to this repository at the moment?

**Comment by tlancina** [comment]
Hey @ihadeed, thanks for reaching out! We are definitely be accepting contributions, but will need to discuss how we evaluate new plugins to add to Ionic Native.  I think if you're looking to contribute, probably the easiest way to do so right now would be to take a look at adding interfaces for any of the core Cordova plugins that are missing.

Ionic Native should be going up on the v2 docs with the first batch of plugins this week, and after that we will continue to add more.

Please let me know if you have any questions about the project or need help with anything.

**Comment by ihadeed** [comment]
Thanks @tlancina for your response.

1. So if I understood correctly you are looking to create the interfaces only for now without any functionality? 
I will follow the way you have the files in this directory are written: https://github.com/driftyco/ionic-native/blob/master/src/plugins


2. I was looking at https://github.com/driftyco/ionic-native/blob/master/src/plugins/statusbar.ts#L67 and I noticed that lines 67-70 are referring to properties of StatusBar that are not defined. I understand those properties exist in the actual plugin but wouldn't it throw TypeScript/JavaScript errors unless it's ran on a device/emulator? Shouldn't we define/declare an alias for those properties?

**Comment by tlancina** [comment]
Yep, the goal for the moment is to just be a wrapper, with no plugin specific logic. A simple example is [BarcodeScanner](https://github.com/driftyco/ionic-native/blob/master/src/plugins/barcodescanner.ts).

StatusBar has not been updated yet, but should be by the end of the week.  Plugins that still have work to be done are: File, Push, StatusBar, Toast and TouchID.  These are somewhat arbitrary and are just the plugins that were added when the project was started.  We will be fleshing things out to add the Cordova core plugins and many of the [plugins from ngCordova](http://ngcordova.com/docs/plugins/) over the coming weeks.

**Comment by ihadeed** [comment]
Ok thanks for clearing things up.

Just submitted a PR .. let me know if I should tweak anything..


--

Off-topic question: I instealled commitizen but when I run `git cz` it only shows me a text editor similar to `vi` instead of options to pick from like the [screenshot here ](https://www.npmjs.com/package/commitizen). I'm using Windows 10. Any clue what I might be missing?

**Comment by tlancina** [comment]
PR looks great, thanks! I left a few comments on the diff.  If you want to add the descriptions of the options that would be awesome, but I can also do it after merge.

I'm actually pretty unfamiliar with commitizen still (I still type the commit messages out by hand) so I'm not sure.  What shell are you using?

**Comment by ihadeed** [comment]
Thanks. I forgot to add the lines you mentioned. Going to fix it and resubmit the PR.

I tried cmd and Git Bash .. Same result.

![image](https://cloud.githubusercontent.com/assets/13794420/13102553/70f504e8-d51d-11e5-8473-545f8b88fd82.png)

**Comment by tlancina** [comment]
Hey @ihadeed apologies that I haven't gotten your PRs merged in yet. They're looking good, but I'd like to test the plugins to make sure everything is working as expected.  If they haven't gotten in by next week please ping me. 

Not sure about the commitizen thing, maybe @jimthedev can chime in quickly on whether there are any windows related commitizen quirks.

**Comment by jimthedev** [comment]
@ihadeed As far as I can see ionic-native isn't configured to use commitizen. Whenever commitizen encounters a project that doesn't have a commitizen adapter configured (usually done with `commitizen init`), it falls back to the git default which is to ask you to manually enter a message (using the built in git editor). If you prefer not to use the editor, you can just provide a message to commitizen using `git cz -m "fix(blah): My message here"` and it will do a normal git commit.

**Comment by tlancina** [comment]
Ah derp, didn't realize it was configured on our end. Thanks! 

@ihadeed try pulling latest and running npm install, and let me know if you still have issues.

There's no conventional changelog yet, but I'll add it before the next release.

**Comment by ihadeed** [comment]
Thank you @jimthedev @tlancina

I didn't know you need to configure anything for commitizen

**Comment by ihadeed** [comment]
@tlancina
