### ISSUE TITLE
Camera plugin doesn't work in Browser

### ISSUE THREAD

**Issue by dudeofawesome** [driftyco/ionic-native#403]
The Camera plugin claims support for the Browser platform in the documentation, but when I attempt to use it in a browser (Chrome v52, OS X 10.11.5) it prints this to console
```
Native: tried calling Camera.getPicture, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator
navigator
```

It works just fine when I build and run on an Android phone. I'm just trying to get media from the gallery on phones, and from the file system in browser.

**Is this just a mistake in documentation, or an actual bug?**

**Comment by ihadeed** [comment]
Did you add the browser platform and run the command "ionic run browser" ?

**Comment by dudeofawesome** [comment]
I didn't realize that there was a difference between `ionic run browser` and `ionic serve`. When I use that, it works!

Do you know of any plans to get a live-reload system working with `run`, or to get ionic-native to work with `serve`?

**Comment by ihadeed** [comment]
You can use live reload with Ionic Native.

First install all the plugins you need, run the livereload, then you can do
any changes to your code and see it in effect immediately on the
device/emulator.

**Comment by josx** [comment]
@ihadeed which is the difference between ionic serve and ionic run browser?

**Comment by ihadeed** [comment]
@josx 
`ionic serve` runs your app as a website (meaning it doesn't have any Cordova capabilities)
`ionic run browser` runs your app in the Cordova browser platform, which will inject `cordova.js` and any plugins that have browser capabilities

**Comment by gopi-it** [comment]
> [`__`](

- 

@1. url

)

**Comment by shreyaspadhye3011** [comment]
Great suggestion by @ihadeed Worked like a charm. Just a suggestion: if `ionic run browser` doesn't work for you try:

`ionic cordova run browser`

If the terminal prompts 

> native-run was not found on your PATH

Then install `npm i -g native-run`

and try `ionic cordova run browser`. It should work.

**Comment by extfoxDusan** [comment]
> Great suggestion by @ihadeed Worked like a charm. Just a suggestion: if `ionic run browser` doesn't work for you, try:
> 
> `ionic cordova run browser`
> 
> If the terminal prompts
> 
> > [ERROR] native-run was not found on your PATH
> 
> Then install `npm i -g native-run`
> 
> and try `ionic cordova run browser`. It should work.

Or you could do it by adding:
`ionic cordova run browser --native-run=false`

**Comment by frederickjjoubert** [comment]
Hey guys, I'm working in an ionic 5 capacitor project and I can't find a workaround for this, any update on how to use this plugin on browser?

**Comment by gerardgm** [comment]
Have same problem @frederickjjoubert

**Comment by DeanCMS** [comment]
Same here. Banging my head against the wall.
Ionic / Capacitor having so many issues. Switching over to ReactNative

**Comment by danielsogl** [comment]
Just follow the capacitor guide how to use the plugin in web-apps: https://capacitorjs.com/docs/apis/camera#pwa-notes
