### ISSUE TITLE
Media plugin loop through audio file

### ISSUE THREAD

**Issue by 05bca054** [driftyco/ionic-native#406]
How can i repeat or loop audio using ionic-native media plugin.

I found some sollution by using cordova media plugin but how can i achieve using ionic-native.
```
function onDeviceReady(){
        snd = new Media( getPhoneGapPath() + "sound/funk_game_loop.mp3", onSuccess, onError, onStatus);
        snd.play();
    }

    // onSuccess Callback
    function onSuccess() {
    }
    // onError Callback 
    function onError(error) {
    }
    // onStatus Callback 
    function onStatus(status) {
        if( status==Media.MEDIA_STOPPED ) {
            snd.play();
        }
    }
```
http://ionicframework.com/docs/v2/native/mediaplugin/1

-Naitik

**Comment by ihadeed** [comment]
You can do something like this:
```typescript

let media = new Media('path/to/file.mp3').then(onSuccess, onError);

media.status.subscribe((status) => {
  if(status === Media.MEDIA_STOPPED) media.play();
});

```

**Comment by 05bca054** [comment]
Hi Ihadeed,

Thanks for your response but tried it with ionic 10 beta and no luck please find app.ts(Constructor) code
constructor(private platform: Platform) {
    this.rootPage = TabsPage;

    platform.ready().then(() => {
let media = new Media(abspath+"media/salamisound.mp3").then(() => {
          alert('Success');
      }, () => {
        alert('Error');
      });
      media.play();
      media.status.subscribe((status) => {
        alert(status);
        if(status === Media.MEDIA_STOPPED) media.play();
      });

    });
  }
}

ionicBootstrap(MyApp);

**Comment by ihadeed** [comment]
Sorry that was a partially misleading code. Here's how you do it:

```typescript
let media = new MediaPlugin('path/to/file.mp3');

media.init.then(onSuccess, onError);
media.status.subscribe(...);
```

**Comment by 05bca054** [comment]
Hi,

Still editor says can't find 

[ts] 
if(status === **Media**.MEDIA_STOPPED) media.play();
Cannot find name 'Media'.

Once declare variable in constructor like **let Media:any;**, Still no luck

**Comment by ihadeed** [comment]
It's MediaPlugin not Media

**Comment by uzumakinaruto123** [comment]
@ihadeed  I am doing it like this 

```
this.file = new MediaPlugin('path/to/file.mp3');
    
this.file.init.then(() => {

       console.log('playback finished');
      
     }, (err) => {
        console.log('somthing went wrong! error code: ' + JSON.stringify(err));
     });

this.file.status.subscribe((status) => {
          console.log('status : '+status);
  });
```


still status callback is not working. any working example ?

**Comment by neoassyrian** [comment]
I still can't get this to work

I'm getting "status" = undefined. 

How do I get the status of the Media file?

**Comment by ihadeed** [comment]
@uzumakinaruto123 @neoassyrian 
My answer above is outdated, and I think the docs are too (will update soon).

To get the status you need to do the following:
```
function onStatusUpdate(status) {
  console.log(status);
}

new MediaPlugin('path/to/file.mp3', onStatusUpdate);
```

**Comment by AleFons** [comment]
Sort of reviving this issue, but how can we pass the status change elsewhere, like, say, to the mediaObject itself?

**Comment by alchibaucha** [comment]
```
public PlayAudio(file)
{
    this.currentFile = this._media.create(file.path);
    this.currentFile.play();
    this.currentFile.onStatusUpdate.subscribe((statusCode)=> {
        if(statusCode == 4)//4 is the statusCode which is passed when the media is finished playing
        {
            //play the song again (if in loop).
            PlayAudio(file);
        }
    });
}
```
Cheers.
