### ISSUE TITLE
Error TS2305: Module "path/to/node_modules/ionic-native/dist/index" has no exported member 'Connection'

### ISSUE THREAD

**Issue by tinquang** [driftyco/ionic-native#407]
Hi, I just upgrade ionic-native from 1.3.2 to 1.3.10 and I got that error message when build.

**Comment by keithdmoore** [comment]
@mhartington removed Connection.  You need to hard-code the string literals in your code or create a Connection class in your code.

**Comment by tinquang** [comment]
thanks.
