### ISSUE TITLE
Screen orientation view width bug (iOS)

### ISSUE THREAD

**Issue by ayyfish** [driftyco/ionic-native#411]
Sometimes when changing the orientation via ScreenOrientation.lockOrientation, the web view doesn't take up the full width of the device screen (iPhone 5s). So basically the entire ui is squished onto the left side of the screen with white space to the right of it. I've noticed that showing or hiding the statusbar via the ionic native StatusBar.show or StatusBar.hide fixes this issue and the view takes the full device width. After looking into the cordova-plugin-statusbar plugin code I think that the resizeWebView function in CDVStatusBar.m is what fixes the view width. I don't know much about cordova plugins or iOS code though and I'm not sure how to fix the ScreenOrientation plugin with this knowledge.

**Comment by ihadeed** [comment]
Hey there

This would be an issue with the plugin and not with the ionic native
wrapper. I suggest opening an issue at their repository.
