### ISSUE TITLE
NFC plugin?

### ISSUE THREAD

**Issue by marcalj** [driftyco/ionic-native#412]
I couldn't find any reference fro NFC support on Ionic Native. It is supported? There's a way to use it?

PD: If not, can be used in Ionic v1?

Thanks! :)

**Comment by ihadeed** [comment]
That would be this plugin: https://github.com/chariotsolutions/phonegap-nfc

We can definitely add a wrapper for it.

**Comment by ihadeed** [comment]
So I was just writing a wrapper for the plugin and I noticed it could be done in two ways. 

1. Return an observable that connects with the `callback` parameter, and have two optional parameters for `onSuccess` and `onError`

2. Return a promise and have a required parameter of `callback`

See here: https://github.com/driftyco/ionic-native/commit/82ccf13e05782df9753cfdc5e2bcd20075b2c360


I think the first option makes more sense, but I would like to know what you think.

CC: @mlynch @mhartington

**Comment by amuramoto** [comment]
+1 on the first option. Observable seems to be in line with how other wrappers implement this type of thing.

**Comment by bokgeek** [comment]
This import is not working in Ionic2 beta11. _**Ionic-native/dist/index has no exported member 'NFC'**_

`import {NFC, Ndef} from 'ionic-native';`

If I open and look for 'nfc' into _Ionic-native/dist/index.js_ & _index.d.ts_, there is no reference to it.
I neither can find any plugin related to NFC into _node_modules/ionic-native/dist/plugins_ directory.

I'm trying to work with the example from [http://ionicframework.com/docs/v2/native/nfc/](http://ionicframework.com/docs/v2/native/nfc/)

Could anybody help me?

Thanks

**Comment by mhartington** [comment]
@bokgeek did you update the installed package of ionic-native? Check your package.json, please make sure you have the most recent version.

**Comment by bokgeek** [comment]
Thanks a lot @mhartington, that was the issue. 
I can't even read a label but that's another story... I keep trying.

**Comment by lehrenberg** [comment]
Hi folks, the phonegap-nfc plugin supports iOS now by adding two additional functions (beginSession & invalidateSession). Is there a way to implement those in the ionic native wrapper so people can use NFC for iOS with Ionic?

**Comment by mhartington** [comment]
@lehrenberg it should be possible to just add the 2 additional method to the class. If you're up for sending a Pull Request to add them, I'd be more than happy to walk you through it and merge it!

**Comment by lehrenberg** [comment]
@mhartington Sure thing! I opened a pull request --> #2048 
Thanks!

**Comment by lehrenberg** [comment]
So I just added the two methods. Not sure if this 100% correct though. Actually never contributed before... The pull request is #2050

**Comment by rayron** [comment]
Hi guys, I have noticed that the ionic-native nfc does not support the invalidateSession function.
I can scan nfc on my app but the invalidateSession cannot be called so the control does not return back to the ionic app?
Any suggestions or solutions would be excellent.
Thanks
