### ISSUE TITLE
ConnectSDK plugin

### ISSUE THREAD

**Issue by rguerreiro** [driftyco/ionic-native#414]
http://www.svlconnectsdk.com/docs/1-6-0/cordova/

**Comment by ghenry22** [comment]
While I'd love to see this functionality in ionic native, connectSDK seems to be essentially abandoned at this point?

**Comment by rguerreiro** [comment]
@ghenry22  I see you point. The repo isn't updated in 11 months and their twitter account last update was almost a year ago. What would you suggest instead? I mainly would like a plugin to connect to Chromecast.

**Comment by ghenry22** [comment]
I just published a cordova plugin for chromecast on iOS
https://github.com/ghenry22/cordova-plugin-chromecastios

Works well for me and I aim to maintain it and continue to implement more features / fixes as best I can.  It's published to npm as well

I have a fork of the android chromecast plugin you mentioned here:
https://github.com/ghenry22/cordova-chromecast

I have made some updates and pulled together some updates from forked repos and it is also working well for me currently for the essentials.

Once I am happy with the iOS plugin I will look into updating the android one and then ideally merging them into a single plugin with a common javascript interface hiding most of the implementation differences.

**Comment by rguerreiro** [comment]
One single plugin is the ideal solution. If you come up with that it would be great and the ionic native team should really consider supporting it. In the meantime imo we should stay with ConnectSDK.

**Comment by ghenry22** [comment]
Like I mentioned I would love to see connectsdk continuing to be supported but it really looks dead.
I started looking at it when I wanted Chromecast support as well, I found the device detection to be flaky, iOS will detect Chromecast, android won't most of the time, some times it does some times it lists it as a dial device instead and then half the features don't work. I could also not get it to stream any media to the device at all, it always returned an obscure error on load media.

I also found it to be quite heavy if you just want chrome cast support, it has multiple dependant repositories, downloads and frameworks and if it's not officially supported I didn't think I would be able to maintain it in any usable state over time.

I agree a single plugin with a common interface would be ideal, but for now there is a solution that works for both android and iOS should you need it.

**Comment by ghenry22** [comment]
I have implemented full metadata support for different media types on my chromecast plugin for iOS.  It is now pretty much feature complete for using a chromecast from iOS.  I am going to start working on some updates for the android version and then an abstraction layer to try and provide a common interface.  This might be hard as the android and ios implementations are quite different, but let's see how it goes.

**Comment by rguerreiro** [comment]
Go ahead @ghenry22 we're all with you :)

**Comment by JustMeDaFaq** [comment]
@ghenry22  did you made any progress on the android plugin?

**Comment by ghenry22** [comment]
not yet haven't had time to even start looking at it.

There is an android plugin there, you would just have to write yourself a chromecast provider which will handle the 2 different platforms for each required function and you could use the 2 plugins as is.

**Comment by JustMeDaFaq** [comment]
@ghenry22 
Your forked plugin actually erroring when compiling:
AAPT: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

Thats why i thought it isnt ready yet

**Comment by JustMeDaFaq** [comment]
Is actually anyone able to get this one to work? 
https://github.com/ghenry22/cordova-chromecast

Cant get the PlayServices to be linked correctly.

Or does someone know any other solution?

**Comment by ayyfish** [comment]
@JustMeDaFaq I've been using the ConnectSDK plugin and it works fine. I've only tested on iOS though

**Comment by JustMeDaFaq** [comment]
@ayyfish  did you may got an example project?
It compiles fine - but detects no devices.

**Comment by ayyfish** [comment]
@JustMeDaFaq Are you sure the devices you are trying to connect to are on the same network as your test device/computer

**Comment by JustMeDaFaq** [comment]
@ayyfish 
Yeah, actually porting one of my hobby projects from xamarin to ionic2. 
My Xamarin App finds my Chromecast and Fire Stick without any issues.

Could be that im doing something realy stupid

**Comment by ghenry22** [comment]
regarding the android chromecast fork it builds fine for me with latest android platform.  Just ran a test project, I have only done minimal testing and merged in a few changes from other forks to the android plugin so I can't gaurantee anything about it.

The ios plugin for chromecast works well though.

re: connectsdk - an ionic native wrapper for this would certainly make it easier to interact with and it already provides a common interface across platforms.  I think if someone could create an example project showing how to use the different connectSDK functions that could serve as a good reference for others and for the ionic-native team to look at putting together a wrapper.

I may be doing something stupid with connectSDK but I found it very hard just to find chromecast/airplay devices and stream a song, I could be doing something completely wrong though as I know some large projects (plex) were listed as using connectSDK so it can't be completely broken.

**Comment by JustMeDaFaq** [comment]
@ghenry22  Could be that you also having old playservices installed? Folder structure changed thats why the forked one doesnt work.

But yeah, an example of connect sdk or the forked one would be realy great. To ensure im not doing something very stupid currently...

**Comment by ihadeed** [comment]
Just checking in here, I see there's a long conversation going on. 

Do you need any help? Is someone working on adding this?
Is the plugin good to be added? or does it have some problems?

**Comment by JustMeDaFaq** [comment]
@ihadeed  actually got it working. Works fawleslly for me, using connectsdk 1.6.

Heres an example code:

`    testConnectSDK(){
        navigator['ConnectSDK'].discoveryManager.pickDevice().success(function (device) {
        function sendVideo () {
            device.getMediaPlayer().playMedia("http://media.w3.org/2010/05/sintel/trailer.mp4", "video/mp4");
        }

        if (device.isReady()) { // already connected
            sendVideo();
        } else {
            device.on("ready", sendVideo);
            device.connect();
        }
    })
    }
   `

As you can see, im just using the navigator way... would realy appreciate an ionic-native implementation :)

**Comment by ghenry22** [comment]
if connectSDK 1.6 is working well then it would definitely make a great addition to ionic native.  An ionic native wrapper for this with some basic examples and docs would open up airplay and chromecast functionality with a much lower learning curve to cordova developers.  This functionality really isn't there at the moment.

You could seperately add my chromecast specific plugin for ios if you wish, it's already promise based so it would be really minimal work.  Unfortunately I am don't really have the time at the moment to refactor the android chromecast plugin and try to merge the 2 into a single plugin.  There is a solid base there for Android though and if anyone wanted to help out with some pull requests against my ios plugin I would gladly merge them in and help out, just don't have the time or android native familiarity to do it all myself.

**Comment by ghenry22** [comment]
@ihadeed connectSDK seems to be dead in the water, no commits for over a year.  It's also a large and monolithic plugin.  I would suggest closing this issue as I can't see it ever getting merged unless someone else takes over maintenance of the plugin and cleans it up and updates it.
