### ISSUE TITLE
Background Geolocation , plugin_not_installed

### ISSUE THREAD

**Issue by AishApp** [driftyco/ionic-native#415]
Hi, I have added Background Geolocation plugin from "**ionic plugin add cordova-plugin-mauron85-background-geolocation**" and updated my **android** platform. But still i am receiving errors and warnings as "**Native: tried calling BackgroundGeolocation.configure, but the BackgroundGeolocation plugin is not installed**." and "**Error on Background Geolocation , plugin_not_installed**" on running. 

Please help

**Comment by ihadeed** [comment]
Are you running latest version of ionic native?

**Comment by AishApp** [comment]
I am using version 1.3.2

**Comment by ihadeed** [comment]
Update to 1.3.10

**Comment by AishApp** [comment]
Thanks a lot. Its working now. Sorry too.
