### ISSUE TITLE
Can't attach to event after upgrade to 1.3.11

### ISSUE THREAD

**Issue by bushev** [driftyco/ionic-native#419]
Expected: Listen for loadstart event
Actual: **TypeError: Bind must be called on a function**

![image](https://cloud.githubusercontent.com/assets/7535766/17643256/1b22c96a-616d-11e6-9ecd-4b2aaaf59099.png)

![image](https://cloud.githubusercontent.com/assets/7535766/17643260/41130838-616d-11e6-8b7d-caa528a0ebfc.png)

Code sample:

```javascript

import {InAppBrowser, InAppBrowserEvent} from 'ionic-native';

// Inside button handler
let browser = new InAppBrowser(`http://oauth....&client_id=${clientId}`, '_blank', 'location=yes');

browser.on('loadstart').subscribe((event: InAppBrowserEvent) => {

    if (event.url.indexOf('my-app://oauth') > -1) {
         // ...
    }
});

```

**Comment by ihadeed** [comment]
Sorry about that I did a mistake with my implementation of the observable
bind function. I'll get that fixed soon.

**Comment by ihadeed** [comment]
This is fixed now.

**Comment by bushev** [comment]
Great, thanks! 👍
