### ISSUE TITLE
Dialogs plugin, alert, 3rd option not optional

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-native#440]
If you do not supply the 3rd arg to Dialogs.alert, the one that is supposed to be optional, your app will crash. XCode reports:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'

Adding the 3rd arg fixes it.

**Comment by Boosten** [comment]
See this PR https://github.com/driftyco/ionic-native/pull/436

**Comment by ihadeed** [comment]
Closed by #436
