### ISSUE TITLE
Bower version not being updated

### ISSUE THREAD

**Issue by Boosten** [driftyco/ionic-native#448]
ionic-native-bower is still on version v1.3.10
https://github.com/driftyco/ionic-native-bower/releases

Can we add the scripts/bower.sh to the current build workflow?

**Comment by mlynch** [comment]
Thanks will get on this 👍🏼🤓

**Comment by mlynch** [comment]
Just pushed the latest release to bower and will look into adding this to our release process

**Comment by mlynch** [comment]
Cool, we now have `npm run publish` which will publish to npm and bower. cc @ihadeed

**Comment by Boosten** [comment]
Great @mlynch! I could have done that by myself actually 😳

**Comment by shanesmith** [comment]
Something doesn't seem to be working, the ionic-native-bower repo is still at v2.0.3... with only one commit even... o_o
