### ISSUE TITLE
Update CameraPreview to use maintained repository

### ISSUE THREAD

**Issue by djonesdev** [driftyco/ionic-native#450]
Requesting to have CameraPreview updated to use the maintained repository:
https://github.com/westonganger/cordova-plugin-camera-preview

The current repository (https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview) is not being maintained as per the notes on the README.md.

> June 13, 2016 - I dont have any time to work on this recently. If people want to contribute lets get a good working version over here westonganger/cordova-plugin-camera-preview with some additional features and nicer API that would be great. Then we can get it merged back to master on this repo.

**Comment by ihadeed** [comment]
I think we have an open issue regarding this.

Not sure if were moving forward with changing the repo since it's not very
clear whether the other repo is stable or not.

If the method names and parameters are the same, you can install the plugin
from the other repo and it should work fine.
