### ISSUE TITLE
Can't find PhotoViewer in ionic-native

### ISSUE THREAD

**Issue by chsakell** [driftyco/ionic-native#462]
The following statement doesn't work cause cannot find <i>PhotoViewer</i>.
```
import { PhotoViewer } from 'ionic-native';
```
The app is built with **beta 11** version and the _com-sarriaroman-photoviewer_ plugin is installed as well. Ionic-native/dist/plugins has no relative <i>d.ts</i> file. Am i missing something here?

Thanks

**Comment by ihadeed** [comment]
Make sure you have latest version of `ionic-native` installed. The one that is included by default with the ionic starter project may be not to date sometimes. 

Run `npm i --save ionic-native@latest`

**Comment by chsakell** [comment]
Fixed. Upgrading to **"ionic-native": "1.3.16"** did the trick indeed. 
Thanks a lot @ihadeed
