### ISSUE TITLE
zip plugin could not unzip gbk encoded file

### ISSUE THREAD

**Issue by sin-bufan** [driftyco/ionic-native#469]
the zip plugin can not unzip file with charset of "gbk", on android platform.
and i tried to use 
ZipInputStream zis = new ZipInputStream(inputStream, Charset.forName("GBK"));
to replace
ZipInputStream zis = new ZipInputStream(inputStream);

get compile error.
my java SDK is 1.8,and from 1.7, ZipInputStream did support the second parameter.

**Comment by ihadeed** [comment]
Ionic Native provides only a wrapper to that plugin.

The code you're using doesn't look familiar anyways, please have a look at our documentation for the ionic-native usage of the plugin: http://ionicframework.com/docs/v2/native/zip/

If you have questions that have to do with the native code of the plugin, please contact the developer at their repo https://github.com/MobileChromeApps/cordova-plugin-zip

**Comment by sin-bufan** [comment]
thanks for the reply!
