### ISSUE TITLE
Todo: Add directions plugin

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic-native#470]
See this simple plugin [here](https://github.com/leecrossley/cordova-plugin-directions).

**Comment by ihadeed** [comment]
We have an awesome navigation plugin by EddyVerbruggen already implemented. Checkout http://ionicframework.com/docs/v2/native/launch-navigator/

**Comment by dylanvdmerwe** [comment]
Ah that's awesome. Closing issue.
