### ISSUE TITLE
BarcodeScanner plugin options don't appear to work

### ISSUE THREAD

**Issue by daveshirman** [driftyco/ionic-native#471]
I've tried calling the plugin 2 ways to change the text displayed at the bottom:

```
      BarcodeScanner.scan({
        prompt: 'Hello'
      }).then((data) => {
      });
```

and

```
      BarcodeScanner.scan({
        "prompt": 'Hello'
      }).then((data) => {
      });
```

Neither works and the plugin fails to load up the scanner.

I get the error:

```
BarcodeScanner.scan failure: success callback parameter must be a function
```

Is it me or is it you?

**Comment by jamesgroat** [comment]
Options seem to work for me. Are you using iOS? Prompt only works on Android. From the docs:

> "prompt" : "Place a barcode inside the scan area", // supported on Android only

**Comment by daveshirman** [comment]
Nope. Android.

**Comment by ihadeed** [comment]
@daveshirman what version of ionic native are you using?

**Comment by daveshirman** [comment]
@ihadeed Good idea....updated absolutely everything I could and the parameter now works.  Thanks.
