### ISSUE TITLE
Ionic 2 Beta 11: Ionic Native missing method setAllowIDFACollection(allow).

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#473]
_From @chocolei on August 24, 2016 10:34_

http://ionicframework.com/docs/v2/native/google-analytics/

Related to the plugin, I cannot find the GoogleAnalytics.setAllowIDFACollection(bool) method in ionic-native.

_Copied from original issue: driftyco/ionic#7849_

**Comment by ihadeed** [comment]
Make sure you're running latest version of Ionic Native. That function along with other missing functions were added in v1.3.15

**Comment by ihadeed** [comment]
Closing this for now, if you still experiencing issues after updating `ionic-native` please let me know and we can re-open this.
