### ISSUE TITLE
Ionic 2, Beta 11, Ionic Native SocialSharing missing method 'canShareViaEmail'

### ISSUE THREAD

**Issue by tomgallagher** [driftyco/ionic-native#477]
Hi

I'm getting this error message:

`Error: Uncaught (in promise): TypeError: Object function SocialSharing() { } has no method 'canShareViaEmail'`

I have added the plugin, I can see it in the package.json, I have done ionic state save, the code is very simple:

```
import {SocialSharing} from 'ionic-native';

this._platform.ready().then(() => {
      
        SocialSharing.canShareViaEmail().then(() => {
          console.log("Sharing via email is possible");
        }).catch(() => {
          console.log("Sharing via email is not possible");
        }); 

}
```

My package.json looks like this:

```
{
  "dependencies": {
    "@angular/common": "2.0.0-rc.4",
    "@angular/compiler": "2.0.0-rc.4",
    "@angular/core": "2.0.0-rc.4",
    "@angular/forms": "0.2.0",
    "@angular/http": "2.0.0-rc.4",
    "@angular/platform-browser": "2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "2.0.0-rc.4",
    "@angular/router": "^2.0.0-rc.2",
    "es6-shim": "0.35.0",
    "ionic-angular": "2.0.0-beta.11",
    "ionic-native": "^1.3.10",
    "ionicons": "3.0.0",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "0.6.12"
  },
```

Any ideas? Help would be much appreciated.

Tom

**Comment by tomgallagher** [comment]
Just a quick update:

This code works:

```
SocialSharing.canShareVia('whatsapp', 'Test whatsapp Message', null, null, null).then(() => {
          console.log("Sharing via whatsapp is possible");
        }).catch(() => {
          console.log("Sharing via whatsapp is not possible");
        });
```

So it's not a problem with my installation, use of the plugin.

This code doesn't:

```
SocialSharing.canShareViaEmail().then(() => {
          console.log("Sharing via email is possible");
        }).catch(() => {
          console.log("Sharing via email is not possible");
        });
```

And neither does this:

`SocialSharing.shareWithOptions(options, onSuccess, onError);`

The report I'm getting from the Android device in Chrome Dev Tools for the second and third is of this type:

```
ORIGINAL EXCEPTION: TypeError: Object function SocialSharing() {
    } has no method 'shareWithOptions'
```

So I imagine I'm just getting the syntax wrong or the code hasn't been written for these functions in Ionic Native yet.

Any chance of some feedback?

Thanks for your time.

Tom

**Comment by ihadeed** [comment]
What version of Ionic Native?

**Comment by tomgallagher** [comment]
"ionic-native": "^1.3.10",

**Comment by tomgallagher** [comment]
from package.json

**Comment by ihadeed** [comment]
That's strange, the method was added in 1.3.8. Try updating to the latest version anyways since you're 7 versions behind. Run `npm i --save ionic-native@latest`

**Comment by tomgallagher** [comment]
Will do. I'll report back. Syntax for failing two looked OK?

**Comment by ihadeed** [comment]
Not sure what you mean.

**Comment by tomgallagher** [comment]
I just mean that you couldn't see any basic errors in the code I've pasted

**Comment by ihadeed** [comment]
No it looks alright

**Comment by tomgallagher** [comment]
Ok the updated worked. Thanks for the pointers.
