### ISSUE TITLE
Add direction plugin(Digital Compass)

### ISSUE THREAD

**Issue by 05bca054** [driftyco/ionic-native#500]
Where app user current latitude and longitude and destination latitude longitude(Based on given degrees by google map).

It  proves best for various location base application.

The compass heading in degrees. Please find below link. If digital compass plugin combined with direction given by google maps API(http://www.w3schools.com/googleAPI/ref_getheading.asp) then it will be the great  User Experience for application user.

**Comment by ihadeed** [comment]
I'm not sure what are you asking for here. Is there a specific plugin that you're requesting to be added? If so, please provide the repository link so we can have a look. 

I can't find anything that's called "digital compass plugin" on Google.  Also, the link you provided no longer exists.
