### ISSUE TITLE
animateCamera on maps does not have callback in ionic native but it does in the original plugin

### ISSUE THREAD

**Issue by morcth** [driftyco/ionic-native#511]
Hello,

I am trying to show a marker after the map has finished animating. I read in the cordova plugin today that animate and move camera both have callbacks as does addMarker. 

I tried using a promise with animateCamera like I successfully did with addMarker and it did not work.

Looking at the ionic native code for animate camera, it does not have the callback function associated with it like addMarker does. 

I am new to angular 2... am I looking at it correctly?

I guess I can use a timeout function to place the marker but it seems like animateCamera lost a piece of it coming to ionic native?

Thanks for any info

**Comment by ZiFFeL1992** [comment]
You are right: https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map#move-the-camera

**Comment by morcth** [comment]
Thanks for looking into it!

I realize now I should have pasted that link in there to save you some time.... sorry about that.

I was able to create the effect I want with a 5 second timeout function but it feels a little sloppy to me.

**Comment by ihadeed** [comment]
thanks @morcth @ZiFFeL1992

**Comment by morcth** [comment]
@ihadeed Thanks!

Noob question: How do I update my project to use the new file? I tried npm update but it stayed at 1.3.1.

Do I make the changes to the files in node-modules myself or is there some command I can run?

Thanks

**Comment by ihadeed** [comment]
I usually use `npm i --save ionic-native@latest` and it does the job. @morcth

**Comment by morcth** [comment]
That did it! Thanks again for the work you are doing.

**Comment by Binitronics** [comment]
Is this issue resolved?
