### ISSUE TITLE
File plugin createDir function replace parameter

### ISSUE THREAD

**Issue by xmellado** [driftyco/ionic-native#516]
Hi!
The `replace` parameter in `createDir(path, dirName, replace)` function inside the file plugin is not properly implemented. It should be negated. Currently, when replace is true, if the directory exists, an error is thrown. When replace is false, if the directory exists, it is replaced. The behaviour should be opposite.

It is the same fix applied to the function createFile() in commit https://github.com/driftyco/ionic-native/commit/14e41a31ef043b94e5404939de6cd279b03b68ab.

Best regards,
                     Xavi

**Comment by ihadeed** [comment]
thanks
