### ISSUE TITLE
google maps places

### ISSUE THREAD

**Issue by sonic182** [driftyco/ionic-native#521]
there is any way to load places library with google maps? there is any plan to make that class too?

**Comment by ZiFFeL1992** [comment]
You should ask for support on Google Maps repo, this is just a wrapper...

**Comment by sonic182** [comment]
Well, I wanted to do what [Geocoder](https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Geocoder) does on [cordova-plugin-googlemaps](https://github.com/mapsplugin/cordova-plugin-googlemaps)

well I guess I've to close this issue

**Comment by ZiFFeL1992** [comment]
You can use geocoder but works in english and you can't change language (in my case this is a problem).

BTW the perfect combination is to use both, Google Places and Geocoder, but from cordova-plugin-googlemaps you can only use geocoder.
