### ISSUE TITLE
Ionic 2, Beta 11, Ionic Native InAppBrowser, insert CSS

### ISSUE THREAD

**Issue by tomgallagher** [driftyco/ionic-native#522]
Hi Ibrahim

InAppbrowser.ts, line 88:

`insertCss(css: {file?: string, code?: string}): Promise<any> {return; }`

This is a typo? I imagine as the Ionic Native docs notes say insertCSS, this might cause a few headaches.

Also, even when I've changed it and got rid of the insertCSS no method error, I'm still getting a unresolved promise error from this code.

```
this.browser.insertCss( { file:  "https://s3-eu-west-1.amazonaws.com/some.css" } ).then( () => {
          console.log("Custom Alert CSS Loaded");
});
```

Any ideas?

Thanks

Tom

**Comment by tomgallagher** [comment]
FYI - I just caught the error from the promise rejection and it's a TypeError. Not getting any more than that at the moment.

**Comment by tomgallagher** [comment]
Actually I was half wrong about the docs. In the USAGE bit, it says:

`browser.insertCSS(...);`

But in the INSTANCE MEMBERS below that, it has:

`insertCss(css)`

Hope that helps.

**Comment by ihadeed** [comment]
Hey there,

The original plugin's API only has one callback for success that gets called if the CSS was inserted successfully. So the promise will never reject unless if an error occurred inside the Ionic Native code.

If you can give me more information related to the error that would be great.

**Comment by tomgallagher** [comment]
Hi Ibrahim

 

I'm developing on Cloud9 so I have no access to an emulator and cannot
directly connect to a device.

 

I'm having to download the apk and then debug using Chrome Dev Tools.

 

As a result, the error messages and stack traces are very limited: I've
given you all I can get.

 

Sorry.

 

Tom

 

  _____

**Comment by ihadeed** [comment]
Hey I just tried using `insertCSS` and it worked. Maybe the remote the URL you're using isn't white listed? or perhaps it could be some CORS issues?

**Comment by tomgallagher** [comment]
Hey there, 

I  just sidestepped it in the end by using the execute script to add the css. There's no real magic in the insertCSS routine so I don't feel like I'm missing much.

As a sidenote, I've been developing quite heavily with the InAppBrowser over the last three weeks. Some things I've found, which you may or may not know:

1) Do not use the InAppBrowser with WKWebView on IOS, it's like jumping into a bag of snakes. Events get fired by the window rather than the URL loading, it's a total nightmare.

2) on IOS, the executeScript with code seems to work much more reliably that the execute script with a file, this may also be a CORS issue, but it was intermittent and therefore hard to debug.

In general, the InAppBrowser behaves as you would expect in Android, all the time, and is a bit flaky with IOS. I mean the plugin, not your native stuff.

I've not quite found a use for the loadstart event either, as it seems to happen too early to actually do anything, there's no URL, no document, nothing.

Anyway, just a few thoughts and thanks for all the work on the native stuff.

Tom

**Comment by ihadeed** [comment]
@tomgallagher one solution could be to use the SafariView plugin for iOS to avoid these issues.

Thanks for the information btw!

**Comment by tomgallagher** [comment]
Pretty sure the SafariView plugin does not offer executeScript sadly

**Comment by tomgallagher** [comment]
Hi Ibrahim

 

I've got a dumb question for you.

 

I've just moved over to Typescript with RC0.

 

Say I'm using AppRate, through Ionic Native.

 

How do I stop the Apprate commands in the code causing Typescript compile
errors on npm run build?

 

Some of the plugins have their own stuff at npm @types but AppRate does not.

 

Thanks

 

Tom 

 

  _____

**Comment by mlynch** [comment]
@tomgallagher the types come from ionic-native, so they will be available for any plugin that we support

**Comment by tomgallagher** [comment]
Hi

That's weird then, because I had the AppRate import from Ionic Native and the compiler was complaining about these two commands:

`AppRate.preferences = {}`

`AppRate.promptForRating();`

That's kind of what I thought should be happening. All the other ones you support were working just fine. Just Apprate causing these issues.

Thanks for getting back though.

**Comment by ihadeed** [comment]
Can you share the code you are using, as well as the errors that you're
getting. Please specify what kind of errors are they, from IDE, compiler,
or browser/debugger.

FYI, the .promptForRating method takes a boolean as a parameter. To decide
whether you want to prompt for rating now, or prompt when the user uses the
app X times (depending on usesUntilPrompt property).
