### ISSUE TITLE
Discussion: Add event wrappers

### ISSUE THREAD

**Issue by ihadeed** [driftyco/ionic-native#53]
Some plugins have events that the user can listen to. Some of them even depend on those events completely, such as battery status plugin:
https://github.com/driftyco/ionic-native/blob/master/src/plugins/batterystatus.ts#L33-L51

I thought we can add a new wrapper to the the cordova decorator. The plugin will basically wrap that event with an observable.

This:
```ts
  static onChange () : Observable<StatusObject> {
    return getEventObservable("batterylevel"); 
  }
```
FYI, The definition for getEventObservable() can be found here: https://github.com/driftyco/ionic-native/blob/master/src/plugins/batterystatus.ts#L72-L78

Will become this:

```ts
@Cordova({
  eventObservable: true,
  event: 'batterylevel'
})
static onChange () : Observable<StatusObject> { return } // return value will be overwritten by @Cordova decorator
```

**Comment by tlancina** [comment]
I think this is great, unsubscribing removes the event listener :+1:
