### ISSUE TITLE
switchtoSettings unavailable in plugin Diagnostic

### ISSUE THREAD

**Issue by zefrench** [driftyco/ionic-native#530]
It seems the typescript file for the plugin "Diagnostic" is not complete.
The function switchToSettings' does not exist and we get this error:
-error in typescript saying: Property 'switchToSettings' does not exist on type 'typeof Diagnostic'

Did you notice it ?

**Comment by ramonornela** [comment]
I believe it was resolved in 1.3.18, exists problem with documentation in ionic-site issue https://github.com/driftyco/ionic-site/issues/771 current [documentation](http://ionic-site-staging.herokuapp.com/docs/v2/native)

**Comment by zefrench** [comment]
Sorry, but it does not appears even with this ionic-native version.

**Comment by ramonornela** [comment]
See https://github.com/driftyco/ionic-native/blob/9c8321d3b4c6f2bd22662e312a13064aceb8171b/src/plugins/diagnostic.ts#L336

**Comment by ihadeed** [comment]
Hey Alex,

Can you run `npm i --save ionic-native@latest`

That will update your ionic native to the latest version and it should fix
the problem.

**Comment by zefrench** [comment]
Thanks Ihadeed !
It works !!
