### ISSUE TITLE
Allow disabling of warnings

### ISSUE THREAD

**Issue by remcohaszing** [driftyco/ionic-native#531]
I'm using `ionic-native` in a project which may run in Cordova, but also in the browser. When running in the browser, this shows annoying warnings. Additionally I've configured tests to fail whenever a warning is logged.

It would be great if these warnings could be disabled. For example by using something such as:

```js
$cordovaProvider.disableLogging();
```

**Comment by ihadeed** [comment]
Are you using ionic 1? You can edit the JavaScript file, search  `console.`
and remove them manually. This will do the job for now.
