### ISSUE TITLE
Module Size (let's modularize/tree shake)

### ISSUE THREAD

**Issue by dwieeb** [driftyco/ionic-native#535]
Ionic Native is one big module. I can't add Device code from Ionic Native without getting YouTube Video Player code. I saw in one project that it added ~1.5mb to an unminified bundle.

Let's fix this!

We have two options: _modularize_ into super tiny modules **or** use _tree shaking_

### Modularization

For modularization we'd need to publish a bunch of npm packages.

- `@ionic/native-core` - core module that all others would depend on
- `@ionic/native-device`
- `@ionic/native-youtube-video-player`

This would inconvenience devs (they'd need to install and import from different modules) and would require quite a bit of refactoring and updates to the build system.

### Tree shaking

The second option is tree shaking, which involves exporting an additional dist format. 

Right now we target `es5` with module type `commonjs`: https://github.com/driftyco/ionic-native/blob/master/tsconfig.json#L3-L4

We'd need to target `es5` with module type `es2015`. We'd keep the commonjs stuff, but have a subdirectory for rollup: `dist/esm`. In `package.json` we'd need `module: "dist/esm/index.js"`.

This would benefit people using rollup (i.e. Ionic 2 apps beta 12+) and would be convenient to developers. It would take a few changes to the build system but we should already know how to do this from Ionic itself

**Comment by mlynch** [comment]
Awesome. I definitely vote Tree Shaking, I think modularization is going to cause way more friction than it's worth.

So, can we target two module formats with tsconfig and output to separate directory?

**Comment by mlynch** [comment]
I've got some initial changes in this branch: https://github.com/driftyco/ionic-native/pull/538

I'm having trouble getting TS to find the rxjs/Observables. To test, run `npm run build:esm`

**Comment by dwieeb** [comment]
Nice, that's how I was going to recommend multiple TS outputs.

Can it not find rxjs because the module type is no longer commonjs?

Try adding `"moduleResolution": "node",`

**Comment by mlynch** [comment]
@dwieeb you dog! That did it 👍 Forgot that

**Comment by mlynch** [comment]
Landed in 7f77b8f06944a887c4b6e33593fdf5ef7fcfb3f4. Can you give it a try?
