### ISSUE TITLE
import {File Opener} from 'ionic-native' not working

### ISSUE THREAD

**Issue by sd5869** [driftyco/ionic-native#543]
![image](https://cloud.githubusercontent.com/assets/8257951/18424926/3a5e0dfe-78d2-11e6-9686-ae84f541c2d8.png)
![image](https://cloud.githubusercontent.com/assets/8257951/18424955/955f2d1e-78d2-11e6-8bd2-caaafe921673.png)

to reproduce the issue try to import FileOpener in a blank project.

**Comment by ihadeed** [comment]
Update to `ionic-native@1.3.21`
