### ISSUE TITLE
$cordovaGeolocation issue

### ISSUE THREAD

**Issue by RTK** [driftyco/ionic-native#544]
Hi,

i get the following error (with stacktrace) using the newest version (1.3.21):

angular.js:13920 TypeError: Cannot read property 'get' of undefined
    at getPromise (app.js:13234)
    at wrapPromise (app.js:13251)
    at Function.<anonymous> (app.js:13382)
    at Function.value [as getCurrentPosition] (app.js:13433)

when calling
`
$cordovaGeolocation
            .getCurrentPosition({
                enableHighAccuracy: true
            })
`

watchPosition works btw

**it works when using 1.3.10**

**Comment by cambronjay** [comment]
You need to import the  ionic native plugin and use it instead.

**Comment by RTK** [comment]
But why does it work with version 1.3.10 ? It thought on angular 1 it falls back to the ngCordova module which works as an angular module and allows me to inject this service into my controller

**Comment by ihadeed** [comment]
Does it work with v1.3.20?

**Comment by ihadeed** [comment]
@RTK we did some modifications to the ng1 support in 1.3.21 and I suspect that it might be causing the issue. Which is why I'm asking if it works with 1.3.20

**Comment by RTK** [comment]
It works in 1.3.20

**Comment by mlynch** [comment]
@RTK how are you bootstrapping your Angular app?
