### ISSUE TITLE
CallNumber not working if passed number instead of string

### ISSUE THREAD

**Issue by aggarwalankush** [driftyco/ionic-native#545]
`    CallNumber.callNumber('4083868925', false);`  - this works
`    CallNumber.callNumber(4083868925, false);`  -  this fails

As mentioned in `call-number.d.ts`, numberToCall is expected in number format but it fails on real device. Passing numberToCall in string format works.

```
/**
 * @name CallNumber
 * @description
 * Call a number directly from your Cordova/Ionic application.
 *
 * @usage
 * ```
 * import {CallNumber} from 'ionic-native';
 *
 * CallNumber.callNumber(18001010101, true)
 *   .then(() => console.log('Launched dialer!'))
 *   .catch(() => console.log('Error launching dialer'));
 *
 * ```
 */
export declare class CallNumber {
    /**
     * Calls a phone number
     * @param numberToCall {number} The phone number to call
     * @param bypassAppChooser {boolean} Set to true to bypass the app chooser and go directly to dialer
     */
    static callNumber(numberToCall: number, bypassAppChooser: boolean): Promise<any>;
}
```

Also, behind the scenes, ionic-native uses `https://github.com/Rohfosho/CordovaCallNumberPlugin `which also expects numberToCall in string.

**Comment by candelibas** [comment]
+1

**Comment by ihadeed** [comment]
thanks for pointing it out, it's fixed now and the fix will be available in the next release
