### ISSUE TITLE
pluginObj._objectInstance is causing problems

### ISSUE THREAD

**Issue by VietAnhh** [driftyco/ionic-native#546]
I'm having trouble figuring out why it's saying this. 

`TypeError: undefined is not an object (evaluating 'pluginObj._objectInstance')`

Can anyone help me out on what exactly is causing this?

I'm using sqlite and this error shows up on xcode

**Comment by ihadeed** [comment]
Would need more details.

- Code that causes this issue
- Plugin that you're trying to use 
- platform you're testing on

**Comment by VietAnhh** [comment]
@ihadeed I switched over to SqlStorage just because of the massive headache trying to figure out that bug T.T sorry but thanks for the response though! I would of provided the code just in case anyone else had the problem but I erased my whole service to start fresh with sqlstorage.

**Comment by ihadeed** [comment]
Hey

Can you share the code that you are using? Also what platform are you
running on?
