### ISSUE TITLE
Issue with typepings for googlemaps

### ISSUE THREAD

**Issue by danielgek** [driftyco/ionic-native#547]
Hello, today i was using googlemaps plugin and i was trying to move camera using `GoogleMapsLatLngBounds` as target, because i want the camera to zoom accordingly with the array of points i have set, but as i'm using typescript, the current typings only accept `GoogleMapsLatLng`.

changing the typing from this:

````
export interface CameraPosition {
    target?: GoogleMapsLatLng;
    zoom?: number;
    tilt?: number;
    bearing?: number;
}
```
to:
````
export interface CameraPosition {
    target?: GoogleMapsLatLng | GoogleMapsLatLngBounds;
    zoom?: number;
    tilt?: number;
    bearing?: number;
}
```
fix the issue

**Comment by ihadeed** [comment]
thanks

**Comment by danielgek** [comment]
wow that was fast !! thanks you

**Comment by danielgek** [comment]
@ihadeed you should add `GoogleMapsLatLng[]` too, sorry for not mention early! i just noticed in the [documentation](https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map.animateCamera()) and i don't have sure but `animateCamera` may need it too.

thanks
