### ISSUE TITLE
showAppSettings() missing from BackgroundLocation plugin

### ISSUE THREAD

**Issue by giltotherescue** [driftyco/ionic-native#548]
According to the cordova plugin's docs there should be a function called showAppSettings():

https://github.com/mauron85/cordova-plugin-background-geolocation#showappsettings

However this function does not in the ionic-native plugin: http://ionicframework.com/docs/v2/native/backgroundgeolocation/

**Comment by ihadeed** [comment]
Thanks for pointing it out.. It's added now and will be available in the next release.

**Comment by giltotherescue** [comment]
Thank you 👍
