### ISSUE TITLE
Discrepancy between JSDoc and source in camera.ts

### ISSUE THREAD

**Issue by bvx89** [driftyco/ionic-native#550]
There is a discrepancy between the jsdoc and source code of the camera.ts with the `cleanup()`-method for the return type.

**JSDoc**:
`@return Returns a Promise`

**Source code**:
Empty (aka. `void`)

This needs to be updated in the source code if the cleanup actually returns a promise.

**Comment by ihadeed** [comment]
Thanks. The function does return a promise. Fixed it now.
