### ISSUE TITLE
$cordovaNetwork/Network onDisconnect is not working

### ISSUE THREAD

**Issue by BioPhoton** [driftyco/ionic-native#551]
Here's my code:

```
this.$cordovaNetwork.onDisconnect()
        .subscribe(() => {console.log('onDisconnect');});
this.$cordovaNetwork.onConnect()
        .subscribe(() => {console.log('onConnect');});
```

onConnect is working well but i never get an onDisconnect message.

**Comment by ihadeed** [comment]
Try using the following code instead and let me know if it works or not:

```
document.addEventListener('offline', () => console.log('onDisconnect'));
```

**Comment by BioPhoton** [comment]
This will work for shur. But it is not the $cordovaNetwork module.

My current solution uses the "vanilla" cordova binding.

```
constructor($rootScope:ng.IRootScopeService) {
      this.$scope = $rootScope.$new();

      this.offlineSubject = new Rx.Subject();
      this.onlineSubject  = new Rx.Subject();

      this.isOnline = this.getOnlineState();
      this.message = 'Offline';

    }

    $onInit():void {

      document.addEventListener("offline", () => { this.offlineSubject.onNext('OFF');}, false);
      document.addEventListener("online",  () => { this.onlineSubject.onNext('ON');}, false);

      let offStream = this.offlineSubject.map((x) => {return false});
      let onStream = this.onlineSubject.map((x) => {return true});

      Rx.Observable.merge(offStream, onStream)
        .subscribe(
          //onNext
          (isOnline) => {
            this.isOnline = isOnline;
            this.$scope.$apply();
          },
          //onError
          () => { this.networkSubscription.unsubscribe(); },
          //onComplete
          () => { this.networkSubscription.unsubscribe(); }
        );

    }

    $onDestroy(): void {
      this.networkSubscription.unsubscribe();
    }


    getOnlineState():boolean {
      return navigator.connection.type !== Connection.NONE;
    }
```

What i would like to have is something like this:

this.$cordovaNetwork.onDisconnect()
      .map((value) => { return true })
      .subscribe(
//onNext
          (isOnline) => {
            this.isOnline = isOnline;
            this.$scope.$apply();
          },
          //onError
          () => { this.networkSubscription.unsubscribe(); },
          //onComplete
          () => { this.networkSubscription.unsubscribe(); }
);


Unfortunately the ionic-native function IMHO is not returning a real observable, it's the subscription i beleive. 
I wondering if there is a special reason to not return the observable.

**Comment by BioPhoton** [comment]
Hi @ihadeed.
To be more specific i want to merge the offline and online stream. 

```
 Rx.Observable.merge(offlineStream, onlineStream)
.subscribe(
          (x) => {},
          (e) => {},
          (c) => {},
       }
```

I tried to understand the code of ionic native. It looks like the wrappers are compiled automatically or so.
Where is the wrapper function for the Network.onConnect function? Its not really clear for me how this code gets generated.

@ihadeed am i right that i cant use the Network plugin to merge the online and offline stream?

**Comment by mlynch** [comment]
Hmm, I wonder if this is related to moving to a new rxjs import. Also the fact that this uses `eventObservable` might be where this issue is happening.

**Comment by BioPhoton** [comment]
Hy Max, nice that you took this one.
For my shame I was not able to find the real Code of the Network thing. 
I would investigate in this if someone could show me where this Code is. 

I reacently finished a big Projekt with ionic and rx. Pretty awesome to work with rx. 😀 

Would love to investigate in this bug...

**Comment by mlynch** [comment]
No worries, taking a look now. Was able to reproduce...

**Comment by mlynch** [comment]
Actually, I wasn't able to reproduce this. This works fine for me in the most recent release:

```javascript
    $cordovaNetwork.onDisconnect().subscribe(() => {console.log('onDisconnect'); alert('onDISCONNECT');});
    $cordovaNetwork.onConnect().subscribe(() => {console.log('onConnect'); alert('onCONNECT');});
```

Am I missing something?

**Comment by mlynch** [comment]
Also the object that this returns is a real observable:

https://github.com/driftyco/ionic-native/blob/master/src/plugins/plugin.ts#L227

**Comment by mlynch** [comment]
One thing...you're using ES6 arrow functions which aren't universally supported. Not sure if you're transpiling, but that would certainly keep this from working on, say, iOS

**Comment by BioPhoton** [comment]
Hy, sry for answering so late. THX for your time! I updated all libs and now it is working fine...

**Comment by BioPhoton** [comment]
PS: I use typescript and yes, i transpile.
