### ISSUE TITLE
File api is incomplete (e.g. getFreeDiskSpace, writeFile) and docs is incomplete (e.g. readAstext)

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#552]
_From @dragGH102 on September 14, 2016 15:34_

I'm using Ionic 2 latest beta (37) and trying to work with files (**File** plugin @ ionic-native).

Some methods (readDire, writeDir, ...) work normally.
However others are either **missing** (not implemented as per also in the Typescript definitions), for example:

- getFreeDiskSpace
- writeFile

or lacking a **proper documentation**. For example...

- readAsText: how to do it **without overriding a file**? (apparently the only way to get a FileEntry is a createFile/writeFile  but both either override the file or throw an error if it exists and replace = false). Eventually refer to my SO question at http://stackoverflow.com/questions/39494174/how-to-get-a-fileentry-to-then-use-readastext-in-cordova-ionic2

I understand this is still a beta but I was wondering if this is intentional of a "work in progress" (in which case feel free to close this issue)?
Thank you

_Copied from original issue: driftyco/ionic#8080_

**Comment by ghenry22** [comment]
Actually getfreediskapace is implemented in the native code but has no JavaScript interface in the plugin itself, been this way forever, you can run a Cordova.exec command to access the native function, this could be implemented in the ionic native wrapper I guess

**Comment by ghenry22** [comment]
This is all that is required and it could be implemented in the ionic-native wrapper for the getFreeDiskSpace call.  The platform detection is to adjust the returned result to be in a consistent format on both android and ios.

```
//file plugin has no js interface to getfreediskspace method
//use cordova.exec directly to access it.
  getFreeDiskSpace(): number {
    var freeDiskSpace: number;
    cordova.exec(function(result) {
      //console.log(result);
      if(isAndroid){
        freeDiskSpace = (result*1000);
      }
      if(isIos){
        freeDiskSpace = (result-512000000);
      }
      return freeDiskSpace;
    }, function(error) {
      //console.log(error);
    }, "File", "getFreeDiskSpace", []);
  }
```

**Comment by ihadeed** [comment]
@ghenry22 thanks for suggestion, just implemented this. However, I'm just returning back the raw response from the native code, not modifying anything based on platform.

**Comment by ihadeed** [comment]
@dragGH102 @ghenry22 Can you try with the latest version v2.2.2 and report back if you still have any issue? Thanks.
