### ISSUE TITLE
Geolocation error condition missing

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic-native#554]
Not sure if missing from [docs](http://ionicframework.com/docs/v2/native/geolocation/) or plugin. 

```
navigator.geolocation.getCurrentPosition((position) => {
                }, (error) => {
                }, options);
```

**Comment by ihadeed** [comment]
It's just missing from the docs.

You can add `.catch()` or add another function (as a second parameter) inside the `.then()`

**Comment by dylanvdmerwe** [comment]
Yes, this was an issue to note that the documentation should be updated.

**Comment by ihadeed** [comment]
@dylanvdmerwe just updated the docs, they should be available in the next docs update
