### ISSUE TITLE
VideoPlayer - ionic-native has no exported member

### ISSUE THREAD

**Issue by aljibbs** [driftyco/ionic-native#556]
I have created an app with ionic 2 and when I tried using the VideoPlayer plugin from ionic-native, I got an error that there is no exported member like that. I looked into the node_modules of the app, looked into the ionic-native folder's plugins' folder and realized it was different from the one hosted here. There are certain plugins like the videoplayer that are not in the ionic-native plugins folder. Please help. I just reinstalled ionic using npm install -g ionic but still didnt fix it

**Comment by ihadeed** [comment]
Make sure you're using the latest version of `ionic-native`. Check your package.json. To update just run `npm i --save ionic-native@latest`.

**Comment by aljibbs** [comment]
I run the npm code you gave and yes, now the plugin is part of the modules but there is still a problem, the videoplayer plugin was not exported in the index.d.ts file. I did it myself to make the compiler happy though and now I could reference it from my page but after all that my video file still does not play. There are some plugins that are still not exported like the videostream plugin.
