### ISSUE TITLE
Getting pluginWarns messages when plugin is called before platform is ready

### ISSUE THREAD

**Issue by NoNameProvided** [driftyco/ionic-native#560]
When I launching the app I call `Splashscreen.hide();` in different places. One flow can be so fast that `platform.ready()` is not fired yet. When this happens I got a plugin warning message: 

```bash
Native: tried calling Splashscreen.hide(), but the Splashscreen plugin is not installed.
```

Of course this happens because it was called before the device ready event but I think calls to Ionic Native plugins should wait for the device ready event and fire the call after it. So we don't have to embed the calls into `platform.ready()` like this: 

```ts
platform.ready().then(() => {
  Splashscreen.hide();  
});
```

One can say it adds performance overhead to call `platform.ready()` every time before calling a plugin function, but I don't think it would make any noticeable difference.

If this was discussed and dropped in the past for some reason then the error messages should be rewritten at least to warn about need of `platform.ready()`. Something like:

```
Native: tried calling Splashscreen.hide(), but the Splashscreen plugin is not installed or was called before the deviceready event.
```

**Comment by mlynch** [comment]
Thanks, I think it would be cool to have all calls Just Work, but in the meantime we can tweak the error message.

**Comment by mlynch** [comment]
Going to let this one sit for a bit
