### ISSUE TITLE
TODO: Add Custom Config Parameters plugin for better security

### ISSUE THREAD

**Issue by deep113** [driftyco/ionic-native#562]
This plugin allows you to store your sensitive data such as passwords, usernames etc. in config.xml. This is stored by creating custom parameters in config.xml. In the runtime, these parameters can be read from config.xml and used in javascript code. This really helps in creating next level of security for cordova based apps.

https://github.com/experiencecommerce/cordova-plugin-customconfigparameters

**Comment by mlynch** [comment]
I don't think this is true, it's easy to inspect a bundled APK or IPA file and find config.xml to read passwords. You should never store sensitive API keys or passwords on the client, except in the keychain if you must. There they are protected by device level encryption but even then you should keep secrets on the server.

**Comment by deep113** [comment]
i have used all the things but i dont get it.
it is available in encrypted format
