### ISSUE TITLE
VideoPlayer plugin missing from ionic-native modules

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#563]
_From @aljibbs on September 19, 2016 11:30_

Cannot import VideoPlayer from the native library (ionic-native) even after downloading the plugin via the ionic 2 docs page. Error says there is no exported member. I have tried lots of solutions online but it just didn't work. I also realized that the plugin is not in the ionic-native modules folder. Is there a problem or is there a special way to get it to work ?

_Copied from original issue: driftyco/ionic#8119_

**Comment by mlynch** [comment]
Should be fixed, @aljibbs can you try the latest version in master?

**Comment by ramonornela** [comment]
@mlynch but it was not exported in line 148
