### ISSUE TITLE
PhotoViewer plugin missing from ionic-native modules

### ISSUE THREAD

**Issue by anand-parmar** [driftyco/ionic-native#565]
Cannot import PhotoViewer from the native library (ionic-native) even after downloading the plugin via the ionic 2 docs page. Error says  has no exported member 'PhotoViewer'. I have tried lots of solutions online but it just didn't work. I also realized that the plugin is not in the ionic-native modules folder. Is there a problem or is there a special way to get it to work ?

**Comment by ihadeed** [comment]
Update to latest version of ionic-native

**Comment by anand-parmar** [comment]
thank you
