### ISSUE TITLE
Ionic native Email Composer not working in Android 5 & 6 

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#568]
_From @PabloFNK on September 22, 2016 15:47_

The Cordova plugin used by Ionic Native as Email Composer is not working. We have tested it using Android 5 and Android 6 and none of them worked.

The plugin hasn't been updated since 2 years ago so it is not going to be fixed.

We have finally moved to use directly another cordova plugin ([https://github.com/hypery2k/cordova-email-plugin], which is a fork but currently supported) and it's working.

Could the Ionic Native Email Composer be updated to use this one?

_Copied from original issue: driftyco/ionic#8174_

**Comment by mlynch** [comment]
@PabloFNK is the API the same? i.e. if we just update the plugin we tell people to install, will it Just Work?

**Comment by PabloFNK** [comment]
Yes, the API provided is the same.

**Comment by mlynch** [comment]
Thanks, I added the new plugin, mind trying?

**Comment by PabloFNK** [comment]
Hi guys, 

how can we get the version with the change from npm as this is not in any stable version?
