### ISSUE TITLE
Cant compile app after upgrading ionic-native

### ISSUE THREAD

**Issue by JustMeDaFaq** [driftyco/ionic-native#570]
Hi,
ive upgraded by using:

npm i --save ionic-native@latest

Now im getting following errors:

> TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/apprate.d.ts(46,21): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/apprate.d.ts(46,32): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(36,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(36,16): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(37,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(37,25): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(38,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(38,18): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(39,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(39,22): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(40,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(40,26): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(40,41): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(41,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(41,20): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(41,35): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(42,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(42,23): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(42,40): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(43,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(43,17): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(43,32): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(44,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(44,27): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(44,49): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(45,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(45,22): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(46,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(46,18): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(47,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(47,20): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(47,35): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(48,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(48,24): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(48,39): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(49,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(49,18): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(49,33): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(75,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(75,23): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(76,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(76,24): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(77,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(77,23): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(78,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(78,24): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(79,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(79,29): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(80,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(80,29): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(96,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(96,18): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(97,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(97,19): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(98,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(98,18): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(124,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(124,18): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(125,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(125,18): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(126,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(126,23): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(127,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(127,27): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(128,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(128,22): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(129,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(129,20): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(130,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(130,24): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(131,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(131,21): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(151,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(151,18): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(152,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(152,18): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(153,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(153,18): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(154,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(154,24): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(155,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(155,19): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(171,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(171,20): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(172,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(172,22): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(173,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(173,27): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(174,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(174,28): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/device.d.ts(41,21): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/device.d.ts(41,27): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/media-capture.d.ts(24,21): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/media-capture.d.ts(24,40): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/media-capture.d.ts(24,59): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/media-capture.d.ts(29,21): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/media-capture.d.ts(29,40): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/media-capture.d.ts(29,59): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/media-capture.d.ts(34,21): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/media-capture.d.ts(34,40): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/media-capture.d.ts(34,59): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/mixpanel.d.ts(71,21): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/mixpanel.d.ts(71,27): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/network.d.ts(47,21): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/network.d.ts(47,31): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/screen-orientation.d.ts(46,21): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/screen-orientation.d.ts(46,32): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/sqlite.d.ts(30,14): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/sqlite.d.ts(30,30): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/statusbar.d.ts(71,21): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/statusbar.d.ts(71,30): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/webintent.d.ts(15,21): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/webintent.d.ts(15,32): Error TS1005: ';' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/webintent.d.ts(16,21): Error TS1005: '=' expected.
TypeScript error: C:/new/n/node_modules/ionic-native/dist/es5/plugins/webintent.d.ts(16,31): Error TS1005: ';' expected.

**Comment by mlynch** [comment]
You got it working? For others: if you're using typescript < 2.0, use 1.3.27, otherwise you can use the 2.0.x release of ionic-native

**Comment by JustMeDaFaq** [comment]
Yeah, ive actually just used 1.3.27, fixed it for me. DIdnt know it came from using typescript < 2.0. Thanks :)
