### ISSUE TITLE
Feature request : Taptic Engine plugin

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic-native#571]
I'd like this plugin for Taptic Engine feedback on iPhone 6S and 7 to be added. https://github.com/EddyVerbruggen/cordova-plugin-taptic-engine

**Comment by Bouzmine** [comment]
@mlynch Could you add the unofficial API to the plugin?

**Comment by ihadeed** [comment]
@mlynch what do you think about adding a new parameter for the `@Cordova` decorator: `customRef`.. so we can do something like:

```
@Cordova({
  customRef: 'unofficial.weakBoom'
  // OR
  customRef: 'TapticEngine.unofficial.weakBoom'
})
static weakBoom(): Promise<any> { return; }
```
