### ISSUE TITLE
Google Maps: addTileOverlay is not working

### ISSUE THREAD

**Issue by SylvainGuittard** [driftyco/ionic-native#579]
# Steps to reproduce:
- Create an app with native google maps plugin.
- Add the following code
```
map.addTileOverlay({
  // <x>,<y> and <zoom> are replaced with values
  tileUrlFormat: "http://tile.stamen.com/watercolor/<zoom>/<x>/<y>.jpg"
}, function(tileOverlay) {
  mTileOverlay = tileOverlay;
  map.showDialog();
});
```
src: https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/TileOverlay

# Error
Error message during build:
``` Error TS2345: Argument of type '{ tileUrlFormat: string; }' is not assignable to parameter of type 'GoogleMapsTileOverlayOptions'. Object literal may only specify known properties, and 'tileUrlFormat' does not exist in type 'GoogleMapsTileOverlayOptions'. ```

**Comment by ihadeed** [comment]
Sorry about that, there was a typo in the interface. Just pushed a commit that fixes this and it will be available in the next release.

https://github.com/driftyco/ionic-native/commit/f36b1c03cbaed2ddc71d4cbd02d55959d2267258
