### ISSUE TITLE
Document or add getPlugin()

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic-native#582]
Should be possible to fallback to calling plugin directly, with our helper magic. Note to self mainly

**Comment by ihadeed** [comment]
As in a method that is injected automatically by the `@Plugin()` decorator that returns `pluginRef` ?

**Comment by mlynch** [comment]
Yea, I want to avoid people having to call the plugin directly on their own (to verify an issue, for example), and be able to still use the ionic-native class since we're not always 100% up to date w plugin changes

**Comment by ihadeed** [comment]
Would be cool if the method is available in every class automagically ... so the user wouldn't have to figure out what the `pluginRef` is .. They can just call `Camera.getPlugin().getPicture(...)` for example.

**Comment by mlynch** [comment]
Yep, exactly. Will be a nice "escape hatch"

**Comment by mlynch** [comment]
Pretty simple, figured adding the plugin check wouldn't be appropriate here as that could be annoying. Instead, they can call `checkInstall()` for a check w/ full error report.
