### ISSUE TITLE
SQLite + ionic-native + Ionic 1

### ISSUE THREAD

**Issue by johnpapa** [driftyco/ionic-native#590]
I'm trying to get SQLite working through an Ionic 1 app. I installed ngCordova and it works ... but when I use ionic-native the `SQLite` object comes back as a function that returns undefined. Has anyone been able to get this combination to work?

cc // @walkingriver @mlynch

**Comment by johnpapa** [comment]
Here is what I get when I inject and try to use `$cordovaSQLite`

![image](https://cloud.githubusercontent.com/assets/1202528/18836603/bd5b5b2e-83ce-11e6-86fb-b5db74933ace.png)

**Comment by mlynch** [comment]
Hey John, `$cordovaSQLite` is a constructor with our plugin, so you'll want to call `new` on it first. Sounds like we got this figured out and we could be more clear about how this works.

I'm also going to review whether we need this to be a constructor. Will file a separate issue.

**Comment by johnpapa** [comment]
Thanks @mlynch for the help


OK … so if i have this right …

1. use ionic to add the plugin
```
 ionic plugin add cordova-sqlite-storage
```

2. add `ionic-native` either through bower or npm (both are the same, right?)

3. Add `ionic-native` as a module dependency 

```
  angular.module('app', [
    'ionic',
    'ionic.native'
  ])
```

4. Inject the service

```
  function MyController($ionicPlatform, $cordovaSQLite) {
```

5. use the new API after `$ionicPlatform.ready`

```
      $ionicPlatform.ready(function () {
        console.log('PLATFORM READY');

        // Just a test to make sure the plugin is there in case the wrapper is not working
        // var db = window.sqlitePlugin.openDatabase({ name: 'demo.db', location: 'default' });

        var db = new $cordovaSQLite();
        db.openDatabase({ name: "my.db", location: "default" })
          .then(function (r, p) {
            console.log('Opened database', r, p);
          })
          .catch(function (r, p) {
            console.log('Unable to open database', err);
          });
  });
```
