### ISSUE TITLE
1.3.27 InAppBrowser typescript definition breaking.

### ISSUE THREAD

**Issue by Yimiprod** [driftyco/ionic-native#591]
Hi

After updating from 1.3.20 to 1.3.27, i stumbled upon a problem, the definition of the class `InAppBrowser` has changed, now when i do:
```
let browser = new InAppBrowser('http://www.google.com',  '_system', 'location=true');
```
It say i shouldn't have passer thoses three parameters and instead i should only do:
```
let browser = new InAppBrowser();
```
But it's not how it's supposed to work.

Ionic informations:
```
Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v6.5.0
Xcode version: Xcode 8.0 Build version 8A218a
```

I don't know what version of typescript i'm currently using (`tsc -v` saying i haven't installed it)

**Comment by ihadeed** [comment]
@Yimiprod the first parameter (url) is the only required one, the other 2 are optional. 

Can you share the error message that you're getting along with usage information?

This plugin is working fine with me, running latest version of Ionic Native.
