### ISSUE TITLE
SQLite: review constructor

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic-native#592]
Right now the SQLite plugin requires you to call `new` on it before you use it. I don't think this should be required: https://github.com/litehelpers/Cordova-sqlite-storage

**Comment by ihadeed** [comment]
Yeah you're right...

`openDatabase` should be a static function that creates a new `SQLite` object and sets it's `_objectInstance` value. It will resolve an instance of `SQLite` on success, or reject with the error if failed. 

```
SQLite.openDatabse('path/to/db').then((db: SQLite) => {

  db.transaction(...);

}).catch(e => console.log(e));
```

**Comment by mlynch** [comment]
Why does it need to be instance based?

**Comment by ihadeed** [comment]
@mlynch to eliminate the need to use callbacks. Some methods have callbacks in them and if we don't make it instance based we wouldn't be able to replace those callbacks with promises.
