### ISSUE TITLE
File#checkFile missed feature.

### ISSUE THREAD

**Issue by adubovsky** [driftyco/ionic-native#594]
Today I have tried to upgrade `ionic-native` to the latest 1.x version (now we are using `1.3.2`) and found out that `File#checkFile` method does not provide `Entry` of existing file anymore, just `true` or `FileError`.

For our case we need to check if file exist and if yes -> get its native url. I can't find a way to do this now because e.g. `File#resolveLocalFilesystemUrl` method is private...

Could you please help? Probably I am missing smth.

**Comment by ihadeed** [comment]
Just pushed a commit that will be merged shortly and published in v2.2.2. `getFile`, `getDirectory`, `resolveLocalFilesystemUrl`, and `resolveDirectoryUrl` will be public. 

That should solve you issue here, right?

**Comment by ihadeed** [comment]
Can you try with the latest version v2.2.2 and report back? Thanks.

**Comment by adubovsky** [comment]
Thanks @ihadeed. 
Okay, at least it will help me to override checkFile method, and return `Promise<FileEntry|FileError>` instead of original `Promise<boolean|FileError>`:

```
File.checkFile = function (path:string, file:string):Promise<boolean|FileError|FileEntry> {
    if ((/^\//.test(file))) {
        var err = new FileError(5);
        err['message'] = 'file cannot start with \/';
        return Promise.reject(err);
    }
    return File.resolveLocalFilesystemUrl(path + file)
        .then(function (fse) {
            if (fse.isFile) {
                return fse;
            }
            else {
                var err = new FileError(13);
                err['message'] = 'input is not a file';
                return Promise.reject(err);
            }
        });
};
```
