### ISSUE TITLE
[2.0.0-rc.0] - Cannot use native plugins

### ISSUE THREAD

**Issue by vlados** [driftyco/ionic-native#602]
After migrating to 2.0 RC0 I am unable to use native plugins.
Example https://github.com/driftyco/ionic/issues/8261

**Comment by ihadeed** [comment]
I'll look into this soon, just finished upgrading an app to rc0. Will test the native plugins in a bit.

**Comment by ihadeed** [comment]
I think this issue is related to https://github.com/driftyco/ionic-native/issues/560

I'm having the same problem as you when the app starts up, but when I try to use plugins later on they work fine. But that's still strange because I wrap everything with `platform.ready()`...

Will investigate further and let you know if I find a solution.

**Comment by vlados** [comment]
Are you able to use native plugins ? 
How did you integrated it?  Can you post simple code?

**Comment by mlynch** [comment]
@vlados try creating a new project w rc0 using ionic CLI to see a plugin or two being used

**Comment by danielgek** [comment]
tried and it says the plugin is not installed, even in a fresh project, but googlemaps plugin works, i use a few more and none of them works

**Comment by vlados** [comment]
@mlynch Yes, I've tried and some of the Plugins are working, some of them returns data wrapped in __zone_value key ... something is not right

**Comment by doender** [comment]
I am having the same issue

**Comment by jgw96** [comment]
Hello @vlados and @doender which plugins are you all having issues with specifically?

**Comment by doender** [comment]
With 'diagnostic', it's the first one I tried.

**Comment by ihadeed** [comment]
@doender can you share your code (that part where you're calling the plugin) and any error messages / stack traces? 

I'm using the diagnostic plugin without any issues.

**Comment by mlynch** [comment]
I need specific plugins in order to assess this. I just tested a bunch and they work great:

```typescript
import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar, Device, Splashscreen, GoogleAnalytics } from 'ionic-native';

import { TabsPage } from '../pages/tabs/tabs';


@Component({
  template: `<ion-nav [root]="rootPage"></ion-nav>`
})
export class MyApp {
  rootPage = TabsPage;

  constructor(platform: Platform) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();

      Splashscreen.hide();

      let name = Device.device.uuid;

      GoogleAnalytics.debugMode();
      GoogleAnalytics.startTrackerWithId('UA-44023830-11');

      console.log('Device name', name);
    });
  }
}
```

**Comment by baltazaroliveira** [comment]
Not Working. Give the same error!

Should unistall GA plugin?

![image](https://cloud.githubusercontent.com/assets/953742/19066210/0ab144fa-8a10-11e6-8e33-2ea7727d4844.png)

Error

![ga - ionic 2](https://cloud.githubusercontent.com/assets/953742/19066216/15d457a0-8a10-11e6-9b1f-c236771968d9.png)

Thanks

**Comment by mlynch** [comment]
Okay, I think I see what's going on here. We're running into a separate issue with using the `name` field I believe.

Does it work if you do this:

```typescript
platform.ready(() => {
  setTimeout(() => {
    Splashscreen.hide()

  }, 1000);
});
```

The `setTimeout` is there to test whether htis is just a race condition

**Comment by ihadeed** [comment]
Please update to `ionic-native@2.1.2`

**Comment by doender** [comment]
My bad, I forgot to wrap the plugin in `platform.ready`...

**Comment by baltazaroliveira** [comment]
Updated to latest Ionic Native 2.1.6. Same error with the change suggested! 

```
constructor(platform: Platform) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.

      // splash screen
      //Splashscreen.hide();

      if (Splashscreen) {
        setTimeout(() => {
          Splashscreen.hide();
        }, 1000);
      }

      // status bar
      StatusBar.styleDefault();

      //let name = Device.device.uuid;

      // GA
      //GoogleAnalytics.debugMode();
      GoogleAnalytics.startTrackerWithId("UA-17772329-16");

    });
  } // construtor
```
Please help to resolve this issue!

**Comment by mlynch** [comment]
Can one of you send me your main.js file from `www/build/main.js`? I think this is a build related issue where the classname is getting renamed. max@ionic.io

**Comment by baltazaroliveira** [comment]
In Attach! Thanks for your help! :-)

[build.zip](https://github.com/driftyco/ionic-native/files/515558/build.zip)

**Comment by mlynch** [comment]
Hey, in your `package.json` for your RC0 app, can you try replacing `build` with this? `"build": "ionic-app-scripts build --dev",`

**Comment by mlynch** [comment]
Can someone send me a project with this issue happening? The more I look at the code the more I'm thinking something else is going on, perhaps in your project or with the plugin (maybe it changed?). The console error might be broken but it shouldn't impact anything else because both the plugin window reference and the method name are still intact, and we don't use the `name` field for anything important.

**Comment by baltazaroliveira** [comment]
Updated Ionic Native to latest - 2.1.9
Changed the package.json

![image](https://cloud.githubusercontent.com/assets/953742/19233249/44f4951a-8edc-11e6-8f72-77c175468124.png)

When run in chrome developer i get this.

![image](https://cloud.githubusercontent.com/assets/953742/19233268/641d2862-8edc-11e6-8fa4-458a804ee36c.png)

Hope teat helps to resolve this issue.

**Comment by ihadeed** [comment]
In the picture it looks like you're making the plugin call before
deviceready is fired. Are you sure you're wrapping all your calls with
platform.ready() ?

**Comment by joubin-ca** [comment]
I'm experiencing the same issue however specifically with SQLite native-plugin.
Here are a few things that I have done to see if they are the solution, to no avail:

1. Check the plugin list. It's listed: cordova-plugin-sqlite-2 1.0.4 "SQLitePlugin"
2. Updated package.json (as suggested here): "build": "ionic-app-scripts build --dev"

Anyone else has the same issue with the SQLite plugin?

**Comment by mlynch** [comment]
@joubin-ca @baltazaroliveira I'm at a loss. Can either one of you zip up and email me your whole project? max AT ionic DOT io. That would be immensely appreciated!

**Comment by mlynch** [comment]
Also, can you try the suggestion here: https://github.com/driftyco/ionic-native/issues/651#issuecomment-252485648

Namely: `ionic state reset` and then `rm -rf node_modules/` then `npm install`

**Comment by joubin-ca** [comment]
@mlynch - I did the following ionic state reset and then rm -rf node_modules/ then npm install, but didn't work. I shared with you a copy of my project.
Thanks.

**Comment by ma77hi4s** [comment]
@mlynch @baltazaroliveira - I had the same problem as baltazaroliveira (GoogleAnalytics). I followed the suggestion _ionic state reset and then rm -rf node_modules/ then npm install_ and it worked for me!

**Comment by baltazaroliveira** [comment]
@mlynch @ma77hi4s I have do that!

1. ionic state reset
2. rm -rf node_modules (used rd /s /q node_modules/) [rm don´t work on Windows)
3. npm install

I have the same error.

![image](https://cloud.githubusercontent.com/assets/953742/19302341/8f68e224-905b-11e6-8d98-9f4916b553c2.png)

Can you share the part of your code where you call? [I call in app.component.ts]

1. GoogleAnalytics.startTrackerWithId("UA-XXX-XX");

**My code**
![image](https://cloud.githubusercontent.com/assets/953742/19302279/550d23a6-905b-11e6-9ddd-c33dda1fcfbe.png)

2. GoogleAnalytics.trackView("Perfil Visitas");

**MyCode**
![image](https://cloud.githubusercontent.com/assets/953742/19302305/6583507a-905b-11e6-9764-537e76278658.png)

Thanks!

**Comment by ma77hi4s** [comment]
app.component.ts:

`import { Component, ViewChild } from '@angular/core';
import { Platform, MenuController, Nav } from 'ionic-angular';
import { StatusBar, GoogleAnalytics } from 'ionic-native';

@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  @ViewChild(Nav) nav: Nav;

  constructor(
    public platform: Platform
  ) {
    this.initializeApp();
  }

  initializeApp() {
    this.platform.ready().then(() => {
      StatusBar.styleDefault();

      // Google analytics
      GoogleAnalytics.startTrackerWithId('UA-XXX');
      GoogleAnalytics.trackView('app_start');
    });
  }
}
`

Page:

`import { Component } from '@angular/core';
import { NavController, NavParams, Platform } from 'ionic-angular';
import { GoogleAnalytics } from 'ionic-native';

@Component({
  templateUrl: 'a-page.html'
})
export class APage{

  constructor(private navCtrl: NavController,  private platform: Platform) {
    this.platform.ready().then(() => {
        GoogleAnalytics.trackView('a_view');
    });

  }

}
`

**Comment by baltazaroliveira** [comment]
Folowing @ma77hi4s, wraping trackview (only on "start" Page) in platform.view make it works (i don´t get trackings in GA but i think that is a question on time). I have no errors! This is the correct way to do?

**Comment by joubin-ca** [comment]
As for cordova-plugin-sqlite, I found this that may be helpful: https://github.com/nolanlawson/cordova-plugin-sqlite-2

**Comment by baltazaroliveira** [comment]
I don´t get logs from Google Analtytics neither records on GA platform.

Any time to receive records? @ma77hi4s it took much time to have records in GA platform? If you ativate debug mode you get logs?

**app.component.ts:**

```
@Component({
  template: `<ion-nav [root]="rootPage"></ion-nav>`
})
export class MyApp {
  rootPage = LoginPage;

  constructor(platform: Platform) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.

      // splash screen
      //Splashscreen.hide();

      if (Splashscreen) {
        setTimeout(() => {
          Splashscreen.hide();
        }, 1000);
      }
                        
      // status bar
      StatusBar.styleDefault();

      // GA
      GoogleAnalytics.startTrackerWithId("UA-xxx--xx");
      GoogleAnalytics.debugMode();

    });
  } // construtor
}
```

**Page:**

```
@Component({
  selector: 'login',
  templateUrl: 'login.html'
})
export class LoginPage {
  @ViewChild('txtutilizador') InputUtilizador_Focus

  utilizador: string = "";
  password: string = "";
  guardadados_login: boolean = false;

  mostra_btnFechar: boolean;

  // ARRANQUE
  constructor(public navCtrl: NavController,
    public loadingCtrl: LoadingController,
    public platform: Platform,
    public alertCtrl: AlertController,

    public servicesFuncoesCtrl: Services_Funcoes) {

    // se ANDROID mostra o botão..
    if (this.platform.is('android')) {
      this.mostra_btnFechar = true;
    }

    // GA (necessário estar dentro do platform.ready())
    // se 1º página de "arranque" - erro a corrigir
     
    this.platform.ready().then(() => {
      GoogleAnalytics.trackView("Login");
    });
 }
```

**Comment by baltazaroliveira** [comment]
Using this code

```
// GA
      GoogleAnalytics.debugMode();
      GoogleAnalytics.startTrackerWithId("UA-17772329-18");

      GoogleAnalytics.enableUncaughtExceptionReporting(true)
        .then((_success) => {
          console.log(_success)
        }).catch((_error) => {
          console.log(_error)
        })

**I get this**

Enabled uncaught exception reporting

```

**Comment by shikharls** [comment]
Hi,
I am having the same problem with the plugin StreamingMedia.

I did:
`rm -rf node_modules/`
`npm install`
`ionic plugin add cordova-plugin-streaming-media`
Plugin "com.hutchind.cordova.plugins.streamingmedia" already installed on ios.

When I run:
```
this.platform.ready().then(() => {
      StreamingMedia.playVideo(url, options);
    });
```
I get:
Install the t plugin: 'ionic plugin add cordova-plugin-streaming-media'

**Comment by mlynch** [comment]
Thanks @shikharls for the test case, we now see it on our end and are digging in. Stand by

**Comment by mlynch** [comment]
Okay, I think I figured this one out! Can you all check your `www/index.html` file, and see if you have this line here:

<img width="470" alt="screenshot 2016-10-15 22 21 19" src="https://cloud.githubusercontent.com/assets/11214/19414987/cb4590a4-9325-11e6-8d4c-1a60014e5dfe.png">

if you do, please remove it. @shikharls this fixed your app you sent me. Once I removed that line it all worked :D

**Comment by shikharls** [comment]
@mlynch Thanks! I had put that for some debugging. Although, one thing: I removed that line from src/index.html. I thought that this would also update www/index.html when I run (serve or emulate) the app?

Thanks

**Comment by baltazaroliveira** [comment]
Still the same error in Google Analtytics.

Made all steps of http://blog.ionic.io/ionic-2-rc-weekend-updates/

I get the same error described above...

Any update?

**Comment by ihadeed** [comment]
@baltazaroliveira 

1. Are you having any issues with other plugins? or is it just the Google Analytics plugin?
2. Try to manually remove the platform and re-add the `@latest` version, instead of using `ionic state reset`
3. Try creating a new project from scratch and just keep it minimal, add the plugin in there and test it out.

Also it might be worth trying to re-install cordova and ionic
```
npm rm -g ionic cordova
npm i -g ionic@latest cordova@latest
```

**Comment by mlynch** [comment]
Also @baltazaroliveira check to see if you have that line as per my comment above

**Comment by mlynch** [comment]
Hey everyone. Follow up to this, please make sure that the plugin you installed is actually listed in the `plugins/` directory. _If it's not_ in the above cases, please let me know by commenting on this issue, as it might actually be a separate CLI issue.

**Comment by baltazaroliveira** [comment]
@ihadeed

Do what you suggested

- Remove Ionic and Cordova
- Add again latest versions
- Create new App
- Install only GA plugin

Extra: Updated Android SDK

**Same error...**

Enabled uncaught exception reporting

When build i get this message. I think that is not important

![image](https://cloud.githubusercontent.com/assets/953742/19469940/6e910d2e-9515-11e6-913e-a56bdbd7425a.png)

App
https://meocloud.pt/link/d6a457f1-1087-4c2e-9013-e91289aadf35/myapp.7z/


In attach the project.

Please help!

**Comment by baltazaroliveira** [comment]
@mlynch Does not have that line.. Have you seen my Twitter about Keyboard?

**Comment by ihadeed** [comment]
@baltazaroliveira delete that `android-4.4w` directory, it's Android Wear SDK anyways.

**Comment by ihadeed** [comment]
@baltazaroliveira check this page here for full instructions on the requirements to build Android packages: https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html

**Comment by baltazaroliveira** [comment]
Deleted folder. No more warning.

Updated JDK but same error.

Will contact you by Slack! Thanks!

**Comment by baltazaroliveira** [comment]
Talked with @ihadeed on Slack Chat. He don´t know what could be the problem.. So i don´t have GA ..

Using Piwik..

**Comment by mlynch** [comment]
@baltazaroliveira just seeing now that you sent a link for the app bundle, thanks for doing that! I will take a look and see if I can figure out what might be up with GA

**Comment by baltazaroliveira** [comment]
Piwik is a little slow, but i get statistics..

**Comment by baltazaroliveira** [comment]
Give up on Piwik, too slow.... GA don´t work.. Waiting for solution or Ionic Analytics. :-)

GA Http don´t work on mobile..

https://www.google-analytics.com/collect?v=1&tid=UA-17772329-19&cid=41f34a9ba27b8ef5&t=pageview&cd=Login&dp=Vendedores&an=Vendedores&av=1.0.0

**Comment by mlynch** [comment]
@baltazaroliveira I fixed the app you sent me. It seemed to be a case of plugins getting in an odd state, which can happen sometimes depending on whether there are build artifacts still in the platform build directories.

To fix it:

```
rm -rf platforms/
cordova platform add android
cordova prepare android
```

If that doesn't work, then remove all the plugins from the plugin directory first, install them again, then follow the steps above.

Confirmed this is not an issue with ionic-native nor RC

**Comment by baltazaroliveira** [comment]
Have you used the UA-17772329-19? If yes i don´t have records...

What i do

> npm rm -g ionic cordova
> npm i -g ionic@latest cordova@latest
> 
> Deleted node_modules folder
> Deleted platforms folder
> Deleted GA plugin
> 
> npm install
> // chart js
> npm install chart.js --save
> // crypto js
> npm install crypto-js --save
> 
> 
> ionic plugin add cordova-plugin-google-analytics
> ionic platform add android
> ionic prepare android
> 
> ionic run android

After all i that i get in Chrome Developer Tools that the track is made, but i don´t see in GA.

![image](https://cloud.githubusercontent.com/assets/953742/19601329/d1d856e8-97a0-11e6-9c8a-a60f55e2aeb7.png)

1. Start

![image](https://cloud.githubusercontent.com/assets/953742/19601341/e0d5f0ba-97a0-11e6-99c1-c7717d79af85.png)

2 and 3

![image](https://cloud.githubusercontent.com/assets/953742/19601359/f587d924-97a0-11e6-9d9d-7dcdfcc8f45b.png)

I don´t get any records :-(

Network

![image](https://cloud.githubusercontent.com/assets/953742/19601375/09e3018c-97a1-11e6-8afb-17864b876723.png)

Maybe plugin problem. I don´t know. I have do this procedure a lot of times...

Thanks in Advance

**Comment by baltazaroliveira** [comment]
After doing a lot of debug tests, i came to the conclusion that the problem come from my device. I test my app with another device and i get records.
I have test also with native apps that i create and no records..

Conclusion: I have a app 'AddAway' that is blocking the GA requests. I revert the changes. Reboot and not all Ok.

Thanks a lot for all responses especially to @ihadeed and @mlynch.

Problem Solved :-)
