### ISSUE TITLE
RC.0 sqlite plugin doesn't work

### ISSUE THREAD

**Issue by richardshergold** [driftyco/ionic-native#604]
This plugin doesn't seem to work for me - I followed the docs here

http://ionicframework.com/docs/v2/native/sqlite/
 
but I get the error

"sqlitePlugin is not defined"

**Comment by richardshergold** [comment]
Just been told this does work so I will try again in the morning and report back.

**Comment by mlynch** [comment]
Hmm, this should work, did you install the plugin? https://github.com/litehelpers/Cordova-sqlite-storage

**Comment by richardshergold** [comment]
Yeah I did.  I will try again in the morning and let you know if it works.

**Comment by richardshergold** [comment]
@mlynch closing this because I was being an eeejot!  Working fine....  (sorry!)
