### ISSUE TITLE
Error storing item, plugin_not_installed

### ISSUE THREAD

**Issue by kyleap** [driftyco/ionic-native#605]
ionic cli version : 2.1.0
"ionic-native": "^2.0.3"
"ionic-angular": "^2.0.0-rc.0",
Plugin Name : http://ionicframework.com/docs/v2/native/nativestorage/
Platform : ios
when run with commend : [npm run ios -l -c] got errors

0     742222   warn     Native: tried calling t.setItem, but the t plugin is not installed.
1     742223   warn     Install the t plugin: 'ionic plugin add cordova-plugin-nativestorage'
2     742224   warn     Native: tried calling t.getItem, but the t plugin is not installed.
3     742225   warn     Install the t plugin: 'ionic plugin add cordova-plugin-nativestorage'
4     742237   error    Error storing item, plugin_not_installed
5     742240   error    plugin_not_installed
6     742389   log      DEVICE READY FIRED AFTER, 213, ms

**Comment by ihadeed** [comment]
From the stack trace you provided it looks like you tried to use the plugin before `deviceready` has fired. Can you wrap your method calls with `platform.ready()` and let me know if that works?

**Comment by kyleap** [comment]
It's work! thanks!

**Comment by xProgrammer-007** [comment]
Hello please look for this.  I tried to wrap my code inside platform still it doesn't seem to work . On the logs here is how it throws error . Installed the plugin & added to providers . Still it persists 

vendor.js:69989 Install the NativeStorage plugin: 'ionic cordova plugin add cordova-plugin-nativestorage'
vendor.js:1703 ERROR Error: Uncaught (in promise): plugin_not_installed
    at c (polyfills.js:3)
    at c (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:4973)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
    at e.invokeTask [as invoke] (polyfills.js:3)
    at p (polyfills.js:2)

**Comment by ourarash** [comment]
I have the same problem. In some runs it works, and it some other runs it says the plugin is not installed. I try to read  the storage after device ready.
