### ISSUE TITLE
Ionic2 Phonegap's plugin barcode scanner parameters

### ISSUE THREAD

**Issue by Andalarian** [driftyco/ionic-native#606]
I saw in the Phonegab barcode scanner plugin documentation tha tI can set some parameters for the plugin but in the Ionic one i saw nothing. 
Is-it possible to set parameters ? 
I've tried to do it like in the phonegap's documentation, but keep getting a "Supplied parameters do not match any signature of call target" error so i guess you can't to it like that.

Thank's in advance.

Phonegap's documentation : https://github.com/phonegap/phonegap-plugin-barcodescanner

Ionic 2 documentation : http://ionicframework.com/docs/v2/native/barcode-scanner/

**Comment by ihadeed** [comment]
Can you share the code that you're trying to use?

**Comment by Andalarian** [comment]
The first is from the documentation of Ionic2 (With the addition of the parameter)
The second is from the documentation of phonegap

`BarcodeScanner.scan().then((barcodeData) => {
 //success
 }, (err) => {
	//error
},
{
//Param
}  `

`cordova.plugins.barcodeScanner.scan(
      function (result) {
          //success
      },
      function (error) {
          //error
      },
      {
         //param
      }
   );`

**Comment by ihadeed** [comment]
The options go in the `scan()` function not in `.then()`.

```
BarcodeScanner.scan().then((barcodeData) => {
 // Success! Barcode data is here
}, (err) => {
    // An error occurred
});
```

With params:
```
BarcodeScanner.scan(
      {
          "preferFrontCamera" : true, // iOS and Android
          "showFlipCameraButton" : true, // iOS and Android
          "prompt" : "Place a barcode inside the scan area", // supported on Android only
          "formats" : "QR_CODE,PDF_417", // default: all but PDF_417 and RSS_EXPANDED
          "orientation" : "landscape" // Android only (portrait|landscape), default unset so it rotates with the device
      
}).then((barcodeData) => {
 // Success! Barcode data is here
}, (err) => {
    // An error occurred
});
```
