### ISSUE TITLE
TODO: Firebase Plugin for Analytics

### ISSUE THREAD

**Issue by prantikv** [driftyco/ionic-native#608]
Would love to see the cordova-plugin-firebase  [here](https://www.npmjs.com/package/cordova-plugin-firebase)

The plugin is primarily used for Firebase Analytics and Remote Config.

There are other plugins for Firebase Realtime database [here ](https://www.npmjs.com/package/cordova-plugin-firebase-realtime-database)and Firebase Auth [here](https://www.npmjs.com/package/cordova-plugin-firebase-auth) as well

Personally I like to use Angular Fire for Auth and Realtime database.

As Firebase **does not allow** Analytics for the web/hybrid hence would love to see the Firebase Analytics plugin added.

-Thanks

**Comment by sferey** [comment]
I need it
+1

**Comment by ihadeed** [comment]
I'll work on adding https://github.com/arnesson/cordova-plugin-firebase

The other don't seem very popular and I'm not sure if they work well.

**Comment by sudharsanmit** [comment]
@ihadeed can you please update on when this will be available in the release?

**Comment by royken** [comment]
Hello this is what I have when I build the project:
![firebase](https://user-images.githubusercontent.com/7059358/31624947-43c8ca64-b29c-11e7-8f89-3fa124ee61ba.PNG)
