### ISSUE TITLE
Feature Request : cordova-plugin-globalization

### ISSUE THREAD

**Issue by phavre** [driftyco/ionic-native#61]
Does this core plugin could be added the the native wrapper classes ?
IMHO if one need to build a multilingual app, it's the surest way to obtain the user's language.

**Comment by ihadeed** [comment]
It has been added. (Not tested yet)
It should be included in the next release.

**Comment by ihadeed** [comment]
@phavre new version is available on NPM now. The globalization plugin is included in that release.
