### ISSUE TITLE
[2.0.3] MediaPlugin doesn't work

### ISSUE THREAD

**Issue by trangnt58** [driftyco/ionic-native#610]
I checked MediaPlugin with ionic-native 1.3.10 and it worked. But with v 2.0.3, it doesn't work. Please check again.

**Comment by ihadeed** [comment]
What is the error that you're getting?

**Comment by trangnt58** [comment]
I have installed cordova plugin media, ionic-native v2.0.3
```
let file = new MediaPlugin('path');
    file.play();
```
but it doesn't work. 
And when I try with old project with ionic-native v1.3.10. It works. Please help me

**Comment by trangnt58** [comment]
It doesn't show error. But it seems `new MediaPlugin` doesn't create

**Comment by ihadeed** [comment]
What version of TypeScript are you using?

**Comment by trangnt58** [comment]
It has version 2.0.3

**Comment by ihadeed** [comment]
Ok I figured the issue out, it's a mistake with my last commit to the media plugin. 

I will fix it soon, in the meanwhile, you can call `file.status.subscribe(()=>{});` before you attempt to play it.

**Comment by ihadeed** [comment]
Fixed in https://github.com/driftyco/ionic-native/commit/58a99a14d50b7de24d7236e2fd2006004d87976f and will be available in the next release

**Comment by trangnt58** [comment]
@ihadeed  thank you so much

**Comment by marban** [comment]
I'm getting `ORIGINAL EXCEPTION: TypeError: undefined is not an object (evaluating 'pluginObj._objectInstance')`
on file.init.then

Makes sense?

**Comment by ihadeed** [comment]
This is fixed in master. Will be available in next release.

As of now, you need to call .status.subscribe() right after creating a new
MediaPlugin in order to get it to work.

**Comment by ihadeed** [comment]
Please update to latest ionic-native version, this is fixed now.
