### ISSUE TITLE
2.0 RC 0 Inconsistent way to import plugin

### ISSUE THREAD

**Issue by lufias** [driftyco/ionic-native#615]
Im not sure if this actually expected. Most of the plugin can directly be imported into the component using import {Plugin} from 'ionic-native'. But for Device plugin, it needs to be imported into the module providers list in app.module.ts before being DI injected into the component. 

Still, neither platform or uuid return anything although the property is there

**Comment by mlynch** [comment]
None of the plugins are injectable so I don't think that's right, as they aren't using any Angular 2 features, it's just a vanilla TypeScript project.. You import from ionic-native. Happy to take a look at your code sample to see what's going on.
