### ISSUE TITLE
Module has no exported member 'Location Accuracy'

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#625]
_From @junaidahmed93 on October 3, 2016 12:9_

Hello everyone,
I am getting error while importing LocationAccuracy from ionic native
`Module has no exported member 'Location Accuracy'`
I have already installed the plugin.
Is there any solution?

_Copied from original issue: driftyco/ionic#8431_

**Comment by jgw96** [comment]
_From @manucorporat on October 3, 2016 12:14_

Can you share the code that is failing?

**Comment by jgw96** [comment]
_From @junaidahmed93 on October 3, 2016 12:23_

Following this code snippet from IONIC 2 native


import { LocationAccuracy } from 'ionic-native';

LocationAccuracy.canRequest().then((canRequest: boolean) => {

  if(canRequest) {
    // the accuracy option will be ignored by iOS
    LocationAccuracy.request(LocaitonAccuracy.REQUEST_PRIORITY_HIGH_ACCURACY).then(
      () => console.log('Request successful'),
      error => console.log('Error requesting location permissions', error)
    );
  }

});

**Comment by jgw96** [comment]
_From @manucorporat on October 3, 2016 12:30_

Can you remove the node_modules folder and: `npm install`? let me know if that fixed the issue

**Comment by jgw96** [comment]
_From @junaidahmed93 on October 3, 2016 12:37_

I have re-installed node_modules after removing previous one, but still no luck
Error is same

**Comment by ihadeed** [comment]
Closing this, discuss in #622
