### ISSUE TITLE
Barcode Scanner crashes app

### ISSUE THREAD

**Issue by frederikschubert** [driftyco/ionic-native#632]
The barcode scanner appears consistently forces a reload of the app after opening and closing it a few times. I am using the WKWebView fork of ionic.
This is really hard to debug, since there are no error messages logged to the console and the total VM memory allocation stays below 13MB with only a few detected memory leaks.

**Comment by ihadeed** [comment]
This is something to discuss at the barcode scanner plugin repo as it doesn't seem to be an ionic-native issue. 

We will be adding the ZBar barcode scanner plugin soon once this PR gets resubmitted https://github.com/driftyco/ionic-native/pull/626

So you can try that when it's available.
