### ISSUE TITLE
GoogleMaps focus

### ISSUE THREAD

**Issue by pascalrijk** [driftyco/ionic-native#641]
Hi,

I am using GoogleMaps and this is working like a charm but overlay items like a menu or alert box are visible but not working because the focus is always on the map. Maybe there is a problem with the z-index or something?

Ionic info output:

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.3 LTS 
Node Version: v5.6.0

Ionic native version: 1.3.21

**Comment by nakulgulati** [comment]
@pascalrijk Try `map.setClickable(false)` when on menu open (it is an even you can subscribe to) and before doing `alert.present()`. You will have `setClickable(true)` to bring focus to map after that.

**Comment by ihadeed** [comment]
This is a common issue when using this plugin with the Ionic Framework (and a few other frameworks). Best place to get help would be the googlemaps plugin repo, or the Ionic forums.
