### ISSUE TITLE
Error when retriving the lat and lng in GoogleMaps

### ISSUE THREAD

**Issue by hugomosh** [driftyco/ionic-native#642]
In the build I get this error when trying to get the camera position:

`Property 'lat' does not exist on type 'GoogleMapsLatLng | GoogleMapsLatLngBounds'.`

In the ts of ionic-native there is this class but it doesnt share the object Instance.
```js
/**
 * @private
 */
export class GoogleMapsLatLng {
  private _objectInstance: any;

  constructor(public lat: number, public lng: number) {
    this._objectInstance = new plugin.google.maps.LatLng(lat, lng);
  }

  equals(other: GoogleMapsLatLng): boolean {
    return this.lat === other.lat && this.lng === other.lng;
  }

  @CordovaInstance({ sync: true })
  toString(): string { return; }

  toUrlValue(precision?: number): string {
    precision = precision || 6;

    return this.lat.toFixed(precision) + ',' + this.lng.toFixed(precision);
  }
}
```

How can I retrive the lat or the original object? `toString` works fine.

Or how can I skipped the ionic-native and use the regular plugin??

**Comment by ihadeed** [comment]
Just pushed a commit that should fix this issue. Please stay tuned for the next release and let us know if the issue is resolved.

**Comment by ihadeed** [comment]
Please update to `ionic-native@2.1.2` and let me know if you're still having this issue.

**Comment by fmendoza** [comment]
I'm having this issue on ionic-native@2.2.3  

```
this.map.getCameraPosition().then(camera => {
      this.params.location = {
        latitude: camera.target.lat,
        longitude: camera.target.lng
      };
});
```
