### ISSUE TITLE
index.js doesnot export PayPalPayment error

### ISSUE THREAD

**Issue by balasivagnanam** [driftyco/ionic-native#647]
I am running the latest version of ionic-native to implement PayPal integration,
But I am getting the below error when I try to use it.

![image](https://cloud.githubusercontent.com/assets/4233785/19140264/fb6b2650-8bbd-11e6-993f-d22672b8fa2f.png)

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v6.7.0

"dependencies": {
        "@ionic/storage": "1.1.2",
        "angular2-moment": "^1.0.0-beta.3",
        "ionic-angular": "^2.0.0-rc.0",
        "ionic-native": "^2.1.3",
        "ionicons": "^3.0.0"
      },

**Comment by ihadeed** [comment]
This is fixed now, please update to `ionic-native@2.1.6`

**Comment by balasivagnanam** [comment]
errors are gone and app is executing.

Haven't tested for paypal working though. Thanks a lot.

Building for device is so slow :-( with new app-scripts

Is there a way to make it work in browser?
I get cordova.js not found and use a device to test in browser.

**Comment by ihadeed** [comment]
@balasivagnanam 

I do the following to develop on device:
```
// run livereload in one terminal
ionic run android -l

// run watch command in another terminal (livereload is broken atm)
npm run watch
```

**Comment by balasivagnanam** [comment]
great thanks 👍 will try it
