### ISSUE TITLE
Duplicated documentation for SocialShare

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#659]
_From @aldo-roman on October 4, 2016 21:53_

We have two links for SocialShare native plugin

http://ionicframework.com/docs/v2/native/social-sharing/
http://ionicframework.com/docs/v2/native/Social%20Sharing/

It seems they are duplicated and we should only keep one of them.

_Copied from original issue: driftyco/ionic#8491_

**Comment by ihadeed** [comment]
This would be an issue to address at the ionic-site repo. Old folders don't get deleted automatically by the doc generator. See https://github.com/driftyco/ionic-site/tree/master/docs/v2/native
