### ISSUE TITLE
BLE isEnabled promise does not return boolean. Instead it returns null

### ISSUE THREAD

**Issue by wanjungao** [driftyco/ionic-native#665]
It's supposed to return a promise of a boolean. But instead, it always returns a promise of null. 

the following code will work. 

declare let ble: any;
isEnabled = (): Promise<boolean> => {
		let p = new Promise<boolean>((resolve, reject) => {

			if (typeof ble != 'undefined' && ble) {
				ble.isEnabled(
					() => {
						console.log("Bluetooth is enabled");
						resolve(true);
					},
					() => {
						console.log("Bluetooth is *not* enabled");
						resolve(false);
					}
				);
			}
			else
				resolve(false);

		});

		return p;
	}

**Comment by tkem** [comment]
@wanjungao: What makes you think it would return a `Promise<boolean>`? It's declared as `Promise<any>`, and the docs make it quite clear there's no `boolean` state involved:
https://github.com/don/cordova-plugin-ble-central#isenabled

**Comment by wanjungao** [comment]
Original library has two call backs, that we can use to determine the enabled or not. The ionic native API is a promise, which is better. However, it always return a promise of null. There is no way to tell it is ebabled or not. Maybe I missed something.

Do you have sample code to use ionic BLE check if it is enabled?

Besides, I think isEnabled function returns a promise of a Boolean is more intuitive.

**Comment by wanjungao** [comment]
Maybe you expect to use catch to determine ble not working?

**Comment by tkem** [comment]
Exactly. The `failure` callback of a Cordova plugin always results in an error, which you can catch. I agree this is not very intuitive in this case, but ionic-native` is just a wrapper for plugins, and does not (and IMHO should not) change basic functionality. In this case, it might be better if the plugin passes a `boolean` to its `success` callback, and reserves `failure` for true errors. But that's beyond the scope of `ionic-native`.

**Comment by wanjungao** [comment]
make sense to me. Thanks.




On Monday, October 10, 2016 11:40 AM, Thomas Kemmer <notifications@github.com> wrote:


Exactly. The failure callback of a Cordova plugin always results in an error, which you can catch. I agree this is not very intuitive in this case, but ionic-nativeis just a wrapper for plugins, and does not (and IMHO should not) change basic functionality. In this case, it might be better if the plugin passes abooleanto itssuccesscallback, and reservesfailurefor true errors. But that's beyond the scope ofionic-native`.

**Comment by ihadeed** [comment]
Just having a look at this.

Calling isEnabled should return a promise that resolves if its enabled and
will reject if it's not.
