### ISSUE TITLE
File plugin writeToFile append does not work

### ISSUE THREAD

**Issue by kadoshms** [driftyco/ionic-native#666]
Hey,

I am currently using version 1.3.21, but could not find any change log about that in later versions, so I can only guess this issue was not resolved.

I am trying to create a logging mechanism in my app, then the reasonable thing to do is to append the logs to a single file.
For some reason, it replaces the last line only, such that at the end the log file has only one single row.

The code I used:

```
File.writeFile(this.base, 'log.text', log, { append:true, replace: false}).then(
      ()  =>  { // do something },
      (error) => { // handle error }
    );
```

Thanks.

**Comment by ihadeed** [comment]
Can you try with the latest version v2.2.2 and report back? Thanks.
