### ISSUE TITLE
Onesignal interfacing seems to be obsolete with Ionic 2

### ISSUE THREAD

**Issue by anaganisk** [driftyco/ionic-native#667]
The current initialisation is failing with onesignal API, 
`OneSignal.init('somekey',
        { googleProjectNumber: 'somenumber', autoRegister: true })
        .subscribe();`
It fails with a promise(failure) presenting an error as unable to call apply on undefined in zone.js .
I dint dig into the code much yet but I think there is some change in the one signal API, and it must be reflected in ionic native bindings to it
tested it both on beta 11 and RC of ionic both of them fail.

**as a temporary workaround** pulling the older commit from onesignal repo works 
https://github.com/OneSignal/OneSignal-Cordova-SDK.git#ac8e1e558a425fa79695cec7482e36b05214faab

**Comment by anaganisk** [comment]
**I've done some digging the one signal API has been significantly changed, and the current bindings in Ionic native are obsolete, the must be fixed!**

**Comment by anaganisk** [comment]
This is the link to the git diff of the current and old one
https://github.com/OneSignal/OneSignal-Cordova-SDK/compare/ac8e1e558a425fa79695cec7482e36b05214faab...master

**Comment by ihadeed** [comment]
Are you waiting for deviceready to fire?

**Comment by anaganisk** [comment]
Yes, I am, it worked untill i updated the plugin to a newer version.

**Comment by anaganisk** [comment]
@ihadeed Yes, I am, it worked untill i updated the plugin to a newer version. Like I mentioned earlier its seems like an obsolete integration, with one signal api, the way the api must be intialised has changed in one signal, correct me if I am worng thank you!

**Comment by mlynch** [comment]
Another data point for adding a version flag to plugins.
