### ISSUE TITLE
InAppPurchase occasionally crashes app

### ISSUE THREAD

**Issue by taljacobson** [driftyco/ionic-native#668]
after installing InAppPurchase from the ionic 2 native page reference
`
$ ionic plugin add cordova-plugin-inapppurchase
`

i occasionally get a white screen on app start after building for android, this can happen on the same build, that is if i reload the chrome inspect window it will either produce the error or work fine.
when i remove the plugin all seems to work fine

`
ionic run android
`

with the following console error
`
polyfills.js:3 Uncaught Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)e.assertZonePatched @ polyfills.js:3e @ main.js:10e @ main.js:10t._bootstrapModuleFactoryWithZone @ main.js:10t.bootstrapModuleFactory @ main.js:10(anonymous function) @ main.js:72(anonymous function) @ main.js:72

main.js:45 DEVICE READY FIRED AFTER 140 ms
`

package.json
```json

{
  "name": "name",
  "author": "auther",
  "homepage": "http://example.com/",
  "private": true,
  "scripts": {
    "build": "ionic-app-scripts build",
    "watch": "ionic-app-scripts watch",
    "serve:before": "watch",
    "emulate:before": "build",
    "deploy:before": "build",
    "build:before": "build",
    "run:before": "build"
  },
  "dependencies": {
    "@ionic/storage": "^1.0.3",
    "angular2-moment": "^1.0.0-beta.3",
    "angularfire2": "^2.0.0-beta.5",
    "firebase": "^3.4.1",
    "ionic-angular": "^2.0.0-rc.0",
    "ionic-native": "^2.0.3",
    "ionicons": "^3.0.0"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^0.0.28",
    "@types/request": "0.0.30",
    "typescript": "^2.0.3"
  },
  "description": "myApp: An Ionic project",
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [
  ]
}

```

rollup.config
```javascript
var ngTemplate = require('../dist/plugins/ng-template').ngTemplate;
var nodeResolve = require('rollup-plugin-node-resolve');
var commonjs = require('rollup-plugin-commonjs');
var globals = require('rollup-plugin-node-globals');
var builtins = require('rollup-plugin-node-builtins');
var json = require('rollup-plugin-json');

// https://github.com/rollup/rollup/wiki/JavaScript-API

var rollupConfig = {
  /**
   * entry: The bundle's starting point. This file will
   * be included, along with the minimum necessary code
   * from its dependencies
   */
  entry: './.tmp/app/main.dev.js',

  /**
   * sourceMap: If true, a separate sourcemap file will
   * be created.
   */
  sourceMap: true,

  /**
   * format: The format of the generated bundle
   */
  format: 'iife',

  /**
   * dest: the output filename for the bundle in the buildDir
   */
  dest: 'main.js',

  // Add this to avoid Eval errors
  useStrict: false,

  /**
   * plugins: Array of plugin objects, or a single plugin object.
   * See https://github.com/rollup/rollup/wiki/Plugins for more info.
   */
  plugins: [
    ngTemplate(),
    builtins(),
    commonjs({
      include: [
        'node_modules/rxjs/**',
        'node_modules/angularfire2/**',
        'node_modules/firebase/**',
        'node_modules/@ionic/storage/**',
        'node_modules/localforage/**',
        'node_modules/angular2-moment/**'
      ],
      namedExports: {
        'node_modules/angularfire2/node_modules/firebase/firebase.js': ['initializeApp', 'auth', 'database'],
        'node_modules/angularfire2/node_modules/firebase/firebase-browser.js': ['initializeApp', 'auth', 'database'],
        'node_modules/angular2-moment/index.js': ['MomentModule']

      }
    }),
    nodeResolve({
      module: true,
      jsnext: true,
      main: true,
      browser: true,
      extensions: ['.js']
    }),
    globals(),
    json()
  ]

};


if (process.env.IONIC_ENV == 'prod') {
  // production mode
  rollupConfig.entry = '.tmp/app/main.prod.js';
  rollupConfig.sourceMap = false;
}
module.exports = rollupConfig;
```

###Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0-201610041708
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v4.5.0

**Comment by ihadeed** [comment]
Do you know what is triggering that error? 

Are you calling any plugin APIs on app startup ?

**Comment by taljacobson** [comment]
closing this issue since it isnt a problem with the ionic native but with the plugin it self..

turns out that the plugin has its own polyfills that interfere/confilict and breaks the app.. i found i fork of the original plugin that removes the polyfills and it seems not to break any more, although i have not actually tested the plugin.

for any one who might have the same problem the fork is
[link to the fork] (https://github.com/rsanchez-forks/cordova-plugin-inapppurchase)
`
https://github.com/rsanchez-forks/cordova-plugin-inapppurchase
`


the ionic team might want to reference the problem on the [in app purchase native page](https://ionicframework.com/docs/v2/native/inapppurchase/), and add the link to the fork

**Comment by kodeine** [comment]
@taljacobson i faced the same issue instead it simply crashes the app and i see white screen of death on start. When i remove the plugin all starts working.
