### ISSUE TITLE
NativePageTransitions problem

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#669]
_From @raul07kry on October 8, 2016 0:54_

In IonicNative there is a NativePageTransition plugin, but use case is completely empty. I only found a way to use it with Ionic 1, but absolutly 0 information about Ionic 2 usage. C'mon guys, you could do better. Can anybody paste a simple code about usage of this thing? Thank you in advance.

_Copied from original issue: driftyco/ionic#8572_

**Comment by dr1v3** [comment]
Any updates?

**Comment by mlynch** [comment]
The docs are here: http://ionicframework.com/docs/v2/native/nativepagetransitions/

**Comment by raul07kry** [comment]
You are funny guy. I really didnt see the docs. Thanks for the link. Now please paste me a link with a use case which i was asking about. How can I use this plugin with NavController, what about default animations. Which line of the linked docs explain that? As you can see I am not the only one who has problem with that plugin so just say you dont know instead of pasting doc and closing issue...

**Comment by mlynch** [comment]
There's a lot more info here: http://plugins.telerik.com/cordova/plugin/native-page-transitions

To use that with this Ionic Native class, substitute `window.plugins.nativepagetransitions` with `NativePageTransitions`

**Comment by raul07kry** [comment]
Thanks, thats a little better. But there is still no use case in Ionic. I have Nav.push(Page). Where do I put code for transition? Should I use some kind of href in html? I just want a little code as a use case. I really didnt expect it was so hard to do for someone with experience in Ionic :/

**Comment by mlynch** [comment]
Then don't use this plugin. Stick with Ionic's `NavController`: http://ionicframework.com/docs/v2/api/navigation/NavController/

I can see how this would be confusing and I appreciate the feedback. We will look into how we can make this more clear.

**Comment by dr1v3** [comment]
@mlynch NavController js animations are rather slow, this plugin's animations are hardware accelerated (i think so), we want to know how to disable NavController animations and use native animations instead.
