### ISSUE TITLE
Use Provider in BaseRequestOptions

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#670]
_From @kyleap on October 10, 2016 5:1_

I want set headers for every http request , so i try get storage data by NativeStorage , but the service provider is null (looks like not Injectable ready) , how can i use service provider in baseRequestOptions , thanks

NativeStorage : [https://ionicframework.com/docs/v2/native/nativestorage/](url)

code:

@Injectable()
export class AppRequestOptions extends BaseRequestOptions {
  constructor(private nativeStorage: NativeStorageService) {
    super();
    // Null
    nativeStorage.get('authorizationData').then((authData)=>{  
        this.headers.append('Authorization', 'Bearer ' + authData.access_token);
    })
  }
}

_Copied from original issue: driftyco/ionic#8596_

**Comment by ihadeed** [comment]
Ionic native doesn't offer Angular2 providers at the moment you can only
use the static methods.
