### ISSUE TITLE
Error on LocationAccuracy.REQUEST_PRIORITY_HIGH_ACCURACY

### ISSUE THREAD

**Issue by junaidahmed93** [driftyco/ionic-native#676]
@ihadeed Initially i was facing problem in Location Accuracy (Module has no exported member 'Location Accuracy'). This problem is now fixed, but i am getting another error after this fix
I also update ionic-native to latest but still no luck.
I am getting error 
```
Argument of type number is not assingable to parameter of type string. (property) LocationAccuracy.REQUEST_PRIORITY_HIGH_ACCURACY
```

LocationAccuracy.canRequest().then((canRequest: boolean) => {

if(canRequest) {
`Error After this line`
LocationAccuracy.request(LocationAccuracy.REQUEST_PRIORITY_HIGH_ACCURACY).then(
() => console.log('Request successful'),
error => console.log('Error requesting location permissions', error)
);
}

});

**Comment by ihadeed** [comment]
thanks this is now fixed and will be available shortly in the next patch release
