### ISSUE TITLE
2.0 RC0 Geolocation Not Working

### ISSUE THREAD

**Issue by lufias** [driftyco/ionic-native#683]
After upgrade, Geolocation plugin keeps returning error of PositionError with no helpful message at all. Tried on two different phone with the same errors returned. Im running it with crosswalk plugin on android platform. I even create a fresh project, but still the errors persist.

https://github.com/lufias/GeoTest

```
import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar, Geolocation } from 'ionic-native';

import { TabsPage } from '../pages/tabs/tabs';

@Component({
  template: `<ion-nav [root]="rootPage"></ion-nav>`
})
export class MyApp {
  rootPage = TabsPage;

  constructor(platform: Platform) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();

      		Geolocation.getCurrentPosition().then(
				(resp)=>{					
					console.log(resp)
				}, 
				(error)=>{
					console.info(error)
				}
			)	
    });
  }
}
```

```
Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04.1 LTS 
Node Version: v6.7.0

```

**Comment by ihadeed** [comment]
Does this only happen when you're using crosswalk?

I'm able to use this plugin on both Android, iOS, and Browser without any
problems.

**Comment by lufias** [comment]
@ihadeed I'll give it a try.. without crosswalk..

**Comment by lufias** [comment]
@ihadeed After removing crosswalk, I still unable to get the result, and the plugin still return me PositionError. But, running ionic serve, chrome shows me this warning instead:

`getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.`

**Comment by lufias** [comment]
@ihadeed it works on firefox though.. as expected.. so, the limitation is due to chrome? since crosswalk is itself a chrome engine.. im not sure if i somehow set my default mobile browser to chrome, that even removing crosswalk still have the effect persist..

**Comment by lufias** [comment]
@ihadeed Finally made it to works.. it is indeed due to crosswalk.. chrome had implemented this http security started with crosswalk 21+ i believe.. it work fine if i downgrade to 18+.. right now, i just skip using  crosswalk altogether.. thanks..

**Comment by ihadeed** [comment]
Let us know if you find a solution/workaround for crosswalk. So we can add
a note in the plugin's docs.

**Comment by lufias** [comment]
@ihadeed there's an issue posted here before on how to serve ionic with https.. 

https://github.com/driftyco/ionic/issues/1686

I have yet to try it, but if it does works, having https as default with autogenerated cert or something would be something nice to put into consideration..

**Comment by lufias** [comment]
@ihadeed it seems people had already discussed this before.. 

https://forum.ionicframework.com/t/geolocation-wont-work-anymore/56687/6

it works fine without live reload.. the best option for me right now is to simply mock up the value during development with live reload on..

**Comment by iantearle** [comment]
I'm still having a problem, I thought it was to do with updated Chrome and Safari not allowing non secure origins access to geolocation? Is it possible to run ionic serve as secure over https?

**Comment by ihadeed** [comment]
Closing this, since it's an issue with Crosswalk.

**Comment by mlynch** [comment]
hmmmmmm, damn. Either way, I think we need to figure out a way forward for people here on this. I'm curious why this hasn't come up before.

Also, are you all using the `cordova-plugin-geolocation`? It should "skip" crosswalk and use the native implementation. Let me know

**Comment by ihadeed** [comment]
@mlynch it doesn't use native code to fetch the location on Android, uses navigator.geolocation instead. See https://github.com/apache/cordova-plugin-geolocation/blob/master/www/android/geolocation.js#L31-L42

**Comment by mlynch** [comment]
Hey, does this work for you guys? seems like crosswalk has settings to work around this, so all is not lost

http://stackoverflow.com/a/36895310

**Comment by iantearle** [comment]
None of this resolves the issue of insecure origin within Chrome or Safari, I don't have crosswalk installed only Cordova geolocation plugin. The only way to develop any further is using Firefox who at the moment don't enforce secure origins to be able to fetch geolocation from the browser.

**Comment by mlynch** [comment]
Ignore ionc ionic serve at the moment. If you deploy your app to an iOS device or android device, does it not work?

Ionic serve needs to support https, that's a separate issue
