### ISSUE TITLE
plugin_not_installed Ionic2 RC

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#688]
_From @h2qutc on October 12, 2016 10:27_

Hi, 
When I tried "ionic run android", I got the error below: 

`Native: tried calling AppVersion.getVersionNumber, but the AppVersion plugin is not installed.
main.js:74377 Install the AppVersion plugin: 'ionic plugin add cordova-plugin-app-version'
main.js:3602 EXCEPTION: Uncaught (in promise): plugin_not_installedErrorHandler.handleError @ main.js:3602
main.js:3607 ORIGINAL STACKTRACE:ErrorHandler.handleError @ main.js:3607
main.js:3608 Error: Uncaught (in promise): plugin_not_installed`

I got the latest version of ionic-native and I installed the necessary plugin.  

Is that an issues of Ionic2 RC or I was doing Something wrong? 

_Copied from original issue: driftyco/ionic#8642_

**Comment by jgw96** [comment]
_From @ramonornela on October 12, 2016 14:48_

Move to repo ionic-native 😉 

Thanks

**Comment by mlynch** [comment]
@h2qutc are you waiting to app `AppVersion.getVersionNumber` after `platform.ready`?

**Comment by h2qutc** [comment]
Hi, this was the raison :) thanks @mlynch

**Comment by yuridicarlo** [comment]
Hello, I got this code

constructor(public platform: Platform, private http: Http) {
		
		this.appVersionControl = '0';
		this.appVersionNumber = '0';
		
		this.platform.ready().then(() => {
			if (this.platform.is('cordova')) {
			
				// Okay, so the platform is ready and our plugins are available.
				// Here you can do any higher level native things you might need.
				AppVersion.getVersionNumber().then((s) => {
					
					this.appVersionNumber = s;
					
					this.getAppVersionControl().subscribe(
						data => {
							this.appVersionControl = data.appVersionControl;
							console.log('Versioni controllo e app ' + this.appVersionControl + ' ' + this.appVersionNumber);
							
						},
						err => {
							console.log(err);
						}
					);
					
				});
			
			}
		});
		
	}

called from app.ts

nitializeApp() {
		let start = this.versionControl.isStartAuthorized();
		let pauth = this.isPreviouslyAuthorized();
		
		this.platform.ready().then(() => {
			// Okay, so the platform is ready and our plugins are available.
			// Here you can do any higher level native things you might need.
			if (start && pauth) {
				this.rootPage = ListPage;
			}
			console.log('Errore nell\'inizializzazione. Motivo auth a start: ' + start + ', login: ' +  pauth);
			
			StatusBar.styleDefault();
			
		});
	}

but I have ever this error on the console

0     201862   log      Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
1     202356   log      deviceready has not fired after 5 seconds.
2     202356   log      Channel not fired: onDOMContentLoaded
3     202357   warn     Native: deviceready did not fire within 2000ms. This can happen when plugins are in an inconsistent state. Try removing plugins from plugins
 and reinstalling them.
4     202878   warn
      *It looks like you're using the old forms module. This will be opt-in in the next RC, and
      will eventually be removed in favor of the new forms module. For more information, see:
      https://docs.google.com/document/u/1/d/1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/pub

5     203024   log      DEVICE READY FIRED AFTER, 4841, ms
6     203041   warn     Native: tried calling AppVersion.getVersionNumber, but the AppVersion plugin is not installed.
7     203096   warn     Install the AppVersion plugin: 'ionic plugin add cordova-plugin-app-version'
8     203097   log      Errore nell'inizializzazione. Motivo auth a start: true, login: false
9     203098   warn     Native: tried calling StatusBar.styleDefault, but the StatusBar plugin is not installed.
10    203098   warn     Install the StatusBar plugin: 'ionic plugin add cordova-plugin-statusbar'
11    203098   warn     Native: tried calling AppVersion.getVersionNumber, but the AppVersion plugin is not installed.
12    203099   warn     Install the AppVersion plugin: 'ionic plugin add cordova-plugin-app-version'
13    203437   group    EXCEPTION: Error: Uncaught (in promise): plugin_not_installed
14    203438   error    EXCEPTION: Error: Uncaught (in promise): plugin_not_installed
15    203438   error    STACKTRACE:
16    203439   error    Error: Uncaught (in promise): plugin_not_installed
    at resolvePromise (http://172.18.113.35:8100/build/js/zone.js:538:32)
    at resolvePromise (http://172.18.113.35:8100/build/js/zone.js:523:18)
    at http://172.18.113.35:8100/build/js/zone.js:571:18
    at ZoneDelegate.invokeTask (http://172.18.113.35:8100/build/js/zone.js:356:38)
    at Object.onInvokeTask (http://172.18.113.35:8100/build/js/app.bundle.js:37559:41)
    at ZoneDelegate.invokeTask (http://172.18.113.35:8100/build/js/zone.js:355:43)
    at Zone.runTask (http://172.18.113.35:8100/build/js/zone.js:256:48)
    at drainMicroTaskQueue (http://172.18.113.35:8100/build/js/zone.js:474:36)
    at ZoneTask.invoke (http://172.18.113.35:8100/build/js/zone.js:426:22)
17    203439   groupEnd
18    203440   error    Unhandled Promise rejection:, plugin_not_installed, ; Zone:, angular, ; Task:, Promise.then, ; Value:, plugin_not_installed

Do you know how can I fix that? I know this code is "not from an expert coder"... but I would like to know how can happen that.

Thanks,
Yuri

**Comment by CHOMNANP** [comment]
I got same problem with CardIO.

`this.platform.ready()
      .then(() =>{
          
          //alert(JSON.stringify(cordova.plugins.Keyboard));
          CardIO.canScan()
          .then((res: boolean) => {               
                alert('Can scan Cardio');
              })
            .catch(function(error) {
              alert(JSON.stringify(error));
            });                 
      });`

Can anyone help me?

**Comment by rogeliotrejo13** [comment]
I have a problem similar when run app in android, debug and release version

main.js:110393 Ionic Native: deviceready did not fire within 5000ms. This can happen when plugins are in an inconsistent state. Try removing plugins from plugins/ and reinstalling them.
