### ISSUE TITLE
BackgroundMode Plugin documentation

### ISSUE THREAD

**Issue by tobiasfiechter** [driftyco/ionic-native#692]
Hi,
I try to use the BackgroundMode Plugin. For me it's unclear how to use it, the documentation on https://ionicframework.com/docs/v2/native/background-mode/ is very rudimentary and doesn't show hot wo override the static "on" Functions.
The plugin doesn't seem to work. What I tried with no success

`BackgroundMode.enable();
BackgroundMode.onactivate().subscribe(() => {
      console.error('BACKGROUND ENTERED');
    });`

`BackgroundMode.enable();
let Backgr: any = BackgroundMode;
    Backgr.onactivate = () => {
      console.error('BACKGROUND ENTERED');
    };`

**Comment by ihadeed** [comment]
This should work:
```
BackgroundMode.onactivate().subscribe(() => {

});
```

Can you share the code you're using?
