### ISSUE TITLE
Cordova File Transfer Plugin

### ISSUE THREAD

**Issue by zackarychapple** [driftyco/ionic-native#70]
I have a new application that I am working on using Ionic2 with Typescript.  One of the requirements is offline video downloads.  I would like to be able to use Ionic-Native to perform the download of the videos and saving on the device.  Is this on the roadmap?

**Comment by ihadeed** [comment]
Yes. This plugin will be added soon: https://github.com/apache/cordova-plugin-file-transfer

**Comment by zackarychapple** [comment]
Fantastic.  I'm subscribed to this thread so hope when it lands it gets tagged.

**Comment by diosney** [comment]
Hi, sorry if I'm trolling with this.

This is different as http://ngcordova.com/docs/plugins/file, right?

Is `cordova-plugin-file` already supported?

Thanks

**Comment by diosney** [comment]
Hi, sorry if I'm trolling with this.

This is different as http://ngcordova.com/docs/plugins/file, right?

Is `cordova-plugin-file` already supported?

Thanks

**Comment by ihadeed** [comment]
Yes that's correct. They are different. The `file` plugin is partially
implemented.

**Comment by dtaalbers** [comment]
Keeping an eye on this issue! Can't wait until this will be added.

**Comment by ghenry22** [comment]
Any news on the file transfer plugin?

**Comment by kewix** [comment]
Would be very useful to mee too !

**Comment by ihadeed** [comment]
The plugin is added and is available in the current NPM package and Github release. Sorry I forgot to close this earlier!

**Comment by aneeskodappana** [comment]
the transfer plugin doesn't ask for permission on android. 
isn't fine to use this.file.dataDirectory instead of cordova.file.dataDirecotory as per the ionic wrapper documentation.

[Transfer plugin docs ](https://ionicframework.com/docs/native/transfer/)

```
download() {
  	const transfer: TransferObject = this.transfer.create();
  	const url = encodeURI("http://someimageurl.com/file.png");

  	transfer.download(url, this.file.dataDirectory + "file.png")
  		.then((entry) => {
  			alert("File downloaded successfully " + entry.toURL());
  		}, (error) => {
  			alert(JSON.stringify(error));
  		});
  }
```

the above code doesn't work. the app also not asking fo storage permission. what is the problem here?
