### ISSUE TITLE
Cordova 3rd party plugin provide own typescript API

### ISSUE THREAD

**Issue by christocracy** [driftyco/ionic-native#702]
As a 3rd party plugin developer, I want to provide my own typescript API for my Cordova plugins.  I don't care to rely on this `ionic-native` mechanism.  I already know how to produce a typescript API for my Cordova plugins.

**Comment by ihadeed** [comment]
I don't understand your reason behind opening this issue @christocracy

**Comment by ihadeed** [comment]
We don't have any wrappers for your plugins. If you're talking about the background geolocation, we aren't providing any support for your plugin and we don't intend to do so. Our BackgroundGeolocation class wraps this fork here: https://github.com/mauron85/cordova-plugin-background-geolocation

**Comment by christocracy** [comment]
I'm not at all interested in having Ionic maintain my *own* plugins` APIs.  Ionic needs to be more like [NativeScript](https://www.nativescript.org/) in this regard, allowing a Cordova plugin to provide in its `package.json`:
```
{
  "name": "some-plugin",
  "main": "some-plugin.js",
  "typings":"some-plugin.d.ts"
}
```

and respect the plugin's `.npmignore` and not copy the `.ts` files when doing an `$ ionic plugin add some-plugin`
```
src/*.ts
!src/*.d.ts
```

**Comment by ihadeed** [comment]
We do not maintain anyone's plugins API at Ionic Native. We simply provide wrappers with few extra features for those who would like to use it. And anyways, we do not have a wrapper for any of your plugins.

As for your concern about the `ionic plugin` command behaviour; I suggest you talk to the maintainers of the `ionic-cli` repo. AFAIK, the Ionic CLI doesn't do much when it comes to installing plugins. They let the Cordova CLI handle that.

Repo link: https://github.com/driftyco/ionic-cli
Plugin command code: https://github.com/driftyco/ionic-cli/blob/master/lib/ionic/plugin.js

**Comment by mlynch** [comment]
@christocracy we appreciate the feedback but I don't really see what you're getting at here. If you have TypeScript bindings for your plugin, that's awesome...why would anything we're doing here get in the way of that?

Anyways, if we had your plugins in ionic-native, perhaps we could add a feature whereby the plugin provides its own typings. I'm sure you know that you're in the minority of Cordova plugin authors that provide typings.

**Comment by christocracy** [comment]
@mlynch my expectation would be to simply be able to
```
$ cordova plugin add some-plugin
```

```Javascript
import {SomePlugin} from 'some-plugin`
```

Unfortunately, since a plugin doesn't exist in `node_modules`, one must provide a relative-path to `/plugins` from the current `.ts` file, eg:
```Javascript
import {SomePlugin} from '../../../plugins/some-plugin`
```

However, even doing that, a simple Hello World app silently fails to build until I manually deleted the plugin's `some-plugin.ts` file.  This wouldn't be an issue were the plugin installed from npm, since the `.npmignore` would prevent the `some-plugin.ts` file from being uploaded but it's a pain while developing.  But yea, once I did all that, sure...everything works great but not very pleasant for the plugin's consumer having to provide a relative-url.

Anyway, this is an issue that should be taken up with `ionic-cli`.  Thanks.

**Comment by mlynch** [comment]
Is this not just a limitation of cordova, since `cordova plugin add` doesn't add the plugin to npm? I'm not sure if we could do much here or on the CLI side to get around this. Perhaps we could add some bundle tweaks so that our app-scripts looks in the plugins directory? My fear is that's non standard.

Are you able to make this work with a vanilla cordova project?

**Comment by christocracy** [comment]
It's too bad that cordova doesn't simply add their plugins to `node_modules`, since plugins migrated to npm.  If I `npm install some-plugin`, in addition to `$ cordova plugin add some-plugin`, that works too.  Having the plugin installed in two folders obviously isn't going to work.

**Comment by distante** [comment]
> It's too bad that cordova doesn't simply add their plugins to `node_modules`, since plugins migrated to npm. If I `npm install some-plugin`, in addition to `$ cordova plugin add some-plugin`, that works too. Having the plugin installed in two folders obviously isn't going to work.

Hi @christocracy How are you managing this in this days? (If you are doing it). I am doing a plugin and even when I want to make a PR for ionic native I also want to let typings for people using another frameworks with typescript.

**Comment by christocracy** [comment]
Ive got this solved ages ago.

My plugin include their own typescript api.

**Comment by christocracy** [comment]
Just have to make sure the plugin is installed to node_modules

**Comment by distante** [comment]
So instruct the user to install with npm too? Which one is your plugin with
this?
