### ISSUE TITLE
StreamingVideo plugin not working in Ionic 2

### ISSUE THREAD

**Issue by shikharls** [driftyco/ionic-native#705]
Hi Ionic team,
I am having a problem with the plugin StreamingMedia in Ioninc 2. I have followed all the steps put by Max on Oct 14 on the blog of updating node modules and @ionic/app-scripts@latest

I did:
`rm -rf node_modules/`
`npm install`
`ionic plugin add cordova-plugin-streaming-media`
Plugin "com.hutchind.cordova.plugins.streamingmedia" already installed on ios.

When I run:
```
this.platform.ready().then(() => {
      StreamingMedia.playVideo(url, options);
    });
```
I get:
Install the t plugin: 'ionic plugin add cordova-plugin-streaming-media'

I also tried adding --dev option in package.json build command.

**Comment by mlynch** [comment]
Any chance you could zip up your app and send it to me? max@ionic.io

I'm having trouble reproducing 😟

**Comment by shikharls** [comment]
Hi @mlynch ,

Thanks for the message. I have sent it to your email.

Thanks!

**Comment by mlynch** [comment]
This one ended up being duplicate cordova.js includes in the index.html file.
