### ISSUE TITLE
cordova-plugin-file support

### ISSUE THREAD

**Issue by Fenkiou** [driftyco/ionic-native#71]
Hi,

I see that this plugin is not enabled (and not implemented in fact). So I'm trying to implement it myself, if I understand correctly, the ionic-native plugin is just a wrapper of the ngCordova plugin ? If not, it could be the reason why I can't make it working.

The plugin :
```
// src/plugins/file.ts
import {Plugin, Cordova} from './plugin';

@Plugin({
  plugin: 'cordova-plugin-file',
  pluginRef: 'cordova.file'
})
export class File {
  @Cordova()
  static getFreeDiskSpace(): Promise<any> { return }
}
  ```

How I call it :
```
// myService.ts
import {Injectable} from 'angular2/core';
import {Storage, Platform} from 'ionic-angular';

import {File} from 'ionic-native';


@Injectable()
export class StorageService {

  constructor(private platform: Platform) {
  }

  getFreeDiskSpace(path: string, directory: string) {
    this.platform.ready().then(() => {
      File.getFreeDiskSpace(path, directory).then(result => {
        console.log(result);
      }, err => {
        console.log(err);
      });
    });
  }
}
```

I have an error on line 100 in plugins.ts `return get(window, pluginObj.pluginRef)[methodName].apply(pluginInstance, args);` If I enable the console.log just before this line, it's the call on File.getFreeDiskSpace with the arguments. But there is no indication on what's wrong.

Just to be sure, to test the package, you do `npm run-script build_bundle` then you install the package like this `npm install path/to/my/local/package` from the ionic project ?

Can I have some help or maybe this will be implemented soon ?

**Comment by ihadeed** [comment]
The code you have looks right to me ..
Do you have the plugin `cordova-plugin-file` installed?

**Comment by Fenkiou** [comment]
Yes, the plugin is installed. Maybe the plugin is missing the equivalent of $cordovaFileError and $window ?

**Comment by ihadeed** [comment]
Hey @Fenkiou ..

I was looking at the plugin's source code. The function `getFreeDiskSpace()` is not exposed in the plugin's JavaScript file. It is a function defined in the Java and Objective-C files only. Which explains why you aren't able to access it through the ionic-native wrapper you wrote.
Ref: https://github.com/apache/cordova-plugin-file/search?utf8=%E2%9C%93&q=getFreeDiskSpace

The ionic-native wrappers route your call to the plugin's methods that are defined in their JavaScript files (which is usually the methods they have documented).

You probably saw the method implemented in ngCordova and thought it's one of the plugin's methods. If you look at their code, they are actually executing the method using `cordova.exec()` which speaks to the Java/Object-C files directly without passing by the JS file.
Ref: https://github.com/driftyco/ng-cordova/blob/master/src/plugins/file.js#L27-L35

We might be looking to implement a similar approach to that method when we add the file plugin.

**Comment by Fenkiou** [comment]
Ok, I thought that ionic-native plugin wrap ngCordova plugin but it's the cordova plugin that is wrapped.

`cordova.exec`is only used in getFreeDiskSpace(), and when I saw it, I tried to implement checkDir() method instead, like this :

```
@Cordova()
static checkDir(path: string, dir: string):Promise<any> {
  let resolveFn, rejectFn;
  let promise = new Promise((resolve, reject) => {resolveFn = resolve; rejectFn = reject; })
    
  var directory = path + dir;
        
  if ((/^\//.test(dir))) {
    rejectFn('directory cannot start with \/');
  }

  try {
    var directory = path + dir;
      
    window.resolveLocalFileSystemURL(directory, function (fileSystem) {
      if (fileSystem.isDirectory === true) {
        resolveFn(fileSystem);
      } else {
        rejectFn({code: 13, message: 'input is not a directory'});
      }
    }, function (error) {
      error.message = error.code;
      rejectFn(error);
    });
  } catch (err) {
    err.message = err.code;
    rejectFn(err);
  }
    
  return promise;
}
```
But it's not working anyway. Even with just something like this :
```
@Cordova()
static checkDir(path: string, dir: string): string {
  return "some string";
}
```

It's still raising an error on https://github.com/driftyco/ionic-native/blob/master/src/plugins/plugin.ts#L100 without tell me the error but it's this call that fails.

**Comment by ihadeed** [comment]
Adding the `@Cordova()` decorator overrides anything that's defined in your function.

**Comment by ihadeed** [comment]
This should work.

```js
static checkDir(path: string, dir: string):Promise<any> {
  return new Promise((resolve, reject) => {
    var directory = path + dir;

  if ((/^\//.test(dir))) {
    reject('directory cannot start with \/');
  }

  try {
    var directory = path + dir;

    window.resolveLocalFileSystemURL(directory, function (fileSystem) {
      if (fileSystem.isDirectory === true) {
        resolve(fileSystem);
      } else {
        reject({code: 13, message: 'input is not a directory'});
      }
    }, function (error) {
      error.message = error.code;
      reject(error);
    });
  } catch (err) {
    err.message = err.code;
    reject(err);
  }

  });
}
```

**Comment by Fenkiou** [comment]
That's it, thank you ! I'll try to implement methods I need to see if it works and I hope get back with a PR.

**Comment by ihadeed** [comment]
@Fenkiou Thanks for feedback. Glad you got it working.
