### ISSUE TITLE
Ndef not exported by NFC plugin

### ISSUE THREAD

**Issue by HendrikGrobler** [driftyco/ionic-native#713]
The Ndef class is not exported the nfc.ts plugin. It has an annotation for private and is not included in the index.ts file. However, the examples in both the ionic docs and code comments suggest importing it alongside NFC.

I get the following error when I run Ionic Serve:
`bundle failed: 'Ndef' is not exported by node_modules/ionic-native/dist/esm/plugins/nfc.js (imported by node_modules/ionic-native/dist/esm/index.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module`

I would like to create a PR to fix this and a few other things related to Ndef, however I am struggling to get the build to reflect the exported class. I have removed the private annotation, added Ndef to the imports in `index.ts` and also added it to the `window['IonicNative']` object. When I run `npm run build` everything runs fine but there is no export for Ndef in either `es5/plugins/nfc.js` or `esm/plugins/nfc.js`.

Would appreciate some guidance in getting this built so I can test it and create the PR.

**Comment by ihadeed** [comment]
Yeah that's because we're using `export declare class Ndef {` ... I had similar issues with other plugins earlier.

We would have to do something else like here: https://github.com/driftyco/ionic-native/commit/b95f88c#diff-a740ceecb06436e4f3c45e162549de31R111

**Comment by HendrikGrobler** [comment]
Will try converting it to a proper class with empty functions. Should I do the same for Nfc while I'm at it or is it fine as is?

**Comment by HendrikGrobler** [comment]
It seems like that Ndef class is mapping to this NPM library: https://www.npmjs.com/package/ndef
I don't see any dependencies in the package.json file other than RxJS, is it up to the user to install the correct dependencies? Or do none of the other plugins have dependencies other than the cordova plugin?

**Comment by ihadeed** [comment]
No the Ndef class comes with the NFC plugin. It is the only thing that needs to be modified. It needs to be converted to a regular class instead of `declare class`, then add `plugin` and `pluginRef` private properties that match the `NFC` class. Then add `@Cordova({ sync: true })` decorators to each function.
