### ISSUE TITLE
Image picker issue

### ISSUE THREAD

**Issue by jtushar53** [driftyco/ionic-native#719]
Hello,

Getting imagepicker issue when installing from
ionic plugin add cordova-plugin-image-picker

but after installing 
ionic plugin add https://github.com/Telerik-Verified-Plugins/ImagePicker.git

it worked properly
Please update the docs.

**Comment by ihadeed** [comment]
Thanks!

Will update it soon.

This is an easy fix you want to submit a PR and contribute.

Edit src/plugins/imagepicker.ts on github and change the `plugin` value
inside of the @Cordova decorator.

**Comment by ihadeed** [comment]
Just had a look. Our wrapper isn't designed for the repo you mentioned, it follows this plugin here: https://github.com/wymsee/cordova-imagePicker

What is the issue what you're having with the plugin?

**Comment by jtushar53** [comment]
Hello @ihadeed ,
i was getting error while accessing requestReadPermission and hasReadPermission functions. 
As also i cant see both function in
https://github.com/wymsee/cordova-imagePicker/blob/master/www/imagepicker.js

and can see here
https://github.com/Telerik-Verified-Plugins/ImagePicker/blob/master/www/imagepicker.js

**Comment by gldraphael** [comment]
Same issue here. According to the [docs](https://ionicframework.com/docs/v2/native/image-picker/), `ImagePicker` should have `hasReadPermission()` and `requestReadPermission()`. 

Both of the static methods are marked with an Android tag. Do I need to do something to get that to work? Am I missing anything?

**Comment by jtushar53** [comment]
@ihadeed ,

Telerik's plugin also have outputType: int which can be set to FILE_URI or BASE64_STRING
