### ISSUE TITLE
TypeScript definitions for filesystem ‘Entry’ is wrong

### ISSUE THREAD

**Issue by bunsen32** [driftyco/ionic-native#720]
In this file:
https://github.com/driftyco/ionic-native/blob/master/src/plugins/file.ts#L28

The property `Entry.fileSystem` should instead be `Entry.filesystem` (with lower-case ‘s’).

**Comment by ihadeed** [comment]
Seems like it is camel case over here too: http://definitelytyped.org/docs/cordova--cordova/interfaces/fileentry.html

**Comment by bunsen32** [comment]
Possibly, but it’s still wrong :)

Fails at runtime if you use the camelCase type definition:

    let entry: Entry = //whatever
    entry.fileSystem.root.toURL()

However, this succeeds at runtime:

    let entry: Entry = //whatever
    (entry as any).filesystem.root.toURL()

**Comment by bunsen32** [comment]
The Cordova File plugin code (which is what the type definitions are for) has all-lower-case `filesystem` property: https://github.com/apache/cordova-plugin-file/blob/master/www/Entry.js#L53

And here is the API which it implements: https://developer.mozilla.org/en-US/docs/Web/API/FileSystemEntry/filesystem (also lower-case)
