### ISSUE TITLE
SMS: Expose `hasPermission` method

### ISSUE THREAD

**Issue by davejlong** [driftyco/ionic-native#721]
To support Android Marshmallow's permission system, The Cordova SMS plugin now has a `hasPermission` method that takes 2 arguments (callback handlers) to test if the app has permission to send SMS messages. Support for this method should be added to the SMS object in Ionic Native.

**Comment by ihadeed** [comment]
thanks, added now and will be available in the next release

**Comment by khurana87** [comment]
I am trying to use haspermission method but nothing is returning that method
