### ISSUE TITLE
Google Maps incomplete documentation

### ISSUE THREAD

**Issue by melkir** [driftyco/ionic-native#730]
The repository and the command to install the plugin are missing
http://ionicframework.com/docs/v2/native/googlemap/

**Comment by nakulgulati** [comment]
@melkir Take a look at this link http://ionicframework.com/docs/v2/native/google-maps/

There are multiple links for the docs. I have filed an issue ([#734](https://github.com/driftyco/ionic-native/issues/734)) for the inconsistency.

**Comment by melkir** [comment]
Thanks nakulgulati for the correct link and the issue.
