### ISSUE TITLE
ContactError constants don’t seem to be exported from ionic-native

### ISSUE THREAD

**Issue by bunsen32** [driftyco/ionic-native#731]
I’m programming against the native plugin Contacts API, and cannot `import { ContactError } from 'ionic-native'`

I see from the source that `ContactError` is declared in https://github.com/driftyco/ionic-native/blob/master/src/plugins/contacts.ts but just not exported. So possibly just a case of adding `export` in front of the declaration?

This is necessary because failed promises from Contacts API return numeric code. Only way to refer to the named numeric constants in my code currently is by adding `declare var ContactError` (which is obviously not type safe). Or hard-coding the numeric values in my code, which would be even worse.

(I would be happier receiving `IContactError` objects as errors, frankly, in case future enhancements to the plugin provide useful values for the `message` field.)

**Comment by ihadeed** [comment]
Added export statement. Fix will be available in the next release.

Let me know if the issue is still there after updating.
