### ISSUE TITLE
InAppBrowser - possible to Customize? insertCss not working

### ISSUE THREAD

**Issue by vaibsVB** [driftyco/ionic-native#733]
Greetings to all,

I have a requirement in which I want to customize `InAppBrowser's` `location bar` in `Android`.
I want to replace/add few buttons and its positions too. I want to hide only the URL portion and keep the buttons, etc.

Is it possible to customize or modify in `InAppBrowser`?
I'm using `cordova-plugin-inappbrowser plugin`.

I tried `executeScript` and `insertCss` methods.
but the problem is `insertCss` not working.

Any help Will be appreciated.
Thanks in advance.

**Comment by ihadeed** [comment]
You will need to use Theamable Browser plugin. See http://ionicframework.com/docs/v2/native/themeablebrowser/

**Comment by vaibsVB** [comment]
@ihadeed Thanks for reply.

I tried `ThemeableBroswer` which is fork of `cordova-plugin-inappbrowser`.
But the `ThemeableBroswer` also not working in my case.

Thanks.
