### ISSUE TITLE
Multiple documentation links for Google Maps (ionic-native)

### ISSUE THREAD

**Issue by nakulgulati** [driftyco/ionic-native#734]
There is more than one link available for Google Maps plugin documentation in the ionic-native docs, leaving people confused over the usage and state of the plugin.

The following are the links that I found: 
1. http://ionicframework.com/docs/v2/native/google-maps/
2. http://ionicframework.com/docs/v2/native/googlemap/
3. http://ionicframework.com/docs/v2/native/Google%20Maps/

In the above link 1 is the accurate one as it gets auto generated with changes and commits to the repo.

**Comment by ihadeed** [comment]
This is fixed now, just waiting on the docs update.

You can see latest docs here for now: http://ionic-site-staging.herokuapp.com/docs/v2/native/google-maps

**Comment by nakulgulati** [comment]
@ihadeed The link you mentioned shows the updated docs but the other links I mentioned are still active.

Also the link in the side menu list on http://ionicframework.com/docs/v2/native/ for Google Maps takes you to link 2 I mentioned above.

**Comment by ihadeed** [comment]
The docs are updated now, closing this issue.
