### ISSUE TITLE
InAppBrowser - possible to Customize? insertCss not working

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#736]
_From @vaibsVB on October 20, 2016 11:29_

Greetings to all,

I have a requirement in which I want to customize `InAppBrowser's` `location bar` in `Android`.
I want to replace/add few buttons and its positions too. I want to hide only the URL portion and keep the buttons, etc.

Is it possible to customize or modify in `InAppBrowser`?
I'm using `cordova-plugin-inappbrowser plugin`.

I tried `executeScript` and `insertCss` methods.
but the problem is `insertCss` not working.

`cordova-plugin-inappbrowser` plugin has `insertCSS` method in it. And in the (typescript definition file) `inappbrowser.d.ts` under the `node_modules` has `insertCss` method. Is there any typos in the `inappbrowser.d.ts` file.

Any help Will be appreciated.
Thanks in advance.

_Copied from original issue: driftyco/ionic#8816_

**Comment by vaibsVB** [comment]
@John-Luke #733 is created by me in `ionic-native`.

And this thread is replicated by `Justin Willis` from #8816 as Justin stated `Copied from original issue: driftyco/ionic#8816`
