### ISSUE TITLE
Contacts, photos property doesn't work with null value

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-native#737]
Given a contact instance, I'm not allowed to set the photos property to a new array to work with a contact that has no photos. So this,

```
        contact.photos = new Array();
```

doesn't validate in TypeScript. @mhartington thinks it may be an issue in the TS definition fie.

**Comment by cfjedimaster** [comment]
A bit more info - basically the issue is that the TS file knows it is an array, but doesn't accept that it may be null too.

**Comment by cfjedimaster** [comment]
So I removed readonly on the photos prop from the TS file and was able to get stuff working. :)

**Comment by keithdmoore** [comment]
You can't just set it to '[]' ?

**Comment by cfjedimaster** [comment]
Nope. You get an error. That goes away when readonly is removed.

**Comment by ihadeed** [comment]
This should be fixed by https://github.com/driftyco/ionic-native/pull/635

**Comment by cfjedimaster** [comment]
Thanks. Any idea when this PR will get pulled in?

**Comment by ihadeed** [comment]
@cfjedimaster The next goal is 2.2.5 with some bug fixes, then I will merge that PR along with #422  and publish 2.3.0. So it shouldn't take long.

**Comment by cfjedimaster** [comment]
Ok, do you mind a dumb question? My code is doing this when a contact has no photos:

              var f = new ContactField('base64',s,true);

              contact.photos = [];
              contact.photos.push(f);

Will that work - specifically setting it to an empty array? I mean it works now with *my* hack (removing readonly), but your proper fix is a bit different.

**Comment by ihadeed** [comment]
@cfjedimaster Should be fixed now! Please update to v2.2.10 and let me know if you're still having any issues.

**Comment by cfjedimaster** [comment]
Thanks!
