### ISSUE TITLE
“Uncaught TypeError” while creating new ionic-native wrapper

### ISSUE THREAD

**Issue by rephchunhoong** [driftyco/ionic-native#740]
Without any code change straight after I perform git clone, I run 
`npm install` 
`npm run build` 

Then, copied all the file under the generated dist folder to the dist folder inside my ionic-native module. The screen is all blank and I saw this from chrome debugger:

![capture](https://cloud.githubusercontent.com/assets/12269078/19638953/c7ebffa8-9a08-11e6-9c5e-e0d96c144eaf.JPG)

**Comment by rephchunhoong** [comment]
Closer look into main.js, this is the part that fall into error. 

![image](https://cloud.githubusercontent.com/assets/12269078/19676476/2f7fdc7a-9ac7-11e6-94cf-facf0c3bed87.png)

**Comment by ihadeed** [comment]
Can you try with latest version of this repo?

**Comment by ramonornela** [comment]
@ihadeed Same problem in 2.2.5

**Comment by mlynch** [comment]
Ah crap, must by my changes to have an explicit name field. Will change this
