### ISSUE TITLE
Diagnostic method registerPermissionRequestCompleteHandler is not available

### ISSUE THREAD

**Issue by pdrosos** [driftyco/ionic-native#743]
Hi,

I would like to use Cordova Diagnostic's plugin registerPermissionRequestCompleteHandler method:
https://github.com/dpa99c/cordova-diagnostic-plugin#registerpermissionrequestcompletehandler
but it's not currently available in the Ionic Native's Diagnostic module.

Will it be possible to add it to Ionic Native or let me know how can I use it directly from the Cordova plugin?

Thanks!

**Comment by ihadeed** [comment]
thanks, just added, will be available in next release
