### ISSUE TITLE
GoogleAnalytics Unhandled Promise rejection: Tracker not started ; Zone: <root> ; Task: setTimeout ; Value: Tracker not started 

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic-native#744]
Hi,

I added GoogleAnalytics in my app.component.ts like following:

    ngAfterViewInit() {
        this.platform.ready().then(() => {
           this.initGoogleAnalytics();
         });
    }
    
    private initGoogleAnalytics() {
        console.log('here1');
        GoogleAnalytics.startTrackerWithId('UA-XXXXX-1').then(() => {
              console.log('here2');
          });
        }
    }

When I debug my app (with Xcode, iPhone 6, OS 9.1), on startup I've got following error in the console

2016-10-27 08:50:52.926 MyApp[2650:55510] here1
2016-10-27 08:50:52.994 MyApp[2650:55510] ERROR: Unhandled Promise rejection: Tracker not started ; Zone: <root> ; Task: setTimeout ; Value: Tracker not started 
2016-10-27 08:50:52.994 MyApp[2650:55510] ERROR: error JSON.stringify()ing argument: TypeError: JSON.stringify cannot serialize cyclic structures.
2016-10-27 08:50:52.994 MyApp[2650:55510] here2

Could that be fixed?

**Comment by ihadeed** [comment]
Catch the error that's coming from that promise and see what the problem is.

Also check that you are using a valid tracker id (for mobile app, not website)

**Comment by peterpeterparker** [comment]
Of course the tracker is valid. Furthermore it works with my Android phone (I see results in my analytics).

Catching the error brings nothing, same error was parsed even by doing

    GoogleAnalytics.startTrackerWithId(this.RESOURCES.GOOGLE.ANALYTICS.TRACKER_ID).then(() => {
                console.log('here2');
            }, (error:any) => {
                console.log('error: ' + error);
                console.error(error);
            });

**Comment by ihadeed** [comment]
Seems to be issue with the plugin, you can find help at their repo. See this conversation here: https://github.com/danwilson/google-analytics-plugin/issues/291

**Comment by peterpeterparker** [comment]
Thx a lot @ihadeed
