### ISSUE TITLE
Background push on Android doesn't work?

### ISSUE THREAD

**Issue by HectorFGarcia** [driftyco/ionic-native#748]
From docs:

> On Android if you want your on('notification') event handler to be called when your app is in the background it is relatively simple.
> 
> First the JSON you send from GCM will need to include "content-available": "1". This will tell the push plugin to call your on('notification') event handler no matter what other data is in the push notification.

I'm sending this from Node using fcm-node.

```
{"to":"LonGkEy",
"notification":
{
"title":"Nuevo mensaje",
"body":"Bla bla bla bla"
},
"data":
{
"id_solicitud":2,
"id_company":7,
"texto":"ola k ase",
"content-aviable":1
}}
```
Response from FCM API is ok and if the app is active, works fine, but when it's in background, nothing happens. I recive the notification and that's all.

ionic version: 2 RC1
cordova version: 6.3.1
cordova platform version android: 5.2.2
cordova plugin version: 1.8.3

**Comment by ihadeed** [comment]
Since this is not an issue related to the Ionic Native wrapper you can get help at the plugin's repo: https://github.com/phonegap/phonegap-plugin-push
