### ISSUE TITLE
Missing enumerations in BackgroundGeolocation

### ISSUE THREAD

**Issue by pdrosos** [driftyco/ionic-native#758]
Hi,

there are a couple of enumerations, which are missing in the BackgroundGeolocation module and which are recommended to use when configuring the plugin - provider, mode and accuracy:
https://github.com/mauron85/cordova-plugin-background-geolocation/blob/master/www/backgroundGeolocation.js#L20

Would it be possible to add them to Ionic Native BackgroundGeolocation?

Thanks!

**Comment by amuramoto** [comment]
These are available as static members of `BackgroundGeolocation`, e.g.:

```
import { BackgroundGeolocation } from  'ionic-native';
...

export class HomePage {

  constructor(public navCtrl: NavController) {
    console.log(BackgroundGeolocation.LocationProvider.ANDROID_DISTANCE_FILTER_PROVIDER);
    console.log(BackgroundGeolocation.LocationProvider.ANDROID_ACTIVITY_PROVIDER);
    console.log(BackgroundGeolocation.Accuracy.HIGH);
    console.log(BackgroundGeolocation.Accuracy.MEDIUM);
    console.log(BackgroundGeolocation.Accuracy.LOW);
    console.log(BackgroundGeolocation.Accuracy.PASSIVE);
    console.log(BackgroundGeolocation.Mode.BACKGROUND);
    console.log(BackgroundGeolocation.Mode.FOREGROUND);

  }

}
```
