### ISSUE TITLE
Error: plugin_not_installed

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic-native#759]
When running an app on Android, I get the following:

![image](https://cloud.githubusercontent.com/assets/2852839/19829563/8807ac12-9de5-11e6-92ae-e06b63b05692.png)

How am I meant to diagnose which plugin is failing? There is absolutely ZERO useful information here. 

I had just installed Crosswalk and before the app even moves off the splash screen I see this. The warnings shown are not correct either as all these plugins exist and have been properly installed.

**Comment by dylanvdmerwe** [comment]
Without Crosswalk installed, everything seems to work fine, but I still have this output in the console:

![image](https://cloud.githubusercontent.com/assets/2852839/19829589/15c6337a-9de6-11e6-80c2-67b22373df08.png)

**Comment by ihadeed** [comment]
What version of Ionic Native?

**Comment by dylanvdmerwe** [comment]
`    "ionic-native": "2.2.3",`

**Comment by ihadeed** [comment]
Can you share your code

**Comment by dylanvdmerwe** [comment]
That's the problem, due to the log output, I do not know where to even begin looking. It could be anything...

This is the list of plugins I have installed:
![image](https://cloud.githubusercontent.com/assets/2852839/19835536/a6e11256-9e92-11e6-869d-2df9f8214549.png)

**Comment by ihadeed** [comment]
Are you waiting for `deviceready` to fire before you call any plugin functions?

**Comment by dylanvdmerwe** [comment]
Ah yes there was something being called outside of device ready. Great suggestion!
