### ISSUE TITLE
Plugin to add: HeaderColor

### ISSUE THREAD

**Issue by John-Luke** [driftyco/ionic-native#760]
Repo: [Headercolor](https://github.com/tomloprod/cordova-plugin-headercolor)

**Comment by John-Luke** [comment]
If in Ionic has a other way to do the same that it, I'll close this plugin

**Comment by tomloprod** [comment]
Now my plugin is inside ionic-native?

**Comment by ihadeed** [comment]
It's not merged yet.

**Comment by tomloprod** [comment]
Oh, I understand. Perfect. Thank you.
