### ISSUE TITLE
bug: Plugins broken with latest framework and crosswalk

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#762]
_From @geraldapeoples on November 1, 2016 13:15_

**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.0</span>  <span ionic-webview>webview</span>

<span ionic-description>I installed the latest cordova, ionic, gulp and bower.

I created a new tabs application, I added crosswalk plugin.

When I deployed to mobile device I got "deviceready has not fired after 5 seconds" error. I removed "cordova-plugin-device", redeployed to the phone and the error was fixed. There is an issue with this key plugin and crosswalk.

Futher testing shows that using "cordova-plugin-network-information" also gives "deviceready has not fired after 5 seconds" error. The "cordova-plugin-camera" doesn't give an error but does not actually work with latest ionic/crosswalk.</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#8977_

**Comment by wwallace** [comment]
Seeing same issue with cordova-plugin-media

**Comment by ihadeed** [comment]
Sounds like an issue with crosswalk and not with Ionic Native. Closing this. Please let me know if you only have this issue with Ionic Native then we can re-open this and investigate.

**Comment by geraldapeoples** [comment]
It turned out that it was cordova 6.4 that broke everything, not crosswalk ... I reverted to cordova 6.3 and it all works now. So, in your installation instructions for Ionic, I would put in a caveat that the user should use cordova 6.3 or less ...
