### ISSUE TITLE
FileTransfer is undefined when trying to use Transfer plugin in Ionic 2 app

### ISSUE THREAD

**Issue by bastibense** [driftyco/ionic-native#763]
I'm having a problem with the latest ionic (updated app scripts this morning to use webpack). I added the file-transfer plugin but whatever I do, I get FileTransfer is not defined (apparently the JS from cordova-plugin-file-transfer is not included for some reason?)

I read somewhere that FileTransfer is not available until deviceready is fired, but when using ionic native's Transfer class, this shouldnt be an issue right? The error apparently happens when Transfer internally tries to create a new FileTransfer() instance, which is at that time undefined.

**Steps to reproduce:**
1. Create a new blank ionic project
2. Add the file-transfer plugin `ionic plugin add cordova-plugin-file-transfer --save` (have to manually add the `cordova-plugin-file` plugin as well?)
3. do a `ionic serve`
4. At the point where you do a `new Transfer()` call, the Transfer class internally tries to instantiate a `new FileTransfer()` instance, which is undefined.

I would expect the file-transfer's plugin JS files (browser in this case) to be included somehow. Bit here I'm not sure if this is my fault or simply a bug.

**ionic info:**
* ionic-native@2.2.6 

> Cordova CLI: 6.3.1
> Ionic Framework Version: 2.0.0-rc.1
> Ionic CLI Version: 2.1.1
> Ionic App Lib Version: 2.1.1
> Ionic App Scripts Version: 0.0.39
> ios-deploy version: 1.9.0 
> ios-sim version: 5.0.9 
> OS: Mac OS X Sierra
> Node Version: v6.6.0
> Xcode version: Xcode 8.0 Build version 8A218a

**Comment by ghenry22** [comment]
file transfer will automatically install file plugin if it's not already there.

I don't think that this will work in ionic serve.  Try it on a real device or an emulator and see if you have the same issue.

I use the file transfer plugin in my app with no issues with ionic-native.

**Comment by ihadeed** [comment]
You still have to wait for `deviceready` to fire even if you are using Ionic Native wrapper. We still don't automatically wrap things with a `deviceready` listener.
