### ISSUE TITLE
Google Map googledesic does not work as expected.

### ISSUE THREAD

**Issue by shamsher31** [driftyco/ionic-native#765]
According to the [source code](https://github.com/driftyco/ionic-native/blob/master/src/plugins/googlemap.ts#L627) for `GoogleMapsPolylineOptions`, there is a option called `googledesic` which allow us to draw polyline according to `geodesics`. <br>
I have following code.
```
let polyLine: GoogleMapsPolylineOptions = {
      points: [
        sourceLocation,
        destLocation
      ],
      googledesic: true,
      color: '#e74c3c',
      width: 2
    };
    
    map.addPolyline(polyLine);
```
I have set `googledesic` to `true` but still getting straight line. See screen shot.

![screenshot_2016-11-02-19-14-33](https://cloud.githubusercontent.com/assets/2920003/19930992/dc1a662a-a130-11e6-991e-0cccff20b9d5.jpg)

**Comment by shamsher31** [comment]
@ihadeed @mlynch Did you get a chance to look at it.

**Comment by ihadeed** [comment]
Sorry for the late response. That was a typo. It should be `geodesic` not `googledesic`. Just fixed it.

**Comment by shamsher31** [comment]
Thanks for the fix.
