### ISSUE TITLE
BackgroundMode onactivate doesn't work

### ISSUE THREAD

**Issue by JesucristoEsteban** [driftyco/ionic-native#767]
I'm trying to use background mode plugin but it doesn't work.

Here's the code i'm using:

`// Called when background mode has been activated`
`BackgroundMode.onactivate().subscribe(() => {`
`               //Background stuff`
`});`

`// Enable background mode`
`BackgroundMode.enable();`

All my code it's inside the Platform ready event, and i get this error:

**Error: Uncaught (in promise): TypeError: BackgroundMode.onactivate is not a function**

¡HELP!

**Comment by ramonornela** [comment]
What version ionic-native?

**Comment by JesucristoEsteban** [comment]
My ionic-native version is 2.0.3, it's in my package.json file. 

Thanks!

**Comment by ramonornela** [comment]
Try
```
BackgroundMode.onactivate().subscribe(
        () => {},
        (err) => {
          if (err.error === 'cordova_not_available' || err.error === 'plugin_not_available') {
            console.log('plugin not install');
          }
        }
      );
```

Thanks
