### ISSUE TITLE
Insomnia pluginRef is not correct

### ISSUE THREAD

**Issue by gjf974** [driftyco/ionic-native#770]
In insomnia.ts :
pluginRef: 'plugins.insomnia',

In Insomnia-PhoneGap-Plugin/plugin.xml
  <js-module src="www/Insomnia.js" name="Insomnia">
    <clobbers target="window.plugins.insomnia" />
  </js-module>

**Comment by ihadeed** [comment]
How is it not correct?

**Comment by gjf974** [comment]
Sorry it was a mistake , 
I use Ionic V1, so  ionic-native bower.

my log error is 
> Unknown provider: $cordovaInsomniaProvider <- $cordovaInsomnia

I locate the problem : 
missing in `window['IonicNative']` 
Line 170 : `Insomnia: insomnia_1.Insomnia,`
