### ISSUE TITLE
VideoPlayer VideoOptions.scalingMode incorrect type.  Should 

### ISSUE THREAD

**Issue by cnanders** [driftyco/ionic-native#774]
Per the spec,

https://developer.android.com/reference/android/media/MediaPlayer.html#VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING

VIDEO_SCALING_MODE_SCALE_TO_FIT and
VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING

return Int.

By setting the VideoOptions interface with scalingMode having type "String", it is impossible to actually set the scaling mode using ionic-native's wrapper for the VideoPlayer plugin.  

Please change this to type "int" and export two static properties of VideoPlayer player 

VideoPlayer.SCALING_MODE_SCALE_TO_FIT: int = 1
VideoPlayer.SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING: int = 2

**Comment by ihadeed** [comment]
Thanks just fixed it
