### ISSUE TITLE
can't find sqlitePlugin variable (despite #686 has been closed)

### ISSUE THREAD

**Issue by pimol** [driftyco/ionic-native#775]
@aishacharya, @mosca90 and me commented the 686 days after that @mlynch had closed it.

Despite I put the line mlynch suggest in #602, I got the same error. I'm trying wit Ionic Serve, but with my device and emulator is the same.

Pietro

**Comment by mlynch** [comment]
sqlite is not available in the browser while testing. You'll need to test on a device as it's a native-only feature.

**Comment by mosca90** [comment]
@pimol 
[I have solved btw](https://stackoverflow.com/questions/40277905/how-to-use-sqlite-with-ionic-2-rc-0/40398191#40398191)
