### ISSUE TITLE
Error in Diagnostic plugin check for location permissions

### ISSUE THREAD

**Issue by nakioman** [driftyco/ionic-native#776]
Hi, I am trying to ask to see if I have permission to use the location for an android app, with the following code: 

`
 Diagnostic.requestLocationAuthorization(Diagnostic.locationAuthorizationMode.ALWAYS).then(status => { 
});
`
But I am having the following error in the console:

> cordova.js:314 Uncaught TypeError: successCallback is not a function(…)onSuccess @ diagnostic.js:572onSuccess @ diagnostic.js:379callbackFromNative @ cordova.js:293(anonymous function) @ VM87:1

Could you help me?

**Comment by dpa99c** [comment]
The ionic-native wrapper is invoking the underlying [requestLocationAuthorization() plugin function](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/www/ios/diagnostic.js#L177) with parameters in the wrong order: the plugin function expects to be passed the arguments `(successCallback, errorCallback, mode)` but the ionic-native wrapper is passing `(mode, successCallback, errorCallback)` which is causing Cordova to throw the observed error.

**Comment by ramonornela** [comment]
Thanks @dpa99c 😉  fix in https://github.com/ramonornela/ionic-native/commit/608d00fc55d67e495c4c5a1da5a4ad4294d2fe23
