### ISSUE TITLE
Voice recognition

### ISSUE THREAD

**Issue by arsewizz** [driftyco/ionic-native#783]
Hellp, there is a date for voice recognition with ionicc-native

**Comment by ihadeed** [comment]
Is there a specific plugin you are asking us to add?

I found one here: https://github.com/macdonst/SpeechRecognitionPlugin

Let me know if there are other plugins that you think are good.

**Comment by ihadeed** [comment]
This was added awhile ago. Sorry I forgot to update this issue.
