### ISSUE TITLE
inappbrowser lint error

### ISSUE THREAD

**Issue by ghenry22** [driftyco/ionic-native#784]
Following the docs I do the below to open a page in the system browser for example.

let browser = new InAppBrowser('https://ionic.io', '_system');

I don't need to inject CSS or javascript or anything else.  I don't need to programmatically close the window as the user will tap the "done" button provided by inappbrowser to close the window.

This works fine but when building the app with ionic2 rc2 it throws a lint error that browser is an unused variable.

maybe a comment in the docs that if you have this simple use case you can just do:
new InAppBrowser('https://ionic.io', '_system');

to avoid the lint errors on build

**Comment by ihadeed** [comment]
I don't think this is necessary. This should be common JavaScript knowledge. There is no need to assign a variable name if you aren't planning on referring to the object later on.
