### ISSUE TITLE
Ionic-native: Secure Storage not work

### ISSUE THREAD

**Issue by usmakas** [driftyco/ionic-native#786]
When I run this app in ionic view application. It show "error create TypeError: undefinded is not a constructor(evaluating 'new cordova.plugins.SecureStorage(res,reg,store)')"
Please find or recommend me for fix this issue.

This is my package.json
{
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "build": "ionic-app-scripts build",
    "watch": "ionic-app-scripts watch",
    "serve:before": "watch",
    "emulate:before": "build",
    "deploy:before": "build",
    "build:before": "build",
    "run:before": "build"
  },
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/compiler-cli": "0.6.2",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/platform-server": "2.0.0",
    "@ionic/storage": "1.0.3",
    "ionic-angular": "2.0.0-rc.1",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.21"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^0.0.36",
    "cordova-ionic-minify": "^1.0.1",
    "typescript": "^2.0.3"
  },
  "description": "demoionic: An Ionic project",
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard",
    "cordova-plugin-image-picker",
    "phonegap-plugin-barcodescanner",
    "cordova-plugin-secure-storage",
    "cordova-plugin-nativestorage"
  ],
  "cordovaPlatforms": []
}

This is my code
import { Component } from "@angular/core";
import { ImagePicker, BarcodeScanner, SecureStorage } from "ionic-native";
import { NavController, Platform, ActionSheetController } from "ionic-angular";

@Component({
    selector: "page-about",
    templateUrl: "about.html"
})
export class AboutPage {

    event = {
        month: "1990-02-19",
        timeStarts: "07:43",
        timeEnds: "1990-02-20"
    };
    private secureStorage: SecureStorage;
    capital: string;
    constructor(
        public navCtrl: NavController,
        public platform: Platform,
        public actionsheetCtrl: ActionSheetController) {
        this.capital = "Initialize data";
        var self = this;
        this.platform.ready().then((readySource) => {
            console.log(`Platform ready from(console) ${readySource}`);
            this.capital = `Platform ready from ${readySource}`;
            // Platform now ready, execute any required native code
            this.secureStorage = new SecureStorage();
            this.secureStorage.create("my_store_name")
                .then(
                () => alert("Storage is ready!"),
                error => alert(error));

        });

    }

    }
}

**Comment by ihadeed** [comment]
Did you install the plugin `cordova-plugin-secure-storage` ?

**Comment by amuramoto** [comment]
This is because the secure storage plugin is not currently supported in Ionic View. A full list of supported plugins is available here: https://docs.ionic.io/tools/view/#supported-plugins.

You can request it be added by opening an issue here: https://github.com/driftyco/ionic-view-issues
