### ISSUE TITLE
docs: NativeAudio play documentation incorrect

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic-native#792]
For the NativeAudio plugin, the example says you use the `play` method like:

`NativeAudio.play('uniqueId1').then(onSuccess, onError);`

However this is not correct as later on in the docs (and in the TypeScript definitions) the play method takes an additional callback. 

`play(id, completeCallback)`

http://ionicframework.com/docs/v2/native/nativeaudio/

**Comment by ihadeed** [comment]
Thanks

The callback is actually optional. I just fixed the typing and updated the docs.
