### ISSUE TITLE
CameraPreview plugin update

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#793]
_From @trollwinner on November 13, 2016 17:32_

Hello!

I have a little question about the camera preview plugin. There are some new features of the flash mode on github repo, but there is no in ionic2 now. Will it be updated sometime?

By the way, can I ask about CanvasCamera plugin? It's 404 in the docs and haven't work with ionic.

Thank you very much!

_Copied from original issue: driftyco/ionic#9142_

**Comment by ihadeed** [comment]
@trollwinner 

I can't see the new features you're talking about on the plugins repo: https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview

`CanvasCamera` had issues and we decided to take remove it from Ionic Native.

**Comment by trollwinner** [comment]
Hello! But there is another fork, which is maintained currently, isn't it? It says in readme.

Here is the fork: https://github.com/westonganger/cordova-plugin-camera-preview

and method from its readme:
setFlashMode(flashMode, successCallback, errorCallback)

**Comment by ihadeed** [comment]
Both repos are being updated recently. They have been confusing. Will stick with the original repo until there's solid evidence that the fork is better and more stable.
