### ISSUE TITLE
'cameraDirection: Camera.Direction.FRONT' camera options not working in android

### ISSUE THREAD

**Issue by vaibsVB** [driftyco/ionic-native#795]
Greetings to all.
I need a little help.

https://github.com/apache/cordova-plugin-camera#cameradirection--enum this GitHub `cordova-plugin-camera` docs say in order to open `FRONT` camera use `integer` '`1`'.

And what `ionic-native` `camera `v2 docs https://ionicframework.com/docs/v2/native/camera/#CameraOptions
says is for `FRONT` camera use `integer` `'0'` (`camera.d.ts` file says the same).

I'm confused, I tried both options `cameraDirection: 0` and `cameraDirection: 1`.
And while running on android `MOTO G4` device it opens back camera.

I also tried this one... `cameraDirection: Camera.Direction.FRONT`. But it opens back camera always.

Can anyone help me out of this?

Thanks in advance.

Check this forum topic too for reference https://forum.ionicframework.com/t/camera-options-not-work/70193/4

**Comment by vaibsVB** [comment]
I went through documentation, 
at this link https://github.com/apache/cordova-plugin-camera#android-quirks-1 the first line says the all. :frowning:

Is there any other option to do work android front camera by default?

**Comment by ihadeed** [comment]
Sorry there is nothing we can do on our end. You will have to contact the developers to ask them to fix this or use an alternative plugin that supports front facing camera. Your app users will still be able to use their front camera but they have to select it manually when the camera app launches.

**Comment by sGambolati** [comment]
Sorry, but is there any workaround or other way to take a picture to use the front camera?

**Comment by YannaAlghamdi** [comment]
Any workaround for this on Android devices? Or do we have to use a different plugin instead?
