### ISSUE TITLE
Property 'get' does not exist on type 'GoogleMapsMarker' 

### ISSUE THREAD

**Issue by santu-git** [driftyco/ionic-native#798]
I want to use following feature listed in cordova-plugin-googlemaps but always getting this error.

https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Marker#add-your-data-and-hold-them

**Comment by ihadeed** [comment]
The wrapper we have for GoogleMaps is for an older version. We haven't
updated it yet.

Use their API directly for now, or downgrade to an older version. Not sure
what the version number is, I'm on my phone right now.

**Comment by santu-git** [comment]
@ihadeed I am using "ionic-native": "^2.0.3".

**Comment by ihadeed** [comment]
I meant the plugin's version, not Ionic Native.

**Comment by santu-git** [comment]
@ihadeed cordova-plugin-googlemaps "version": "1.3.9",

**Comment by ihadeed** [comment]
Oh never mind, I'm sorry. This method was there in v1, we just didn't have it in our wrapper. Will fix this soon.

**Comment by santu-git** [comment]
@ihadeed I am new to Ionic2 can please guide me how to Use their API directly any code snippet??

**Comment by ihadeed** [comment]
Ok this is fixed now.
