### ISSUE TITLE
push plugin docs missing SENDER_ID

### ISSUE THREAD

**Issue by aggarwalankush** [driftyco/ionic-native#803]
```
ionic2-push-base$ ionic plugin add phonegap-plugin-push
Unmet project requirements for latest version of phonegap-plugin-push:

    cordova (6.3.1 in project, >=6.4.0 required)
Fetching highest version of phonegap-plugin-push that this project supports: 1.8.4 (latest is 1.9.0)

Fetching plugin "phonegap-plugin-push@1.8.4" via npm

Error: Variable(s) missing (use: --variable SENDER_ID=value).

```
[Push docs] (https://ionicframework.com/docs/v2/native/push/) has following:
`$ ionic plugin add phonegap-plugin-push`

**Comment by mlynch** [comment]
This is a limitation with our doc system right now that we're not able to customize the plugin install line. @perrygovier any thoughts on how we could customize that first `ionic plugin add [PLUGIN_NAME]` to allow plugins to add params?

**Comment by perrygovier** [comment]
Yeah, I can add a new param to the docs to override the install command. Something like:

```
/ * 
  * @installCommand npm install phonegap-plugin-push@1.8.4
  * /
```
Which if present, would override the default install command. 

Like the idea?

**Comment by ihadeed** [comment]
@perrygovier @mlynch we already have a way to override install commands, just add `install` in the `@Plugin()` decorator meta.

Example: 
https://github.com/driftyco/ionic-native/blob/master/src/plugins/deeplinks.ts#L67

**Comment by perrygovier** [comment]
Thank @ihadeed! I forgot about that.
