### ISSUE TITLE
Google Maps 3D buildings

### ISSUE THREAD

**Issue by gigiojr** [driftyco/ionic-native#805]
The Google Maps plugin didn't have a function to enable/disable 3D buildings on maps, but they'll include in versions v.1.4 and v.2.0 ([issue](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1183)). Can you include too? 

Thank you.

**Comment by ihadeed** [comment]
We don't need to do anything to support that. The options take parameter takes type of `any` so you can pass any parameters.
