### ISSUE TITLE
Native Plugin Card IO error "plugin_not_installed"

### ISSUE THREAD

**Issue by CHOMNANP** [driftyco/ionic-native#809]
I have follow the instruction on CardIO native plugin, but I got the message "plugin_not_installed" after I run it on the device.

plugin url: https://ionicframework.com/docs/v2/native/cardio/

My system system info:
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v5.10.1
Xcode version: Not installed

I tried other plugin like "Camera", and it work fine.
I'm not sure what do I miss for "CardIO".

Thanks,
Punleu

**Comment by ihadeed** [comment]
Hey there,

Unfortunately, I wasn't able to reproduce this issue.

I'm working with a fresh Ionic 2 project. I installed the plugin by running the command `ionic plugin add https://github.com/card-io/card.io-Cordova-Plugin` then I executed the following code:

```ts
    this.platform.ready().then(() => {
      CardIO.canScan().then((canScan: boolean) => {
        
        console.log('Can scan:', canScan);
        
        if (canScan) {
          CardIO.scan({})
            .then(data => console.log('Scanned: ', data))
            .catch(e => console.log('Error scanning: ', e));
        }
      })
      .catch(e => console.log('Error checking if can scan: ', e));

    });
```

**Comment by CHOMNANP** [comment]
I test this CardIO on Ionic View and it doesn't work.
This CardIO work unless I publish the APK and install it on my device.

https://forum.ionicframework.com/t/cardio-plugin-doesnt-work-in-ionic2/70419

**Comment by ihadeed** [comment]
@CHOMNANP Ionic View only has a few plugins that are bundled in the binary. You can't add custom plugins to it. You can try using `--livereload` flag when running on device/simulator for faster debugging. I think for now it has an issue though with the plugins so you will have to wait for the next `ionic-cli` and `ionic-app-scripts` release.

**Comment by CHOMNANP** [comment]
The test environment that I'm facing the issue is accessing the app in Ionic View. The root cause is because CardIO is not supported on Ionic View.

I don't have any issue with CardIO if I build APK from the project and install the APK on my device.
So CardIO work fine on device. There is no issue.
