### ISSUE TITLE
Custom url scheme

### ISSUE THREAD

**Issue by royipressburger** [driftyco/ionic-native#81]
Hi

Is there any plan to implement custom url scheme plugin?
https://github.com/EddyVerbruggen/Custom-URL-scheme

**Comment by ihadeed** [comment]
Hey @royipressburger ,

I checked out the plugin just now, and it seems like there aren't any methods to wrap with Ionic Native.

Installing and using the plugin could be done through the command line without the need to write any code. Simply run the following command:
```shell
$ cordova plugin add cordova-plugin-customurlscheme --variable URL_SCHEME=mycoolapp
```
Make sure to replace `mycoolapp` with the URL Scheme you desire.
