### ISSUE TITLE
isInstalled

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic-native#811]
Right now `installed` is not shipped as part of any typing for plugins, despite being available on every plugin. This makes it impossible to quickly check if a plugin is installed w/o doing something like `Camera['installed']()`

Either add this as a type, or export an `isInstalled` function that takes the class as an arg:

`isInstalled(Camera)`

**Comment by ihadeed** [comment]
How about creating a base interface with optional methods/properties. Then make all plugins implement it.

```typescript
export interface IPlugin {
  /**
   * Checks if plugin is installed
   */
  installed?(): boolean;
  pluginName?: string;
  plugin?: string;
  pluginRef?: string;
  repo?: string;
  platforms?: string[];
}

export class Camera implements IPlugin { ... }
```

**Comment by billygerhard** [comment]
I see you closed this issue, but I haven't been able to find any documentation on how to actually use this. What I am trying to really get to is dynamically being able to see if the plugin is installed on a given platform without having to know before hand if that platform is supported.

**Comment by ihadeed** [comment]
Figured it out...
![image](https://cloud.githubusercontent.com/assets/13794420/25468036/cefa2946-2ae0-11e7-888f-087361d2fe85.png)
