### ISSUE TITLE
Plugin: Geolocation - duplicate error code in error object on reject  

### ISSUE THREAD

**Issue by TrapSpace** [driftyco/ionic-native#812]
Geolocation.getCurrentPosition().then(
            position => alert(JSON.stringify(position)),
            error => alert(JSON.stringify(error))
);

On reject an error object is returned with an error code and message. When location services is turned off on the device, error code 1 is returned with the message "Location services are disabled". 

When users do not allow the app to retrieve position information on the device error code 1 is returned again, with the message "". 

Suggestion would be to return a unique error code and message when users do not allow the app to retrieve position information on the device. 

Thanks !

**Comment by ihadeed** [comment]
These error messages come from the plugin. You need to request this feature at the plugin's issue tracker.
