### ISSUE TITLE
cordova.file.tempDirectory is 'null' on Android.

### ISSUE THREAD

**Issue by tinydream12** [driftyco/ionic-native#815]
I am working with Ionic 2 rc version and Camera plugin( for capturing photos), and File plugin ( for storing to local storage permanently.)

But  cordova.file.tempDirectory is 'null' in the following block(just on Android, works fine on iOS).
`moveFile(cordova.file.tempDirectory, capturedPhotoName, cordova.file.dataDirectory, newFileName);`

**Comment by tinydream12** [comment]
Sorry, looks like cordova-plugin-file issue, not ionic-native issue.

**Comment by jurerick** [comment]
So did you fix this?
