### ISSUE TITLE
Support for custom Google Analytics dispatch period

### ISSUE THREAD

**Issue by mattss** [driftyco/ionic-native#816]
The Cordova Google Analytics plugin (https://github.com/danwilson/google-analytics-plugin) by default queues events and dispatches them every 30 seconds.

The original plugin allows you to customise this variable in the 'startTrackerWithId', but the Ionic Native wrapper doesn't support this extra variable.

At the moment I'm having to use the raw plugin to achieve this, but it would be great if the the ionic wrapper could be updated to allow the dispatch period variable.

**Comment by ihadeed** [comment]
Thanks, this is added now.

**Comment by mattss** [comment]
@ihadeed Brilliant - thank you!
