### ISSUE TITLE
I wrote a custom plugin that added to the ionic-native,erro: Uncaught TypeError: Cannot assign to read only property 'name' of function 'function Lyxpay()

### ISSUE THREAD

**Issue by Gtanxingwen** [driftyco/ionic-native#824]
![image](https://cloud.githubusercontent.com/assets/18392906/20592697/f5b1ffe0-b269-11e6-8528-60b68e11b40c.png)
![image](https://cloud.githubusercontent.com/assets/18392906/20592720/13033d48-b26a-11e6-9761-c9b3c51b63e7.png)

what should i do

**Comment by Gtanxingwen** [comment]
@mlynch  @Brandy Carney

**Comment by ihadeed** [comment]
Are you setting the property `name` anywhere in your plugin wrapper?

Can you share some code so I can have a look.

**Comment by Gtanxingwen** [comment]
/**
 * This is a template for new plugin wrappers
 *
 * TODO:
 * - Add/Change information below
 * - Document usage (importing, executing main functionality)
 * - Remove any imports that you are not using
 * - Add this file to /src/index.ts (follow style of other plugins)
 * - Remove all the comments included in this template, EXCEPT the @Plugin wrapper docs.
 * - Remove this note
 *
 */
import { Plugin, Cordova } from './plugin';

/**
 * @name Lyxpay
 * @description
 * This plugin does something
 *
 * @usage
 * ```
 * import { Lyxpay } from 'ionic-native';
 *
 * Lyxpay.functionName('Hello', 123)
 *   .then((something: any) => doSomething(something))
 *   .catch((error: any) => console.log(error));
 *
 * ```
 */
@Plugin({
  name: 'Lyxpay',
  plugin: 'lyxpay', // npm package name, example: cordova-plugin-camera
  pluginRef: 'navigation.lyxpay', // the variable reference to call the plugin, example: navigator.geolocation
  repo: '', // the github repository URL for the plugin
  install: '' // OPTIONAL install command, in case the plugin requires variables
})
export class Lyxpay {

  /**
   * This function does something
   * @param arg1 {number} Some param to configure something
   * @param arg2 {string} Another param to configure something
   * @return {Promise<any>} Returns a promise that resolves when something happens
   */
  @Cordova()
  static pay(arg1: number, arg2: string): Promise<any> { return; }

}

@ihadeed  this is all lyxpay.ts

**Comment by Gtanxingwen** [comment]
@ihadeed  Or above the JS I should be how to write TS
@mlynch

**Comment by ihadeed** [comment]
This line shouldn't be in your `@Plugin` decorator. 
```typescript
 name: 'Lyxpay',
```

**Comment by Gtanxingwen** [comment]
@ihadeed thanks
