### ISSUE TITLE
nfc plugin maybe have something wrong when wrap up to phonegap-nfc 

### ISSUE THREAD

**Issue by zhaoadou** [driftyco/ionic-native#827]
I have used the nfc native plugin to use addTagDiscoveredListener function .
It is defined 
`static addTagDiscoveredListener(mimeType: string, onSuccess?: Function, onFailure?: Function): Observable<any>`

but i find the define in phonegap-nfc.js ,it is 
`addTagDiscoveredListener: function (callback, win, fail) {
        document.addEventListener("tag", callback, false);
        cordova.exec(win, fail, "NfcPlugin", "registerTag", []);
    }`
I think there is no mimeType parameter when wrap up to cordova nfc plugin .

any ideas?

**Comment by stormwin** [comment]
+1
Also there is some static functions that is missing in definition, like bytesToString, stringToBytes, bytesToHexString ... etc
I think that definition for nfc is out-of-date

**Comment by zhaoadou** [comment]
@stormwin  So that is there any plan to update the definition for latest version or not ?

**Comment by stormwin** [comment]
tested locally and works great. will make a PR tomorrow

**Comment by DavidTalamona** [comment]
@stormwin: The "addMimeTypeListener" on the other hand needs a "mimeType" argument thats missing in TS and the documentation.
Think the initial creator of the TS just swapped the arguments of the two listeners.
So, please fix the "addMimeTypeListener" too and update the doc, thanks.

**Comment by stormwin** [comment]
no problem, i will fix it

**Comment by dalbir** [comment]
Same Problem. Please Fix it.

**Comment by stormwin** [comment]
https://github.com/driftyco/ionic-native/pull/937

@DavidTalamona @dalbir Guys, just created PR with fix

**Comment by ihadeed** [comment]
Just merged it, will be available in the next release.
