### ISSUE TITLE
$cordovaToast is not working without any errors but window.plugins.toast works

### ISSUE THREAD

**Issue by almothafar** [driftyco/ionic-native#829]
Hello 

I have an issue that I spent good time to debug and fix or get around it without anything make sense, I was trying to use `$cordovaToast` inside my app to show a toast, but it was not working at all, nothing was showing and no errors in console, tried to wrap it inside `$ionicPlatform.ready()` and was not helpful (actually this was not necessary because the method that call `$cordovaToast` is wrapped already)

After a lot of attempts, I finally used just `window.plugins.toast` and it is worked, it seems something wrong with `$cordovaToast` not the plugin itself.

I'm testing on:

- Android version 5.1 
- Ionic-native: 2.2.6
- Ionic 1.3.2

**Comment by ihadeed** [comment]
Our wrapper returns an Observable. That means the function will not be executed until you call `.subscribe()`. 

See https://github.com/driftyco/ionic-native/issues/395 for more info.

**Comment by almothafar** [comment]
@ihadeed Thanks , yes I was able to show toast with `.subscribe()` , I was referring to ngCordova document

**Comment by sryze** [comment]
This needs to be somewhere in documentation for ionic native. Docs claim that it works the same way with ionic v1 as ngCordova but with ngCordova you don't need to call `subscribe`. I just wasted half an hour trying to figure out why it's not working until I installed ngCordova back.

**Comment by ihadeed** [comment]
@sryze what part of the docs states that it works the same way as ngCordova?

Ionic Native is a different project and it's API doesn't follow ngCordova.

**Comment by sryze** [comment]
OK, it wasn't documentation, I think I got that impression from this blog post: http://blog.ionic.io/ionic-native-native-powers-for-your-app/

> For those in the community that have used our similar project for Angular 1, ngCordova, it’s now time to say good bye to that project. As of Ionic Native 1.3.0, Angular 1 is now supported out of the box, with practically identical service and API names as ngCordova. Plugin support is now on par or better than ngCordova, and we’re baking Ionic Native by default into all new Ionic 2 projects, so usage should be much higher than with ngCordova. Additionally, ngCordova was bound to Angular 1, and Ionic Native is framework agnostic.

> To start using Ionic Native in Ionic 1 projects, include the bundle file in the latest release, and change your import from ngCordova to ionic.native. Many calls should Just Work, but take a look at the docs to see what needs to be changed. You’ll need to prefix each Class name with $cordova before injecting and calling it. For example: $cordovaCamera.
