### ISSUE TITLE
Failed to create Contact in Ionic v1

### ISSUE THREAD

**Issue by neojato** [driftyco/ionic-native#831]
I have previously used ngCordova for my Ionic v1 apps and have recently started using Ionic-Native (mainly because of the limitations on the Google Login plugin) and I am unable to rewrite to Ionic v2 at this time. All of my Ionic v1 plugins still work without changes, however, the Contact plugin results in an error (via logcat):

`TypeError: $cordovaContacts.save is not a function`

As the docs state, "Ionic Native works as a stand-in for ngCordova [in Ionic v1 apps]." So here is how I have it setup:

```
angular.module('myApp', ['ionic', 'ionic.native'])

.controller('MyCtrl', function ($scope, $cordovaContacts) {
  $scope.addContact = function () {
    $cordovaContacts.save($scope.contactForm).then(function (result) {
      // Contact saved
    }, function (err) {
      // Contact error
    });
  };
});
```

When I console.log `$cordovaContacts` I receive this:

`function Contacts {}`

Everything I have tried has been unsuccessful as well as not being able to find any postings of this similar issue including in the forum (of which I received no response).

Thanks in advance!

**Comment by ihadeed** [comment]
This should work:
```javascript
var contact = $cordovaContacts.create();
contact.displayName = 'John Smith';
contact.save().then(...);
```

**Comment by neojato** [comment]
Thanks @ihadeed that worked. Not sure why it didn't when I previously tried that style, but it does now. Greatly appreciated!

**Comment by ihadeed** [comment]
@neojato I fixed a few things in the latest release so that might be why. Glad you got it working!
