### ISSUE TITLE
Super Wrong doc for Native Backgroundmode

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-native#833]
_From @workfluo on November 28, 2016 9:51_

Ionic 2 > Native > Backgroundmode: http://ionicframework.com/docs/v2/native/background-mode/

Static Members: isEnabled(), isActive() don't return Boolean but Promises.
Static Members: isActive(), ondeactivate(), onfailure() are Observables.

_Copied from original issue: driftyco/ionic#9383_

**Comment by amuramoto** [comment]
Thanks! Fixed in https://github.com/driftyco/ionic-native/pull/836
