### ISSUE TITLE
globalization.numberToString needs number param

### ISSUE THREAD

**Issue by medi-y-sato** [driftyco/ionic-native#835]
Globalization.numberToString() is convert number to string as format, but  src/plugins/globalization.ts hasn't number param.
Therefore, transpile fails.

> [18:45:03]  typescript: src/pages/globalization/globalization.ts, line: 95 
>             Supplied parameters do not match any signature of call target. 
> 
>       L95:      Globalization.numberToString(3.141592,{type:'decimal'}).then(
>       L96:        res=>{ this.state.push({name:'numberToString', value: res.value}) },
> 
> [18:45:03]  transpile failed

I think fix solution is below . Is it correct ?

https://github.com/driftyco/ionic-native/blob/master/src/plugins/globalization.ts#L102

```javascript
-  static numberToString(options: { type: string }): Promise<{ value: string }> { return; }
```

```javascript
+   static numberToString(numberToConvert: number , options: { type: string }): Promise<{ value: string }> { return; }
```

env:
> node : v6.9.1
> ionic-native : 2.2.7
> cordova-plugin-globalization : 1.0.4

**Comment by ihadeed** [comment]
Thanks! I just pushed a commit to fix this.

The fix will be available in the next patch release.
