### ISSUE TITLE
Wrong doc for social-sharing and File

### ISSUE THREAD

**Issue by workfluo** [driftyco/ionic-native#839]
http://ionicframework.com/docs/v2/native/social-sharing/
It seems to me that the doc forgets to mention that the social-sharing class has to be added also as providers.
It the same for File just like it's mentioned for Storage for example.

**Comment by ihadeed** [comment]
It's a static class, not an Angular 2 provider. Not sure what you mean.

**Comment by workfluo** [comment]
Hello ihadeed
Not sure what I've meant too.
My mistake. I've mixed up with Storage that needs to be added.
And the console said me to do it.
Hey! what a perfect excuse: "I know that I should not have done that but THE CONSOLE said me so".
Sorry :-).
