### ISSUE TITLE
cordova-plugin-http doesn't work in ionic 2 rc3

### ISSUE THREAD

**Issue by hpwahyao** [driftyco/ionic-native#842]
I just encountered a very strange problem after upgrading to ionic 2 rc3. Does anyone encounter this error? 
Thanks

=========================
source code

HTTP.post(endPoint, req, {})
.then(
data=> {
let respString = data.data;

==========================
Result
5 565589 warn Native: tried calling HTTP.post, but the HTTP plugin is not installed.
6 565590 warn Install the HTTP plugin: 'ionic plugin add cordova-plugin-http'
7 565594 error "plugin_not_installed">
8 565596 log 
9 565598 log 
10 565599 error [{"errorMsg":"Network request fail"}]

**Comment by Ehsan55** [comment]
me 2
