### ISSUE TITLE
GoogleMaps - expose off() method

### ISSUE THREAD

**Issue by fmendoza** [driftyco/ionic-native#843]
I added the following code to disable map events

`this.map.off();`

Then I receive an error saying the following:

> Property off() does not exist on type Google Maps

**Comment by ihadeed** [comment]
The method `off` is used to unsubscribe to a specific event that was initially listened to by using the `on` method. 

In Ionic Native, we return an observable when you call the `on` method. To unsubscribe from the event (call the `off` method) you just have to unsubscribe from the observable returned.

Example:
```typescript

// subscribe to event
let subscription = this.map.on('my event').subscribe((data) => console.log('Got data from my event', data));

// unsubscribe from event
subscription.unsubscribe();

```

**Comment by fmendoza** [comment]
sweeet
