### ISSUE TITLE
Add missing marker properties to GoogleMapsMarkerOptions

### ISSUE THREAD

**Issue by pdrosos** [driftyco/ionic-native#844]
Hi,

cordova-plugin-google maps has [disableAutoPan](https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Marker#disable-auto-pan) marker property. It can not be used via the Ionic Native wrapper, because it's missing in GoogleMapsMarkerOptions.

There are also two other useful marker properties - [markerClick and infoClick](https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Marker#click-an-infowindow)

Could you please add them to GoogleMapsMarkerOptions? Thanks!

**Comment by ihadeed** [comment]
Thanks! Added and will be available in next release.
