### ISSUE TITLE
cordova-plugin-googlemaps does not install

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#849]
_From @jamesabc on December 5, 2016 7:45_

**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Steps to reproduce:**
- Start a new project with `ionic start MyIonic2Project tabs --v2` 
- Run `ionic plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"` as described in the docs (substituting real API keys)
- Copy the exact code from http://ionicframework.com/docs/v2/native/google-maps/ into a new page component.
- `npm run ionic:serve`
- Navigate to the page in the browser
... OR
- `ionic run android --livereload`
- navigate to the page in the emulator

-->

**Current behavior:**
<img width="817" src="https://cloud.githubusercontent.com/assets/22513691/20877056/b214dc98-baf8-11e6-859d-48ca65716d84.png">
<img width="438" src="https://cloud.githubusercontent.com/assets/22513691/20877101/e8e2ce24-baf8-11e6-812b-752906671555.png">

**Expected behavior:**
A map of some kind

**Other information:**

**Ionic info:**

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v7.2.0
Xcode version: Not installed
```

_Copied from original issue: driftyco/ionic#9491_

**Comment by ihadeed** [comment]
This plugin doesn't have browser fallback. I suspect you might have this issue because of a current bug with `livereload`. Could you run it without `livereload` on a device or a simulator and let me know if you're still having the same issue?

**Comment by galhardi** [comment]
I have the same problem here.
I tried upload APP on IonicView, but I still have the problem.

**Comment by ihadeed** [comment]
@galhardi Ionicview doesn't support plugins. You need to run your app using the `run` command.

**Comment by galhardi** [comment]
@ihadeed, it's work fine now, thks!

**Comment by skolsuper** [comment]
No I just get a blank screen now.  Have tried grepping the logs for relevant error, maybe this will help?:

```
12-10 12:10:43.173  1759  2421 I ActivityManager: Start proc 2864:com.google.android.apps.maps/u0a38 for broadcast com.google.android.apps.maps/com.google.android.apps.gmm.iamhere.ble.StartBleServiceReceiver
12-10 12:10:43.293  2864  2864 W System  : ClassLoader referenced unknown path: /system/app/Maps/lib/x86_64
12-10 12:10:43.537  2864  2878 W art     : Suspending all threads took: 6.831ms
12-10 12:10:44.207  2864  2864 D StrictMode: StrictMode policy violation; ~duration=690 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65567 violation=2
12-10 12:10:44.207  2864  2864 D StrictMode: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1263)
12-10 12:10:44.207  2864  2864 D StrictMode: 	at libcore.io.BlockGuardOs.access(BlockGuardOs.java:67)
12-10 12:10:44.207  2864  2864 D StrictMode: 	at java.io.File.doAccess(File.java:281)
12-10 12:10:44.207  2864  2864 D StrictMode: 	at java.io.File.exists(File.java:361)
12-10 12:10:44.207  2864  2864 D StrictMode: 	at android.app.ContextImpl.createFilesDirLocked(ContextImpl.java:418)
12-10 12:10:44.207  2864  2864 D StrictMode: 	at android.app.ContextImpl.getFilesDir(ContextImpl.java:441)
12-10 12:10:44.207  2864  2864 D StrictMode: 	at android.app.ContextImpl.openFileInput(ContextImpl.java:383)
12-10 12:10:44.207  2864  2864 D StrictMode: 	at android.content.ContextWrapper.openFileInput(ContextWrapper.java:177)
12-10 12:10:44.207  2864  2864 D StrictMode: 	at com.google.android.apps.gmm.shared.i.h.a(PG:250)
12-10 12:10:44.207  2864  2864 D StrictMode: 	at com.google.android.apps.gmm.map.m.q.a(PG:8693)
12-10 12:10:44.207  2864  2864 D StrictMode: 	at com.google.android.apps.gmm.shared.f.a.a(PG:48)
12-10 12:10:44.207  2864  2864 D StrictMode: 	at com.google.android.apps.gmm.map.m.e.a(PG:1531)
12-10 12:10:44.207  2864  2864 D StrictMode: 	at com.google.android.apps.gmm.base.app.a.a(PG:244)
12-10 12:10:44.207  2864  2864 D StrictMode: 	at com.google.android.apps.gmm.base.app.a.a(PG:2265)
12-10 12:10:44.207  2864  2864 D StrictMode: 	at com.google.android.apps.gmm.base.app.GoogleMapsApplication.a(PG:206)
12-10 12:10:44.207  2864  2864 D StrictMode: 	at com.google.android.apps.gmm.base.app.GoogleMapsApplication.onCreate(PG:174)
12-10 12:10:44.207  2864  2864 D StrictMode: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
12-10 12:10:44.207  2864  2864 D StrictMode: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
12-10 12:10:44.207  2864  2864 D StrictMode: 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
12-10 12:10:44.207  2864  2864 D StrictMode: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
12-10 12:10:44.207  2864  2864 D StrictMode: 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-10 12:10:44.207  2864  2864 D StrictMode: 	at android.os.Looper.loop(Looper.java:148)
12-10 12:10:44.207  2864  2864 D StrictMode: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
12-10 12:10:44.207  2864  2864 D StrictMode: 	at java.lang.reflect.Method.invoke(Native Method)
12-10 12:10:44.207  2864  2864 D StrictMode: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
12-10 12:10:44.207  2864  2864 D StrictMode: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by wwallace** [comment]
Yeah, I just tried installing with the latest version of Ionic and a fresh starter project. I am seeing in location  that the "plugin is not installed" after running Ionic run android

**Comment by wwallace** [comment]
Sorry, I'm on my phone, and I meant "log cat" not "location"

**Comment by ihadeed** [comment]
@skolsuper this seems like an issue with the plugin. I suggest you open an issue at their repo or check their existing issues.
