### ISSUE TITLE
URL Matching with Ionic Deep Links

### ISSUE THREAD

**Issue by samarthagarwal** [driftyco/ionic-native#850]
I have done everything required to define the custom URL scheme and trying to test DeepLinks in my Ionic2 App. Let's say my app is called PollsApp, I have the following code in the constructor of my landing page,

`Deeplinks.route({
      '/polls/:unique_poll_id': PollsPage
    })
.subscribe((match) => {
            console.log('Successfully matched route', match);
    }, 
(nomatch) => {
      console.error('Got a deeplink that didn\'t match', nomatch);
    });`

Now when I try the Url `<a href="pollsapp://polls?unique_poll_id=1234">Test</a>`, It always gives `nomatch`. But if I try with this Url, `<a href="pollsapp://polls/polls?unique_poll_id=1234">Test</a>`, It works. 

Why do we need to pass in another _/polls/_ in the Url?

Is it what we should expected?

**Comment by mlynch** [comment]
To be most compatible with URL parsers, we recommend the format `pollsapp://app/polls?` so "app" becomes the hostname
