### ISSUE TITLE
2.2.10 broke Device plugin (and probably other plugins?)

### ISSUE THREAD

**Issue by biesbjerg** [driftyco/ionic-native#851]
After updating to 2.2.10, when accessing `Device` plugin, it is undefined.

I'm calling it when platform is ready. Other plugins I'm using seems to work (`AppVersion`, `SocialSharing`)

Snippets from my code;

```
import { GoogleAnalytics, Device, AppVersion, SocialSharing } from 'ionic-native';

... 

	public onSupport(): void {
		this._platform.ready().then(() => {
			SocialSharing.canShareViaEmail()
				.then(() => {
					const subject = this._getLocalizedSubject();
					const body =
						this._getLocalizedBody() +
						`\n\n\n\n\n` +
						`------------------------------\n` +
						`**INFO**\n` +
						this._getDebugInfo()

					return SocialSharing.shareViaEmail(body, subject, [config.supportEmail]);
				})
				.catch(err => {
					const alert = this._alertController.create({
						title: this._translateService.instant('Error occurred'),
						message: JSON.stringify(err),
						buttons: [
							this._translateService.instant('OK')
						]
					});
					alert.present(alert);
				});
		});
	}
```

After downgrading to 2.2.9, `Device` works again.

**Comment by ihadeed** [comment]
Thanks, will fix this right now.

**Comment by ihadeed** [comment]
This is fixed now, please note that the static property `device` doesn't exist anymore on the class `Device`. 

For example, `Device.device.platform` becomes `Device.platform` now.

**Comment by biesbjerg** [comment]
Nice! Thanks!

**Comment by samarthagarwal** [comment]
How do we use it? Any help? Does it return a promise. I need to get the device UUID.

**Comment by biesbjerg** [comment]
Use `Device.uuid`

**Comment by ihadeed** [comment]
Sorry @samarthagarwal for not updating the other issue as well. What @biesbjerg said should work.

**Comment by samarthagarwal** [comment]
Not working. This is an instance property so I should do `new Device().uuid`, right? I have tested `Device.uuid` and it is not working.

**Comment by ihadeed** [comment]
@samarthagarwal did you update to latest version `v2.2.11` ?

**Comment by samarthagarwal** [comment]
Yes I have.

![screenshot_2](https://cloud.githubusercontent.com/assets/3234592/20929340/b231e8ea-bbef-11e6-8782-ad979b717a3c.png)

**Comment by biesbjerg** [comment]
I had to restart VSCode before it understood that there was a "new API" for `Device` - maybe that's it?

**Comment by samarthagarwal** [comment]
I don't think VS Code has to do anything with it. I am getting a blank JSON object `{}` if I do the following.

`alert(JSON.stringify(new Device()));`

**Comment by ihadeed** [comment]
@samarthagarwal 
![image](https://cloud.githubusercontent.com/assets/13794420/20929679/db44c092-bb98-11e6-841c-f2c717af9aed.png)

**Comment by biesbjerg** [comment]
You shouldn't do `new Device`. Just access it directly: `Device`

**Comment by samarthagarwal** [comment]
Thanks @biesbjerg and @ihadeed . It works now.

**Comment by Math3v** [comment]
Hello everybody,
I am still experiencing this issue. I have 'ionic-native' 2.2.11 and cordova-plugin-device installed.

`import { Device } from 'ionic-native';`
`platform.ready().then(() => {
      console.log( Device );
    });`

This code gives me empty object to console.

`Device.uuid` gives me also nothing.

Is there anything that I could have missed?

Thanks
Matej

**Comment by ihadeed** [comment]
@Math3v are you running on a device/simulator? are you using livereload?

**Comment by Math3v** [comment]
@ihadeed result is the same when using livereload and device. Also, I have noticed the 'cordova-plugin-device' is not installed warnings, but there is no IonicNative script included in my index.html file.

**Comment by Math3v** [comment]
@ihadeed sorry. I was accessing the Device in constructor. I moved the code inside ngOnInit() and it works just fine. 👍
