### ISSUE TITLE
Ionic2:BarcodeScanner.encode error

### ISSUE THREAD

**Issue by ksphp** [driftyco/ionic-native#854]
** code
```
BarcodeScanner.encode(BarcodeScanner.Encode.TEXT_TYPE,'http://www.nytimes.com').then(() => {
    console.log('suc');
}, (err) => {
    console.log(err);
});
```
** Error
Exception calling native with command :: BarcodeScanner :: encode ::exception=TypeError: success is not a function

**Comment by ihadeed** [comment]
@ksphp I'm unable to reproduce this issue.

Seems like the `encode()` method isn't working at all with me (problem with the actual plugin).
