### ISSUE TITLE
how can I use ionic-native with cordova standalone?

### ISSUE THREAD

**Issue by yozman** [driftyco/ionic-native#857]
hi, I try to use cordova without angular2,
so can I use ionic-native standalone?

could you tell me how to do that?

**Comment by yozman** [comment]
```javascript
import { Dialogs } from 'ionic-native'

// work well
window.alert = navigator.notification.alert
window.alert('work well')

// no alert
Dialogs.alert('not work')
```

this it the I write

**Comment by ihadeed** [comment]
Include `ionic.native.min.js` in your `index.html`. Then you can use plugins using the global `IonicNative` variable. Here is a quick example:

```javascript
IonicNative.Dialogs.alert('Hello world');
```

**Comment by yozman** [comment]
@ihadeed 
is there any way to use like 'webpack.ProvidePlugin'?

**Comment by yozman** [comment]
@ihadeed 
I do like this first copy `ionic.native.min.js` from `node_modules/ionic-native/dist/ionic.native.min.js`
add include in `index.html`
```html
<script type="text/javascript" src="static/ionic.native.min.js"></script>
```
and run code
```javascript
IonicNative.Dialogs.alert('hello world')
```

but doesn't work

**Comment by ihadeed** [comment]
You also need to wrap your code with `deviceready` event listener.

```
function showDialog() {
   IonicNative.Dialogs.alert('Hello world');
}

document.addEventListener('deviceready', showDialog, false);
```

**Comment by yozman** [comment]
@ihadeed 
Now I'm sure there is a bug,
it doesn't work

**Comment by yozman** [comment]
I catch the reason.
need `es6-promise`
