### ISSUE TITLE
Native SMS.send().then()..catch() promise throws error

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic-native#858]
_From @barocsi on December 9, 2016 16:44_

**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Native SMS.send() falls into error after sms is sent.
```
SMS.send(a,b)
      .then(() => {
        // should be active
      })
      .catch((error: any) => {
          // THIS IS ACTIVE, error echoes "OK"
          })
        }
      );
```
**Expected behavior:**
code above

**Steps to reproduce:**
code above

_Copied from original issue: driftyco/ionic#9572_

**Comment by ihadeed** [comment]
@barocsi This occurs when the options param is omitted. Just fixed it and it will be available in next patch release. For now you can just pass `null` or `{}` as a third param to work around this issue.

**Comment by barocsi** [comment]
Thanks! That will do for now!
