### ISSUE TITLE
Gatting error "sqlitePlugin is not defined"

### ISSUE THREAD

**Issue by anand-parmar** [driftyco/ionic-native#859]
Hi,

I am working with sqlite plugin in ionic 2. 

**ionic info**

ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v6.9.1
Xcode version: Not installed

i have installed sqliteplugin
`ionic plugin add cordova-sqlite-storage`

**Comment by ihadeed** [comment]
Are you waiting for `deviceready` event to fire? do you have the plugin installed?
