### ISSUE TITLE
Please add support for Subscribe/Unsubscribe for Topics in Native Push

### ISSUE THREAD

**Issue by naveedahmed1** [driftyco/ionic-native#861]
Hi,

Sincce the plugin phonegap-plugin-push supports Subscribe/Unsubscribe for Topics it would be really nice if its support could also be addded to Ionic Native Push.

The subscribe method is used when the application wants to subscribe a new topic to receive push notifications.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushsubscribetopic-successhandler-errorhandler

The unsubscribe method is used when the application no longer wants to receive push notifications from a specific topic but continue to receive other push messages.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushunsubscribetopic-successhandler-errorhandler

**Comment by uj** [comment]
Same goes for .clearAllNotifications(...) <-- ERROR HERE: Property 'clearAllNotifications' does not exist on type 'PushNotification'.

https://github.com/driftyco/ionic-native/issues/983

**Comment by ZiFFeL1992** [comment]
You can close this as well @ihadeed :)
