### ISSUE TITLE
pb pluggin db-meter. It creates a build Fail.

### ISSUE THREAD

**Issue by workfluo** [driftyco/ionic-native#866]
This plugin creates a build Fail: 
https://ionicframework.com/docs/v2/native/db-meter/.

**Comment by mlynch** [comment]
Any console output or anything to help?

**Comment by workfluo** [comment]
To have this plugin installed (without using it or even mentioning it in config.xml) is enough to create a build fail for iOS but for iOS only (for android the problemes come after with a blacked screen).

Here is some of the error outputs
** BUILD FAILED **
The following build commands failed:
	CompileSwift normal i386 /Users/Workfluo/ionic-server/wad/platforms/ios/What a Day/Plugins/cordova-plugin-dbmeter/DBMeter.swift

	CompileSwiftSources normal i386 com.apple.xcode.tools.swift.compiler
(2 failures)

Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/Workfluo/ionic-server/wad/platforms/ios/cordova/build-debug.xcconfig,-project,What a Day.xcodeproj,ARCHS=i386,-target,WaD,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/Workfluo/ionic-server/wad/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/Workfluo/ionic-server/wad/platforms/ios/build/sharedpch

**Comment by ihadeed** [comment]
@workfluo I suggest you open an issue at the plugins repo to get help with this. It doesn't look like an Ionic Native related problem to me.

Repo url: https://github.com/akofman/cordova-plugin-dbmeter
