### ISSUE TITLE
white blank screen after cordova splashscreen 

### ISSUE THREAD

**Issue by MELAS007** [driftyco/ionic-native#870]
I got a white blank screen after cordova splashscreen.

 if I close the app and open again (without memory cleaning) the splash doesn't rise, and the screen is white until the app is ready!

I can't see the homepage...

Anyone can tell me how to solve this?

**Comment by ihadeed** [comment]
@MELAS007 there are a few threads on the forums regarding this, did you have a look at them?

https://forum.ionicframework.com/t/splashscreen-on-android-doesnt-work-only-showing-white-screen-for-2-seconds/15604/34
