### ISSUE TITLE
MediaCapture Typings not being picked up?

### ISSUE THREAD

**Issue by richardshergold** [driftyco/ionic-native#876]
I'm getting the same error that that was the subject of this closed issue:

https://github.com/driftyco/ionic-native/issues/396

i.e I have added the media capture plugin as instructed here:

https://ionicframework.com/docs/v2/native/media-capture/

However, when I add this code:

import { MediaCapture } from 'ionic-native';
...
...
getMultiPicture() {
        let options: CaptureImageOptions = { limit: 3 };
        MediaCapture.captureImage(options)
            .then(
            (data: MediaFile[]) => console.log(data),
            (err: CaptureError) => console.error(err)
            );
}

I get an error "Cannot find name CaptureImageOptions".  I've restarted Visual Code but I still get the error - is there something I am missing?  

(I can see the media-capture.d.ts inside the project)

**Comment by richardshergold** [comment]
by the way these are my dependencies in package.json:

"dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/storage": "1.1.6",
    "ionic-angular": "2.0.0-rc.3-201611211919",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "moment": "2.15.1",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26",
    "angularfire2": "2.0.0-beta.6",
    "firebase": "^3.6.1"
  },

**Comment by richardshergold** [comment]
Actually, the latest version is 2.2.11 (no idea why I had 2.2.3 in there) so I have installed that and now have

 "ionic-native": "2.2.11"

in package.json.  **I still get the same errors though when I open Visual Code.**

**Comment by richardshergold** [comment]
Someone else seems to have the same issue:

https://forum.ionicframework.com/t/error-in-mediacapture-native/72848

**Comment by mebibou** [comment]
Maybe you should `import { CaptureImageOptions, MediaCapture } from 'ionic-native';`?

**Comment by richardshergold** [comment]
Thanks @mebibou - that solves the problem.  I hadn't thought of doing that (doh!).  I had to import MediaFile and CaptureError as well.  Thanks.
