### ISSUE TITLE
Add media plugin

### ISSUE THREAD

**Issue by ghenry22** [driftyco/ionic-native#88]
Please add the media plugin, I notice that it's currently missing.

I am just starting on a fresh rewrite of my app using ionic v2 and it would be nice to do so with the media plugin through ionic native as I HD it through ngcordova before.

**Comment by ihadeed** [comment]
Since the plugin uses instance methods, it will be added once we solve this issue here: https://github.com/driftyco/ionic-native/issues/86

**Comment by ghenry22** [comment]
I assumed as much, thought it was worth having an issue open for tracking.  I am happy to help testing the media plugin when you get to it.
