### ISSUE TITLE
cordova-plugin-network-information: Network undefined

### ISSUE THREAD

**Issue by jayh92** [driftyco/ionic-native#884]
After installing the cordova network plugin with 'ionic plugin add cordova-plugin-network-information', and implementing in Typescript as described here (http://ionicframework.com/docs/v2/native/network/) I am seeing that Network (imported from ionic-native) is always undefined. And therefore Network.connection is also always undefined. 

The Network plugin used to work but has stopped very recently. Ionic Info:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.36
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.2 Build version 8C30a

**Comment by ihadeed** [comment]
Works fine with me, can you provide steps to reproduce.

**Comment by jayh92** [comment]
Yep I will post a code sample in just a minute but I feel like it may have to do with my dependencies. Could you post what your package.json setup looks like so I can compare with mine?

**Comment by ihadeed** [comment]
Fresh Ionic 2 project. Latest version. (latest CLI version too)

**Comment by jayh92** [comment]
OK I have Ionic-Angular 2.0.0-rc.1 and Ionic 2.1.13 because when I tried updating to the latest (RC.4 and 2.1.17 respectively) I only got a CordovaLib.xcodeproj when building for iOS and then when I try to run on my iPad, nothing happens.

**Comment by jayh92** [comment]
Can you please post a code snippet of how you're using the Network.connection where it's working?

**Comment by ihadeed** [comment]
Sorry I thought you said `Network` is undefined, not `Network.connection`.

I just pushed a commit to fix this. Please update to the latest version.

Now you will need to use `Network.type` instead of `Network.connection`.

**Comment by jayh92** [comment]
Thanks so much for the fix. The update to ionic-native@2.2.12 and changing Network.connection to Network.type seems to have done the trick. So was this a bug?

**Comment by ihadeed** [comment]
Yes

**Comment by ironbone** [comment]
It would be nice to have also the documentation changed

**Comment by ironbone** [comment]
The problem is also then when installing ionic rc4 we have 
ionic-native@2.2.11
and there is no type property
The connection is also undefined

**Comment by FieldMarshallVague** [comment]
I had this until I updated to the latest version of Ionic-Native (2.2.16). My network plugin is version 1.3.1. Having said that, I am having trouble getting the onConnect subscription to fire.
