### ISSUE TITLE
Initial Network status is not available

### ISSUE THREAD

**Issue by philipbrack** [driftyco/ionic-native#886]
When using the Network plugin
ionic-native/src/plugins/network.ts

My usage-
```
 Network.onConnect().subscribe(() => {
      console.log('online');
      this.online = true;
    });
```

this only fires when a network change is detected.  

There should be away to receive the network status upon app startup.  How is this accomplished?  Could a new API be added if there currently is not an elegant way to do so?

**Comment by philipbrack** [comment]
Hello,  I updated my service as follows to get the initial network state and it appears to work on ios-

```

  constructor() {
    this.online = navigator.onLine;
  }
```

Perhaps some documentation update at least would be nice talking about this on the doc page-

https://ionicframework.com/docs/v2/native/network/

**Comment by ihadeed** [comment]
There are 2 static properties of the `Network` class that will return values right away. 
```
Network.type;
Network.downlinkMax;
```

**Comment by OvidiuGuta** [comment]
Hi. The documentation states that the Network class has these two properties but in the .d.ts file from npm (version 2.2.11) there are just three properties. (connection, onConnect and onDisconnect) so I'm not sure what to make of it.

Also, even when using the onConnect() method like in the documentation, the Network.connection returns undefined on the device and an empty object in the browser.

Please advice if there are other versions of ionic-native or cordova plugin (I have version 1.3.1) I should be using.

Thank you.

**Comment by nnixaa** [comment]
@OvidiuGuta just solved this for myself - install the 2.2.12 version of ionic native and use `Network.type` instead of `Network.connection`.

@ihadeed would be awesome if you note such changes in the Breaking Changes section, as this is the section that draws the attention mostly.

**Comment by ihadeed** [comment]
@nnixaa sorry I forgot to publish the release/changelog for that version, I just published it now.

**Comment by OvidiuGuta** [comment]
@nnixaa Thank you for the quick response. It worked like a charm. The npm.org cache was playing tricks on me because it says the latest version is 2.2.11.

However, in the browser Network.type still returns an empty object instead of a string. I'm wandering if I should use it another way or it shouldn't work at all, but the documentation says the Browser platform is supported so I'm not sure how to proceed.

**Comment by ihadeed** [comment]
Browser platform isn't `ionic serve`, it's `ionic run browser`.
