### ISSUE TITLE
ionic add plugin cordova-plugin-facebook4 bug

### ISSUE THREAD

**Issue by olixis** [driftyco/ionic-native#889]
Lost 3 hours trying to figure out why I was receiving the "User cancelled dialog" message.

Turns out that because of some bug, ionic plugin add, adds the plugin and the line to config.xml but doesn't work. Please fix or make it clear in the doc!

ionic plugin add cordova-plugin-facebook4 --save --variable APP_ID="myid" --variable APP_NAME="meuname" bugged.

 cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="myid" --variable APP_NAME="myname" works!

**Comment by ihadeed** [comment]
The following works for me:
```
ionic plugin add cordova-plugin-facebook4 --variable APP_ID="myid" --variable APP_NAME="meuname"
```

**Comment by fredgalvao** [comment]
So the issue was? The position/presence of the `--save` parameter?

**Comment by ihadeed** [comment]
@fredgalvao not sure, but I highly doubt that the install command is the reason.
