### ISSUE TITLE
Google maps setMapTypeId(typeId:string)

### ISSUE THREAD

**Issue by chinaza** [driftyco/ionic-native#892]
I have tried passing every possible combination of string values to change my map to satellite view to no avail. Here are some of the values I have tried:

MAP_TYPE_SATELLITE
satellite
SATELLITE

How do I change my Map to satellite view?

**Comment by ihadeed** [comment]
`MAP_TYPE_SATELLITE` is correct, if the map type is still not changing then I'm guessing there is a problem with the plugin.
