### ISSUE TITLE
GoogleMaps moveCamera with LatLngBounds doesn't work anymore on RC4

### ISSUE THREAD

**Issue by malvadeza** [driftyco/ionic-native#893]
Hello there!

I've been using Ionic2-rc2 in the company I work for. We are developing an app that uses GoogleMaps native plugin.
Using RC2 I'm able to move/animate Camera towards a LatLngBounds, but after trying to update Ionic version to RC4 it doesn't work anymore.

I've set a minimum app to show it: [https://github.com/malvadeza/mapsplugin](https://github.com/malvadeza/mapsplugin).

~~I've tried to put a branch with Ionic2-RC2 but was not able to do it. But with this project it's already possible to see the problem.~~
There's a branch called ionic-rc2 and the move camera works there, but not on the master branch (ionic-rc4)

I've tested on Android devices: 5.1.1 and 6.0.1.

Thanks in advance

**Comment by ihadeed** [comment]
This would be an issue with Ionic Framework or the plugin itself, doesn't seem to be an Ionic Native issue.
