### ISSUE TITLE
[Ionic RC3] BackgroundMode fail setDefaults(options)

### ISSUE THREAD

**Issue by fjms** [driftyco/ionic-native#895]
When click in the app notification when the app is in background mode, android open app info no the app!

BackgroundMode.setDefaults is ignored.

      BackgroundMode.setDefaults({
        title: 'BlablablaApp',
        text: 'Ionic is great!',
      });

Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.1
Xcode version: Not installed

   <plugin name="cordova-plugin-background-mode" spec="~0.6.5" />

**Comment by fjms** [comment]
Anyone can replicate this?

**Comment by mhartington** [comment]
Hmm, just tested this out and all is working fine on 4.4.

On 6x, it's a bit different, but still working.

Was able to replicate the same results using ionic and ionic-native, as well as cordova and raw API. Chances are, there's probably an issue with the plugin and should be brought the plugin repos attention.

**Comment by fjms** [comment]
Have you updated the sdk of android? Because for me it's not working in 4.4... I don't know if it can have any relation.
Thank, @mhartington
