### ISSUE TITLE
NativeStorage not being cleared after uninstall on Android

### ISSUE THREAD

**Issue by Maziar-Fotouhi** [driftyco/ionic-native#898]
I am not sure if I should report this here, or in the [NativeStorage github](https://github.com/TheCocoaProject/cordova-plugin-nativestorage). But, since I noticed this issue only after I updated _ionic-native_ to **2.2.12**, I'm reporting this here.

After the update, I noticed that the _NativeStorage_ entries are not being cleared after uninstalling the app. Looking at the [NativeStorage github](https://github.com/TheCocoaProject/cordova-plugin-nativestorage), it seems like android is using `Sharedpreferences`.

I googled [similar issues](http://stackoverflow.com/questions/35517239/sharedpreferences-are-not-being-cleared-when-i-uninstall) and it seems like, we have to set `android:allowBackup=false` in the _application_ tag of _AndroidManifest.xml_.

Currently, my _application_ tag looks like this:
` <application android:hardwareAccelerated="true" android:icon="@mipmap/icon" android:label="@string/app_name" android:supportsRtl="true">`

**Comment by ihadeed** [comment]
This would be an issue with the plugin and not with Ionic Native. I suggest you open an issue at their repo.
