### ISSUE TITLE
RC4 update docs for Device

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#899]
_From @chrisbenseler on December 16, 2016 11:38_

Ionic version: 2

The [official docs for the native Device](https://ionicframework.com/docs/v2/native/device/) are obsolete.
Example:
The Device object does not have more a device attribute.
 
Example:
_Device.device.uuid_ wont compile. The compiler outputs

> Property 'device' does not exist on type 'typeof Device'.

Now the right implementation is
`Device.uuid`

_Copied from original issue: driftyco/ionic#9667_

**Comment by jgw96** [comment]
_From @keyframeindia on December 19, 2016 13:8_

I have also same issue in RC4

**Comment by ihadeed** [comment]
The docs are updated now.
