### ISSUE TITLE
Google Maps V2

### ISSUE THREAD

**Issue by THEDOWNCOUNTRY** [driftyco/ionic-native#903]
I am trying to test the https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/v2-beta since its only missing documentation but the map com on with my existing codes but having issues getting the camera position data. the following is my codes.

		this.map.getCameraPosition().then(data => {
			console.log('tap received ++' + data);

			let corv = data.target.toString().split(",")
			let lat = +corv[0];
			let lng = +corv[1];
			let locatorMark = new GoogleMapsLatLng(lat, lng);
			console.log(lat, lng);
			// create new marker
			
			let markerOptions: GoogleMapsMarkerOptions = {
				position: locatorMark,
				title: 'Text value',
				snippet: 'text snipet',
				icon: {
					url: 'icon_path'
				},
				animation: GoogleMapsAnimation.BOUNCE
			};

			this.map.addMarker(markerOptions)
				.then((marker: GoogleMapsMarker) => {
					marker.showInfoWindow();
				});

			Geocoder.geocode(corv).then(data => {
				console.log('Geocode Data' + data);
			})
		})

**Comment by ihadeed** [comment]
Google Maps v2 isn't going to work with our interface. We will update our wrapper once V2 is stable. If you wish to try out V2 now, you need to use their API directly.

**Comment by THEDOWNCOUNTRY** [comment]
Already using it and its pretty cool and faster!
