### ISSUE TITLE
Last change in diagnostic.ts breaks build when using noImplicitAny option

### ISSUE THREAD

**Issue by Ritzlgrmft** [driftyco/ionic-native#905]
The last [change](https://github.com/driftyco/ionic-native/commit/9986e0d0b3436b9a82f1e8506ac4630df8d2b9be) in [diagnostic.ts](https://github.com/driftyco/ionic-native/blob/master/src/plugins/diagnostic.ts) breaks the build, when the typescript option `noImplicitAny` is used, since the generated `diagnostic.d.ts` contains

```
    static permissionStatus: {
        GRANTED;
        DENIED;
        NOT_REQUESTED;
        DENIED_ALWAYS;
        RESTRICTED;
        GRANTED_WHEN_IN_USE;
    };
```

Apparently, `GRANTED` etc. do not have a type declaration.

It would be great if you could add the types again, so I could enable `noImplicitAny` again.

**Comment by ihadeed** [comment]
Just pushed a commit that should fix it, will publish a release soon once I'm done reviewing other issues/PRs.
