### ISSUE TITLE
Got an error when calling the upload of Transfer

### ISSUE THREAD

**Issue by ninechung** [driftyco/ionic-native#909]
and no native function is called(i tried NSLog).

in the log, the path exists, and i used the File.checkFile

error is
`{"line":951,"column":37,"sourceURL":"file:///var/containers/Bundle/Application/084ED2B6-958F-4206-94B2-322892B84A41/tongzhanbu.app/www/cordova.js"}`
or
`{"line":2,"column":xxx,"sourceURL":"file:///var/containers/Bundle/Application/084ED2B6-958F-4206-94B2-322892B84A41/tongzhanbu.app/www/build/polyfills.js"}`
when the Transfer.upload.error

plz save me...

**Comment by ihadeed** [comment]
The information you provided doesn't really help. Can you check the console log using Safari/Chrome?
