### ISSUE TITLE
how can I use HTTP with cookie?

### ISSUE THREAD

**Issue by yozman** [driftyco/ionic-native#911]
hey guys,
I just want to make my app as my site with cookie to make auth,
so how can I use HTTP plugin with cookie?

could you please help me?

**Comment by ihadeed** [comment]
Add a header to your request(s). The key should be `Cookie` and the value is the content of your cookie.

**Comment by yozman** [comment]
@ihadeed 
could u give some example?
no description on docs

**Comment by ihadeed** [comment]
If you plan to use the cookie for all the future requests, you can call the function `setHeader` as follows:
```
Http.setHeader('Cookie', 'COOKIE CONTENT HERE');
```

If you only want to use it for specific requests, then you need to do the following:
```
HTTP.get('https://path/to/whatever', {}, { 'Cookie': 'COOKIE_CONTENT_HERE' });
```

**Comment by yozman** [comment]
@ihadeed 
how can I get the previous cookie ?

**Comment by ihadeed** [comment]
@yozman 

Every response has 3 properties: `status`, `data` and `headers`. You can read the `headers` property and extract the sub-property `Cookie` from there to get the previous cookie.

**Comment by yozman** [comment]
@ihadeed 
where should I save the cookie for next app start?
I add cookie to every request use your example.
when I exitapp and restart will the cookie still alive?

**Comment by ihadeed** [comment]
You need to store it in a service in runtime, and if you wanna keep using it then you should store it in localstorage.

**Comment by yozman** [comment]
@ihadeed 
Thanks, I'll try it,
By the way why don't let it be automatic with default?
I'm sure it will be really helpful

**Comment by ihadeed** [comment]
@yozman that's something to discuss with the plugin's developers at their repo. Also, in the future if you need support you should submit a post on the forums instead of here.

**Comment by bhlokhandwala** [comment]
@ihadeed have we found any support for persisting the cookie after ios app is terminated and reopened.
I store my PHP session ID in the cookie of Http Request Header and it gets clear when I terminate the app ( force kill ) and when I reopen my Http Request Header cookie is cleared

**Comment by Vickypr1902** [comment]
I'm building an ionic app, and I need to implement cookie-based authentication, to authenticate the pages that I open in inappbrowser.
So my question is how to save the cookie that I get in response(chrome dev tools) and use it further in inappbrowser for auth.
