### ISSUE TITLE
gulp plugin:create -n PluginName (command not working)

### ISSUE THREAD

**Issue by vishuhanda001** [driftyco/ionic-native#912]
hi i want create custom plugin using ionic 2 and have followed this link https://github.com/driftyco/ionic-native/blob/master/DEVELOPER.md  but  stuck here as the command gulp plugin:create -n PluginName  is not working .
i am getting this error  (Task 'plugin:create' is not in your gulpfile)

I have installed gulp already but this is not working

kindly help

**Comment by ihadeed** [comment]
Works fine for me, make sure you're in the root directory of Ionic Native.

**Comment by vishuhanda001** [comment]
`
r
vishuhanda@IT-TestingMachine:~/Desktop/ionicpractice/vibapp/node_modules/ionic-native/dist/esm/plugins$
 gulp plugin:create -n MyPlugin                                                                        
[11:32:13] Working directory changed to ~/Desktop/ionicpractice/vibapp                                 
[11:32:14] Using gulpfile ~/Desktop/ionicpractice/vibapp/gulpfile.js                                   
[11:32:14] Task 'plugin:create' is not in your gulpfile                                                
[11:32:14] Please check the documentation for proper gulpfile formatting                               
vishuhanda@IT-TestingMachine:~/Desktop/ionicpractice/vibapp/node_modules/ionic-native/dist/esm/plugins$`


getting this error again after navigating to ionic-native directory

**Comment by ihadeed** [comment]
No, you need to clone this repository, then run `npm install` and then you can run that gulp command. You can't develop a new plugin using the compiled version of Ionic Native.

**Comment by vishuhanda001** [comment]
Hi can you please make a demo video on how to add custom plugin using ionic 2  from scratch as i am not able to get it .
Thanks

**Comment by ihadeed** [comment]
@vishuhanda001 No, I can't do that.

To create a custom plugin from scratch, this is the wrong place to look for instructions. Here are some instructions on how to develop a plugin: https://cordova.apache.org/docs/en/latest/guide/hybrid/plugins/

If you intend to create an Ionic 2 wrapper for a Cordova plugin, you need to do the following:

```
// Clone this repo
git clone https://github.com/driftyco/ionic-native

// Go to the directory
cd ionic-native

// install node modules
npm i
```

Then you can follow these instructions: https://github.com/driftyco/ionic-native/blob/master/DEVELOPER.md#creating-plugin-wrappers

**Comment by mluis** [comment]
Is it supposed to run the command on the plugin folder? What's the steps to reproduce successfully?
I'm getting the same issue since there's no gulpfile.js on the plugin folder.

**Comment by federicomartinlara1976** [comment]
This is a lie. Cloning the repository gives the following error:

"C:\Program Files\Git\bin\git.exe" clone -v --recurse-submodules --progress "git clone https://github.com/driftyco/ionic-native" "D:/Develop/git/ionic-native"
Cloning into 'D:/Develop/git/ionic-native'...
fatal: I don't handle protocol 'git clone https'
Done

Dedicate yourself to something other than programming

**Comment by pierresh** [comment]
> This is a lie. Cloning the repository gives the following error:
> 
> "C:\Program Files\Git\bin\git.exe" clone -v --recurse-submodules --progress "git clone https://github.com/driftyco/ionic-native" "D:/Develop/git/ionic-native"
> Cloning into 'D:/Develop/git/ionic-native'...
> fatal: I don't handle protocol 'git clone https'
> Done
> 
> Dedicate yourself to something other than programming

The address of the repository changed, the following command works:

git clone https://github.com/ionic-team/ionic-native
