### ISSUE TITLE
InAppBrowser insertCss Not Working

### ISSUE THREAD

**Issue by sly18** [driftyco/ionic-native#921]
I instanciate a an InAppBrowser with
`let browser = new InAppBrowser('my_fancy_url', "_self", 'location=no,hidden=yes,useWideViewPort=yes');`

Then a call on `browser.insertCss({code: this.cssETransaction});` raises an error :

> TypeError: Cannot call method 'apply' of undefined 

I tried to call `insertCss()` after `browser.show()`, I tried to set hidden to no but I never managed to insert CSS.

On the other hand on [chrome://inspect](url) when I call the InAppBrowser from `cordova.InAppBrowser.open(...)` I can easily insertCss.

Any Thoughts on that ?

**Comment by spongessuck** [comment]
I get a similar error using `insertCss` in the iOS simulator:

    TypeError: undefined is not an object (evaluating 'pluginObj._objectInstance[methodName].apply')

**Comment by aronbierbaum** [comment]
In order to workaround this I have added the following code to my project:

```typescript
const browser_proto = (this.browser as any)._objectInstance.__proto__;
browser_proto.insertCss = browser_proto.insertCSS;
```

**Comment by ihadeed** [comment]
Just pushed a commit to fix this, will be available in the next release.
