### ISSUE TITLE
Keyboard.close is not working on Android

### ISSUE THREAD

**Issue by casper123** [driftyco/ionic-native#925]
Hi,
I'm trying to close a keyboard when user clear the search bar. This is what I've done so far

```
<ion-col style="padding:0px;" col-90 center>
				<ion-searchbar style="padding:0px;" (ionInput)="getItems($event)"  (ionClear)="onClear($event)"></ion-searchbar>
			</ion-col>

onClear(event){
    console.log('g');
    Keyboard.close();
  }
```

I've used ionic-native for keyboard API. As far as i think, it is supposed to close the keyboard as soon as i click cross button on search bar. The function fires up fine as I get 'g' in console. The problem is it doesn't close the keyboard! Am I missing something?

**Comment by ihadeed** [comment]
Does it work if you call `cordova.plugins.Keyboard.close();` instead ?

**Comment by casper123** [comment]
It gives me during transpile if i use `cordova.plugins.Keyboard.close();`

```
[19:05:57]  Error: Error at 
            /Users/abdulwahab/Documents/mobileapps/bytemunch/.tmp/pages/choose-location/choose-location.ts:126:5 
[19:05:57]  Cannot find name 'cordova'. 
[19:05:57]  ngc failed 
[19:05:57]  ionic-app-script task: "build" 
[19:05:57]  Error: Error


```

**Comment by ihadeed** [comment]
You need to add `declare var cordova:any;` at the top of the page.

**Comment by ihadeed** [comment]
I think this is an issue with Ionic Framework.

Using the console to show the keyboard works, but when I do it from within the app it doesn't work. I'm having the opposite issue though, `close` works but `show` doesn't work.

**Comment by casper123** [comment]
I I tried this
`declare var cordova:any;`

But it still doesn't work. The keyboard does not close and remains open

**Comment by Killmore** [comment]
I have the same issue. It works fine on ios but for android it keeps the keyboard open (and retains focus on the searchbar input). In my case, I am trying to close the keyboard when the user scrolls the results being returned from the search.

```
<ion-content (ionScrollStart)="closeKeyboard()">
   ...
</ion-content>
```
```
closeKeyboard(){
   Keyboard.close();
}
```
