### ISSUE TITLE
how will work contacts plugin with ionic 2 ?

### ISSUE THREAD

**Issue by DILEEP-YADAV** [driftyco/ionic-native#926]
Hi ! any body would explain , how will work contacts plugin with ionic 2 ?
I tried more , but it's not working.
Code:

import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import {Geolocation} from 'ionic-native';

@Component({
  selector: 'page-contact',
  templateUrl: 'contact.html'
})
export class ContactPage {
   contacttobefound = '';
   contactsfound = [];
   search = false;
constructor(public navCtrl: NavController) {
 }

  findfn(val) {
    let options = {
      multiple: true,
      hasPhoneNumber: true,
      filter: val
    }

 let cantactFields:ContactFieldType[] = ['displayName'];
      Contacts.find(cantactFields, options).then((contacts) => {
          this.contactsfound = contacts;
          alert(JSON.stringify(contacts[0]));
      })

      if(this.contactsfound.length == 0)
      this.contactsfound.push({displayName: 'No Contacts found'});
      this.search = true;
  }

}
`

**Comment by ihadeed** [comment]
What platform are you testing on?

Are you getting any errors?

Is the promise resolving or rejecting? Or are you not getting any response at all?

**Comment by DILEEP-YADAV** [comment]
Hi! @ihadeed , error ->
![error](https://cloud.githubusercontent.com/assets/8583769/21562689/dcdbcbc4-cea0-11e6-971b-0e69ac7bb4a6.PNG)

**Comment by DILEEP-YADAV** [comment]
Please help me to upgrade corodva contact plugin  app with latest ionic 2?
it's working with old ionic v .js type file. but not with TypeScript Ionic v2 App 
[Sample App](https://github.com/rajayogan/ionic2-contacts)

**Comment by ihadeed** [comment]
@DILEEP-YADAV here is an example on how to find contacts:

https://github.com/ihadeed/ionic-native-playground/blob/master/src/pages/contacts/contacts.ts#L35-L46
