### ISSUE TITLE
SecureStorage does not work in browser

### ISSUE THREAD

**Issue by tobiasmuecksch** [driftyco/ionic-native#928]
In the docs the browser is listed as supported platform of SecureStorage.

See: 
https://ionicframework.com/docs/v2/native/secure-storage/

But when I add the following code to my app, it won't work anymore and an error is thrown:
`Can't find variable : Cordova`

```
let secureStorage: SecureStorage = new SecureStorage();
secureStorage.create('my_store_name')
 .then(
   () => console.log('Storage is ready!'),
   error => console.log(error)
);
```
Are the docs wrong or is SecureStorage broken?

**Comment by ihadeed** [comment]
You need to run `ionic run browser` or `ionic build browser` to get the browser support.
