### ISSUE TITLE
Plugin Request For: cordova-plugin-android-permissions

### ISSUE THREAD

**Issue by prantikv** [driftyco/ionic-native#929]
Cordova permission plugin helps in getting permission from the user to allow app access to features. As per the new permission system for Android API 23 and above, now the user needs to grant/deny permissions on the fly.
Previously the permissions were granted during installation.

Here is the [npm repo](https://www.npmjs.com/package/cordova-plugin-android-permissions).

https://github.com/NeoLSN/cordova-plugin-android-permission

**Comment by darwiin** [comment]
Agree, it would be very good to have it in the ionic native plugins

**Comment by airstep** [comment]
So? Any updates? Or how to add it?

**Comment by danielsogl** [comment]
Hey @prantikv,

I will add this plugin this week.
