### ISSUE TITLE
Getting file path instead of base64

### ISSUE THREAD

**Issue by parth181195** [driftyco/ionic-native#931]
Hello there,

I am using camera plugin and while trying to pick video I am not getting base64 even though I have set destinationType to data url. I even tried to access the file with the path provided using file plugin but I am running into errors there too I am getting error code 5. Thanks in advance.

**Comment by smitthakkar96** [comment]
Getting the same issue had to use file transfer to upload the video file to server.

**Comment by ihadeed** [comment]
I think the Base64 works for images only, not videos. Even if it did work for videos, it would be a bad idea to do that.. Converting data to a Base64 string is memory intensive.
