### ISSUE TITLE
GooglePlus.login() causes java.lang.NullPointerException

### ISSUE THREAD

**Issue by eidng8** [driftyco/ionic-native#932]
As title says, call the function without parameter causes exception. But it works if called `GooglePlus.login({})`.

I followed the [doc](https://ionicframework.com/docs/v2/native/google-plus/), added the plugin, makes the `GooglePlus.login()` call, runs `ionic run android`, and then boom!

Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.48
Ionic Native Version: 2.2.11
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v4.3.1
Xcode version: Not installed
cordova-plugin-googleplus version: 5.1.1

**Comment by ihadeed** [comment]
Thanks I just fixed it, will be available in the next release.
