### ISSUE TITLE
Google analytics does not support browser

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic-native#934]
The [google analytics native thing](https://ionicframework.com/docs/v2/native/google-analytics/) says it supports "browser", however it does not.

`Native: tried calling GoogleAnalytics.startTrackerWithId, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator`

**Comment by ihadeed** [comment]
To run the browser platform you need to run `ionic run browser`. The `serve` command opens your app as a website, not as a cordova platform.

**Comment by AmitMY** [comment]
@ihadeed Cheers, it works better.
However, that command is not documented anywhere, but github issues. I wasn't even aware it existed

**Comment by ihadeed** [comment]
@AmitMY I agree, the Cordova browser platform is poorly documented compared to the other platforms. It should be documented in the Cordova docs.

**Comment by AmitMY** [comment]
@ihadeed I was acctualy more specifically referring to pages like this https://ionicframework.com/docs/guide/testing.html

Testing your app
- iOS (iOS command)
- android (android command)
- browser (ionic serve) - not mentioning that you can build for the browser
