### ISSUE TITLE
Globalisation does not have supported platforms 

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic-native#935]
The[ globalisation native thing](https://ionicframework.com/docs/v2/native/globalization/) does not list the supported platform. The repo however, does list them:

Amazon Fire OS
Android
BlackBerry 10
Firefox OS
iOS
Windows Phone 8
Windows
Browser

**Comment by ihadeed** [comment]
Thanks just pushed a commit to fix this. Will be available in the next docs update.
