### ISSUE TITLE
Market plugin doesn't work

### ISSUE THREAD

**Issue by fttx** [driftyco/ionic-native#936]
I've this exactly same issue: https://forum.ionicframework.com/t/ionic-native-market-api-throws-plugin-is-not-installed-but-ive-already-installed-it/67474

When i call Market.open the console says that the plugin is not installed, while if i use the cordova global variable it works.

![image](https://cloud.githubusercontent.com/assets/5663423/21685137/ab565adc-d360-11e6-8a33-4ed39abe996a.png)

**Comment by ihadeed** [comment]
I just tried the plugin and it worked fine on Android 7.1.x.

https://github.com/ihadeed/ionic-native-playground/blob/master/src/pages/market/market.ts#L18

**Comment by fttx** [comment]
I updated the package.json matching the one of the ionic2-app-base and worked

**Comment by sagar1351** [comment]
Please use this plugin once your platform is ready.
For e.g:-
  this.platform.ready().then(res=>{
    this.market.open('Your_package_name');
    })
