### ISSUE TITLE
InAppBrowser insertCss should be insertCSS

### ISSUE THREAD

**Issue by aronbierbaum** [driftyco/ionic-native#938]
It appears that https://github.com/apache/cordova-plugin-inappbrowser uses `insertCSS`. This causes an error when trying to look up the method.

```
TypeError: undefined is not an object (evaluating 'pluginObj._objectInstance[methodName].apply')
```

**Comment by spongessuck** [comment]
This is probably a duplicate of #921.

**Comment by aronbierbaum** [comment]
In order to workaround this I have added the following code to my project:

```typescript
const browser_proto = (this.browser as any)._objectInstance.__proto__;
browser_proto.insertCss = browser_proto.insertCSS;
```

**Comment by ihadeed** [comment]
Closing in favor of #921.
