### ISSUE TITLE
ScreenOrientation.unlockOrientation() doesn't unlock

### ISSUE THREAD

**Issue by ivanovvitaly** [driftyco/ionic-native#939]
I have modal page presented in landscape mode. When user dismisses the modal page I want to return screen orientation back to portrait mode without locking the orientation. 

The problem is that orientation does changes to portrait, however after screen is rotated to portrait it stays locked in portrait orientation and doesn't react on device rotation. Using ionic-native 2.2.14 and iPhone

code from modal page

```typescript
ionViewWillUnload(){
    ScreenOrientation.lockOrientation('portrait');
    ScreenOrientation.unlockOrientation();    
}
```

As workaround if I add delay to unlock the orientation it works, after screen returned to portrait I can rotate the phone and it changes the screen orientation
 
```typescript

ionViewWillUnload(){
    ScreenOrientation.lockOrientation('portrait');
    setTimeout(function() {
        ScreenOrientation.unlockOrientation();    
    }, 100);        
}
```

So, maybe it does make sense to change lock\unlock functions to return Promise\Observable?

Please advice

**Comment by ihadeed** [comment]
@ivanovvitaly 

Can you try to modify your `index.html` and make sure that `cordova.js` is included AFTER `polyfills.js` ?

**Comment by ivanovvitaly** [comment]
Moved `cordova.js` under `polyfills.js`. Didn't help, it rotates back to portrait, but stays locked.

**Comment by ihadeed** [comment]
@ivanovvitaly I just realized  the plugin returns back a promise, see https://github.com/apache/cordova-plugin-screen-orientation/blob/master/www/screenorientation.js#L71-L83

I will do the necessary changes to the `ionic-native` code to work with that.

**Comment by ivanovvitaly** [comment]
Orientation still stays locked after update. Following doesn't help

`ScreenOrientation.lockOrientation('portrait').then(() => ScreenOrientation.unlockOrientation());`

Unlock after timeout still works as workaround. 

After update ScreenOrientation.lockOrientation raises error, however orientation is changing.
```

console.error: EXCEPTION: Uncaught (in promise): TypeError: undefined is not an object (evaluating
            'pluginResult.then') http://172.26.9.242:8100/build/main.js:418:21
            http://172.26.9.242:8100/build/main.js:371:19 t@http://172.26.9.242:8100/build/polyfills.js:3:11330
            tryNativePromise@http://172.26.9.242:8100/build/main.js:370:31
            ionViewWillUnload@http://172.26.9.242:8100/build/main.js:62499:96
            _lifecycle@http://172.26.9.242:8100/build/main.js:8632:37
            _willUnload@http://172.26.9.242:8100/build/main.js:8577:24
            _willUnload@http://172.26.9.242:8100/build/main.js:33508:25
            _cleanup@http://172.26.9.242:8100/build/main.js:33442:33
            _trnsFinish@http://172.26.9.242:8100/build/main.js:33367:26 [native code]
            onInvoke@http://172.26.9.242:8100/build/main.js:40827:43
            run@http://172.26.9.242:8100/build/polyfills.js:3:6487 http://172.26.9.242:8100/build/main.js:33311:28
            _didFinish@http://172.26.9.242:8100/build/main.js:11497:29
            _didFinishAll@http://172.26.9.242:8100/build/main.js:11484:28
            onTransitionEnd@http://172.26.9.242:8100/build/main.js:10931:31
            onTransitionEnd@http://172.26.9.242:8100/build/main.js:6512:25
[18:08:43]  console.error: ORIGINAL STACKTRACE:
[18:08:43]  console.error: s@http://172.26.9.242:8100/build/polyfills.js:3:4220
            t@http://172.26.9.242:8100/build/polyfills.js:3:11356
            tryNativePromise@http://172.26.9.242:8100/build/main.js:370:31
            ionViewWillUnload@http://172.26.9.242:8100/build/main.js:62499:96
            _lifecycle@http://172.26.9.242:8100/build/main.js:8632:37
            _willUnload@http://172.26.9.242:8100/build/main.js:8577:24
            _willUnload@http://172.26.9.242:8100/build/main.js:33508:25
            _cleanup@http://172.26.9.242:8100/build/main.js:33442:33
            _trnsFinish@http://172.26.9.242:8100/build/main.js:33367:26 [native code]
            onInvoke@http://172.26.9.242:8100/build/main.js:40827:43
            run@http://172.26.9.242:8100/build/polyfills.js:3:6487 http://172.26.9.242:8100/build/main.js:33311:28
            _didFinish@http://172.26.9.242:8100/build/main.js:11497:29
            _didFinishAll@http://172.26.9.242:8100/build/main.js:11484:28
            onTransitionEnd@http://172.26.9.242:8100/build/main.js:10931:31
            onTransitionEnd@http://172.26.9.242:8100/build/main.js:6512:25
```

**Comment by tskweres** [comment]
@ivanovvitaly I tried wrapping unlock inside a $timeout ( Angular 1.5 ) and it's not working, still locked. Can you send me a code sample of what you speak of as a work-around?

**Comment by ivanovvitaly** [comment]
@tskweres
This works in ionic-native 2.4.0. Play with timeout values 200-300 is enough
```
 ionViewWillUnload(){
    ScreenOrientation.lockOrientation('portrait');

    setTimeout(function() {
        ScreenOrientation.unlockOrientation();    
    }, 300);        
}
```

**Comment by nadavb** [comment]
I'm using ionic 1.7.16 and cordova-plugin-screen-orientation 3.0.1, and the unlock doesn't work on iphones... Any clue why? the lock works.

**Comment by Anuj-logiciel** [comment]
@nadavb  It also depends on th plugin method.
I am using [](https://github.com/apache/cordova-plugin-screen-orientation) and its working by using 
method : `window.screen.orientation.unlock();`

**Comment by TheSniper102** [comment]
this work fine for me 

    if(this.platform.is('cordova')){
      this.platform.ready().then(()=>{
        this.screenOrientation.lock(this.screenOrientation.ORIENTATIONS.LANDSCAPE);
      })
    }
