### ISSUE TITLE
Geolocation's watchPosition has an incomplete declaration

### ISSUE THREAD

**Issue by badpenguin** [driftyco/ionic-native#942]
Geolocation plugin has incorrect declaration for watchPosition returning Geoposition
that's incorrect because you are returning also PositionError as a normal result.

Please fix the declaration or emit PositionError as an error instead.

**Comment by ihadeed** [comment]
I remember we had an issue with Observables that led us to do that. They stop emitting after a single error, which causes the watch functionality to break.

**Comment by mestremuten** [comment]
Documentation should be little different thou, typescript won't compile as it is now.

Original:
```javascript
var subscription = Geolocation.watchPosition()
                              .filter((p) => p.code === undefined) //Filter Out Errors
                              .subscribe(position => {
  console.log(position.coords.longitude + ' ' + position.coords.latitude);
});
```

Correct:
```javascript
var subscription = Geolocation.watchPosition()
                              .filter((p) => p.coords !== undefined) //Filter Out Errors
                              .subscribe(position => {
  console.log(position.coords.longitude + ' ' + position.coords.latitude);
});
```

Typescript error:
```
Property 'code' does not exist on type 'Geoposition'.
```

**Comment by ihadeed** [comment]
Thanks @mestremuten just updated it
