### ISSUE TITLE
NFC on Android not working with this code snippet

### ISSUE THREAD

**Issue by piyushmakhija** [driftyco/ionic-native#945]
I am trying to test NFC functionality in ionic native with this code snippet: https://jsfiddle.net/n5ehohL5/
I just change the value of a property title when NFC tag is read but it is not working. I am waiting for deviceready to fire in main app component. ionic-native v2.2.11 and ionic-angular v2.0.0-rc.4.
Thanks in advance.

**Comment by mebibou** [comment]
Maybe you should still put the code when the platform is ready, just in case:
```typescript
export class Page1 {
  title = "old";

  constructor(public navCtrl: NavController, platform: Platform) {
    platform.ready().then(() => {
      NFC.addNdefListener(() => {
        this.title = "new";
      }, () => {});

      NFC.addMimeTypeListener(() => {
        this.title = "new";
      }, () => {});
    });
  }
}
```

**Comment by piyushmakhija** [comment]
@mebibou Tried this. Still not working :(

**Comment by stormwin** [comment]
1. update to latest ionic-native
2. Read docs from here http://ionic-site-staging.herokuapp.com/docs/v2/native/nfc/

addMimetypeListener have first parameter mimeType, it's mimeType
All functions return Observable, so you should subscribe to.

So try something like this:

```
export class Page1 {
  title = "old";

  constructor(public navCtrl: NavController, platform: Platform) {
    platform.ready().then(() => {
      NFC.addNdefListener().subscribe(() => {
               // your code here
      });
      NFC.addMimeTypeListener(<-- mimeType here -->).subscribe(() => {
        // your code here
      });
    });
  }
}
```

read about mimeType here: 
https://github.com/chariotsolutions/phonegap-nfc#nfcaddmimetypelistener

**Comment by piyushmakhija** [comment]
Subscribing to the returned observable works! Thanks a lot for the help.

**Comment by mebibou** [comment]
hum the documentation should be updated and `onSuccess, onFailure` should be removed from the functions definitions

**Comment by stormwin** [comment]
i will take a look
