### ISSUE TITLE
Push should be implemented in the same way as SQLite

### ISSUE THREAD

**Issue by dexterouschen** [driftyco/ionic-native#953]
In ngCordova pushV5 maintains an instance of PushNotification but now in ionic-native, init function returns that instance which is way less helpful since it leaves the handling back to developers.

static init(options: PushOptions): PushNotification { return; }

The whole point of using ngCordova is that we can initialize once and use it across the board, and as a stand-in for it, ionic-native should follow similar concept right? I don't see why Push can't be implemented in the same way as SQLite using CordovaInstance.

private _objectInstance: any;

**Comment by ihadeed** [comment]
Already have a PR for it here: https://github.com/driftyco/ionic-native/pull/425
