### ISSUE TITLE
docs(Network): incorrect property name

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic-native#957]
http://ionicframework.com/docs/v2/native/network/

See the screenshot below which shows the documentation error:
![image](https://cloud.githubusercontent.com/assets/2852839/21809475/92636346-d750-11e6-8187-a7de55d94d99.png)

The `connection` property should be `type`.

**Comment by ihadeed** [comment]
This is fixed already, just not published on the production site yet. See here: http://ionic-site-staging.herokuapp.com/docs/v2/native/network/#advanced

Thanks though!
