### ISSUE TITLE
Native VideoPlayer plugin 'is not installed'

### ISSUE THREAD

**Issue by jguix** [driftyco/ionic-native#959]
After successfully installing VideoPlayer native plugin using:

`ionic plugin add cordova-plugin-videoplayer --save`

I can't open videos from my hybrid app. I always get the following message in console.

`Native: tried calling VideoPlayer.play, but the VideoPlayer plugin is not installed.`

My code:

```
      if (this.platform.is('cordova')) {
        // Playing a video.
        VideoPlayer.play(filePath).then(() => {
          console.log('video completed');
        }).catch(err => {
          console.log(err);
        });
      } else {
        window.open(filePath, '_blank');
      }
```

I can see that the plugin is in the platforms/android/assets/www/plugins/cordova-plugin-videoplayer folder as well as in the platforms/android/platform_www/plugins/cordova-plugin-videoplayer folder

**Comment by ihadeed** [comment]
@jguix try wrapping your code with `this.platform.ready().then(() => { ... });`

**Comment by jguix** [comment]
I already did it, I can post my full componentes if you want.

**Comment by jguix** [comment]
So here's my full component:

```
import { Component } from '@angular/core';
import { NavController, Platform } from 'ionic-angular';
import { File, VideoPlayer } from 'ionic-native';

@Component({
  selector: 'page-videos',
  templateUrl: 'videos.html'
})
export class VideosPage {

  constructor(
    public navCtrl: NavController,
    public platform: Platform) {

  }

  play(fileName) {
    let filePath: string;

    this.platform.ready().then(() => {
      if (this.platform.is('cordova')) {
        filePath = 'file:///android_asset/www/video/' + fileName + '.mp4';
      } else {
        filePath = './assets/doc/' + fileName + '.mp4';
      }
      console.log('Open video at ' + filePath);

      if (this.platform.is('cordova')) {
        // Playing a video.
        VideoPlayer.play(filePath).then(() => {
          console.log('video completed');
        }).catch(err => {
          console.log(err);
        });
      } else {
        window.open(filePath, '_blank');
      }
    });

  }

}
```

I am still getting the Native VideoPlayer plugin is not installed.

More info:

```
$ ionic info

Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: OS X El Capitan
Node Version: v6.9.4
Xcode version: Xcode 8.0 Build version 8A218a
```

This is my full project:

https://github.com/jguix/cucs

Thank you

**Comment by avatsaev** [comment]
Same problem

**Comment by ihadeed** [comment]
The docs say to install `cordova-plugin-videoplayer`. That package on NPM does not match the plugin.

Please uninstall the plugin and then install it directly from the repo 

```
ionic plugin rm cordova-plugin-videoplayer
ionic plugin add https://github.com/moust/cordova-plugin-videoplayer
```

**Comment by jguix** [comment]
Thanks!

**Comment by carponte** [comment]
I ran:

1) ionic cordova plugin remove cordova-plugin-videoplayer
2) ionic cordova plugin add https://github.com/moust/cordova-plugin-videoplayer
I get:

An error occurred while running cordova plugin add 

        https://github.com/moust/cordova-plugin-videoplayer --save (exit code 
        1):
        
        Error: Failed to fetch plugin https://github.com/moust/cordova-plugin-videoplayer via registry.
        Probably this is either a connection problem, or plugin spec is 
        incorrect.
        Check your connection and plugin name/version/URL

Any suggestion?

Thanks

**Comment by jguix** [comment]
Well, as of today, the package name has changed to `cordova-plugin-video-player`, so you could simply try:

`cordova plugin add cordova-plugin-video-player`

**Comment by 2010abinas** [comment]
@jguix `cordova plugin add cordova-plugin-video-player` did it work?
