### ISSUE TITLE
bug: Native VideoPlayer plugin 'is not installed'

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic-native#960]
_From @jguix on January 10, 2017 17:10_

After successfully installing VideoPlayer native plugin using:

`ionic plugin add cordova-plugin-videoplayer --save`

I can't open videos from my hybrid app. I always get the following message in console.

`Native: tried calling VideoPlayer.play, but the VideoPlayer plugin is not installed.`

My code:

```
      if (this.platform.is('cordova')) {
        // Playing a video.
        VideoPlayer.play(filePath).then(() => {
          console.log('video completed');
        }).catch(err => {
          console.log(err);
        });
      } else {
        window.open(filePath, '_blank');
      }
```

I can see that the plugin is in the platforms/android/assets/www/plugins/cordova-plugin-videoplayer folder as well as in the platforms/android/platform_www/plugins/cordova-plugin-videoplayer folder.

Also created in ionic-native project:
https://github.com/driftyco/ionic-native/issues/959

_Copied from original issue: driftyco/ionic#9939_

**Comment by jsayol** [comment]
The user had already opened issue #959, I'd suggest closing this one.

**Comment by jguix** [comment]
Yeah, sorry for all this mess :)

I was directed by the ionic documentation page or somewhere else to the ionic project, then realized that I could post my issue here.

Thanks
