### ISSUE TITLE
GoogleMapsLatLngBounds getters returning undefined

### ISSUE THREAD

**Issue by jgodoy86** [driftyco/ionic-native#972]
I recently updated to RC 5 and the GoogleMapsLatLngBounds northeast, northwest and even type properties are returning undefined now, it was working properly before updating Ionic
the _objectInstance does have the proper values

![image](https://cloud.githubusercontent.com/assets/17893712/21937947/290cd11e-d987-11e6-985d-8f97bbf2f5ee.png)

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.2.0
Xcode version: Not installed

**Comment by ziggyJ** [comment]
Same thing happened here. My project used to use ionic-native 2.2.3, it worked well. But after I upgraded ionic native to 2.3.1. The GoogleMapsLatLngBounds northeast/sourthwest value is undefined. It seems InstanceProperty decorator does not work well.

**Comment by ihadeed** [comment]
Sorry about that. Just fixed it. 

Will be available in the next patch release.
