### ISSUE TITLE
Camera.getPicture promise never returns on iOS

### ISSUE THREAD

**Issue by waynebloss** [driftyco/ionic-native#975]
Using Ionic `1.x` with Ionic Native ~~`2.2.11`~~ `2.2.16` on Android, everything works fine.

On iOS 10, calling `$cordovaCamera.getPicture(opt).then(success).catch(fail);` the promise never returns and neither of my `success` or `fail` functions are called. The picture is taken and stored in the photo album (against my wishes, since `saveToPhotoAlbum` is `false`), but there is no error or stack trace or console output from my functions.

However, when I do the following, everything works:

```js
    navigator.camera.getPicture(function gotPic(pic) {
      util.logData('navigator.camera.getPicture gotPic', pic);
    }, function gotErr(err) {
      util.logData('navigator.camera.getPicture gotErr', err);
    }, opt);
```

I can't test on iOS 9 anymore because Apple won't let me downgrade my device and their crummy Simulator doesn't do webcam pass-through.

So, besides just switching my code to use `navigator.camera.getPicture` - what should I try? Here's my code that works on Android but not iOS. The `opts` are the same in either case:

```js
        $cordovaCamera.getPicture(opt)
        .then(function gotPicture(filePath) {
          util.logData('Got photo', filePath);
          return new PhotoResult(filePath);
        })
        .then(processExif)
        .then(moveToPrivateStorage);
```

**Comment by mlynch** [comment]
Is this on device or simulator?

Otherwise could be related to our ng1 support.

**Comment by waynebloss** [comment]
It's on my device, an iPhone 6s.

**Comment by waynebloss** [comment]
I don't think this is an issue with Ionic Native anymore because I'm now having the same issue when calling `navigator.camera.getPicture` directly.

If I don't pass any options, everything works fine. If, however, I pass the following options then the success path never returns. (Canceling the camera after it pops up causes the failure path to return in every case.)

```js
  var options = {
    // Size
    quality: 80,
    targetWidth: 1024,
    targetHeight: 768,
    // Actions
    allowEdit: false,
    correctOrientation: false,
    saveToPhotoAlbum: false,
    // iOS
    popoverOptions: CameraPopoverOptions,
    // Basic
    encodingType: Camera.EncodingType.JPEG,
    sourceType: Camera.PictureSourceType.CAMERA,
    destinationType: Camera.DestinationType.NATIVE_URI
  };
```

So, I need to narrow it down the exact option that is causing this.

**Comment by ihadeed** [comment]
@waynebloss can you try the fix mentioned here: https://github.com/driftyco/ionic-native/issues/505#issuecomment-273504996

Might be related...

**Comment by waynebloss** [comment]
It turns out, the problem happens whenever I use `destinationType: Camera.DestinationType.NATIVE_URI` regardless of whether `saveToPhotoAlbum` is `true` or `false`.
