### ISSUE TITLE
Ionic/Angular 1 Demo

### ISSUE THREAD

**Issue by briananderson1222** [driftyco/ionic-native#98]
I've noticed there is a ng1demo folder in this repository which makes me believe that this plugin is supported in Angular 1. I believe maybe a folder was omitted when being checked in as I am unable to see where the js/bundle.js gets generated from which I assume would have the code example for how to correctly import this plugin in an Angular 1 application. Is there official support for Ionic/Angular 1 applications so that we can attempt to bridge the gap between Ionic 1 and Ionic 2 a bit more?

**Comment by ihadeed** [comment]
Hey Brian,

Yes there is official support for Angular 1.x and any other JavaScript
framework (including plain JavaScript). At the moment there isn't an
official documentation for that, but you can get a rough idea of how it
works here: http://jsdev.ca/ionic-native-cordova-plugins-simplified/

I hope that helps. Let me know if you have any further questions.

**Comment by briananderson1222** [comment]
Awesome, thanks for this link. I am going to check this out. Might be worth checking out getting the missing files into the ng1demo folder or providing some additional documentation (or even this link) somewhere.

Also the link calls out that Ionic Native is still in Beta.. Is this still the case? I don't see anything in the Github repository that confirms this and even the package.json lists the version number at 1.10 which I would assume means it is a stable release

**Comment by ihadeed** [comment]
What I really meant by "Ionic Native is still in Beta" is that it's an incomplete project at the moment. Not all major plugins (which are available in ngCordova) have been fully added, documented and/or tested.

**Comment by ddennis** [comment]
It would still be very helpfull to have the source files instead of just the compiled bundle file.

**Comment by ihadeed** [comment]
@ddennis you can acquire those files by cloning the repo.
