### ISSUE TITLE
No way to use InAppBrowser in ionic 1

### ISSUE THREAD

**Issue by sryze** [driftyco/ionic-native#982]
When trying to use `$cordovaInAppBrowser.open()` it does nothing and only outputs:

Native: Your current usage of the InAppBrowser plugin is depreciated as of ionic-native@1.3.8. Please check the Ionic Native docs for the latest usage details.

How are we supposed to use it in ionic 1.x if the object is created elsewhere?

**Comment by sryze** [comment]
I thought deprecated means "it works but will be removed soon". The message is misleading.

**Comment by ihadeed** [comment]
Sorry for the misleading message. I will get rid of it.

Try this:
```
var ref = new $cordovaInAppBrowser('https://google.com');
ref.open();
```

**Comment by sryze** [comment]
Thanks, this works perfectly!

I've actually tried that before but without the `new` keyword and was frustrated that it didn't work. I feel very dumb right now.

**Comment by ggiacomo** [comment]
Please add this
`var ref = new $cordovaInAppBrowser('https://google.com');`

somewhere in the main ionic documentation. Spent like 2h to solve this issue :(

**Comment by ggiacomo** [comment]
@ihadeed , how to pass the option object to this new syntax? 
This open the browser
`var ref = new $cordovaInAppBrowser('https://google.com',);`
but this  is not opening the browser
`var ref = new $cordovaInAppBrowser('https://google.com', '_blank,', {location:"no"});`

Thank you very much.

**Comment by ggiacomo** [comment]
Ok I answer myself, the new syntax receive an option string instead the object
`'location=no,toolbar=no,...'`
