### ISSUE TITLE
Geolocation Typescript Error

### ISSUE THREAD

**Issue by wshaheer** [driftyco/ionic-native#987]
After updating to ionic-native v2.2.16, calling `subscribe()` on observable returned by `Geolocation.watchPosition()` causes error: 

_Type 'Subscription' is not assignable to type 'Subscription'. Two different types with this name exist,
but they are unrelated. Property '\_subscriptions' is missing in type 'Subscription'_

***Note:*** Here I'm assigning the return from calling `subscribe()` to a variable of type 'Subscription'

**Comment by wshaheer** [comment]
Declaring the variable (that's assigned the return from calling `subscribe()`) as 'any' fixes the error

**Comment by ihadeed** [comment]
@wshaheer this might be because I changed the `rxjs` version in the latest release. Does it work perfectly in 2.2.14? In your app's `package.json`, what is the `rxjs` version defined there?

**Comment by wshaheer** [comment]
@ihadeed  I haven't tested against v2.2.14. Currently I have rxjs v5.0.3

**Comment by ihadeed** [comment]
How come you have 5.0.3? both Ionic and Ionic Native use `5.0.0-beta.12`.

**Comment by wshaheer** [comment]
When I ran `npm outdated` , v5.0.3 was the latest. Is there a list of all the pinned packages that's compatible with Ionic, or is it just whatever that's listed in the package.json when starting a blank project?

**Comment by ihadeed** [comment]
@wshaheer you should stick to that the fresh project provides you with
