### ISSUE TITLE
Property 'post' does not exist on type 'HTTP'

### ISSUE THREAD

**Issue by ankitjainOfficial** [driftyco/ionic-native#988]
I'm trying to use HTTP module.

This is my current code:
```
import { HTTP } from 'ionic-native';

constructor(private constants: Constants, private http: HTTP) {}
signup (user: SignupUser) {
    return this.http.post(this.requestAPI('user'), user, {})
}
```

I'm getting typescript error: Property 'post' does not exist on type 'HTTP'

When I change the code to this:
```
signup (user: SignupUser) {
    return HTTP.post(this.requestAPI('user'), user, {})
}
```

Compile is working but, I get the following error
```
Runtime Error
Cannot read property '__symbol__' of undefined
```

Any help would be appreciated.

Thanks,

**Comment by ihadeed** [comment]
@ankitjainOfficial the plugin is not injectable, it's a static object.

The correct usage is:

```
import { HTTP } from 'ionic-native';

HTTP.post(....);
```
