### ISSUE TITLE
Push native plugin

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic-native#989]
1) Missing supported platforms. From my experience, at least `browser`, `iOS`, and `android`
2) The snippets of code:
```
let push = Push.init({
    android: {
        senderID: config.gcmApiKey
    },
    ios: {
        alert: "true",
        badge: true,
        sound: "default"
    },
    windows: {}
});

push.on("registration", (data) => {
    console.log(data.registrationId);
    alert(data.registrationId.toString());
});
push.on("notification", (data) => {
    console.log(data);
    alert("Hi, Am a push notification");
});
push.on("error", (e) => {
    console.log(e.message);
});
```

Are bad, as `push.on` is not defined when doing `ionic serve`, and such will throw an error that breaks the app.
Instead, I found that doing:
`if (!push["error"]) {`
Before the `push.on` handles that error, however badly.

- Is it possible to convert the push plugin interface to be promise-like?

3) I find it weird trying to know what device is it. (Push is different for iOS, android, and browser), and even when I do for example `new Platform().is("ios")` it works on browser when shown the iOS styling. Is it possible to also add the device type to the registration? I couldn't find how to differentiate devices.

Thanks

**Comment by ihadeed** [comment]
We have a PR here that should address some of these issues. I will try to enhance it further to cover all the points you mentioned.

https://github.com/driftyco/ionic-native/pull/425

**Comment by AmitMY** [comment]
I didn't notice there is an open PR, my apologies.
Is there an ETA for a merge & release?

**Comment by AmitMY** [comment]
Was merged in v3
