### ISSUE TITLE
Plugin Request - BackgroundFetch

### ISSUE THREAD

**Issue by pdrosos** [driftyco/ionic-native#990]
I will most probably use [this BackgroundFetch plugin](https://github.com/transistorsoft/cordova-plugin-background-fetch) in combination with BackgroundGeolocation, to send regular location updates to server even app is in background.
It will be great if the plugin could be included in Ionic Native at some point.
https://github.com/transistorsoft/cordova-plugin-background-fetch
Thanks!

**Comment by joshstrange** [comment]
Plugin added in this pull request https://github.com/driftyco/ionic-native/pull/1008

**Comment by joshstrange** [comment]
Plugin is actually in this pull request now https://github.com/driftyco/ionic-native/pull/1013 due to my mistake of 2 things falling into the same pull request (which was then closed)

**Comment by joshstrange** [comment]
@pdrosos This plugin has been added to the [v2.5.0 milestone](https://github.com/driftyco/ionic-native/milestone/21)

**Comment by pdrosos** [comment]
@joshstrange great, thank you!

**Comment by ihadeed** [comment]
This plugin was added awhile ago. Sorry I forgot to update this issue.
