### ISSUE TITLE
GoogleMaps addEventListener dose not work

### ISSUE THREAD

**Issue by ziggyJ** [driftyco/ionic-native#999]
It throws a lot of TypeError: evt.toLowerCase is not a function. (In 'evt.toLowerCase()', 'evt.toLowerCase' is undefined)

I check the code, it seems in the recent change in the googlemap.ts, a lot of addEventListener functions were added. But instead of using 
`this._objectInstance.addEventListener(event, observer.next.bind(observer));`
, it should use 
`this._objectInstance.addEventListener(eventName, observer.next.bind(observer));`

**Comment by ihadeed** [comment]
Fixed in `2.4.0`. Thanks for pointing it out.
